### ISSUE TITLE
Dokka fails to merge two enums

### ISSUE THREAD

**Issue by pikinier20** [Kotlin/dokka#1000]
Enum from jsMain
![image](https://user-images.githubusercontent.com/48246851/85364974-a6cb1a80-b524-11ea-9c4b-1b243e0cf748.png)
Enum from jvmMain
![image](https://user-images.githubusercontent.com/48246851/85364945-9b77ef00-b524-11ea-8eeb-8b998df327a9.png)
Content of ImplementedInterfaces extras
![image](https://user-images.githubusercontent.com/48246851/85364919-8dc26980-b524-11ea-9250-ddbbf8e5fa26.png)
I think it's because default interfaces that Enum inherit from, are different in js and jvm platform.
![image](https://user-images.githubusercontent.com/48246851/85365116-f90c3b80-b524-11ea-9388-e1cdd7458277.png)

**Comment by MarcinAman** [comment]
Afaik issue was resolved in https://github.com/Kotlin/dokka/pull/1004/files
