### ISSUE TITLE
CSS in runnable samples should be displayed properly

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1075]
- Code is not displayed by default, only after clicking  + button.
- Run and copy icons are overlapped.
- When sample is run, code is displayed like with extra scrollbars.

Also it doesn't look nice:
![image](https://user-images.githubusercontent.com/15652452/86892649-d3745a00-c100-11ea-9df5-1a0f5a4614ef.png)
Imho text should not be bold and there should be a padding on the icons that matches the one used in copying signature. Also we should style it the way that koltin has it's samples: https://kotlinlang.org/docs/reference/collections-overview.html

**Comment by mshishkina** [comment]
Dokka v.1.4.0-dev-81.
Text of sample is still not displayed by default, only after pressing + button.
![image](https://user-images.githubusercontent.com/26213849/87645377-11ebc380-c756-11ea-97fd-e0d608efed64.png)

**Comment by MarcinAman** [comment]
@mshishkina I think that css in runnable samples finally fine after merging #1170 . So fo the Clock example it looks like:
![image](https://user-images.githubusercontent.com/15652452/87801718-6e330e00-c850-11ea-8acf-6f3d367216d1.png)
And after running:
![image](https://user-images.githubusercontent.com/15652452/87801756-7db25700-c850-11ea-9159-2a264b456b2e.png)
![image](https://user-images.githubusercontent.com/15652452/87801785-899e1900-c850-11ea-8d3b-6931c1daec8b.png)
