### ISSUE TITLE
Javadoc: the list of superclasses is not wrapped

### ISSUE THREAD

**Issue by mshishkina** [Kotlin/dokka#1095]
Dokka v.1.4.0-M3-dev-61.
The list of superclasses must be wrapped as list of interfaces, now it's all of them are in one line.
![image](https://user-images.githubusercontent.com/26213849/87150104-247b7e00-c2ba-11ea-9204-2dcd2c8daaea.png)

**Comment by kamildoleglo** [comment]
As @MarcinAman discovered this is a bug in the original Javadoc output (up to JDK 14)
