### ISSUE TITLE
Support specifying subprojects via exclude list or pattern

### ISSUE THREAD

**Issue by zach-klippenstein** [Kotlin/dokka#1114]
The Dokka Gradle config currently supports generating output for multiple subprojects via the `subProjects` property. However, this is an include list. For library projects that consist of many modules, most of which need documentation to be generated, it would be helpful to have more sophisticated ways of specifying the subproject set. 

For example, I work on a project that has around 12 different library modules/projects, and a bunch of sample app modules. All the sample modules are grouped under a separate directory. The config I would like to write is to simply say "include all subprojects except children of the `:samples` project".

This is possible to do by filtering and mapping Gradle's list of projects, but that's a lot of wiring code to write and Gradle's APIs aren't always intuitive here. However, this approach would already be a lot easier to get right if the subProjects property took actual project references instead of raw strings (#1113).

**Comment by MikeAde1** [comment]
Is there any solution to this?
I have the same issue.
