### ISSUE TITLE
Comment for data class is displayed for each its default method 

### ISSUE THREAD

**Issue by mshishkina** [Kotlin/dokka#1162]
Dokka v.1.4.0-dev-84
```
/**
 * Comment for data class
 */
data class ClassC(val name: String)
```
Comment is duplicated for class and each method:
![image](https://user-images.githubusercontent.com/26213849/87656100-b8899180-c761-11ea-8b3e-a4dd6fe470a0.png)

**Comment by sellmair** [comment]
Cherry picked into 1.4.0-M3 🍒

**Comment by mshishkina** [comment]
Verified fix in dokka v.1.4.0-dev-90
