### ISSUE TITLE
Comment with @return tag is lost

### ISSUE THREAD

**Issue by mshishkina** [Kotlin/dokka#1166]
Dokka v.1.4.0-M3-dev-84

```
/**
     * Meaningless param [addText]
     * @return return something
     */
    fun jvmOnly(addText: String): String = addText + "JVM"
```
Comment with @return is lost, we should think how it will be displayed in dokka.
![image](https://user-images.githubusercontent.com/26213849/87665280-56d02400-c76f-11ea-8d41-7cd4581d329f.png)

**Comment by BarkingBad** [comment]
Can you check whether this bug exists inside dedicated page for `jvmOnly`? As far as I know it is done on purpose the named sections like `@return`, `@param`, `@constructor` are ommited in generated documentation. For example for stdlib 

http://dokka-snapshots.s3.eu-central-1.amazonaws.com/dev-0.11.0/stdlib/latest/kotlin-stdlib/kotlin-stdlib/kotlin.collections/-abstract-mutable-collection/add.html

![obraz](https://user-images.githubusercontent.com/32793002/87667467-ae1fc580-c76a-11ea-8685-abb29a768ab6.png)
![obraz](https://user-images.githubusercontent.com/32793002/87667497-bd9f0e80-c76a-11ea-8dc8-d25819734265.png)
![obraz](https://user-images.githubusercontent.com/32793002/87667512-c5f74980-c76a-11ea-8cfc-be8d9b737e8a.png)

**Comment by BarkingBad** [comment]
@mshishkina please verify whether your `@return` section exists in dedicated page, so we can close the issue or fix the bug
