### ISSUE TITLE
Anchors to androidx are broken

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#1230]
For an example project see the `it-android-0` in the `integration-tests`

Dokka creates a link to: https://developer.android.com/reference/kotlin/androidx/appcompat/app/AppCompatActivity.html#findViewById-kotlin.Int-
while the correct one looks like this:
https://developer.android.com/reference/kotlin/androidx/appcompat/app/AppCompatActivity.html#findviewbyid

**Comment by mshishkina** [comment]
Add please it to tests.
