### ISSUE TITLE
Javadoc should produce files in standard package directory structure

### ISSUE THREAD

**Issue by bsiegel** [Kotlin/dokka#1239]
**Describe the bug**
When generating Javadoc, Dokka generates the files in the following structure, where packages exist in a single folder with the fully qualified package name. This is a problem because when other docs want to link to the Dokka-generated docs, the links get generated incorrectly - they expect that docs exist in the standard Javadoc folder structure where package name components are represented as nested folders.

Example of how the javadocs are generated today:
```
├── ...
├── com.mycompany.packagename
│   ├── ClassName.html
│   └── ...
├── com.mycompany.packagename.subpackagename
│   └── ...
├── com.mycompany.otherpackagename
│   └── ...
├── ...
```

**Expected behaviour**
Javadoc should generate files in the standard Javadoc folder structure where package name components are represented as nested folders:
```
├── ...
├── com
│   └── mycompany
│       ├── otherpackagename
│       │   └── ...
│       └── packagename
│           ├── ClassName.html
│           ├── ...
│           └── subpackagename
│               └── ...
├── ...
```

**To Reproduce**
Execute the standard `dokkaJavadoc` task

**Installation**
- Operating system: macOS 10.15
- Build tool: Gradle v6.5.1
- Dokka version: 1.4-mc-1

**Additional context**
Since Dokka does not generate a `package-list` if you are generating Javadoc today, I am just hand-crafting it in order to test linking another set of Javadocs to the Dokka-generated docs.

**Comment by MarcinAman** [comment]
Hi, sorry for the long response time. 
The package list (as well as element-list) was implemented. As for the directory structure: i think it is also fixed, since for a class `adaptation.nested.SampleNestedPackage` i get a result in a folder `./adaptation/nested` which is the same as in original javadoc. 

Would you mind upgrading to 1.4.0 and checking it out?
