### ISSUE TITLE
Generated docs are missing spaces between text and links, and between lines of text.

### ISSUE THREAD

**Issue by bsiegel** [Kotlin/dokka#1241]
**Describe the bug**
```java
/**
 * Builder for {@link FooObject}.
 * A builder to configure and build a {@link FooObject}.
 */
```

Generates the following output:

Builder for[FooObject]().A builder to configure and build a[FooObject]().

**Expected behaviour**
Spaces should be preserved between text and links. Spaces should be preserved between newlines. For example:

Builder for [FooObject](). A builder to configure and build a [FooObject]().

Additionally, empty lines should be able to separate paragraphs. I understand that full markdown / syntax support in doc comments is still TBD, but this seems like a bug since the output is clearly wrong in very simple scenarios.

**To Reproduce**
Run the dokkaHtml or dokkaJavadoc tasks with the above doc comment in place.

**Installation**
- Operating system: macOS 10.15
- Build tool: Gradle v6.5.1
- Dokka version: 1.4-mc-1

**Comment by ethauvin** [comment]
Still an issue in 1.4.0-rc and was also an issue in the 1.3.x versions.

**Comment by IgnatBeresnev** [comment]
Unable to reproduce with 1.6.21. Do let me know if I need to do anything else to reproduce this
```java
/**
 * Builder for {@link java.util.ArrayList}.
 * A builder to configure and build a {@link java.util.LinkedList}.
 */
public class TestClass {}
```

![2022-04-27_18-15-38](https://user-images.githubusercontent.com/22685910/165551711-e9ce7bba-3568-4a27-b908-03ecf248687e.png)
