### ISSUE TITLE
DokkaSourceSet: Suppressed files are documented

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#1245]

**Comment by mikepenz** [comment]
@sellmair when trying 1.4.0-rc today we were facing the same problem, do you know of any workaround currently? 

Thank you very much

**Comment by sellmair** [comment]
Unfortunately, I cannot think of one for now 😢 
This is the reason why I am now working on this at the moment! 
I will push a PR for this today, but can't promise when this will be in any available build!

**Comment by mikepenz** [comment]
@sellmair thank you so much for coming back on this! appreciate your work to fix this

**Comment by sellmair** [comment]
PR is available. Hope to get a review today ☺️ 👍
