### ISSUE TITLE
Section orders

### ISSUE THREAD

**Issue by msink** [Kotlin/dokka#1247]
**Question**

In 0.9.x section in documentation were:
- Constructors
- Properties
- Inherited Properties
- Functions
- Inherited Functions

In 1.4.10-dev order is different:
- Constructors
- Functions (plain list, including inherited)
- Properties (plain list, including inherited)

Is it a bug or intended behavior?
If intended - it should be configurable.

**Comment by MarcinAman** [comment]
In the new dokka user is able to sort tabs using this extension point: https://github.com/Kotlin/dokka/blob/b84bd718c4bbe86eb7d08df7c9ddd68afcf00be2/plugins/base/src/main/kotlin/DokkaBase.kt#L44

it defaults to this implementation: https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/renderers/DefaultTabSortingStrategy.kt

**Comment by msink** [comment]
So say `Functions` and `Inherited Functions` will be now always in one flat list?
In Kotlin stdlib documentation they are separated.

**Comment by Kordyjan** [comment]
This is intended design for dokka 1.4. I've created an issue for creating a switch that would allow reverting to the old behavior in the new dokka. #1254
