### ISSUE TITLE
SourceLinks not generated for mpp

### ISSUE THREAD

**Issue by KotlinIsland** [Kotlin/dokka#1262]
![image](https://user-images.githubusercontent.com/65446343/89360593-44149380-d70c-11ea-9a24-7dcc2e912cd8.png)

![image](https://user-images.githubusercontent.com/65446343/89360676-8d64e300-d70c-11ea-9d89-f8ce8a778f44.png)

observed with
`id("org.jetbrains.dokka") version "1.4.10-dev-22"`
and
`id("org.jetbrains.dokka") version "1.4.0-rc"`

**Comment by BarkingBad** [comment]
Could not reproduce. Can you create example project where the problem occurs? It would be helpful

**Comment by KotlinIsland** [comment]
I can't reproduce either, I think it was resolved.

**Comment by BarkingBad** [comment]
Have you tried old versions? If so, it is really weird why previously there were no `(source)`. I can wait with closing if you would like to confirm that with old dev build everything goes alright.

**Comment by KotlinIsland** [comment]
`path = "src/main/kotlin"` should be `path = "src/jvmMain/kotlin"`

**Comment by MarcinAman** [comment]
Hi, i've checked it out on my sample project and didn't see anything wrong with SourceLinks, so for now i am closing this issue. 

If you have problems in the future feel free to reopen 👍
