### ISSUE TITLE
Dokka generates unwanted javascript

### ISSUE THREAD

**Issue by martmists-gh** [Kotlin/dokka#1263]
**Describe the bug**
Dokka generates unwanted javascript at the start of the `body` tag on each page.

**Expected behaviour**
This javascript does not appear.

**Screenshots**
![Screenshot_20200805_033352](https://user-images.githubusercontent.com/16361449/89361828-8c13c600-d6cc-11ea-9175-1bbe587525f4.png)

**To Reproduce**
Add dokka, run `gradle dokkaHtml`

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dokkaHtml {
    outputDirectory = "${rootProject.rootDir}/docs"
}

dependencies {
    dokkaHtmlPlugin("org.jetbrains.dokka:javadoc-plugin:1.4.0-rc")
}
```

**Installation**
- Operating system: Arch Linux
- Build tool: Gradle v6.3/v6.5
- Dokka version: 1.4.0-rc

**Additional context**
I was unable to find the snippet that causes this in the repo; Perhaps someone made a modified version and accidentally released it?
Also perhaps related, the title seems incomplete: `<title>gunpowder-api (docName 0.0.1)</title>`

Affected branch: https://github.com/Gunpowder-MC/Gunpowder/tree/rename

**Comment by MarcinAman** [comment]
Thats how javadoc works and we would like to use same mechanisms to be as close as possible to the java version
