### ISSUE TITLE
No way to navigate to Modules view from individual module

### ISSUE THREAD

**Issue by KotlinIsland** [Kotlin/dokka#1266]
1. Be on modules view
2. Click a module
3. How do you get back again?

**Comment by sellmair** [comment]
@kamildoleglo Would you like to take care of this? I also noticed this, but I am not sure if this is a regression?

**Comment by kamildoleglo** [comment]
It is not a regression, there was no way to do it from the beginning. Sure, I'll take care of it

**Comment by mshishkina** [comment]
I think it's better to fix by 1.4.10 as it gives rather bad UX

**Comment by MarcinAman** [comment]
Fixed in 1.4.30
