### ISSUE TITLE
Improved HTML Styles?

### ISSUE THREAD

**Issue by beckettsimmons** [Kotlin/dokka#1275]
**Question**
Is the dokka html style up for debate? I just tried out 1.4.0-rc and was disappointed to see function/class signatures still at the bottom with some awkward whitespace at the top. What's the intuition behind this? It seems to me like signatures would fit cleanly at the top and also provide pertinent information on how a function/class is called. Additionally, there seem to be many other inaccuracies and awkward spacing all throughout. 

Is there a plan to clean this up in the future? Are custom plugins the answer?
Otherwise, I've got a few spare cycles and don't mind contributing to a style that I would find more clean and coherent.

**Comment by mshishkina** [comment]
Hi! We're planning to improve html format further, share please your vision of new format.

**Comment by beckettsimmons** [comment]
I don't have a particular overall vision for the new format. In fact, the current format looks like it has a lot of potential. However, there are many many small changes that I think could be made. Just to name a few:
1. For functions and classes, the type signature is shown at the bottom below the description. To me this is very awkward/useless and is not similar to some of the [official kotlin docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html).
2. As mentioned before. There are many awkward spacing inaccuracies throughout. (Too many to name, unless you want a very specific diagram. (One example though, is that the platform pills are show entirely on their own line, leaving some extra whitespace at the top of every function.))
3. Seemingly, paragraph breaks aren't respected at all. (As KDoc suggests)
4. Following from 3, in a package's page, the "Types" and "Functions" tab contains the unabridged docstrings. This makes quickly scanning the list very tiresome. In [the official docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/index.html) just the first paragraph is shown.
5. Code examples (using triple back ticks) aren't particularly pretty. And formatting such as indentation is not preserved.
5. In multiplatform, the platform filter pills all the way at the top and are not very accessible. Perhaps a top bar could be added for keeping these handy.
6. In multiplatform, should duplicate implementations be shown? In most cases I am only documenting my `expect` classes and leave the `actual` implementations completely undocumented. Is would be nice if the documentation could reflect this and just contain one function/class with pills for each platform.
7. Not an HTML specific thing, but why are inherited functions included? Do we really need to see `.equals()`, `.hashCode`, and `.toString` for every single class?
8. Also, I'm pretty new to the extension function game. I have many extension functions that are at the top-level of a file. In the Jvm and Native these appear in a namespace. In the documention, however, they all appear to be directly in the package (as will as in the "Extensions" tab of the respective class). Not sure if this is intended behavior, but it makes things somewhat cluttered at the package level.

I've already had to write a custom gradle task using Jsoup to include a lot of these suggestions and I like it a lot better. Hopefully, many of these can find their way into a release build someday. Perhaps, even, if someone could point me in the right direction, I could start to work on a few of these.

**Comment by IgnatBeresnev** [comment]
Hi! Thank you for the detailed feedback.

HTML format has been completely re-implemented in 1.6 and a lot of time has passed since then, I encourage you to give the new version a go if you haven't seen it already :) 

I'll close this issue for now as it seems to be specific to the old UI, but feel free to open a new issue with suggestions for the new format, it's here to stay and we'd love to get some constructive feedback.
