### ISSUE TITLE
Could not find method dokkaHtmlMultimodule() for arguments (MultiModule Project)

### ISSUE THREAD

**Issue by adilmas13** [Kotlin/dokka#1276]
How do I generate a single document for my three modules namely app, data and domain ?? I'm able to generate separate documents but cant understand who to create a single master doc for all the modules. I tried following the repo readme but cant seems to understand what im doing wrong.

- Dokka version: 1.4.0-rc
- Android Studio 4.0.1

```
apply plugin: 'org.jetbrains.dokka'
tasks.dokkaHtml {
    outputDirectory = "$buildDir/docs"
}
```

added a above code in all three gradle files of the modules..
However, where do I have to add 'dokkaHtmlMultimodule'. I tried adding it in the app module but was unable to get the gradle sync... 

Need immediate assistance.. thanks

**Comment by floscher** [comment]
You could try adding the dokka plugin to the root project, not just to your three subprojects:
```
buildscript {
  repositories.jcenter()
  dependencies {
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0-rc")
  }
}
plugins {
  id "org.jetbrains.dokka"
}
```
(maybe you don't even need the buildscript block, but in my case it was necessary)

Then there should be a task `dokkaHtmlMultimodule` in the root project:
```
./gradlew :dokkaHtmlMultimodule
```

It generates the multimodule documentation in the `$buildDir/dokka/htmlMultimodule/` directory. You'll need a `README.md` at the root of each subproject/module.

See https://github.com/Kotlin/dokka#multi-module-projects

**Comment by sellmair** [comment]
Thanks @floscher for the answer ☺️ 👍 
@adilmas13 : Feel free to drop me a message in the Kotlin Slack channel if you need further help ☺️
