### ISSUE TITLE
Sidebar navigation missing when viewing docs using file:// protocol

### ISSUE THREAD

**Issue by floscher** [Kotlin/dokka#1278]
**Describe the bug**
When I run `./gradlew dokkaHtmlMultimodule` on my machine and then try to view the generated docs in the browser, the navigation is not displaying.

I'm trying to figure out how to setup a project with the new Dokka. For a long time I thought I had something misconfigured, because I could not see any navigation (see screenshots). Finally I discovered that the Console in the DevTools displays an error that a CORS request is blocked, because a protocol other than `http://` or `https://` is used.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp for details on the error message.

This means that the navigation only displays if the docs are served over HTTP(S), but not if you want to view them in your local filesystem using the `file://` protocol

**Expected behaviour**
There should be a navigation sidebar

**Actual behaviour**
The sidebar is completely empty. Error message in DevTools console.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3904348/89673373-85f93180-d8e6-11ea-9137-3c9f2d2e7e1d.gif)

**To Reproduce**
Open documentation generated by Dokka in the browser using the `file://` protocol

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.5.1
- Dokka version: 1.4.0-rc
- Browser: Firefox 79.0, Chromium 84.0

**Comment by MarcinAman** [comment]
closing in favour of: https://github.com/Kotlin/dokka/issues/1795 as it is planned for 1.5
