### ISSUE TITLE
Make the dokkaHtml generated site mobile friendly!

### ISSUE THREAD

**Issue by sureshg** [Kotlin/dokka#1279]
The site generated by `dokkaHtml` plugin is not mobile friendly. This request is to make website design responsive and mobile friendly.

Here is an example http://dokka.kweb.io/kweb-core/ which shown on a mobile device

<img width="431" alt="Screen Shot 2020-08-08 at 2 24 01 PM" src="https://user-images.githubusercontent.com/356994/89720042-1a18d680-d983-11ea-85b2-659a03206dd3.png">

**Comment by Kordyjan** [comment]
New mobile fronted is available in our nightly builds. Moreover, it will be a major feature of the 1.4.10 release which you can expect within a week.
