### ISSUE TITLE
Change the location of the index.html

### ISSUE THREAD

**Issue by Jaimss** [Kotlin/dokka#1282]
**Is your feature request related to a problem? Please describe**
Github pages for a specific repository only has a few available options as to where the documentation is located. I have my dokka outputting to a directory called `docs` which allows it to be the site for that repositories github pages, however, I can not change my index.html file location, so github pages doesn't recognize it without a lot of manual refactoring.

**Describe the solution you'd like**
I would like to be able to specify that the index.html will go directly into the docs directory (while still pointing to the proper pages of the site of course), so that I can generate sources, and push to github immediately and it will pick up the new documentation.

**Describe alternatives you've considered**
I've considered hosting myself on my own web server, but that's not as easy as using github pages.

**Additional context**
N/a

**Comment by ethauvin** [comment]
The location of the support files (css, images, etc.) should be fully customizable.

In this day in age, it no longer makes sense to have the support files located in the root directory. This stems from Sun's JavaDoc original implementation that was solely intended for the JVM as a whole.

**Comment by MarcinAman** [comment]
Location of the index file is more github-friendly in 1.4.30+. Right now it is on the root and below it there are folders with assets and content. This should allow you to have out-of-the-box support for docs hosting
