### ISSUE TITLE
KDoc (HTML) not suppressed if `@property` is part of doc comment

### ISSUE THREAD

**Issue by codeprogression** [Kotlin/dokka#129]
If I document a class with `@property` and `@suppress`, the class is still generated in the HTML (but not JavaDoc). Changing `@property` to `@param` will enable the class to be suppressed from generation.

KDoc entry not suppressed:
```kotlin
/**
 * @property foo A Foo
 * @suppress
 */
class Example(val foo: Foo)
```

KDoc entry suppressed:
```kotlin
/**
 * @param foo A Foo
 * @suppress
 */
class Example(val foo: Foo)
```

**Comment by kamildoleglo** [comment]
Fix confirmed on 1.4.30
