### ISSUE TITLE
DokkaMultiModuleTask output should be in a single output directory

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#1290]
Currently, the `DokkaMultiMoudleTask` is just linking to the output directories of the child dokka tasks. This is highly impractical, since those paths are separated a lot and often include file strucutres like "../.../childModle/build/...". 

We want to provide a file-layout that is "compact", which can easily be published on any web-server.

**Comment by floscher** [comment]
I think this is the same as #1168.

**Comment by sellmair** [comment]
Yes, thanks a lot! I closed #1168 in favour of this now 👍
