### ISSUE TITLE
DokkaCollectorTask showing confusing and seemingly unnecessary source set bubbles

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#1294]
E.g. running `dokkaHtmlCollector` on spring framework.
![image](https://user-images.githubusercontent.com/34319766/89811017-49c00e00-db3e-11ea-8bba-74ebc322a2b3.png)

**Comment by mikepenz** [comment]
I saw the same problem today, changing the `displayName` actually affects this and allows you to change it, but this felt pretty off to be honest.

**Comment by sellmair** [comment]
![image](https://user-images.githubusercontent.com/34319766/90120980-b2380680-dd5b-11ea-9ccc-b17dafc8e0fb.png)
PR is on the way 👀

**Comment by mikepenz** [comment]
Thank you @sellmair . Are there currently snapshots builds available after PRs are merged, or perhaps nightly builds?

**Comment by sellmair** [comment]
Unfortunately, the kotlin-dev repository is dead :( 
I would really like to push snapshots and will ping you once we have switched to some other repository!

**Comment by mikepenz** [comment]
thank you so much for all your effort!

**Comment by sellmair** [comment]
Fix available in [1.4.0-dev-35](https://bintray.com/kotlin/kotlin-dev/dokka/1.4.0-dev-35)!
Please note, that this build also includes changes in the Gradle Plugin. I will create a post about it in the Kotlin Slack.
