### ISSUE TITLE
@sample tag on public property is not able to show sample

### ISSUE THREAD

**Issue by pinakinkansara** [Kotlin/dokka#1299]
**Describe the bug**
 ```
/**
     *
     *  [maskChar] allows to set custom char for masking
     *  @sample testFun
     */
    var maskChar: CharSequence = "-"
```

when we provide @sample to property defined dokka is not able to include sample in the documentation generated. It generates the documentation if @sample is applied to function.

**Expected behaviour**
property declared should also produce respective set & get function in the function list and should include sample using @sample

**To Reproduce**

- define new property in a class 
- add comment on it
- add @sample annotation with sample function as reference

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dokka { 
    outputFormat = 'html'
    ...
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.6.0
- Dokka version: 1.4.0-rc

**Comment by sellophane** [comment]
Hello,
not generating sub-pages for getters and setters was a design decision, but yes, there should be some kind of presentation for tags declared on properties. So this information will be added on properties parent page.
