### ISSUE TITLE
MultiModule: Module description file containing only `*` bullets is not included

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#1322]

**Comment by BarkingBad** [comment]
What do you mean by this title? Having only unordered list with bulletpoints from asterisks e. g. 
```
* some
* list
```
or just inserting asterisks randomly, e. g.
```
***********************
```

**Comment by sellmair** [comment]
I think this was fixed by #1387. 
I'll close this now, since I cannot reproduce it anymore
