### ISSUE TITLE
kotlinx-serialization: Package documentation duplicated

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#1323]
![image](https://user-images.githubusercontent.com/34319766/90397335-0151a480-e098-11ea-98a6-53f19403906f.png)

**Comment by MarcinAman** [comment]
I think the issue is no longer present. Here is an output from the latest dev using 1.4.0-RC branch in kotlinx.serialization:
![image](https://user-images.githubusercontent.com/15652452/91996900-cb6c1b80-ed39-11ea-85af-9c217764eaa4.png)
