### ISSUE TITLE
Unstable sort order for overloaded member functions

### ISSUE THREAD

**Issue by arturbosch** [Kotlin/dokka#1333]
**Describe the bug**
Hi, on CI we verify if the documentation gets generated correctly and is uptodate when creating PRs.
The code in the `Screenshots` section, generates files which are unstable for version control because the order changes on each dokka invocation.

**Expected behaviour**
Documentation generation should be stable for version control.

**Screenshots**

It is the following code:

https://github.com/detekt/detekt/blob/c6ff7112b0b33afdf62e043075d67508c9e1e5b9/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/Context.kt#L13-L45

![2020-08-17-202736_1913x435_scrot](https://user-images.githubusercontent.com/20924106/90430721-3bd33580-e0c8-11ea-9dc8-5e125894167b.png)

**To Reproduce**
1. `git clone https://github.com/detekt/detekt`
2. `git checkout -b "try-dokka-1.4" "origin/try-dokka-1.4"`
3. `gradle generateDocumentation --rerun-tasks` 2x

**Dokka configuration**

```kotlin
tasks.withType<DokkaTask>().configureEach {
    outputDirectory = "$rootDir/docs/pages/kdoc"
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.6.0
- Dokka version: 1.4.0-rc

**Additional context**
We are upgrading to Kotlin 1.4 and want to upgrade dokka.
Old dokka does not allow us to upgrade Gradle because it throws an OOM exception for Gradle > 6.5 on Java 11.

**Comment by kamildoleglo** [comment]
Hi! Could you please try to use the newest dokka version (`1.4.0-rc` is published to the `jcenter`)? It should allow you to generate the documentation correctly preserving order.

The OOM error is easily fixable in Gradle by adding more memory (eg. you can put `org.gradle.jvmargs=-Xmx4096m` in your `gradle.properties` file)
