### ISSUE TITLE
1.4.0-rc: wrong dependency scope

### ISSUE THREAD

**Issue by gabrielittner** [Kotlin/dokka#1334]
**Describe the bug**

I have a Gradle plugin that has a dependency on the Dokka plugin to access `DokkaTask`. With 1.4.0-rc I'm getting this compile error when calling `DokkaTask.outputDirectory`: `Cannot access 'org.jetbrains.dokka.plugability.Configurable' which is a supertype of 'org.jetbrains.dokka.gradle.AbstractDokkaTask'. Check your module classpath for missing or conflicting dependencies`. Looks like the dependency scope is not defined correctly.

You can see it on this branch https://github.com/vanniktech/gradle-maven-publish-plugin/tree/dokka

**Expected behaviour**

No compile error.

**Comment by altavir** [comment]
Got the same error. To fix that, need to add `"org.jetbrains.dokka:dokka-core` explicitly.

**Comment by sellmair** [comment]
You can try out this dev build [1.4.0-dev-35](https://bintray.com/kotlin/kotlin-dev/dokka/1.4.0-dev-35). It should work there, but this issue might come up at other corners and needs some attention from our side 🤔

**Comment by sellmair** [comment]
Tried the build 1.4.0-dev-35 on your project. 
Compiles fine ✅ 
Tests are passing ✅ 
Sebi is happy ✅ 🎉
