### ISSUE TITLE
How to use samples?

### ISSUE THREAD

**Issue by Jaimss** [Kotlin/dokka#1343]
**Question**
How can I make samples show up properly? Currently my samples show up as just the path to the method (seen below). How can I make it show properly?

**Screenshots**
![image](https://user-images.githubusercontent.com/53633325/90565678-4ac3f180-e175-11ea-9440-c4bda426e814.png)

**Installation**
- Operating system: Windows 10
- Build tool: Gradle v6.1.1
- Dokka version: 1.4.0-rc

**Additional context**
I am using the `dokkaHtmlCollector` task on a multi-module project. My build files are below:
###### `build.gradle` (root)
```gradle
plugins {
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version '1.4.0'
    id 'com.github.johnrengelman.shadow' version '6.0.0'
    id 'org.jetbrains.dokka' version '1.4.0-rc'
}

allprojects {
    apply plugin: 'org.jetbrains.dokka'
    apply plugin: 'maven-publish'
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'com.github.johnrengelman.shadow'

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
        repositories {
            mavenLocal()
        }
    }

    shadowJar {
        archiveClassifier.set("")
    }

    repositories {
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://papermc.io/repo/repository/maven-public/' }
        maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    }

    dependencies {
        compileOnly "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
        testCompile group: 'org.jetbrains.kotlin', name: 'kotlin-test-junit', version: '1.4.0'
    }
}

dokkaHtmlCollector {
    outputDirectory = "$projectDir/docs"
}

def ver = '2.1.1'

group 'dev.jaims'
version ver

subprojects {
    group 'dev.jaims.mcutils'
    version ver


}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

###### `build.gradle` (bukkit module)
```gradle
dependencies {
    implementation project(":common")
    compileOnly 'com.destroystokyo.paper:paper-api:1.16.1-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.10.4'

    testImplementation 'com.destroystokyo.paper:paper-api:1.16.1-R0.1-SNAPSHOT'
}
```

###### `build.gradle` (bungee module)
```gradle
dependencies {
    implementation project(":common")
    compileOnly 'io.github.waterfallmc:waterfall-api:1.16-R0.1-SNAPSHOT'
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testImplementation 'io.github.waterfallmc:waterfall-api:1.16-R0.1-SNAPSHOT'
}
```

###### `build.gradle` (common module)
```gradle
dependencies {
    compileOnly 'com.github.ascclemens:khttp:39f76b4186'
    testImplementation(project(":common"))
}
```

**Comment by deniskr** [comment]
@Jaimss you need to include the source file with the samples (`samples.kt`) as follows:

```kotlin
tasks.withType<DokkaTask> {
    dokkaSourceSets {
        register("main") {
            includes = listOf("readme.md")
            samples  = listOf("src/test/kotlin/samples.kt")
        }
    }
}



```

**Comment by Jaimss** [comment]
Thanks.

**Comment by JitenderVerma** [comment]
@deniskr I am facing the same issue where in my generated sample, the reference of the sample class method is being printed.

I am not sure how to apply ur answer as its giving me error. Apart from the above code, Here is the additional info - 

build.gradle(module level) -

dokkaJavadoc.configure {
    dokkaSourceSets {
        named("main") {
            skipDeprecated.set(true)
            skipEmptyPackages.set(true)
            includeNonPublic.set(false)
            reportUndocumented.set(true)
            perPackageOption {
                skipEmptyPackages.set(true)
                includeNonPublic.set(false)
                matchingRegex.set("packagename")
                suppress.set(false)
                matchingRegex.set("packagename")
                suppress.set(true)
            }
        }
    }
}


dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            skipDeprecated.set(true)
            skipEmptyPackages.set(true)
            includeNonPublic.set(false)
            reportUndocumented.set(true)
            perPackageOption {
                skipEmptyPackages.set(true)
                includeNonPublic.set(false)
                matchingRegex.set("packagename")
                suppress.set(false)
                matchingRegex.set("packagename")
                suppress.set(true)
            }
        }
    }
}




build.gradle - project level - 

tasks.dokkaJavadocCollector.configure {
    outputDirectory.set(file("$buildDir/javadoc"))
}
