### ISSUE TITLE
dokkaHtml doesn't create code blocks with format

### ISSUE THREAD

**Issue by jaiew** [Kotlin/dokka#1346]
**Describe the bug**
Given the below KDoc comment:

```
/**
 * Utility for building a String that represents an XML document.
 * The XmlBlob object is immutable and the passed values are copied where it makes sense.
 *
 * Note the XML Declaration is not output as part of the XmlBlob
 *
 *    val soapAttrs = attrs("soap-env" to "http://www.w3.org/2001/12/soap-envelope",
 *        "soap-env:encodingStyle" to "http://www.w3.org/2001/12/soap-encoding")
 *    val soapXml = node("soap-env:Envelope", soapAttrs,
 *        node("soap-env:Body", attrs("xmlns:m" to "http://example"),
 *            node("m:GetExample",
 *                node("m:GetExampleName", "BasePair")
 *            )
 *        )
 *    )
 *
 */
```

**Expected behaviour**
Expect that when running `./gradlew dokkaHtml` that the generated documentation would have the above code block formatted correctly

**Screenshots**
In version 10.1 it was working:
![Screen Shot 2020-08-19 at 9 47 16 pm](https://user-images.githubusercontent.com/289692/90631143-8fc75100-e265-11ea-9dd4-267bfd4f7d24.png)

In 1.4.0-rc the code block is not formatted but is inside a `<code>` element:
![Screen Shot 2020-08-19 at 9 44 51 pm](https://user-images.githubusercontent.com/289692/90630921-3b23d600-e265-11ea-80cb-a44b8686dc7f.png)

**To Reproduce**
Create a code block in a KDoc and run dokkaHtml with 1.4.0-rc

**Dokka configuration**
Nothing apart from the outputDirectory

```kotlin
tasks.dokkaHtml {
    outputDirectory = "$buildDir/javadoc"
}
```

**Comment by asfalcone** [comment]
We're seeing the same thing in 1.4.0-rc in both javadoc and html formats

**Comment by SUPERCILEX** [comment]
The root cause is that javadoc HTML tags are failing to parse correctly because each line is being evaluated independently. For example, this first `ol` fails to parse, while the second succeeds.

```
 * <ol>
 *     <li>a</li>
 *     <li>b</li>
 *     <li>c</li>
 * </ol>
 *
 * <ol><li>z</li><li>y</li><li>x</li></ol>
```

**Comment by BarkingBad** [comment]
![obraz](https://user-images.githubusercontent.com/32793002/91163385-c79f2000-e6cd-11ea-9d8e-279ba5b63626.png)
![obraz](https://user-images.githubusercontent.com/32793002/91163692-44ca9500-e6ce-11ea-8045-79a74deb0e8d.png)

![obraz](https://user-images.githubusercontent.com/32793002/91163575-11880600-e6ce-11ea-83ad-aca1a455e6a9.png)
![obraz](https://user-images.githubusercontent.com/32793002/91163538-0208bd00-e6ce-11ea-8b05-b43811c60b5a.png)

**Comment by BarkingBad** [comment]
@SUPERCILEX I couldn't reproduce your error. Are you sure that the newest version still shares this behaviour? Probably it has been fixed already.
