### ISSUE TITLE
Code blocks do not preserve newlines in Javadoc HTML output

### ISSUE THREAD

**Issue by xenomachina** [Kotlin/dokka#136]
If I have the following KDoc:

```
 * ```
 * This is a test
 *     of Dokka's code blocks
 * and how they
 *     turn into HTML
 * ```
```

The resulting Javadoc HTML looks like this:

```
<code><pre>This is a test    of Dokka's code blocksand how they    turn into HTML</pre></code>
```

The `pre` ends up being useless because the newlines are stripped from the output. The expected/desired output is more like:

```
<code><pre>This is a test
    of Dokka's code blocks
and how they
    turn into HTML</pre></code>
```

**Comment by semoro** [comment]
Fixed in [0.9.14](https://github.com/Kotlin/dokka/releases/tag/0.9.14)
