### ISSUE TITLE
Wrong error message: No value has been specified for property 'unsuppressedSourceSets.$4.sourceLinks.$0.remoteUrl'. if "includes" or "localDirectory" is wrongly specified

### ISSUE THREAD

**Issue by mshishkina** [Kotlin/dokka#1392]
If `includes.from` or 
```
sourceLink{
                    localDirectory.set(file("src/linuxX64Main/kotlin"))
}
```
is wrongly specified or localDirectory is missing, then I've got error message:
```No value has been specified for property 'unsuppressedSourceSets.$4.sourceLinks.$0.remoteUrl'```
The correct properly must be specified and proper source set if possible.
Dokka version: 1.4.0-dev-54

**Comment by IgnatBeresnev** [comment]
Relevant for any groovy-based misconfiguration. For instance, omit `new` when creating an object or instead of `.set()` use `x = y`
