### ISSUE TITLE
Does mvn's dokka:javadoc download a bunch of stuff?

### ISSUE THREAD

**Issue by GlenKPeterson** [Kotlin/dokka#1408]
![Screenshot from 2020-08-30 19-08-40](https://user-images.githubusercontent.com/2416031/91671486-219c4d00-eaf5-11ea-81c3-b520e2d74024.png)

This is my resources during a build.  You can see that around 30 seconds ago, it switched from CPU intensive, to a solid download.  This was the exact point where the `dokka-maven-plugin:1.4.0-rc:javadoc` task was being executed by maven.  It didn't do this in gradle.

```text
$ mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.8, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-112-generic", arch: "amd64", family: "unix"
```

```xml
<plugin>
	<groupId>org.jetbrains.dokka</groupId>
	<artifactId>dokka-maven-plugin</artifactId>
	<version>1.4.0-rc</version>
	<executions>
		<execution>
			<phase>pre-site</phase>
			<goals>
				<goal>dokka</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Huh.  I eventually waited maybe 4 or 5 minutes and it completed.  Rebuilding again, it only downloaded for 10 or 20 seconds.  What's it doing?  Why?  You might want to add some maven output like, "Downloading the flux capacator...  23% complete" or something.  This is a mixed Java/Kotlin/Maven project.

**Comment by Kordyjan** [comment]
I'm not sure what was downloaded back then, but right now javadoc rendering is rewritten from the scratch so the issue can be closed.

**Comment by Kordyjan** [comment]
Sorry for closing that. I was under the impression that I'm commenting under different issue.

**Comment by kamildoleglo** [comment]
I think it may be due to our dependencies to some Eclipse Aether artifacts. This was done to automatically preload dokka plugins for tasks like `dokkaJavadoc` as we haven't found a better way to do it in Maven

**Comment by GlenKPeterson** [comment]
So this shouldn't happen if I use Gradle?  I've switched some projects from Java to Kotlin and Maven to Gradle, but stopped when I found that my Javadoc wasn't working.  Now that it's fixed (and I hear the Kotlin issue about inheriting default methods in interfaces is fixed too) I should be good to move the rest of my projects to Gradle with .kts files.

**Comment by stephenbyrne-mfj** [comment]
It appears to to download a bunch of stuff using the repository configured in `~/.m2/settings.xml`, but it does not send the configured credentials, so I get a 401 from my Nexus server just trying to build documentation. Which makes this plugin completely unusable.

**Comment by GlenKPeterson** [comment]
Thanks for adding a progress bar(s) in Gradle in org.jetbrains.dokka 1.4.10.  I don't mind waiting so much if I know what it's doing and can see progress!

**Comment by GlenKPeterson** [comment]
Oh.  It's still got no progress bar or indication that anything is happening in Maven.

**Comment by GlenKPeterson** [comment]
Another aspect of this is it actually prevents you from compiling without an internet connection.  I was working on a project today, compiling repeatedly (with Gradle) and publishing to mavenLocal.  At one point I had to turn off my network connection and was shocked to discover that I couldn't compile and publish to mavenLocal because that required dokka which failed the build with an `java.net.UnknownHostException: kotlinlang.org` like this:

```
$ gradle clean publishToMavenLocal
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :dokkaJavadoc
Dokka 1.4.* is an alpha project
Initializing plugins
Creating documentation models
Transforming documentation model before merging
Merging documentation models
Transforming documentation model after merging
Creating pages
Transforming pages
Rendering


> Task :dokkaJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dokkaJavadoc'.
> java.net.UnknownHostException: kotlinlang.org

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
2 actionable tasks: 2 executed
```

It's normal for gradle/maven to download stuff the first time you compile something, but I've never had another JVM project require internet access for subsequent builds.  I'd like to propose that we change this from a "question" to a "bug."  I'm sure I'm not the only person who will be surprised by this behavior and stranded somewhere with no internet and be unable to run a build.  Well, without editing their build file.

I really appreciate having Dokka to generate javadoc-like documentation for Kotlin.  I'm especially glad that the new version works with later versions of the JVM - that's great!  I can see you've fixed and closed a number of bugs already which is excellent.  Thank you for dokka!
