### ISSUE TITLE
javadoc contains org.jetbrains.dokka.ContentBlock@1 for line breaks

### ISSUE THREAD

**Issue by HaasJona** [Kotlin/dokka#141]
I'm applying dokka in javadoc mode on a .java file and get this output:

> public class FileBackedQueue<E>
> Eine Queue, die Elemente beim Überschreiten eines Grenzwertes ins Dateisystem auslagert und dadurch sehr viele Elemente aufnehmen kann. Diese Queue ist abgesehen vom Iterator threadsicher. Je nach Konstruktor verwendet die Queue einen benutzerdefinierten Serializer um die Objekte im Dateisystem abzulegen, oder den Standard-Java-Serializer. Es gibt vordefinierte geerbte Queue-Klassen, die für einfache Datentypen optimierte Serializer benutzen. Für weitere Datentypen ist ein benutzerdefinierter QueueSerializer zu implementieren. Wichtig: nachdem die Queue nicht mehr gebraucht wird sollte FileBackedQueue.clear aufgerufen werden um nicht mehr gebrauchten Speicher auf der Festplatte freizugeben.org.jetbrains.dokka.ContentBlock@1Diese Queue ist auf mehrere gleichzeitige Einfügungen von mehreren Threads spezialisiert. Das Auslesen von Objekten geht im allgemeinen sehr schnell, kann aber nur von einem Thread gleichzeitig durchgeführt werden.org.jetbrains.dokka.ContentBlock@1Für das Speichern im Dateisystem werden die Objekte serialisiert. Das heißt, die Objekte, die zu der Queue hinzugefügt werden sind möglicherweise nicht identisch (im Sinne von Objektidentität) zu den Objekten, die aus der Queue ausgelesen werden.
> 
> See Also:
> FileBackedQueue.clear

The input javadoc comment is:

```
/**
 * Eine Queue, die Elemente beim Überschreiten eines Grenzwertes ins Dateisystem auslagert und dadurch sehr viele Elemente aufnehmen kann. Diese Queue ist
 * abgesehen vom Iterator threadsicher. Je nach Konstruktor verwendet die Queue einen benutzerdefinierten Serializer um die Objekte im Dateisystem abzulegen,
 * oder den Standard-Java-Serializer. Es gibt vordefinierte geerbte Queue-Klassen, die für einfache Datentypen optimierte Serializer benutzen. Für weitere
 * Datentypen ist ein benutzerdefinierter {@link QueueSerializer} zu implementieren. Wichtig: nachdem die Queue nicht mehr gebraucht wird sollte {@link
 * #clear()} aufgerufen werden um nicht mehr gebrauchten Speicher auf der Festplatte freizugeben.<br />Diese Queue ist auf mehrere gleichzeitige Einfügungen von
 * mehreren Threads spezialisiert. Das Auslesen von Objekten geht im allgemeinen sehr schnell, kann aber nur von einem Thread gleichzeitig durchgeführt
 * werden.<br />Für das Speichern im Dateisystem werden die Objekte serialisiert. Das heißt, die Objekte, die zu der Queue hinzugefügt werden sind
 * möglicherweise nicht identisch (im Sinne von Objektidentität) zu den Objekten, die aus der Queue ausgelesen werden.
 *
 * @author Kappich Systemberatung
 * @version $Revision$
 * @see FileBackedLongQueue
 * @see FileBackedIntQueue
 * @see FileBackedShortQueue
 * @see FileBackedByteQueue
 * @see FileBackedStringQueue
 */
```

Obviously the explicit line breaks (`<br />`) are not being handled correctly. Version 0.9.13.

(There also seems to be some problem with the @see tags)

**Comment by semoro** [comment]
Fixed in [0.9.14](https://github.com/Kotlin/dokka/releases/tag/0.9.14)
