### ISSUE TITLE
Rendering of suspend lambdas

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#1418]
Source code like: 
![image](https://user-images.githubusercontent.com/34319766/91831937-ff194980-ec44-11ea-9c3e-590f76e032b6.png)

Is currently rendered as :
![image](https://user-images.githubusercontent.com/34319766/91831980-0f312900-ec45-11ea-9ad8-8d73021f33a2.png)

But we should prefer rendering it as `block: suspend () -> T` instead

**Comment by sellmair** [comment]
Similar #1350

**Comment by Kordyjan** [comment]
It is part of a more general problem: how should we treat function-like types. Right now they are a special case for us in signature provider. Maybe we should handle them in the model as new kind of type bound.

**Comment by Kordyjan** [comment]
I think that the fact that we have three issues with the same root cause (this one, #1350 and #1351) strongly suggests that we should fix that problem on the model level.
