### ISSUE TITLE
Can't document primary constructor?

### ISSUE THREAD

**Issue by kvnxiao** [Kotlin/dokka#142]
If I have a class:

```kotlin
open class Example(val someProperty: String) {
    // other stuff
}
```

How can I document all three: the class, the primary constructor which takes in a string, and the someProperty: String field?

I have tried
```kotlin
/**
* Class documentation
*/
open class Example
/**
* Constructor documentation
*/
(
    /**
    * Property documentation
    */
    val someProperty: String) {
    // other stuff
}
```

However, the constructor documentation does not show up, and instead takes the same description as the one defined for the overall class.

**Comment by yole** [comment]
As documented in http://kotlinlang.org/docs/reference/kotlin-doc.html the primary constructor documentation is introduced with the `@constructor` tag.
