### ISSUE TITLE
Is there a way to consume snapshot versions?

### ISSUE THREAD

**Issue by patrickyin** [Kotlin/dokka#1425]
**Question**
I'd love to consume the latest master branch's build since it contains some bug fixes. Is the plugin available on any maven/plugin repo?

If not, is there any information about the next release date?

**Comment by Kordyjan** [comment]
We have nightly-ish builds available if you add `maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")` to your repositories. 
[Here](https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev/org/jetbrains/dokka/dokka-core/maven-metadata.xml) you can see a list of available versions. Right now there are two branches `1.4.0` that contains only stable fixes and `1.4.10` that is slightly more experimental. At the moment of writing this comment, the newest builds are `1.4.0-dev-65` for the stable branch and `1.4.10-dev-51` for the experimental one.
