### ISSUE TITLE
Dokka causing JVM crash

### ISSUE THREAD

**Issue by sanity** [Kotlin/dokka#145]
Whenever I add samples = ["samples.kt"]  to my Dokka gradle task it crashes my JVM when I try to run the dokka task.  

Here is the hs_err_pidXXXX.log file: https://gist.github.com/sanity/90f60a3c9826c1b6a9a1fbe25f00ce79

Dokka version: 0.9.9
Kotlin version: 1.1.1

**Comment by sanity** [comment]
Possibly related to #135

**Comment by yole** [comment]
https://youtrack.jetbrains.com/issue/KT-17016
