### ISSUE TITLE
Extraneous <p> tags are added causing invalid HTML

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/dokka#1458]
```kotlin
/**
 * Sentence 1.
 *
 * Sentence 2.
 */
class Foo
```

In the Dokka DocTag model, this will be generated as `P[P[Sentence 1], P[Sentence 2]]` which is invalid HTML. The extraneous outer paragraph should be removed.

**Comment by SUPERCILEX** [comment]
I think I know what's going on. There's no "do nothing" DocTag, so when we get a Description Tag wrapper which only supports a root DocTag, the assumption was that things could just be grouped together with a <p> tag.

Solutions:
- Use divs instead (not a fan)
- Create a new `RootGroup` DocTag that isn't intended to be rendered. Or rather, it gives developers the choice of what to render.

**Comment by BarkingBad** [comment]
Hey, tell me whether do you encounter any problems with rendered output. I know `DocTags` have nested paragraphs, but we deal with them during construction of `ContentNodes`. I can intorduce top-level `RootDocTag` for sake of corectness with Html spec, however, `DocTags` don't represent actual HTML tree

**Comment by BarkingBad** [comment]
https://github.com/Kotlin/dokka/commit/00c7b4790c7ebbb0139ffc6ac6c8e68e46d917a2

will this new node satisfy you @SUPERCILEX ? Or you are thinking on something different?

**Comment by SUPERCILEX** [comment]
That would be perfect, thank you!
