### ISSUE TITLE
Strikethrough in javadoc removed the text

### ISSUE THREAD

**Issue by asfalcone** [Kotlin/dokka#1461]
**Describe the bug**
`~~text~~` should be rendered as `<del>text</del>` but is rendered as `<del></del>` where the text is actually deleted rather than striked through

Using:
```
/**
 * A brutally difficult function to ~~render~~. Good luck!
*/
```

Expected
```
<p>A brutally difficult function to <del>render</del>. Good luck!
</p>
```

Actual
```
<p>A brutally difficult function to 
  <del></del>
. Good luck!
</p>
```
**Installation**
- Operating system: all
- Build tool: cli
- Dokka version: 1.4.10-dev-70

**Comment by asfalcone** [comment]
The DocumentationNode looks like
![image](https://user-images.githubusercontent.com/1848683/92940953-c2f0a080-f41d-11ea-8a29-45ca11927a0a.png)

**Comment by BarkingBad** [comment]
https://github.com/Kotlin/dokka/pull/1397/commits/139a0200a85180866289059bc76c5a6785e31396

should now be OK
