### ISSUE TITLE
Overflow with tables

### ISSUE THREAD

**Issue by quentinguidee** [Kotlin/dokka#1462]
**Describe the bug**
Tables cause display problems

**Expected behaviour**
A correctly formatted table

**Screenshots**
![2020-09-11_22-58](https://user-images.githubusercontent.com/12123721/92975072-0aefe180-f477-11ea-8d47-cb4f8ca1bb61.png)
**(There is text under the bottom gray frame, see the code below)**

**To Reproduce**

1. Type this doc : 
```kt
   /**
     * Example 1
     * Example 2
     *
     * | Example | Example |
     * |---|---|
     * | 1 | Example |
     * | 2 | Example |
     * | 3 | Example |
     * | 4 | Example |
     *
     * Example 5
     * Example 6
     */
```
2. `./gradlew dokkaHtml`
3. Observe (see screenshot). Example 5 + Example 6 are missing (in facts, they are under the gray box)

**Dokka configuration**
Nothing, just the basic installation (see `README.md`)

**Installation**
- Operating system: Linux
- Browsers: Firefox, Chromium
- Build tool: Gradle v6.3
- Dokka version: 1.4.0

**Additional information**
Note that the table is displayed correctly if there is only the table.

**Comment by IgnatBeresnev** [comment]
Looks like this has been resolved for the new HTML UI :) 

![2022-04-27_17-16-36](https://user-images.githubusercontent.com/22685910/165539124-a64b126d-11d6-468f-9849-7f0bbf0f53be.png)
