### ISSUE TITLE
How to produce documentation only for src/main/kotlin in a Java + Kotlin project

### ISSUE THREAD

**Issue by sdeleuze** [Kotlin/dokka#1466]
Hey, I am working on migrating Spring Framework Kdoc from Dokka 0.10 to Dokka 1.4, see the [WIP commit](https://github.com/sdeleuze/spring-framework/commit/dokka).

My current issue is that documentation is generated for both Java and Kotlin code, even if I have specified `sourceRoots.setFrom(file("src/main/kotlin"))`.

Could you please let me know how can I generate the documentation only for Kotlin code, not Java one?

**Comment by sellmair** [comment]
Closing this issue with an answer:
https://github.com/sellmair/spring-framework/tree/dokka-1466
