### ISSUE TITLE
android-gradle-plugin question regarding provided dependency in build.gradle

### ISSUE THREAD

**Issue by frnusmartobjects** [Kotlin/dokka#147]
Shouldn't the provided dependency `provided 'com.android.tools.build:gradle:2.2.0'` in [here](https://github.com/Kotlin/dokka/blob/3da12b4f1d3018a0e4b66d01f2251f89b617854b/runners/android-gradle-plugin/build.gradle) point to the latest android gradle tools '2.3.0' for this plugin to be able to work with the latest Android Studio 2.3 and gradle 3.3? Could this relate to Issue #140 ?

**Comment by semoro** [comment]
@frnusmartobjects Looks like directly related. The version of build tools set as it will be used to obtain classpath for type resolution. Also android-build-tools API changes every major release and such changes needs to be supported in Dokka.

**Comment by frnusmartobjects** [comment]
@semoro Perfect. I guess now is a matter of waiting for a fix. Thank you.

**Comment by semoro** [comment]
Fixed in [0.9.14](https://github.com/Kotlin/dokka/releases/tag/0.9.14)
