### ISSUE TITLE
Alternative markup language

### ISSUE THREAD

**Issue by SalomonBrys** [Kotlin/dokka#148]
Some of us prefer other markup languages to write our documentation.

I personally favour [AsciiDoctor](http://asciidoctor.org/) over Markdown. Which one is better is irrelevent, it's a matter of taste.  
There is a [doclet](https://github.com/asciidoctor/asciidoclet) available that allows us to write JavaDoc in AsciiDoctor.

I think KDoc would greatly benefit from a plugin system that would allow us to change the markdown language.

**Comment by yole** [comment]
KDoc is supported both in the IDE and in the documentation generation tool, and supporting a plugin system that would work in both environments is a non-trivial endeavour. We have no plans to support it at this time.
