### ISSUE TITLE
External links stopped working between 1.4.0-rc and 1.4.0

### ISSUE THREAD

**Issue by bsiegel** [Kotlin/dokka#1490]
For a Dokka configuration that contains one or more valid `externalDocumentationLink` stanzas, with dokka-gradle-plugin 1.4.0-rc, external documentation links are generated correctly (that is, a type that is not part of the library being documented but has documentation via an `externalDocumentationLink` is linked correctly to the external documentation).

Upgrading to 1.4.0 breaks this feature - types are no longer linked to external documentation. The only changes I made were to bump the version from "1.4.0-rc" to "1.4.0", and to replace the following because `configureEach` no longer seems to work:

```diff
    dokkaHtml {
        dependencies {
            dokkaHtmlPlugin("org.jetbrains.dokka:kotlin-as-java-plugin:1.4.0")
        }
        dokkaSourceSets {
-           configureEach {
+           named("main") {
                ...
                externalDocumentationLink {
                    url = new URL("https://square.github.io/okhttp/3.x/okhttp/")
                    packageListUrl = new URL("https://square.github.io/okhttp/3.x/okhttp/package-list")
                }
                ...
```

**Expected behaviour**
Link to types defined in external documentation (e.g. `okhttp.Interceptor`) link to the external documentation for that type (e.g. https://square.github.io/okhttp/3.x/okhttp/okhttp3/Interceptor.html)

**To Reproduce**
Just update a project that was correctly generating external documentation links under 1.4.0-rc to 1.4.0 as described above.

**Dokka configuration**
Described above

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.6
- Dokka version: 1.4.0

**Additional context**
- This is a Java project, but I am using the kotlin-android plugin to expose the source sets to Dokka.
- I have tried dev builds in the 1.4.10 series and they exhibit the same problem (latest tested: dev-72).

**Comment by kamildoleglo** [comment]
Cannot reproduce in 1.4.20, please reopen if the issue persists
