### ISSUE TITLE
Links to the same page in comments are constructed incorrectly

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#1503]
http://dokka-snapshots.s3.eu-central-1.amazonaws.com/master/stdlib/latest/kotlin-stdlib/kotlin-stdlib/kotlin.coroutines/-continuation/index.html#kotlin.coroutines.intrinsics//intercepted/kotlin.coroutines.Continuation[TypeParam(bounds=[kotlin.Any?])]#/PointingToDeclaration/
Link to `Continuation` in comment has `href=".html"` instead of some reasonable value, like `#`

**Comment by BarkingBad** [comment]
I think it is resolved now (or at least more correct), we should reconsider closing this issue
