### ISSUE TITLE
Define equals/hashCode implementations for all documentables that include sourceSets

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/dokka#1507]
On large sources (thousands of files), adding a DClass to a hashset takes multiple milliseconds because hashCode appears to be comparing the entire source tree. Documentables should simply be compared by their DRI.

**Comment by kamildoleglo** [comment]
Documentables have always been compared by their DRIs. Their hashcode implementation is also just the hashcode from the DRI as of now:
https://github.com/Kotlin/dokka/blob/1aba0ec4973d7915caa93f1e9b3146ad82111903/core/src/main/kotlin/model/Documentable.kt#L10
but there was a discussion that they should be in fact compared deeply: 
https://github.com/Kotlin/dokka/pull/667#discussion_r382555806
