### ISSUE TITLE
reuse property description for constructor params

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#151]
it would be nice if I do not have to repeat the documentation for the constructor like in the following example
```kotlin
/**
 * My description, bla bla..
 *
 * @property name The last name of the person.
 *
 * @constructor
 * @param name The last name of the person.
 */
data class Person(val name: String)
```
It should suffice to define `@property`

**Comment by yole** [comment]
The opposite thing works now:
```
/**
 * My description, bla bla..
 *
 * @param name The last name of the person.
 */
data class Person(val name: String)
```

The description of the parameter will be copied to the description of the property.

**Comment by robstoll** [comment]
Good as well, even though the opposite would have the benefit, that the properties can be documented in an interface and we do not need to document anything in addition in a data class implementing the interface
