### ISSUE TITLE
How to create table of content

### ISSUE THREAD

**Issue by XCarbone** [Kotlin/dokka#1513]
**Question**
How can i create a table of content with dokka Kdoc?
I follow this : https://blog.jetbrains.com/kotlin/2020/08/dokka-preview-based-on-kotlin-1-4-0-rc/
But you can see under DOCS that you got a nice table of content but mine doesn't ...

**Screenshots**
![Capture d’écran 2020-09-29 à 12 48 07](https://user-images.githubusercontent.com/26289803/94667471-2419de80-030f-11eb-989a-d64e1676c26a.png)

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.4.1
- Dokka version: 1.4.10
- Android studio

**Comment by sellophane** [comment]
Hi, if I see correctly, judging by the lack of navigation pane, you are simply opening `.html` file with the browser, instead of running them through any server - in that case, js scripts will not run and much of dokka functionality will be missing.

**Comment by XCarbone** [comment]
You right i open the idem.html with the browser so maybe the Js doesn't apply.
Is there a way to use Js in a browser ? or how can i run through a server ?
I am sorry i am very new to web programmation and documentations.
Thanks for you help anyway.

**Comment by XCarbone** [comment]
Ok i found out that i could use mamp to create a local server and it s work perfectly. thanks for your help.
