### ISSUE TITLE
[1.4.20-multimodule-dev-3] Do not list non-overridden default methods in the documentation

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/dokka#1523]
**Describe the bug**

Classes for some reason have their `hashCode`, `equals` and `toString` listed even when they do not override it and do not provide additional documentation.
This is also applicable for implementation via delegation, e.g. https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-array/index.html

**Expected behaviour**
`hashCode`, `toString`, `equals` and delegated methods are not listed.

**To Reproduce**
`kotlinx-serialization` project, branch `dokka-fixed-revisions`, `./gradlew dokkaHtmlMultiModule`

**Dokka configuration**

https://github.com/Kotlin/kotlinx.serialization/blob/dokka-fixed-revisions/gradle/dokka.gradle#L17

**Installation**
- Operating system: macOS
- Build tool: Gradle 6.3
- Dokka version: 1.4.20-multimodule-dev-3

**Comment by kamildoleglo** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/1758
