### ISSUE TITLE
documentationFileName no longer exists for multi-module documentation

### ISSUE THREAD

**Issue by mattmook** [Kotlin/dokka#1530]
**Describe the bug**
The documentation at https://github.com/Kotlin/dokka#multi-module-projects suggests being able to set `documentationFileName` to override the module documentation file name.

`documentationFileName` no longer exists in 1.4.10 - indeed searching the source code in GitHub the only references to it I can find are in the documentation. It was present in the v1.4.0 release.

**Expected behaviour**
`documentationFileName` to exist or documentation to be updated to list the correct way of changing the module documentation file names to use.

**Screenshots**

<img width="601" alt="image" src="https://user-images.githubusercontent.com/182422/95068555-58b9db80-06fd-11eb-8621-42a4ea76c6ea.png">

**To Reproduce**
Use code from documentation in your root build.gradle.kts file.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(buildDir.resolve("dokkaCustomMultiModuleOutput"))
    documentationFileName.set("README.md")
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.6.1
- Dokka version: 1.4.10

**Comment by KotlinIsland** [comment]
[changed here](https://github.com/Kotlin/dokka/commit/02ccae10e3f717c330dae5d87b49a0e72f798905#diff-cc5ba17a06ffd3152085a78cd5b73c8b5672ea7bc5247ce3905c07ce323a5971)

**Comment by KotlinIsland** [comment]
02ccae10e3f717c330dae5d87b49a0e72f798905
