### ISSUE TITLE
[1.4.20-multimodule-dev-7] Requires Java 11

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/dokka#1531]
**Describe the bug**
Running on Java 8, dokka task in Gradle produces a cryptic output:

```
> Task :dokkaHtmlMultiModule FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dokkaHtmlMultiModule'.
> java.nio.file.Files.writeString(Ljava/nio/file/Path;Ljava/lang/CharSequence;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;
```

see also https://github.com/Kotlin/kotlinx.serialization/pull/947#issuecomment-703415268

Running with `--stacktrace` produces more light on reason: 
```
Suppressed: java.lang.NoSuchMethodError: java.nio.file.Files.writeString(Ljava/nio/file/Path;Ljava/lang/CharSequence;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;
```

This method (https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html#writeString(java.nio.file.Path,java.lang.CharSequence,java.nio.file.OpenOption...) is marked as 'Since Java 11', so it's not available in Java 8.

**Expected behaviour**

I'm not sure if this is a desired behavior. If Dokka requires Java 11, then: a) binaries should probably also be compiled with Java 11 target (producing well known 'java class unsupported major.minor version' error) and b) this should be highlighted in README. 

If this is not the case, then it's clearly a bug and dokka should be linked with Java 8 stdlib instead of 11.

**To Reproduce**

`./gradlew dokkaHtmlMultiModule` in kotlinx.serialization project. `JAVA_HOME` should be set to JDK installation with version lower than 11.

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.3
- Dokka version: 1.4.20-multimodule-dev-7

**Comment by kamildoleglo** [comment]
Fixed in `1.4.32`
