### ISSUE TITLE
What is expected output for dokkaHtmlMultiModule?

### ISSUE THREAD

**Issue by mkrussel77** [Kotlin/dokka#1536]
**Question**
I am not sure if the output I'm seeing from the dokkaHtmlMultiModule is correct.

From the documentation.

> DokkaMultiModule depends on all Dokka tasks in the subprojects, runs them, and creates a toplevel page (based on the documentationFile) with links to all generated (sub)documentations

But it doesn't create any top-level index.html file.  It creates `-moudles.html` which has a list of modules and just a link back to this page in the navigation pane.  Clicking on any of the individual modules takes you to a page that is completely independent of all the others.  The navigation pane, shows only the one module and then it's packages.

Is this what should be produced?

Having the root of the documentations be a page called `-modules.html` seems strange.
Also each module page has the module name duplicated in the path.

**Installation**
- Operating system: macOS
- Build tool: Gradle 6.2.2
- Dokka version: 1.4.0

**Comment by lukaszfikustsh** [comment]
I have the same situation. I would like to have navigation between modules. How to achieve it?

**Comment by MarcinAman** [comment]
Hi, for now it is how it should work, but we are working on improving that behavior. The work on that is tracked under: https://github.com/Kotlin/dokka/issues/1402, so i'll close this issue for now.
