### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by paulzhang5511** [Kotlin/dokka#1547]
**Question**

FAILURE: Build failed with an exception.
 What went wrong:
Execution failed for task ':demo:dokkaJavadoc'.
> java.net.SocketException: Connection reset

```kts
plugins {
    id("com.android.library")
    kotlin("android")
    kotlin("android.extensions")
    id("org.jetbrains.dokka") version ("1.4.10")
}

tasks.dokkaJavadoc.configure {
    outputDirectory.set(buildDir.resolve("dokka"))

    dokkaSourceSets {
        named("main") {
            println("start...")
            noAndroidSdkLink.set(false)
            noJdkLink.set(false)
            noAndroidSdkLink.set(false)
            println("end...")
        }
    }
}

```

**Screenshots**
![image](https://user-images.githubusercontent.com/53463972/95652478-c4e47700-0b23-11eb-9499-0acda1f8d525.png)

**Installation**
- Operating system: Windows
- Build tool: Gradle v6.1.1
- Dokka version: 1.14.10

**Additional context**

**Comment by kamildoleglo** [comment]
Could you please confirm if this has been fixed and, if not, post the stacktrace?
