### ISSUE TITLE
Dokka fails to resolve a link to a parameter

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1553]
Example from kotlinx.serialization:
```
/**
 * Decodes and deserializes the given [byte array][bytes] to to the value of type [T] using deserializer
 * retrieved from the reified type parameter.
 */
@OptIn(ExperimentalSerializationApi::class)
public inline fun <reified T> BinaryFormat.decodeFromByteArray(bytes: ByteArray): T =
    decodeFromByteArray(serializersModule.serializer(), bytes)
```
byte array is a unresolved link

**Comment by Alton09** [comment]
I'm seeing the same issue as well.

**Dokka configuration**
I'm using the Android configuration as specified in the readme.

**Installation**

Operating system: macOS
Build tool: Gradle v6.1.1
Dokka version: 1.4.10

**Comment by kamildoleglo** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/1713
