### ISSUE TITLE
Let the maven plugin fail the build if dokka generates a warning

### ISSUE THREAD

**Issue by dibog** [Kotlin/dokka#1556]
**Is your feature request related to a problem? Please describe**
It would be great for CI if the maven Dokka plugin would fail the build if the Dokka raises
a warning. 

**Describe the solution you'd like**
The plugin should be configurable so that for specific warnings (or all) the maven (or Gradle) plugin 
raise a build error, so the build fails on a bad formatted or not documented source code.

**Describe alternatives you've considered**
Is there an alternative to check for missing or wrong formated kotlin docs?

**Comment by kamildoleglo** [comment]
I believe this has been implemented, the configuration argument is called `failOnWarning` 
https://github.com/Kotlin/dokka/blob/6bb04a1ca37ebd972efbb1108d16a7d134619d27/runners/maven-plugin/src/main/kotlin/DokkaMojo.kt#L160

**Comment by dibog** [comment]
Thanks, that is working.
