### ISSUE TITLE
Mention in README there is maven repository with snapshot builds

### ISSUE THREAD

**Issue by filipproch** [Kotlin/dokka#156]
Hi, as releases od Dokka are not so often and we need to use EAP builds (for now with Android for example) I suggest to add mention that there is 
```
maven {
    url "https://dl.bintray.com/kotlin/kotlin-dev"
}
```
which can be used to obtain EAP builds of Dokka

**Comment by Sloy** [comment]
Doesn't look like snapshots are updated anymore :(
The latest version I see there is 0.9.14-eap-3
