### ISSUE TITLE
Short description in Types tab should drop tags and only display description

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1562]
for example:

```
/** @author eaftan@google.com (Eddie Aftandilian) */
public class ArrayEquals extends BugChecker implements MethodInvocationTreeMatcher {
```
Should not display anything in the short description but instead it is `eaftan@google.com (Eddie Aftandilian)`

**Comment by IgnatBeresnev** [comment]
Not able to reproduce for the new HTML UI, short description is empty
