### ISSUE TITLE
Missing Enum method on JDK14 

### ISSUE THREAD

**Issue by arturbosch** [Kotlin/dokka#1577]
**Describe the bug**
We noticed a difference between generating documentation with JDK8/11 and JDK14.
An Enum declaration has a missing method `describeConstable` on JDK 14.
See https://github.com/detekt/detekt/pull/3149

**Expected behaviour**
No differences in documentation when generating with different JDKs.
Kotlin version was not changed.

**Screenshots**
https://github.com/detekt/detekt/pull/3149

**To Reproduce**
1. Check out https://github.com/detekt/detekt/pull/3149
2. Build with JDK 11
3. Build with JDK 14
4. Notice the `verifyDocumentation` task fails on JDK 11

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kt
plugins {
    id("org.jetbrains.dokka")
}

dependencies {
    ...
    dokkaJekyllPlugin("org.jetbrains.dokka:jekyll-plugin")
}

tasks.withType<DokkaTask>().configureEach {
    outputDirectory.set(rootDir.resolve("docs/pages/kdoc"))
}

```

**Installation**
- Operating system: macOS/Linux
- Build tool: Gradle v6.7.0
- Dokka version: 1.4.10

**Additional context**
-

**Comment by IgnatBeresnev** [comment]
[describeConstable()](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Enum.html#describeConstable()) method was introduced in JDK 12, so it's present in JDK14, but it doesn't yet exist in JDK11.

Dokka analyses whatever it finds on its classpath. If you are using JDK11 and you look at methods inherited from `java.lang.Enum`, you will not find `describeConstable()` there. However, if you are using JDK14, you will. Dokka merely documents what it sees, so it is to be expected.

If you don't want to see properties/functions inherited from `java.lang.Enum` or `java.lang.Object`, you can enable `suppressObviousFunctions` configuration property, then there will be no difference when using different JDKs.

As for this particular case, it doesn't look like there's anything we can do with Java, so I'm closing the issue as won't fix.
