### ISSUE TITLE
Side menu not generated

### ISSUE THREAD

**Issue by lukaszfikustsh** [Kotlin/dokka#1588]
**Describe the bug**
I'm generating documentation for multimodule Android project and no matter what I try it generates with an empty side menu 

**Expected behaviour**
I would like to be able to navigate with the drop-down menu.

**Screenshots**
<img width="1524" alt="Zrzut ekranu 2020-10-22 o 17 28 10" src="https://user-images.githubusercontent.com/67113018/96898198-bedd8700-148f-11eb-9b44-a4392077cf88.png">

**Dokka configuration**
apply plugin: 'org.jetbrains.dokka'
dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            moduleName.set("SDK")
            noAndroidSdkLink.set(false)
            suppress.set(false)
            skipDeprecated.set(true)
            includeNonPublic.set(false)
            skipEmptyPackages.set(true)
            sourceRoots.from("${project(':x').projectDir}/src/main/java")
            sourceRoots.from("${project(':y').projectDir}/src/main/java")
            sourceRoots.from("${project(':z').projectDir}/src/main/java")
        }
    }
}

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.1.1/v6.5
- Dokka version: 1.4.10.0/1.4.10.2

**Comment by MarcinAman** [comment]
Hi, do you use a http server to host the documentation?

**Comment by lukaszfikustsh** [comment]
> Hi, do you use a http server to host the documentation?



> Hi, do you use a http server to host the documentation?

Nope, I just opened them on my local device

**Comment by MarcinAman** [comment]
In order to have a fully featured documentation you need to have an http server. The simples one is provided by the intellij when you open an html file and click on the icon of your browser of choice (in the top, right corner)

**Comment by lukaszfikustsh** [comment]
> In order to have a fully featured documentation you need to have an http server. The simples one is provided by the intellij when you open an html file and click on the icon of your browser of choice (in the top, right corner)

Thank you a lot for that response. It works fine with http server!
