### ISSUE TITLE
Javadoc @inheritDoc tag is not handled in HTML output

### ISSUE THREAD

**Issue by eskatos** [Kotlin/dokka#159]
When dokka processes a Java type using the `@inheritDoc` tag in its Javadoc, it is rendered as is in the Dokka HTML output.

I would be expected that it is replaced by inherited documentation or at least link to it.

For an example, see the list of `Inherited Functions` [here](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.api.tasks/-copy/index.html)

**Comment by JWT007** [comment]
I would also like to see support for the @inheritDoc annotation.

I think I saw a post from @yole on another forum saying that `/** {@inheritDoc} */` is superfluous and blows up the code; however, while I get where he is coming from I still would love to see it for the following reasons:

- I harp on my collegues all the time about Javadoc'ing their code - not supporting this results in mish-mash of documented and undocumented methods in a kotlin file
- The presence of the `/** {@inheritDoc} */` at least lets me know that the code author put some thought into documenting the method and decided that the parent documentation was sufficient.

Wouldn't it be possible to both keep the default behavior of inheriting documentation if none is present and supporting the annotation?

**Comment by pdvrieze** [comment]
While mere `/** {@inheritDoc} */` is probably poor code style, it is actually very helpful to partially override inherited javadoc. Either by extending (prepending/appending) the documentation of a specific element (parameter, exception....) or by selectively replacing parts.

**Comment by dsebastien** [comment]
I agree with @pdvrieze, I use {@inheritDoc} a lot exactly for that purpose. It allows to provide additional details, which is particularly interesting when you have different implementations of the same base type.

**Comment by CLOVIS-AI** [comment]
I know I'm a bit late, but I'm interested by this too and since this issue has never been closed, I'd like to have it discussed again.

**Comment by basshelal** [comment]
Little late as well, but I too would also like this for the very same reason @pdvrieze said.
Copying and pasting documentation from the parent is just more documentation to maintain and linking back to the parent's documentation is a little inconvenient.

**Comment by hXtreme** [comment]
Is this feature even being considered?

It seems very helpful in extending base class/interface documentation as others have already pointed out.

**Comment by kamilok1965** [comment]
It should be fairly easy to do as a plugin when the `0.11.0` is released
