### ISSUE TITLE
Task dokkaHtmlMultiModule doesn't provide search on the index page

### ISSUE THREAD

**Issue by e5l** [Kotlin/dokka#1593]
**Is your feature request related to a problem? Please describe**

We're going to migrate https://api.ktor.io to the new Dokka version. Right now we have a top-level cross-module search. In the new Dokka version, we have only the modules list without any search. It would be nice to have it there.

**Comment by MarcinAman** [comment]
Fixed by: https://github.com/Kotlin/dokka/pull/1631
