### ISSUE TITLE
Add version list on the title page of dokkaHtmlMultiModule and allow to add new version incrementally

### ISSUE THREAD

**Issue by e5l** [Kotlin/dokka#1594]
**Is your feature request related to a problem? Please describe**

We're going to migrate https://api.ktor.io to the new Dokka version. Right now we can generate documentation for a specific version and put it under the version folder. It allows users to inspect all versions we generate documentation for.

**Comment by MarcinAman** [comment]
Neat idea 👍 

For sake of tracking issues related issues:
Similar suggestion for all dokkaHtml tasks: #1584

**Comment by MarcinAman** [comment]
Fixed by: https://github.com/Kotlin/dokka/pull/1654
