### ISSUE TITLE
The DRI for inherited properties is incorrect.

### ISSUE THREAD

**Issue by asfalcone** [Kotlin/dokka#1598]
**Describe the bug**
The DRI for inherited properties appears to be incorrect. Possibly related to #983 

For a class called `One` that extends a class called `Five` the model is as follows:

![image](https://user-images.githubusercontent.com/1848683/97462760-730a6200-1915-11eb-8fcc-e4a1852804ca.png)

One (the Class) has fiveFunction (a function) with a DRI that points to Five (the class) and a fiveProperty (a property) with a DRI that points to One (the class) even though both fiveFunction and fiveProperty are defined in Five (the class)

**Expected behaviour**
Properties and functions that are inherited from the same class should have the same base DRI

**To Reproduce**
```
open class One() : Five() {
    /** Property docs. */
    val v = 0

    /** Function docs. */
    fun w() = Unit
}

open class Five {
    /** Five Function docs. */
    fun fiveFunction() = Unit

    /** Five property docs. */
    val fiveProperty = 5
}
```

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: CLI
- Dokka version: 1.4.10.2-dev-19

**Comment by kamildoleglo** [comment]
This is not a bug, DRIs have been designed this way from the start to differentiate objects. 
In fact implementing them like in this proposal would be possible but memory-ineffective as we would have to assert the referential integrity between objects with the same DRI. 
If you want to check which property/method/etc. is inherited, you should have this information available in the `extra` field
