### ISSUE TITLE
Safari does not render links in the sidebar

### ISSUE THREAD

**Issue by Kordyjan** [Kotlin/dokka#1609]
The problem was discovered by users of scala3doc but is also present in the latest release of dokka. 
![obraz](https://user-images.githubusercontent.com/11855167/98563510-8e795380-22ab-11eb-83a4-e4c07fb5710c.png)

**Comment by Kordyjan** [comment]
Original issue: https://github.com/lampepfl/scala3doc/issues/231

**Comment by romanowski** [comment]
The bug applies to older version of chome (checked on 69.0.3497.100) as well.

**Comment by rbares** [comment]
Applies to latest chrome (86.0.4240.198) when accessed from local filesystem. I assume this is also the reason why the filter is broken. Javadoc output appears to behave correctly in these circumstances - including search
