### ISSUE TITLE
Function parameters order is not conform

### ISSUE THREAD

**Issue by pmariac** [Kotlin/dokka#1611]
**Describe the bug**
When documenting a function, the parameters order is not conform.

**Expected behavior**
Parameters should appear in the function order, not in alphabetical order, this is particularly confusing when the function use a lambda as the last parameter.

**Screenshots**
```
/**
 * Check for param ordering.
 *
 * @param param the first param
 * @param otherParam the second param
 * @param init the last param, trailing lambda
 */
public fun orderedParams(param: Double, otherParam: Double, init: () -> Unit) {

}
```

![image](https://user-images.githubusercontent.com/28013510/98659174-29be0780-2344-11eb-8b53-d82e270f9ba8.png)

**Dokka configuration**
Version 1.4.10

**Comment by MarcinAman** [comment]
Hi, it should be a fairly simple thing to do somewhere here: https://github.com/Kotlin/dokka/blob/07e43676665bdc009e135b767e6d43c536b413fa/plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt#L298

Would you mind submitting a PR and a test or two?

**Comment by gzoritchak** [comment]
Hi @MarcinAman,

I'm working with @pmariac and currently having a fork of Dokka to work on plugins. 

The fix is indeed quite easy, but the test no ;-). Can you give a hint on the location where the test should be added?

**Comment by MarcinAman** [comment]
Sure, that will work. Also you can do it in the `ContentForParamsTest`

**Comment by MarcinAman** [comment]
Also: if you would like to share your plugin with the community, we have a plugins list: 
https://kotlin.github.io/dokka/1.4.10.2/community/plugins-list/
https://github.com/Kotlin/dokka/blob/master/docs/src/doc/docs/community/plugins-list.md
