### ISSUE TITLE
Provide a configuration option to suppress equals, hashCode, toString and componentX functions

### ISSUE THREAD

**Issue by gzoritchak** [Kotlin/dokka#1613]
**Is your feature request related to a problem? Please describe**
Currently, a marker interface generates documentation for `equals()`, `hashCode()`, `toString()` functions. 

**Describe the solution you'd like**
An option (name to find) should disable this documentation. 

The documentation of data class functions `component1()`, `component2()`..., `copy()` should also be disabled by configuration.

**Comment by sevar83** [comment]
I thought the `@suppress` markup was supposed to do that but couldn't make it work.

**Comment by gzoritchak** [comment]
> I thought the `@suppress` markup was supposed to do that but couldn't make it work.

I created another issue for the fact that `@suppress` doesn't work.
https://github.com/Kotlin/dokka/issues/1612

(I know you saw it, but it's just to inform other guys ).
