### ISSUE TITLE
dokkaJavadoc incorrectly renders top-level const val

### ISSUE THREAD

**Issue by rbares** [Kotlin/dokka#1624]
**Describe the bug**
Javadoc output displays these as private final fields on the generated `{Filename}Kt` class, with final getters.

**Expected behaviour**
Javadoc output displays these as public static final fields on the generated `{Filename}Kt` class, without getters, reflecting the generated bytecode.

**To Reproduce**
Create Kt file with the following content:
```kotlin
const val FIRST = "String"
const val SECOND = 2
```

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dependencies {
    classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.4.10.2"
}
...
apply plugin: 'org.jetbrains.dokka'
```

**Installation**
- Operating system: Windows
- Build tool: Gradle 6.3
- Dokka version: 1.4.10.2

**Comment by MarcinAman** [comment]
Hi, this should be a fairly simple thing to do (probably in `KotlinToJavaConverter.kt`). Would you mind contributing a PR? I can then provide you with a custom build from space packages repository.

**Comment by rbares** [comment]
absolutely, will aim to make a start Wednesday

**Comment by bishiboosh** [comment]
I'm actually in the process of implementing that as part of #1284 (as I've done quite a bit of work on `KotlinToJavaConverter`), I can extract just this part as a PR if needed

**Comment by rbares** [comment]
Hadn't started on it yet so feel free to resolve as appropriate. Thanks for the heads up
