### ISSUE TITLE
dokka-maven-plugin ignores non-standard maven local repo

### ISSUE THREAD

**Issue by adangel** [Kotlin/dokka#1625]
**Describe the bug**
When you run your maven build and use a local maven repo at a non-standard location (not `~/.m2/repository`), then dokka-maven-plugin still downloads dependencies there. If you want to keep your dependencies separate, that's not possible then.

**Expected behaviour**
When Maven is configured or instructed to use a specific location for the local maven repository, then the default local repo location should not be modified.

**To Reproduce**
* A maven project with the dokka-maven-plugin added
* clear your default local maven repo location (e.g. `mv ~/.m2/repository ~/.m2/repository-old`)
* run `mvn clean verify -Dmaven.repo.local=$(pwd)/m2repo`

Now all dependencies should be placed into `./m2repo` and `~/.m2/repository` should not exist.

**Dokka configuration**

```xml
            <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>${dokka.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>javadocJar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Installation**
- Operating system: Linux
- Build tool: Maven
- Dokka version: 1.4.10.2

**Additional context**
The path `~/.m2/repository` seems to be hard coded here: https://github.com/Kotlin/dokka/blob/eba25082251b5cc9b6e398e780b8092f2bb9fb9c/runners/maven-plugin/src/main/kotlin/DokkaMojo.kt#L268

**Comment by MarcinAman** [comment]
Hi, since you already debugged what is the cause of this behaviour would you mind contributing a PR for that?

**Comment by adangel** [comment]
@MarcinAman I've created a PR, see #1644
