### ISSUE TITLE
includeNonPublic.set(false) doesn't omit Java package-private classes

### ISSUE THREAD

**Issue by Flyentology** [Kotlin/dokka#1629]
**Describe the bug**
I have a module mixed with java/kotlin classes in Android project. Generating docs with includeNonPublic set to false still adds java package-private classes to the output. 

**Expected behaviour**
Java package-private classes not visible in the html output.

**To Reproduce**
1. Create TestClassA.java:

```java
package com.example.test;

class TestClassA {

    private void testMethod1() {
    }

    public void testMethod2() {
    }
}
```
2. Run ./gradlew app:dokkaHtml
3. Output should not contain TestClassA

**Screenshots**
![image](https://user-images.githubusercontent.com/37186104/99290081-1e844380-283e-11eb-88f5-f1e8a6dd7e06.png)
![image](https://user-images.githubusercontent.com/37186104/99290120-27751500-283e-11eb-8884-15b60244b845.png)

**Dokka configuration**

Module configuration:

```groovy
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

apply from: '../scripts/dokka/dokka.gradle'
```
dokka.gradle:

```groovy
apply plugin: 'org.jetbrains.dokka'

dokkaHtml {
    outputDirectory.set(new File("$rootProject.rootDir/dokka/$project.name"))

    dokkaSourceSets {
        configureEach {
            jdkVersion.set(8)
            includeNonPublic.set(false)
            skipEmptyPackages.set(true)
        }
    }
}
```

Main build.gradle:
```groovy
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.4.10.2")
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.7
- Dokka version: 1.4.10.2

**Additional context**
I see the this issue from version 1.4.0-rc.

**Comment by Jova-art** [comment]
Yes
