### ISSUE TITLE
How do I create individual sets of doc per Android flavour with Dokka (1.4.x) ?

### ISSUE THREAD

**Issue by hkhc** [Kotlin/dokka#1634]
**Question**
How do I create individual sets of doc per Android flavour?

Let say we have an Android library project that generates two different flavours, which based on different combinations of source sets.

Then I want to have a doc site for each of the flavours, which only refers to the source set of that particular flavour.

How do we do that with Dokka 1.4.x?

With Dokka 0.10 I am free to create my custom Dokka tasks. However Dokka 1.4.x created and configured in DokkaPlugin and I have no way to create a properly configured DokkaTask of my own.

**Comment by kamildoleglo** [comment]
You can also do that in 1.4.x ☺️ 
You can just create a separate dokka task and add all required plugins: http://kotlin.github.io/dokka/1.4.10.2/user_guide/gradle/usage/#applying-plugins

**Comment by xerus2000** [comment]
Hey, I think I have the same issue: I have created a custom sourceSet, and would now like to create a documentation jar for it. However, I don't see how I might change the inputs. Still using `0.10.1`.

**Comment by hkhc** [comment]
@xerus2000 Turn out here is my solution to create a custom Dokka task. One for each combination of sourceset

```
project.tasks.register("MyCustomDokka", DokkaTask::class.java) {
    dokkaSourceSets.create("MyCustomSourceSets") {
        sourceRoots.setFrom(dir1, dir2, ...)
        ... further customization to DokkaTask
    }
}
```

**Comment by xerus2000** [comment]
Didn't even know about dokkaSourceSets, thanks :)
