### ISSUE TITLE
externalDocumentationLinks not working 

### ISSUE THREAD

**Issue by asfalcone** [Kotlin/dokka#1637]
**Describe the bug**
Configuring externalDocumentationLinks either via gradle plugin or Kotlin configuration does not resolve any external links

**To Reproduce**
[This project](https://github.com/chrisbanes/accompanist/pull/151/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L131 it updating to 1.4.10 from an older version and now links don't resolve

**Dokka configuration**
Gradle config in the link above 

Kotlin config, a test:
```
val extLinks = listOf(
            ExternalDocumentationLink(url = "https://developer.android.com/reference/", packageListUrl = "https://developer.android.com/reference/package-list"),
            ExternalDocumentationLink(url = "https://guava.dev/releases/18.0/api/docs/", packageListUrl = "https://guava.dev/releases/18.0/api/docs/package-list")
        )

        val configuration = dokkaConfiguration {
            sourceSets {
                sourceSet {
                    val sources = File(sourceDir).absoluteFile
                    check(sources.isDirectory) { "$sources does not exist or is not a directory" }
                    sourceRoots = listOf(sources.absolutePath)
                    classpath += listOfNotNull(jvmStdlibPath)
                    externalDocumentationLinks = extLinks
                    noStdlibLink = false
                    noJdkLink = false
                }

            }
            failOnWarning = true
        }
```
from a class that extends `AbstractCoreTest()`

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle and CLI
- Dokka version: 1.4.10

**Comment by kamildoleglo** [comment]
`sourceSets{}` does not configure DokkaSourceSets but rather the Gradle ones. The correct closure is `dokkaSourceSets {}`. Also all properties are Gradle's Properties, so `=` probably won't work, `.set()` should be used instead
