### ISSUE TITLE
Left navigation + search

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1647]
- Left navigation should include all entries that have pages
- Search should allow for better searching in a form of `<module>.<package>.<phrase>` or with dropping a module
- Search should have some sort of information about a type of searched entry (eg. icon for package, module, enum etc.)

**Comment by IgnatBeresnev** [comment]
> Left navigation should include all entries that have pages

Has been implemented in 1.7.20+

> Search should have some sort of information about a type of searched entry (eg. icon for package, module, enum etc.)

Has been implemented in 1.7.20+

> Search should allow for better searching in a form of <module>.<package>.<phrase> or with dropping a module

Should be improved as part of #2864

___

I'll close the issue for now as 2/3 items have been implemented and the last one has a separate issue for it.
