### ISSUE TITLE
JDK types not linked for Javadoc output in 0.9.14

### ISSUE THREAD

**Issue by andreihh** [Kotlin/dokka#165]
In Dokka 0.9.14, JDK types are not linked (i.e., they appear as `java.lang.String` with no link) for the following gradle task configuration:

```
dokka {
    moduleName = project.name
    includes = ['Module.md']
    impliedPlatforms = ['JVM']
    jdkVersion = 7

    outputFormat = 'javadoc'
    outputDirectory = javadoc.destinationDir
}
```

However, if I change the `outputFormat` to `'html'`, it works fine.

**Comment by semoro** [comment]
This mainly a problem of Javadoc doclet and API itself 
I've spent some time investigating fix possibility, a partial fix can be applied there (it's impossible to make Javadoc correctly link types to Kotlin-like docs)
Anyway it's planned for future release (>0.9.17)

**Comment by andreihh** [comment]
Thanks for the update! I'd love to see a fix soon, generating Javadocs seems like an essential feature for library developers who want to make Java-interoperable libraries.

**Comment by semoro** [comment]
You can check or even contribute to the fix at https://github.com/Kotlin/dokka/tree/javadoc-ext-links-experiments

**Comment by camdenorrb** [comment]
Any updates?

**Comment by GaborPeto** [comment]
Dokka still only links JDK types `outputFormat` is 'html'. It does not work with `javadoc` in 0.9.17.
This is a very old issue. Is there an update on it?

**Comment by Kordyjan** [comment]
It works in the new javadoc.
