### ISSUE TITLE
valueOf and values are missing on enums in Kotlin

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1656]
`valueOf` and `values` are not present when we look at the documentation of a kotlin enum

**Comment by vparashchak** [comment]
Hi, can someone, please tell how to avoid these warnings now:
Undocumented: com.example/ExampleEnum/values/#/ (androidJvm)
Undocumented: com.example/ExampleEnum/valueOf/#java.lang.String/ (androidJvm)

**Comment by IgnatBeresnev** [comment]
@vparashchak hi! What version of Dokka are you using? Is it reproducible on 1.6.10/1.6.21?

**Comment by IgnatBeresnev** [comment]
@vparashchak I'll have a look, thanks. I'm afraid at the moment there's nothing you can do from your side, I think Dokka should skip such methods, I'm surprised it doesn't already. 

There are some rules in [ReportUndocumentedTransformer](https://github.com/Kotlin/dokka/blob/ef1afa98dfd48a893319b5b139fb69365dcb7088/plugins/base/src/main/kotlin/transformers/documentables/ReportUndocumentedTransformer.kt#L28), one more needs to be added.

**Comment by vparashchak** [comment]
@IgnatBeresnev Thanks!

**Comment by vparashchak** [comment]
Hi @IgnatBeresnev. I made another investigation today and understood that the library reports undocumented values() and valueOf() methods only for Java enums.

**Comment by vparashchak** [comment]
@IgnatBeresnev thank you for looking into this. I decided to convert all my enums from Java to Kotlin and no issues on my side anymore ;)
