### ISSUE TITLE
Classes/functions in default package not generated with 0.9.14

### ISSUE THREAD

**Issue by FredDeschenes** [Kotlin/dokka#166]
I can't seem to get classes or functions located in the default package to have their documentation generated. This used to work with 0.9.13.

I'm using the Gradle plugin if this changes anything.

**Comment by JWT007** [comment]
I can confirm that the same problem exists with the dokka-maven-plugin 0.9.15

**Comment by Kordyjan** [comment]
It works in 1.4.0
