### ISSUE TITLE
DRI clash in KotlinAsJava for generated getters and setters

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#1663]
**Describe the bug**
Kotlin as Java generates getters and setters for properties with clashing DRI

**Expected behaviour**
Generated DRIs should probably contain `get` and `set` prefixes

**To Reproduce**
Reproducible by 
```
var CanBeDisabled.isEnabled: Boolean
    get() = isDisabled.not()
    set(value) {
        isDisabled = value.not()
    }
```
in https://github.com/Hexworks/zircon

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
    create<DokkaTask>("dokkaHtmlAsJava") {
        val dokka_version: String by project
        dependencies {
            plugins("org.jetbrains.dokka:kotlin-as-java-plugin:$dokka_version")
        }
    }
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.7/KotlinAsJavaPlugin
- Dokka version: 1.4.20

**Additional context**
Most probably `DProperty.javaAccessors()` is failing

**Comment by adam-arold** [comment]
What's a DRI? I looked it up and I think it is not *Dietary Reference Intakes* nor *Dirty Rotten Imbecibles*. 😄

**Comment by kamildoleglo** [comment]
It stands for Dokka Resource Identifier https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/links/DRI.kt

*Dirty Rotten Imbecibles* is superb though, we should consider renaming 🤔

**Comment by adam-arold** [comment]
Was this fixed or is it a won't do?

**Comment by adam-arold** [comment]
@kamildoleglo ping

**Comment by kamildoleglo** [comment]
Sorry, didn't see the previous message. This issue was fixed some time ago ☺️
