### ISSUE TITLE
Proper Way to Color Text (HTML not working)

### ISSUE THREAD

**Issue by piacenti** [Kotlin/dokka#1665]
**Question**
What is the proper way to color documentation text?

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.6.1
- Dokka version: 1.4.20

**Additional context**
I have a class that performs highlighting and I would like to add an example of what the highlighted stuff should look like in the docs. Markdown doesn't supports coloring directly through any custom syntax but it should through html. However, no html I've tried inputting seems to render correctly. 
Something as simple as 
```
*
*<span style="color:darkgoldenrod">test</span>
*
```
renders as plain html rather than rendered html

**Comment by msink** [comment]
This is not supported on github:
https://github.com/github/markup/issues/369

**Comment by MarcinAman** [comment]
Possible work-around would be to include an image as this is supported by markdown

**Comment by piacenti** [comment]
@MarcinAman that's what I'm doing for now
