### ISSUE TITLE
Is it possible that the alpha project warning causes a build with failOnWarning.set(true) to fail

### ISSUE THREAD

**Issue by nk-coding** [Kotlin/dokka#1668]
**Question**
Is it possible that the alpha project warning causes a build with `failOnWarning.set(true)` to fail

**Installation**
- Operating system: Windows
- Build tool: Gradle v6.7.1
- Dokka version: 1.4.20

**Additional context**
The build failed with `failOnWarning.set(true)`, and I could not find any other warning in the log. I did not see any other warning on the console than `Dokka 1.4.* is an alpha project`.  
If the build failure could be caused by that warning, is this intended? Is it possible to prevent this from happening? Because if not, it would be basically impossible to use the alpha in combination with failOnWarning set to true

**Comment by MarcinAman** [comment]
Oh, that was a quite unexpected bug. I've fixed it and it should be in the next release/nightly
