### ISSUE TITLE
IntDef Annotation comments not showing under javadoc generator

### ISSUE THREAD

**Issue by jsong** [Kotlin/dokka#1672]
**Describe the bug**
When build the dokka doc using dokkaJavadocCollector, the code comments not showing, however, it shows correctly under dokkaHtmlMultiModule.

For eg: 

```java
import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import static com.sample.model.Month.JAN;
import static com.sample.model.Month.FEB;
import static com.sample.model.Month.INVALID

/**
 * Annotation class that defines the Months.
 */
@Retention(RetentionPolicy.RUNTIME)
@IntDef({JAN, FEB,INVALID})
public @interface Month {
    /**
     * Month: JAN - First Month.
     */
    int JAN = 1;

    /**
     *Month: FEB - Second Month.
     */
    int FEB = 2;

    /**
     * Month: Not set
     */
    int INVALID = -1;
}
```

**Expected behaviour**
Code comments showing correctly under javadoc generator.

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
Always 

**Dokka configuration**

```groovy
dokka { 
    outputFormat = 'html'
    ...
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.6.0
- Dokka version: 0.14.20

**Additional context**
Add any other context about the problem here

**Comment by MarcinAman** [comment]
According to the docs this annotation is not annotated with `@Documented` so dokka wont display it in final documentation: https://developer.android.com/reference/androidx/annotation/IntDef
