### ISSUE TITLE
Sometimes pathToRoot not defined in safari

### ISSUE THREAD

**Issue by lukaszfikustsh** [Kotlin/dokka#1673]
**Describe the bug**
the variable￼ pathToRoot￼ in￼ navigation-loader.j￼s is not always defined in safari on page refresh resulting in the side-menu disappearing

 Our hacky workaround is adding a 100ms timeout before calling￼fetch(pathToRoot + "navigation.html"

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
apply plugin: 'org.jetbrains.dokka'
dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            moduleName.set("XXX")
            noAndroidSdkLink.set(false)
            suppress.set(false)
            skipDeprecated.set(true)
            includeNonPublic.set(false)
            skipEmptyPackages.set(true)
            sourceRoots.from("${project(':xxx1').projectDir}/src/main/java")
            sourceRoots.from("${project(':xxx2').projectDir}/src/main/java")
            sourceRoots.from("${project(':xxx3').projectDir}/src/main/java")
        }
    }
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.1.1/v6.5
- Dokka version: 1.4.10.0/1.4.10.2

**Comment by MarcinAman** [comment]
Hi, did you experience the same issue with the new version (1.4.20), i did change the order of fetching items there
