### ISSUE TITLE
Kotlin dokka generates javadoc does not recognize @author tags

### ISSUE THREAD

**Issue by L-bo** [Kotlin/dokka#1677]
**Question**
Your question

**Screenshots**
If applicable, add screenshots to help explain your problem

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v5.6.0/Maven/Cli/3rd party plugin 
- Dokka version: 0.10.0

**Additional context**
Add any other context about the problem here

Kotlin dokka generated javadoc does not recognize the @author tag, but generated Html does not have this problem

**Comment by MarcinAman** [comment]
Closing in favour of: https://github.com/Kotlin/dokka/issues/1770
