### ISSUE TITLE
Dokka 1.4.20 in mutlimodule gradle setup fail build with "GC overhead limit exceeded"

### ISSUE THREAD

**Issue by IRus** [Kotlin/dokka#1680]
Dokka 0.10.1 - works fine
Dokka 1.4.20 - fails with GC overhead limit exceeded. [Migration commit](https://github.com/Heapy/komodo/commit/24f960dfa51494e33498ac8d810e321254fa48b8). Build is extremely slow when generating javadoc/html.
Increasing heap size (`org.gradle.jvmargs=-Xmx512m`) helps to process more modules, but eventually build fails. 

JDK: openjdk8
Kotlin: 1.4.20
OS: Ubuntu bionic

Dokka setup:

```
private fun Project.dokkaJavadocJar(): TaskProvider<Jar> {
        return project.tasks.register<Jar>("dokkaJavadocJar") {
            group = "documentation"
            val dokkaJavadoc = project.tasks.named<DokkaTask>("dokkaJavadoc")
            dependsOn(dokkaJavadoc)
            from(dokkaJavadoc.flatMap { it.outputDirectory })
            archiveClassifier.set("javadoc")
        }
    }

    private fun Project.dokkaHtmlJar(): TaskProvider<Jar> {
        return project.tasks.register<Jar>("dokkaHtmlJar") {
            group = "documentation"
            val dokkaHtml = project.tasks.named<DokkaTask>("dokkaHtml")
            dependsOn(dokkaHtml)
            from(dokkaHtml.flatMap { it.outputDirectory })
            archiveClassifier.set("html-doc")
        }
    }
```

Example build: https://travis-ci.com/github/Heapy/komodo/jobs/463208617

**Comment by MarcinAman** [comment]
For now the work-around would be to set `-Xmx1g`.
As dokka is current state is a fairly new project it takes a little bit more memory. We are aware of the issue and will work on optimising it in the future
