### ISSUE TITLE
Dokka doesn't link to Android SDK classes

### ISSUE THREAD

**Issue by Arasthel** [Kotlin/dokka#169]
Hello, thank you for your great work with this tool!

I was just publishing an Android library written in Kotlin and trying to generate some docs with dokka, resulting in this:

![](https://i.imgur.com/2F9cKcy.png)

I've tried linking with the Android reference like this:

```groovy
externalDocumentationLink {
    url = new URL("https://developer.android.com/reference/")
}
```
Apparently, there are no errors as the build succeeds, but the result is what you see in the image. Every class on the Android SDK is shown as **\<ERROR CLASS>**. 

Am I doing something wrong?

**Comment by connected-tlip** [comment]
I have the same issue trying to link to RxJava's docs:
```groovy
externalDocumentationLink {
    url = new URL ("http://reactivex.io/RxJava/1.x/javadoc")
    packageListUrl = new URL ("http://reactivex.io/RxJava/1.x/javadoc/package-list")
}
```

**Comment by semoro** [comment]
@Arasthel Hello, please make sure you using `apply plugin: 'org.jetbrains.dokka-android'` and 
```
buildscript {
    dependencies {
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.14"
    }
}
```

**Comment by semoro** [comment]
@connected-tlip 
Could you provide full Dokka task configuration? 
Are RxJava added to your dependencies block for the project on which Dokka task are applied?

**Comment by Arasthel** [comment]
It's defined on project-level `build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.1.2-4'
    ext.support_library_version = '25.3.1'
    ext.dokka_version = '0.9.14'
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:$dokka_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.5'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

And I have the `apply plugin` line on the `build.gradle` of the library module.

**Comment by connected-tlip** [comment]
I have everything in the project-level `build.gradle`, and I'm adding submodules to `sourceDirs`:

```groovy
buildscript {
    ext {
        kotlinVersion = '1.1.2-3'
        dokkaVersion = '0.9.14'
    }
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.4.0-alpha7'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:${dokkaVersion}"
    }
}
apply plugin: 'org.jetbrains.dokka'

dokka {
    outputFormat = 'javadoc'
    outputDirectory = "${projectDir}/dokka-generated"
    processConfigurations = []

    sourceDirs += files('ui/src/main/kotlin')
    sourceDirs += files('presentation/src/main/kotlin')

    externalDocumentationLink {
        url = new URL ("http://reactivex.io/RxJava/1.x/javadoc")
        packageListUrl = new URL ("http://reactivex.io/RxJava/1.x/javadoc/package-list")
    }
}
```
The hope is that I can run `dokka` on the project level and generate documentation for all the modules combined together.

**Comment by semoro** [comment]
@connected-tlip It's another issue, please see #157

**Comment by semoro** [comment]
@Arasthel 
How did you run gradle? Which tasks? I'd use 'assemble dokka'. 
Can you provide minimal build.gradle of your library?

**Comment by Arasthel** [comment]
This is my library's build.gradle: https://ghostbin.com/paste/3ky2o

I also modified `bintrayv1.gradle` to tell the task that creates the -javadoc jar to use the `/docs` folder.

This is the output os executing `./gradlew :spannedgridlayoutmanager:dokkaJavadoc`: https://ghostbin.com/paste/s66p3

**Comment by semoro** [comment]
@Arasthel 
The problem is the type of task, you should use `task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaAndroidTask) {` for Android, also sourceDirs not needed when it set properly.

**Comment by semoro** [comment]
We need to clarify this in the readme.

**Comment by Arasthel** [comment]
That fixed it! Thanks, everything works as it should now.

**Comment by connected-tlip** [comment]
@semoro My issue isn't that I cannot link between different modules, it's that external documentation isn't linking event with `externalDocumentationLink`

for example, 
val statusObservable: Observable<Int>

```
val statusObservable: <ERROR CLASS><Int>
```

**Comment by semoro** [comment]
@connected-tlip `<ERROR CLASS>` means that Dokka's Internal Kotlin Compiler unable to detect such class in Dokka classpath.
It is defined by `processConfigurations`, so if you set them to empty list, no dependencies will be processed, and all classes that are external to your sourceDirs will be marked `<ERROR CLASS>`.

Now you can define some custom configuration on your root project and put it in `processConfigurations` of Dokka. 
Other possible (And more elegant) way is to specify full configuration path in `processConfigurations`, like ` [ ':subproject:compile' ] `, but unfortunately it not supported by Dokka yet.

See example project of first way I've attached: 
[example.tar.gz](https://github.com/Kotlin/dokka/files/1058856/example.tar.gz)

**Comment by DougSig** [comment]
I'm using 0.9.15, compiling from source (in order to add services) and running using the jar. What is the right way to add Android SDK links? Right now, I'm running:

java -jar dokka-fatjar.jar <project source directory> -format <my custom format> -output <output dir> **-links https://developer.android.com/reference/^https://developer.android.com/reference/package-list^^https://developer.android.com/reference/android/support/^https://developer.android.com/reference/android/support/package-list**

...and it's not finding the Android SDK classes. Any ideas?
