### ISSUE TITLE
Dokka Gradle task should not relay progress logging to Gradle's lifecycle level

### ISSUE THREAD

**Issue by eskatos** [Kotlin/dokka#1690]
**Describe the bug**
Dokka Gradle task is too verbose and clutters the build output.

The Dokka Gradle task currently relays all progress logging to the Gradle lifecycle level:
https://github.com/Kotlin/dokka/blob/afb1f44a76558c6997558b64a766e2f7bc2a9d36/runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt#L94

FWIW, the Dokka Maven goal does this differently and relays all progress logging to the info level:
https://github.com/Kotlin/dokka/blob/afb1f44a76558c6997558b64a766e2f7bc2a9d36/runners/maven-plugin/src/main/kotlin/MavenDokkaLogger.kt#L12

**Expected behaviour**
Running the Dokka Gradle task doesn't show all progress logging in the build output by default.
Running Gradle with `--info` shows Dokka's progress logging.

**Comment by eirnym** [comment]
@eskatos there was a [PR](https://github.com/Kotlin/dokka/pull/2915). Unfortunately it has been rejected

**Comment by whyoleg** [comment]
[Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html) doesn't log in lifecycle: https://github.com/Kotlin/dokka/pull/3833
