### ISSUE TITLE
Execution failed for task ':dokkaHtml'. com/intellij/openapi/roots/ProjectFileIndex

### ISSUE THREAD

**Issue by elect86** [Kotlin/dokka#1697]
**Describe the bug**

On Travis MacOsX, we get the [following error](https://travis-ci.com/github/scenerygraphics/scenery/jobs/471770996):
```
> Task :dokkaHtml FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':dokkaHtml'.
> com/intellij/openapi/roots/ProjectFileIndex
```

If I skip it, the [very next error](https://travis-ci.com/github/scenerygraphics/scenery/jobs/471810655) is:
```
> Task :dokkaJavadoc FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':dokkaJavadoc'.
> com/intellij/openapi/roots/ProjectFileIndex
```

**Expected behaviour**
Flawless compilation

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
    dokkaHtml {
        dokkaSourceSets.configureEach {
            sourceLink {
                localDirectory.set(file("src/main/kotlin"))
                remoteUrl.set(URL("https://github.com/scenerygraphics/scenery/tree/master/src/main/kotlin"))
                remoteLineSuffix.set("#L")
            }
        }
    }
```

**Installation**
Travis Mac, [here](https://travis-ci.com/github/scenerygraphics/scenery/jobs/471826712#L9-L35)

**Additional context**

The only workaround I found is to simply skip `:dokkaHtml` and `:dokkaJavadoc` with:

`onlyIf { !(System.getenv("TRAVIS")?.toBoolean() == true && Os.isFamily(Os.FAMILY_MAC)) }` 

I tried to max out MaxMetaspaceSize to 2g in case it was this [issue](https://github.com/Kotlin/dokka/issues/1405), but it wasnt unfortunately..

**Comment by kamildoleglo** [comment]
Could you please post a full stacktrace?

**Comment by MarcinAman** [comment]
Also i tried to reproduce this issue on travis but the build passes after removing `isCi` flag from build.gradle: https://travis-ci.com/github/MarcinAman/scenery/builds/213269611

**Comment by elect86** [comment]
Hi,

sorry, but it turned out that dokka tasks are not necessary on CI, so we skip them completely
