### ISSUE TITLE
[1.4.20] DokkaMultiModuleTask not writing to outputDirectory

### ISSUE THREAD

**Issue by chrisbanes** [Kotlin/dokka#1698]
**Describe the bug**

I'm using the following code to merge all module docs together:
```
tasks.withType(org.jetbrains.dokka.gradle.DokkaMultiModuleTask).configureEach {
    outputDirectory = rootProject.file('docs/api')
    failOnWarning = true
}
```

This worked on 1.4.10.+, but has stopped working with the upgrade to 1.4.20. 

**Expected behaviour**
All modules docs are in the set directory.

**Dokka configuration**
https://github.com/chrisbanes/accompanist/blob/main/build.gradle

**Comment by MarcinAman** [comment]
Hi, i have just checked out your project and the documentation is generated properly and put under `docs/api`. 
The only thing i did after cloning the main branch was:
```
diff --git a/buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt b/buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
index e6f3837..a763cce 100644
--- a/buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
+++ b/buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
@@ -36,7 +36,7 @@ object Libs {
     }
 
     object Dokka {
-        private const val version = "1.4.10.2"
+        private const val version = "1.4.20"
         const val gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:$version"
     }
 
diff --git a/gradle.properties b/gradle.properties
index 362d821..f031fe0 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -18,6 +18,7 @@
 org.gradle.configureondemand=true
 org.gradle.caching=true
 org.gradle.parallel=true
+org.gradle.jvmargs=-Xmx10G -XX:MaxPermSize=1024m
 
 # Declare we support AndroidX
 android.useAndroidX=true
```
And run `./gradlew clean dokkaHtmlMultiModule --no-daemon`

the memory bump was not necessary for dokka but `./gradlew assemble` failed for me with OOM so i gave it a... little boost ☺️

**Comment by MarcinAman** [comment]
Could you try it yourself with `./gradlew clean` and without daemons `./gradlew --stop` and `--no-daemon` flag?

**Comment by chrisbanes** [comment]
Hi Marcin, very weird. It definitely wasn't working for me on CI or locally yesterday. I'll double check today with a full clean.

**Comment by chrisbanes** [comment]
Seems to be working now, as you found. Very weird. Thanks for checking anyway!
