### ISSUE TITLE
support for doclet artifacts or native asciidoctor

### ISSUE THREAD

**Issue by mariotoffia** [Kotlin/dokka#170]
Hi, we're using asciidoctor to comment our java codebase (around 1M LOC). We're in transition to use kotlin as mixed _kotlin_ / _Java_ projects. When we generate our documentation we use a maven plugin _maven-javadoc-plugin_ and inside the configuration we specify a _docletArtifact_.

We also combine the possibility to use _diagram_ inside our asciidoc in order to render diagrams of various sort.

Our maven doclet config:

```
<configuration>
    <aggregate>true</aggregate>
    <skip>false</skip>
    <source>${java.version}</source>
    <doclet>org.asciidoctor.Asciidoclet</doclet>
    <docletArtifact>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoclet</artifactId>
        <version>${version.asciidoclet}</version>
    </docletArtifact>
    <additionalparam>
        --base-dir ${project.basedir}
        --attribute
        "project_name=${project.name}"
        --attribute
        "project_version=${project.version}"
        --attribute
        "project_desc=${project.description}"
        --attribute
        "imagesdir=${asciidoctor.configuration.images-dir}"
        --attribute
        "data-uri=${asciidoctor.configuration.images-dir}"
        --gem-path
        ${project.build.directory}/gems-provided
        --require
        asciidoctor-diagram
    </additionalparam>
    <linksource>true</linksource>
    <overview>src/main/java/overview.adoc</overview>
</configuration>
```

Is it possible to get some sort of support to allow dokka to use asciidoctor or support the doclet plugin interface?

Cheers,
 Mario

**Comment by yole** [comment]
Supporting asciidoc might be possible but that's a lot of work which will benefit rather few users. Supporting the doclet plugin interface is not possible at all because Dokka uses a completely incompatible internal representation for documentation. What features of asciidoc are you using which aren't available in markdown?

**Comment by mariotoffia** [comment]
@yole I think the most deviation from markdown is the ability via diagram plugin produce diagrams in asciidoc (such as state, class, component and so on). In addition there are few but not essential such as note, warn..., quote that as far as I understand do not work in MD.

In addition we're compiling both code documentation (in Javadoc format), user, business, and administrator manuals and powerpoint presentations where we can incorporate asciidoc content since they are also written in asciidoc.

**Comment by yole** [comment]
We need to ensure feature parity between Dokka-generated documentation and quick documentation in the IDE, and supporting diagrams in the IDE is basically infeasible because of the limitations of the UI used to display the documentation, so I don't see any way to support your usecases.

**Comment by mariotoffia** [comment]
I understand, thanks for your time!

**Comment by mariotoffia** [comment]
@yole Just a last comment. I'm investigating how we would port our Javadoc (written in asciidoc syntax) part into markdown. However the following is not supported by dokka:
* Blockquotes- this is supported within the IDEA
* GitHub markdown: Table
* GitHub markdown: syntax highlightining for java, javascript, xml

Is it possible to incorporate any of those into docka when it generates Javadoc?
