### ISSUE TITLE
Trying to use the ExtraProperty

### ISSUE THREAD

**Issue by viniciusguardieirozup** [Kotlin/dokka#1703]
**Question**
I would like to pass a custom value from a project, on build.gradle file, for my custom dokka-plugin. I'm trying to use the ExtraProperty, I followed the documentation (https://kotlin.github.io/dokka/1.4.0/developer_guide/data_model/#extraproperty-class-usage) and create the CustomExtra class, but I don't know how to pass this value on my build.gradle file.
**Screenshots**

**Installation**
- Operating system: /Linux
- Build tool: Gradle 
- Dokka version: 1.4.0

**Additional context**

**Comment by MarcinAman** [comment]
I think there is a misconception about dokka plugins being gradle plugins - they are not. 

If you want to pass values from gradle to dokka you need to use configuration (`pluginsConfiguration` or `pluginsMapConfiguration` blocks):
https://kotlin.github.io/dokka/1.4.20/user_guide/gradle/usage/#applying-plugins

After that you can get them from `DokkaContext` just like here:
https://github.com/Kotlin/dokka/blob/00c5a78bdd5a83873f5f8ef78e50db0d4fc29557/plugins/base/src/main/kotlin/renderers/html/htmlPreprocessors.kt#L88

Keep in mind that objects in this configuration needs to be serialised to JSON. 

An example of applying a plugins configuration:
https://github.com/MarcinAman/dokka-example/commit/81f91175e03a86daa69aebd458b17ab930042b95

**Comment by viniciusguardieirozup** [comment]
Thank you for the explanation. I was think like a gradle plugin, I'll see the example to implements here.
