### ISSUE TITLE
Creating custom sourceset

### ISSUE THREAD

**Issue by ShawnTuckerZem** [Kotlin/dokka#1705]
Hi. 
Is there a way to configure Dokka to generate documentation for specific files instead of specific packages?

I couldn’t find a way from the documentation. Is there something I’m missing?
I thought maybe I can create custom sourceset but I could not find a way to achieve it with ease.

Thanks

**Comment by ShawnTuckerZem** [comment]
Thank you for responding.

Do you have an example on how to achieve it? 
I thought from the documentation that setting the `sourceRoots` will only append to the default `sourceRoots`

```
// By default, sourceRoots are taken from Kotlin Plugin and kotlinTasks, following roots will be appended to them
// Repeat for multiple sourceRoots
   sourceRoot.from(file("src"))
```

**Comment by kamildoleglo** [comment]
This is a ordinary Gradle property, so you can use `setFrom()` instead https://docs.gradle.org/current/javadoc/org/gradle/api/file/ConfigurableFileCollection.html

**Comment by MarcinAman** [comment]
I have a question: why would you like to document only some sources in a package rather than all of them?

The thing with @kamildoleglo approach is that you may encounter unresolved classes if you attempt to link to the undocumented parts of the code (unless you add them to classpath manually).

**Comment by ShawnTuckerZem** [comment]
@kamildoleglo Okay cool, good to know. Thank you for your help!
@MarcinAman Thanks for that input. I guess with that in mind, we will probably prefer to work directly with packages,
I was asked to investigate it because in java we did the same.

Also, do we have a way to annotate the methods/classes we would like to document? (opposite of suppress)

**Comment by kamildoleglo** [comment]
I think there is no such way. You can always create a plugin for that, if it's crucial for you   ☺️
