### ISSUE TITLE
parameters messed up in HTML output in 0.9.14

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#171]
I updated to the version 0.9.14 and the parameters of a function are now messed up IMO. They are not aligned one under the other (was \<p> before) but are rather just bold keywords in a text.

**Comment by nd** [comment]
```<p>``` were removed in f65fbf534807c168a81f4e80919680ca7dcff47b, which tweaks kotlin website format, strange that it affects the html format..

**Comment by semoro** [comment]
Fixed in [0.9.15](https://github.com/Kotlin/dokka/releases/tag/0.9.15)
