### ISSUE TITLE
Make the creation of themes for HTML output simpler

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#172]
I am questioning the generated HTML output. For instance, what is the reasoning behind that exceptions of a functions are in a h3 tag and return is just a strong tag. IMO the generated HTML is very bad when it comes to customising, creating a theme for the layout respectively. 
I would prefer if the structure is simpler and has more in focus that one might want to apply another theme to it. In the easiest case everything would just be a \<div> with corresponding classes and ids (I would suggest to use the same as KDoc, so for exceptions it would be `throws`).

Have a look at https://robstoll.github.io/atrium/0.3.0/doc/
and the corresponding css: https://robstoll.github.io/atrium/0.3.0/style.css
I had to use quite a bit of strange looking CSS selectors (e.g. lines 12-76) to make the page look like I want it to look like.

Furthermore it would be great if the headings like `Functions`, `Properties` etc. would either include an `id` attribute or further anchors (\<a name="...>) are included, so that one can directly link to those headings.

**Comment by ianbrandt** [comment]
+1 for adding `id` attributes to facilitate anchor links.

It would be great to be able to have for example https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/index.html#sorted jump to the associated table row.  (I'm assuming Dokka is used to generate the standard documentation?)

Should that be forked off to its own issue since it's fairly limited in scope?  It might be more actionable that way.

**Comment by robstoll** [comment]
@ianbrandt go on, create another issue only focusing on adding id. Would already be some progress :+1:

**Comment by Kordyjan** [comment]
This issue is about old html output which was dropped in 1.4.0.

**Comment by robstoll** [comment]
@Kordyjan so is theming in 1.4 now easier?

**Comment by kamildoleglo** [comment]
It is indeed, you can transform the format by using page transformers or even create a new one
