### ISSUE TITLE
Move from bintray/jcenter to mavenCentral or another repo

### ISSUE THREAD

**Issue by micHar** [Kotlin/dokka#1725]
Since jcenter is closing you'll need to move somewhere else. Adding this issue to track when it happens.

**Comment by MarcinAman** [comment]
Hi, dokka is already present on maven central (starting from 1.4.10.2), and nightly builds are on space packages.
The only thing that is left is to publish 1.4.20 but it will be done shortly

**Comment by micHar** [comment]
And possibly updating the readme. Thanks Marcin!

**Comment by deepy** [comment]
Is there any chance of older releases also being uploaded? I'm specifically thinking of `0.10.1` because of #1692

**Comment by ibauersachs** [comment]
@MarcinAman The 1.4.10.2 release on Maven Central is useless and broken until all dependencies are also there. See the original issue #41 for details.

**Comment by MarcinAman** [comment]
@ibauersachs We know that not all dependencies are present but have already contacted their authors and offered help to publish them. Most of them are Jetbrains libraries and as for the external one (korte), they are already working on it so please be patient. Rome wasn't built in a day ☺️

**Comment by MarcinAman** [comment]
@deepy We've decided that we will publish older version of dokka (0.10.1) to maven central or (if this wouldn't be possible) at least to space packages, so the builds wont break :D

**Comment by szpak** [comment]
Maybe that issue could be kept open until dokka (and its dependencies) are available in Maven Center?

I've just reported a [duplicate](https://github.com/Kotlin/dokka/issues/1741) as I missed that one closed.

**Comment by MarcinAman** [comment]
There is an issue regarding that: https://github.com/Kotlin/dokka/issues/41
