### ISSUE TITLE
Source link and undocumented warning options don't work anymore

### ISSUE THREAD

**Issue by cromefire** [Kotlin/dokka#1728]
**Describe the bug**
Even though I set some options the options do not get applied correctly. `1.4.20` worked fine.
This happens both with the MultiModule, but also while generating individual module docs.

**Expected behaviour**
I added a source link, so there should be a link to the source of course. There's also a ton of undocumented code, but doesn't emit warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/26320625/106928701-be51bf00-6713-11eb-9338-bd7fb99abc8d.png)
Missing source link

![image](https://user-images.githubusercontent.com/26320625/106930638-112c7600-6716-11eb-8398-1ea8224923a6.png)
No warnings ([also seen here](https://gitlab.com/factory-org/tools/mikrate/-/jobs/1008494681))

**To Reproduce**
The affected project can be found [here](https://gitlab.com/factory-org/tools/mikrate/) but it's not an ideal sample.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
named<DokkaTaskPartial>("dokkaHtmlPartial") {
    named("main") {
        sourceLink {
            localDirectory.set("src/main/kotlin")
            remoteUrl.set(URL("https://gitlab.com/..."))
            remoteLineSuffix.set("#L")
        }
        reportUndocumented.set(true)
    }
}
named<DokkaTask>("dokkaHtml") {
    named("main") {
        sourceLink {
            localDirectory.set("src/main/kotlin")
            remoteUrl.set(URL("https://gitlab.com/..."))
            remoteLineSuffix.set("#L")
        }
        reportUndocumented.set(true)
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.8.1
- Dokka version: 1.4.20.2-dev-62

**Additional context**

**Comment by cromefire** [comment]
This seems to be related to offline mode, not sure if this change in behavior is intended and I misunderstood, what offline mode does or if this is buggy

**Comment by cromefire** [comment]
But even turning offline mode off, doesn't bring back the source links

**Comment by kamildoleglo** [comment]
You have misconfigured Dokka, because you call `named("main")` two times and the configuration is not executed at all. You have to remove this line https://gitlab.com/factory-org/tools/mikrate/-/blob/master/build.gradle.kts#L97 in your config. Moreover, you set `skipEmptyPackages.set(true)` two times

**Comment by cromefire** [comment]
Oh man you're right that must have happened when I transitioned to the partial jobs

**Comment by cromefire** [comment]
I still tested it by setting it directly in the individual project (so it should have ignored this error) but I'm not sure why that didn't work.
