### ISSUE TITLE
jdkVersion seems broken for javadoc

### ISSUE THREAD

**Issue by cromefire** [Kotlin/dokka#1729]
**Describe the bug**
When the `jdkVersion` is set to `11` I'd expect the link to also go to the JDK 11 docs. Instead I get the following link: `https://docs.oracle.com/javase/8/docs/api/java/util/List.html`

**Expected behaviour**
The correct link should be `https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/List.html`

**Screenshots**
![image](https://user-images.githubusercontent.com/26320625/106934921-07f1d800-671b-11eb-8476-bc6fe4fb812d.png)

**To Reproduce**
Use some java type and set the jdk version.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
tasks {
    dokkaJavadoc {
        dokkaSourceSets {
            named("main") {
                jdkVersion.set(11)
            }
        }
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.8.1
- Dokka version: 1.4.20.2-dev-62

**Additional context**
Be aware the docs URL has changed for JDK 11

**Comment by cromefire** [comment]
The same seems to be the case for `html`

**Comment by kamildoleglo** [comment]
Wrong configuration, explained in https://github.com/Kotlin/dokka/issues/1728
