### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by cromefire** [Kotlin/dokka#1731]
**Is your feature request related to a problem? Please describe**
Some people may like a dark theme (the intelliJ IDEs have one for example, the the new kotlin docs too at far as I'm aware), to reduce the strain on their eyes, so I propose to add a dark theme to the generated docs.

**Describe the solution you'd like**
A dark theme can easily implemented using js and css.
I'd propose the use of a simple button and a bit of js glue that adds or removes a css class from `body`. persistence can be handled via local storage.
In addition the initial value could be set via media query ([observable via js](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries)) with maybe an option for auto that reacts to media queries (for stuff like dark mode after sunset).

**Describe alternatives you've considered**
Dark reader works okay-ish. Some contrasts are not good, but most things are readable.

**Additional context**
I'd be willing to help here, especially with the js/button part, but some graphics need an update:
![image](https://user-images.githubusercontent.com/26320625/106952991-26af9900-6732-11eb-8ec4-2f1d0d6a8f4d.png)
(all icons are SVGs so this might be relatively easy and even doable with my limited skills)

Icons are available from [material](https://material.io/resources/icons/?search=brightness&style=baseline) for example.

**Comment by cromefire** [comment]
I sady can't find where the web frontend is available/generated...

**Comment by yalishevant** [comment]
Solved in 1.6.0
