### ISSUE TITLE
Wrong link in the last breadcrumbs item

### ISSUE THREAD

**Issue by nd** [Kotlin/dokka#174]
Last item in the breadcrumbs shows a directory, should probably open the file for appropriate entity.

To reproduce:
- open some class, breadcrumbs look like ```module / package / class ```
- click on the ```package```, package docs are shown, breadcrumbs become ```module / package```
- click on the ```package``` again - directory listing is shown

**Comment by nd** [comment]
possible fix: https://github.com/Kotlin/dokka/pull/175

**Comment by semoro** [comment]
Fixed in [0.9.16](https://github.com/Kotlin/dokka/releases/tag/0.9.16)
