### ISSUE TITLE
Support documentation for multiple versions

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1745]
**Is your feature request related to a problem? Please describe**
I would like to provide documentation for multiple versions of my library in the same place, in particular one for the latest release and one for snapshot builds.  One example is the Kotlin stdlib docs, with it's version dropdown.  This is currently not possible in a nice way via Dokka.

**Describe the solution you'd like**
I'd like to be able to specify an output directory, and have dokka create the documentation for the current version and version navigation, leaving already present versions' docs (that aren't the current version) alone (but including them in navigation).

**Describe alternatives you've considered**
I'm currently doing this via having one site for release and one for snapshot, but this is sub-optimal and doesn't preserve past versions.

**Comment by MarcinAman** [comment]
1.4.30 release introduced a versioning plugin: https://kotlin.github.io/dokka/1.4.30/user_guide/versioning/versioning/

Right now it only supports multimodule documentation but supporting single module will come in the future
