### ISSUE TITLE
Source link 404s if remoteUrl ends with /

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1747]
**Describe the bug**
If a sourceLink's `remoteUrl` ends with a `/`, the generated link 404s because there are 2 `/`s in it.  For example: `https://github.com/rnett/compiler-plugin-utils/blob/main/compiler-plugin-utils//com/rnett/plugin/ir/IrTransformer.kt#L15`.

**Expected behaviour**
The `remoteUrl` should be trimmed of trailing `/`s.

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
Add a `sourceLink` with a `remoteUrl` ending with a `/`, as seen below.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
tasks.dokkaHtml{
    moduleName.set("Compiler Plugin Utils")
    moduleVersion.set(version.toString())

    dokkaSourceSets{
        all {
            includes.from("docs.md")

            sourceLink{
                localDirectory.set(file("src/main/kotlin"))
                remoteUrl.set(URL("https://github.com/rnett/compiler-plugin-utils/blob/$sourceLinkBranch/compiler-plugin-utils/"))
                remoteLineSuffix.set("#L")
            }
        }
    }
}
```

**Installation**
- Operating system: Windows
- Build tool: Gradle v6.8.2
- Dokka version: 1.4.20

**Additional context**
Add any other context about the problem here

**Comment by MarcinAman** [comment]
Hi, i've checked out your repository and links work with and without the `/` at the end. I think in this case it was a matter of missing `src/main/kotlin` at the end
