### ISSUE TITLE
Flow type rendered as <ERROR CLASS>

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1749]
**Describe the bug**
I have a function returning a (coroutines) Flow.  It shows up in the documentation as `<ERROR CLASS>`.  

**Expected behaviour**
`Flow` is rendered as `Flow`.

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
See https://rnett.github.io/kotlin-js-action/snapshot/-kotlin%20-j-s%20-git-hub%20-action%20-s-d-k/com.rnett.action.glob/glob-flow.html

Docs are auto-generated by the CI in https://github.com/rnett/kotlin-js-action/, sources are linked.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```kotlin
tasks.dokkaHtml {
    moduleName.set("Kotlin JS GitHub Action SDK")
    moduleVersion.set(version.toString())

    dokkaSourceSets {
        val main by getting {
            includes.from("packages.md", "module.md")

            platform.set(org.jetbrains.dokka.Platform.js)

            sourceLink {
                localDirectory.set(file("src/main/kotlin"))
                remoteUrl.set(URL("https://github.com/rnett/kotlin-js-action/blob/$sourceLinkBranch/src/main/kotlin"))
                remoteLineSuffix.set("#L")
            }

            externalDocumentationLink {
                url.set(URL("https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/"))
            }
        }
    }
}
```

Note that this happens even without the external documentation link, that's from a failed attempt to fix it.

**Installation**
- Operating system: Windows
- Build tool: Gradle v6.8.2
- Dokka version: 1.4.20
- Kotlin/JS

My guess is it's related to importing `Flow` and `flow`, but that's just a guess.

**Comment by asfalcone** [comment]
If you download the package-list for coroutines, change the first line to $dokka.format:kotlin-website-html instead of $dokka.format:kotlin-website, give the package-list as a local URL, then the linking works for Flow. I'm not sure if the problem is in Dokka or if the package-list for coroutines needs to be updated.

**Comment by rnett** [comment]
It looks like they are using `dokka_version=0.9.16-rdev-2-mpp-hacks`, that may be the cause.

**Comment by kamildoleglo** [comment]
`<ERROR CLASS>` indicates that the class cannot be resolved, so basically it's not on the Dokka's classpath. If it was resolved, then the links would have worked, I presume

**Comment by rnett** [comment]
Is there any way to verify that this is caused by the old version?  I'll make an issue on coroutines if so.

**Comment by mattmook** [comment]
For a project I'm currently working on, I'm only seeing <ERROR CLASS> for code that is not in common, in my case in iOS only code.

As an aside, externalDocumentationLink for the common code where Flow works, the link results in a 404 because of the older version of dokka in use.

**Comment by kamildoleglo** [comment]
@rnett I think that's not the case. Please just make sure (preferably by debugging) that Dokka has the coroutines on the classpath (in the appropriate `dokkaSourceSet` there is a property called `classpath`)

**Comment by rnett** [comment]
I finally got around to working on this, and it still happens even with the library on the classpath.  I can print `classpath.files` and see 
```
[C:\Users\jimne\Google Drive\My Stuff\Github Actions\kotlin-js-action\serialization\build\classes\kotlin\main, C:\Users\jimne\Google Drive\My Stuff\Github Actions\kotlin-js-action\kotlin-js-action\build\libs\kotlin-js-action-1.3.0-SNAPSHOT.klib, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-serialization-json-js\1.2.1\80c5fe5a2d608d0c75b1c6d59a2b8585ee6bd911\kotlinx-serialization-json-jsir-1.2.1.klib, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-nodejs\0.0.7\ba0ec05570ec7fc558b9cc7a073371455fcf2d81\kotlinx-nodejs-0.0.7.klib, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-test-js\1.5.10\a81b0896d15768898359a9d7129096bbb6f36c78\kotlin-test-js-1.5.10.jar, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core-js\1.5.0\217834c27f3ba5f28b897fead52238f6f30febb1\kotlinx-coroutines-core-jsir-1.5.0.klib, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-serialization-core-js\1.2.1\ddf1ed605747a19c432b66d12a2c2e95dfd68cac\kotlinx-serialization-core-jsir-1.2.1.klib, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\atomicfu-js\0.16.1\a462e9d32ae4d38851d2c831025981198f10f75b\atomicfu-jsir-0.16.1.klib, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-js\1.5.10\2cab0f51a869235a20bdafb360b698b9083fc61\kotlin-stdlib-js-1.5.10.jar, C:\Users\jimne\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.5.10\6b84d926e28493be69daf673e40076f89492ef7\kotlin-stdlib-common-1.5.10.jar]
```
but the documentation still has `<ERROR CLASS>` in place of any serialization or coroutines classes.
