### ISSUE TITLE
Is it possible to exclude internal classes?

### ISSUE THREAD

**Issue by egek92** [Kotlin/dokka#1759]
**Question**
I have internal classes in my SDK so I want to exclude them from my documentation, is this possible?

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v5.6.0/Maven/Cli/3rd party plugin 
- Dokka version: 1.4.0-rc

**Comment by MarcinAman** [comment]
`includeNonPublic` should be used to hide non public members. By default it is set to false so internal members should be hidden. Could you try it with a newer version like 1.4.20 or send me a case to test on?

**Comment by egek92** [comment]
it is working in both older and newer versions
