### ISSUE TITLE
How to specify custom style sheets in Groovy syntax?

### ISSUE THREAD

**Issue by dmitry-trenov** [Kotlin/dokka#1761]
I try to use example from documentation to specify some custome style sheets. It looks like:
```
dokkaHtml {
    dokkaSourceSets {
        pluginConfiguration<DokkaBase, DokkaBaseConfiguration> {
            customStyleSheets = ["dokka/customStyleSheets/someStyles.css"]
        }
    }
}
```
But I get an exeption:
```
Could not compile build file '/project-dir/build.gradle'.
> startup failed:
  build file '/project-dir/build.gradle': 132: expecting '}', found ',' @ line 132, column 38.
             pluginConfiguration<DokkaBase, DokkaBaseConfiguration> {
                                          ^
```
Without generic it doesn't work neither: function type parameters are required.
Could you please clarify how to specify custom style sheets in Groovy syntax?

**Comment by MarcinAman** [comment]
The example that you took is designed to work for `.kts` and it requires to have a dokka base plugin on classpath. 

If you want to specify custom configuration in groovy unfortunately you need to do it the json way:
```
pluginsMapConfiguration.set(["org.jetbrains.dokka.base.DokkaBase": """{ "customStyleSheets": ["${file("dokka/logo-styles.css")}"] }"""])
```
