### ISSUE TITLE
add support for markdown images

### ISSUE THREAD

**Issue by Groostav** [Kotlin/dokka#177]
I went through the trouble of making [a diagram for a state machine](https://www.draw.io/?lightbox=1&highlight=0000ff&layers=1&nav=1&title=StateMachine_1_4%5B1%5D.xml#R7Z1tc5s4EIB%2FjT%2B6AwgJ%2BJjX3t3cS6e5mbt%2BJLZic8XIg3Fe%2ButPGClGK9uRsSCYJp3pGCEWLO0%2BWa12yQhdLZ4%2F5%2FFy%2Fgeb0nTkOdPnEboeeV4UOfz%2FsuGlaghCv2qY5cm0anK3DXfJDyoaxXWzdTKlK6VjwVhaJEu1ccKyjE4KpS3Oc%2FakdntgqXrXZTyjWsPdJE5l6ye8bf8nmRZz0e6SaHviF5rM5uLmoUeqE%2Ffx5PssZ%2BtM3HHkoYfNT3V6EUtZ4quu5vGUPdWa0M0IXeWMFdWnxfMVTcvBlQMnryte5NOO0OW8WKT8wOUfN6dv91zsmlzMv1xOs6J%2Bu33ykCaPTvlIikOa3rOnm23D5WZcaHmto953VcR5cVHOHG%2FIWEZl222SpqL7f7QoXoSuxOuC8SaWF3M2Y1mc%2Fs7YUsh6YFkhurkhP948BT94pHmR8Dkum7Iif%2Fm3lPvJw%2FL4m7jPqsjZd3rFUpZvvhK6Jt6VF7yekfqAygufk6Iuhx9%2B2zuUcvDZOp%2BI0UKxGzy4E4qx43p4Go%2BFnfCvPqPiMqGK5cDW5Ij5%2BEzZgvKH5x1ymsZF8qgqdiwsYfba7%2FXSLyzhT%2BY5wmh9abTCZv3AUUVUzy2uqusEEOR6QBACgqovpwni0x%2B%2F1Lotyw6rAw%2BMwX1C5%2BBzIVftL49Ff%2F6hegJ5VBvcbdNG%2F%2FfYljCGxzhdS%2BPySMpn8XKaPPKPs%2FLjLeODeFdwbRXnuNjaac2eCvpcqLaS01XyI77fdCj1VYwT740vR%2Fiat8RpMst4w4SrHuVKfClV%2F0KcWCTT6cYg0%2FieppevyKopvYCW7MLyKc132YSu5khhs3jQLbjKZ6HPBzVZnOVGpUyYtIQTFX2MIkXs2Af6yR4eVrQAunG0NoTaVL4P%2FSTqXIVzFa8aoa7GOSHGCHWhTjbSDdkIAAUKG5KNAER6UNAesjVQH981gUnJkb9KyxwsTKQZnU6TsfMJY6k8L4oCngoUwBPcBk92%2BH294klghycbMRO2SCbilBFbonfzmiASUIibsQUDSAUOEGSRLd6Ho1I3KStsQZgEKgaQFbgEQL3aQIvXb7R07am4MuRQw8m%2BhVrbfIkQWOR4DX2XAIAqgF6vPb4g%2F8N3qduVFb642PWtAMX1VXfFD9pACu4ZUhxLqx%2B3IVMCHSmu1w1CQhCPwaQhQiIClj8tIgSbIORLvF7RgwzRLhkubLBN2AREXSiN7bBnDNZfYyDBDntIv9nTeKWksicwZg%2FR2RN2gx64OvJdW6sj1N7qSBrMG94LV5KBuy%2FEIlECD7gdnhWgSOoJoW4rkZegbzypbP%2F0TauGPJGOSx0oUTdAcR1HnXEMN5eMieKqgkx3qZo4M6EZUQa%2FHgosAgUHTqhMoJ1wCwDKWELQLlF6vjfUPJarboMbx28lt3sRcQks%2BSwhauazHLsPDkNE2Le7r%2B3r%2BKqx6vypZHOHKUSh14KbowaBYQjQDpOinjGpivtayMxplJizKwYsKfXh5OxycoiJk%2FOVrtaLwyGb8wdKZBEopAWajL0W%2BCE16735YYcRhyhkxI8d8d6OlkgBDPdGTXeMgCACEwItwiMygcfwV0jSiKygQ27zvyiKdKp3rMiUmS9WSaL%2FIvm1HHE4u0%2FzpKB3y3hjcU95vASMkXnVuyDxwDlTnzBc%2FtsFD7L5OWT05lPiO8CeZPbYUy3BXEYf57XccrhfU58lZZwPWdie1VRtlC8mE7osvtBsmmSz4Q03Ih0Ot9H21d80zvmgZYY4O%2FsZwF6HM2AYc%2BNOx6vGD3MWXjHzHnag%2F16%2FuGf5cCADB7dTpsv1aG10q%2FXVYIYXZhx0O7x6CvYm4WA6vHHtlMxy%2B8ggt2PgaIbT0CmaAx0e6ywbBDYglTtVb6TXWNZrIrdBjH4XRo5a2REyjr%2FuyFnpqFrIh9s2TdPloKAQCrJVB4nUIG%2FwVh0ksI6j%2B4vVja39JWT0%2B2D45QgSHL0tnAzA3rgseLUa%2FfH17L1zKyl%2Fe98KOSG6vT0yJm3EzT4VlAPvpnHpAhSEoSBbIAUK%2FmZBOQCv7YJyX3fRSgBeTL6fC%2B1e9VzXXd9admFbZeJg77SdMnGZ1%2Fre22Y7iNaIWiMEyyMOFqAbMe39qjsDmVUmXTioA8aV4xgIcswQ1kSj9LDFcKghzaW31IhUqT5I%2BbLDDO%2FDRTrBRcI6TrpaWsq3OshwJqRA06UlMXwRxdEeka%2F%2BDiT%2BGx4RSFyS7xCy5RFh%2FRU7v%2FEnGALYvJ6DbQwzo9txh%2FwPtJ2Ath3v2Ak68pRsLfagoLYWe8GRiz3S8mIP6ykDm93pgfht%2FgfeymE4%2F%2BCWwfsSjfhmvi3Qfrq1rXdsaJLagpfr%2BMfRK3Jappceqtps4A6EXr2PVXVCLzLkWFVwKFZ1RG3sjkq2jlywCNTIE%2FgeOuPCNR8IMqRYE5XSg1VVCtMwwEH6Hq4iCKhMG9jQw1VnjQ29xvVgZb4RNnaUi3T1AkNQ7orlexqOrjWDSTdQkK2FG6xpe8P1wTAmFdp1fYgek7p5nnPnpxgCwPoelnJhRUorBNOjUudNsOBAvZu6wNuuzACImoTZg1YIBt8N1Jhgb6LQEsEgkaR%2FtTck5h7sfzrB9NDTn5xUX9fnGlg3phWAnf8eBBu7nq%2BqXRsE%2BykCT6fko1rAG2kFb3CvDzd9e%2F3PumlI9NjUT5BfulrGkzKZH117J3Nxj2K3zEUQhbAS0%2BKH2z%2BtVHXf%2FgErdPM%2F) used on our application, but was disappointed to learn when I hit `ctrl` + `alt` + `k` in intelliJ that `<img.../>` tags aren't converted with standard markdown `![hover text](https://img-src)`. 

can I ask for support for markdown image links in documentation? if the links were local-only that would suffice to, but embedding web images would be nice.

**Comment by BoxResin** [comment]
I hope this feature to be added to `dokka` soon!

**Comment by clarcharr** [comment]
Wanted to add that I am also missing this feature. It would be nice if we could specify files to be included with the Dokka output as well, with linked images and other things automatically included.

**Comment by BoD** [comment]
I, too, just spent an hour making a very nice diagram only to realize I cannot embed it in my code documentation 😢   I am very sad now.

**Comment by zathras** [comment]
+1 on the above.  I can't live without embedding diagrams in my generated documentation.  It seems that dokka won't let me embed an `<img>`, either, so I had to resort to post-processing, viz:
```
tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }

    val copyDocImages by registering(Copy::class) {
        from("../docsrc")
        include("*.svg")
        into("$buildDir/dokka/lib")
    }

    val dokka by getting(DokkaTask::class) {
        dependsOn(copyDocImages)
        outputFormat = "html"
        outputDirectory = "$buildDir/dokka"
        configuration {
            includes = listOf(
                "../docsrc/module.md", 
                "../docsrc/com.jovial.db9010/package.md"
            )
        }
        doLast {
            PostProcessHack.process(File("$buildDir/dokka/lib"))
        }
    }
}

object PostProcessHack {
    val imageRegex = Regex("""\${'$'}IMAGE[ \t]*\(([^)]*)\)""")
        // Yow.  That matches "$IMAGE (foo.svg)", with MatchResult's
        // groupValues[1] containing "foo.svg".  You're welcome.

    fun process(dir: File) {
        for (f : File in dir.listFiles()) {
            if (f.isDirectory) {
                process(f)
            } else if (f.name.endsWith(".html")) {
                var modified = false
                val text = f.readText()
                val result = imageRegex.replace(text) { mr ->
                    modified = true
                    """<img src="${mr.groupValues[1]}">"""
                }
                if (modified) f.writeText(result)
            }
        }
    }
}
```

It works and all, but I am saddened that it's so difficult to produce good-looking, complete documentation.  This encourages more people to commit _Crimes Against Software™_.

**Comment by kamilok1965** [comment]
We can't fix this in IntelliJ, as they don't use dokka internally, you can file an issue on YouTrack for that. We can probably do something about this in dokka

**Comment by kamildoleglo** [comment]
Image tags in markdown are now parsed in Dokka. As mentioned before, IntelliJ is a separate story and a separate ticket should be created for them
