### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/dokka#1772]
**Is your feature request related to a problem? Please describe**
Some tools like `dependabot` are detecting dev version as stable versions

**Describe the solution you'd like**
Usage of semantic versioning

**Additional context**
Currently, `dependabot` is creating this PR:

Bumps dokka from 1.4.20 to 1.4.20-dev-65.
Updates dokka-core from 1.4.20 to 1.4.20-dev-65

I created an issue in `dependabot` for asking for a custom regex option, but after a quick search, I saw this petition was done months or years ago, and it is not implemented, so should be great if Dokka could change something to avoid this problem.

**Comment by kamildoleglo** [comment]
If you're talking about MavenCentral, then that version was put there by mistake, no dev version should be present on MavenCentral as we have Space repository for that. I've written a version assert that should make sure no future artifacts are  published with an incorrect version. 
That being said, 1.4.20 and 1.4.20-dev-65 are completely the same, just the version number has changed. 
I hope that dependabot will correctly pick up 1.4.30 which will be released any day now

**Comment by JavierSegoviaCordoba** [comment]
That can be the problem then, I will re-check this issue to close it when the next version is available.

**Comment by MarcinAman** [comment]
I think this issue can be closed as this dev version was a mistake :D
