### ISSUE TITLE
Publish the Gradle plugin to plugins.gradle.org

### ISSUE THREAD

**Issue by netvl** [Kotlin/dokka#1775]
**Is your feature request related to a problem? Please describe**

Currently it seems that Dokka Gradle plugin is not published to plugins.gradle.org: https://plugins.gradle.org/plugin/org.jetbrains.dokka
The latest version there is 0.10.something, while apparently now the latest version is 1.4.20.

This is a problem, because the Gradle plugins portal is the central place where Gradle plugins are usually found, and it is very confusing that there is a need to add custom setup in `settings.gradle.kts` to make the Dokka plugin work.

**Describe the solution you'd like**

The plugin should be published to plugins.gradle.org and thus be available directly by their ids without any additional setup. Especially in light of what will happen with bintray in the nearest future.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by joffrey-bion** [comment]
I think this has been fixed at the beginning of this week. I see the Dokka plugin version 1.4.30 published there.
Although 1.4.31 is still missing, but that's https://github.com/Kotlin/dokka/issues/1788 I guess.

**Comment by MarcinAman** [comment]
Dokka 1.4.30 is published there so you can use it ☺️
