### ISSUE TITLE
Compiler artefacts for 1.4.31

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1788]

**Comment by joffrey-bion** [comment]
Will there also be a sister version for Kotlin 1.4.32? It would be nice if the 2 Gradle plugins were aligned (so that the global kotlin version can be used for both in builds)

**Comment by MarcinAman** [comment]
There will be no version for 1.4.31 since it is just a bugfix release and we can already go for 1.4.32. Compiler artifacts were bumped in https://github.com/Kotlin/dokka/pull/1818 so we will release it soon
