### ISSUE TITLE
Module index.md generated in wrong folder

### ISSUE THREAD

**Issue by bherbst** [Kotlin/dokka#1796]
**Describe the bug**
1.4.30 appears to have introduced a bug that causes a module's index.md (I have only tried with the GFM format) to be generated in the wrong place when setting an output directory.

For example, let's assume I have a single `core` module in my project with this dokka configuration:

```kotlin
tasks.dokkaGfm.configure {
    val outputPath = "$rootDir/docs"
    outputDirectory.set(buildDir.resolve(outputPath))
}
```

In Dokka 1.4.20, the structure of the docs folder would look something like:
```
docs/
 └ core/
    ├ com.example.packagename/
    ├ index.md
    └ package-list
```

In Dokka 1.4.30, the structure looks like this:
```
docs/
 ├ index.md
 └ core/
    ├ com.example.packagename/
    └ package-list
```

**Expected behaviour**
I expect Dokka to retain the behavior it had in 1.4.20, where the index file for a module was placed in the module's directory in the output directory.

**To Reproduce**
I have attached a sample project.

To reproduce, run `./gradlew dokkaGfm` and look at the generated `/docs` folder.

If you change the Dokka version to 1.4.20 in `/core/build.gradle.kts` you can re-run `dokkaGfm` and see the old behavior as well.

[Here is the sample project](https://github.com/Kotlin/dokka/files/6164858/dokka-directory-sample.zip)

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
tasks.dokkaGfm.configure {
    val outputPath = "$rootDir/docs"
    outputDirectory.set(buildDir.resolve(outputPath))
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.3.0 (have also tested with 6.8.2)
- Dokka version: 1.4.30

**Comment by MarcinAman** [comment]
Hi, 
this behaviour is intentional from our side because it makes publishing dokka on sites way easier. If you want to change this behaviour you need to write a [dokka plugin](https://kotlin.github.io/dokka/1.4.30/developer_guide/introduction/) that changes the location of the root page and linking to it (i think it will require a change in LocationProvider)

**Comment by bherbst** [comment]
Thanks! While the behavior change after updating Dokka was unexpected, I was able to successfully (and pretty easily) switch over to using `dokkaGfmMultiModule` to get the behavior I wanted.
