### ISSUE TITLE
Dokka does not generate output for Classes within companion object.

### ISSUE THREAD

**Issue by kimjiwongit** [Kotlin/dokka#1797]
**Describe the bug**
Dokka does not generate output for Classes within companion object.

**Expected behaviour**
Dokka should generate output for Classes within companion object. For functions in companion object, it generates as expected.

**To Reproduce**

```
abstract class WordRoomDatabase : RoomDatabase() {

    companion object {

        private class WordDatabaseCallback(
            private val scope: CoroutineScope
        ) : RoomDatabase.Callback() {

            ...
        }

        /**
         * Populate the database in a new coroutine.
         * If you want to start with more words, just add them.
         */
        suspend fun populateDatabase(wordDao: WordDao) {
            ...
        }
    }
}
```

In the above, code there's no html file generated for `WordDatabaseCallback` whereas Dokka properly generates for `populateDatabase`

**Dokka configuration**
Android Gradle

**Installation**
- Operating system: Window
- Build tool: Gradle v6.8.0
- Dokka version: 1.4.30

**Additional context**
It must generate the documentation for Classes inside companion object, otherwise it gives false idea that no classes exists within companion object when browsing the Dokka docs alone.

**Comment by shipsywor** [comment]
Thank you! It worked.

**Comment by kimjiwongit** [comment]
Thank you! It worked.
