### ISSUE TITLE
Annotations are missing the annotation name in 1.4.30 GFM format

### ISSUE THREAD

**Issue by bherbst** [Kotlin/dokka#1798]
**Describe the bug**
As of Dokka 1.4.30 annotations are missing their name from generated GFM docs.

For example, `@Json(name = "param") val param: String` is now rendering as `@(name = param)param: String`

**Expected behaviour**
I expect that the annotation name to show up in the generated docs.

**To Reproduce**
[Here is a sample project](https://github.com/Kotlin/dokka/files/6165073/dokka-annotation-sample.zip).

Run `./gradlew dokkaGfm`, then inspect `/docs/core/core/-deep-thought/-deep-thought.md`.

Swapping Dokka 1.4.30 for Dokka 1.4.20 results in the expected output.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
tasks.dokkaGfm.configure {
    val outputPath = "$rootDir/docs"
    outputDirectory.set(buildDir.resolve(outputPath))
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.3.0 (have also tried with Gradle 6.8.3)
- Dokka version: 1.4.30

**Comment by MarcinAman** [comment]
Will be fixed in next version ☺️ 

Btw: in the current one you can just add an external link to this library for example: 

```
tasks.dokkaGfm.configure {
    val outputPath = "$rootDir/docs"
    outputDirectory.set(buildDir.resolve(outputPath))

    dokkaSourceSets.configureEach {
        externalDocumentationLink {
            url.set(URL("https://square.github.io/moshi/1.x/moshi/"))
        }
    }
}
```

This was the reason why you didn't see any annotations. They were not rendered as text when dokka failed to resolve them :(

**Comment by bherbst** [comment]
Thanks for the fix and the workaround!
