### ISSUE TITLE
outputFormat HTML formatting issues

### ISSUE THREAD

**Issue by TheRealAgentK** [Kotlin/dokka#180]
On the page for a function, the output isn't quite right. Using:

```
     * @param[type] event type: (sign_up|unlock_achievement|ecommerce_purchase)
     * @param[payload] JSON object with payload. Payload is specific to event type.
     * @return Bundle that was logged to FA
     * @author Kai Koenig
     * @since 2.1
     * @exception PayloadParsingException When internal payload parsing failed.
```

produces:

<img width="666" alt="screen shot 2017-06-28 at 8 54 25 am" src="https://user-images.githubusercontent.com/322372/27609638-9897e002-5bdf-11e7-95b4-962e5a75d625.png">

There ares some things that could be improved here:

- each @param should render on a new line
- there should be a margin above the "Exceptions" heading
- there should be a margin above the "Returns" heading
- Maybe all the headings should be the same element and not differentiate

**Comment by kamilok1965** [comment]
I think that's mainly fixed in the newer versions:
<img width="489" alt="Screenshot 2019-09-24 at 14 48 59" src="https://user-images.githubusercontent.com/9080183/65512920-7fceb200-deda-11e9-8c7e-9985c8beacc4.png">
