### ISSUE TITLE
Attaching generated Documentation to SDK

### ISSUE THREAD

**Issue by egek92** [Kotlin/dokka#1801]
**Question**
We are developing an SDK and I want to attach the generated documentation to our code so whenever a user implement our SDK can see our documentation when they hover our classes or methods like this https://stackoverflow.com/questions/20994336/android-studio-how-to-attach-javadoc

**Comment by MarcinAman** [comment]
Wouldn't just attaching libraries sources work? I don't think that this is related to documentation, more to the Intellij platform. In fact i've contacted one of them and he said that as far as he knows there is no way to attach only docs  in newer intellij-s. 

I've tried to do it but half of options that he is using in this thread are not present in IJ2021
