### ISSUE TITLE
Already published version 0.10.1 changed in maven central today.

### ISSUE THREAD

**Issue by tprochazka** [Kotlin/dokka#1803]
I'm using Gradle dependency verification. And today all our builds failed because of existing dependency in maven central was updated, it has PGP signature but the key is not available in any official public repository and the hash is different. 

https://repo1.maven.org/maven2/org/jetbrains/dokka/dokka-gradle-plugin/0.10.1/

Was it hacked? Or it for a purpose? Replace existing artifacts is definitely not good practice.

**Comment by kamildoleglo** [comment]
There was no update. Dokka versions prior to `1.4.10` did not exist on the Maven Central. As a part of migrating away from Bintray (which is being disabled in 2 months) we've decided to publish several Dokka versions to Maven Central with `0.10.1` being the first one that got published there. 
The PGP key is available both on http://keys.gnupg.net/ and http://pgp.mit.edu/ AFAIK

**Comment by tprochazka** [comment]
So the issue is that it was before probably from a different repository, but now the same version exists in two different artifactory with different hash. It will be solved by closing Bintray.
