### ISSUE TITLE
Clicking on the edit button from the website leads to a 404 page

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/dokka#1809]
Hello!

I'd like to submit typo fixes and improvements to the doc of Dokka, but when I click on the edit button, it doesn't take me to the right url.

This is certainly caused by a misconfiguration of MKDocs that wasn't caught.

Take this page: https://kotlin.github.io/dokka/1.4.30/user_guide/gradle/usage/
Clicking the pen icon at the top of the page content leads here: https://github.com/Kotlin/dokka/edit/master/docs/user_guide/gradle/usage.md

**Comment by LouisCAD** [comment]
Has the update been deployed yet?
I'm still seeing a 404 for the example of this issue.

**Comment by MarcinAman** [comment]
It is automatically deployed for current dev version which is 1.4.32: https://kotlin.github.io/dokka/1.4.32/

**Comment by LouisCAD** [comment]
You don't have a way to quick-fix the website in production in a way that is decoupled from the releases of the Dokka plugin itself?
