### ISSUE TITLE
There are no `suppressObviousFunctions` property in `AbstractDokkaTask` in Gradle plugin

### ISSUE THREAD

**Issue by AzimMuradov** [Kotlin/dokka#1815]
**Describe the bug**
There are no `suppressObviousFunctions` property in `AbstractDokkaTask`, but it is in [Gradle configuration options](https://kotlin.github.io/dokka/1.4.30/user_guide/gradle/usage/#configuration-options).

![image](https://user-images.githubusercontent.com/31899809/113059145-c4b26380-91b7-11eb-8978-af6fda3311c5.png)

There are a chance that this property intended to be in the next release.

Also, I should mention that `DokkaDefaults` currently has a `suppressObviousFunctions` property.

![image](https://user-images.githubusercontent.com/31899809/113058962-85841280-91b7-11eb-9a06-379263451ff6.png)

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.8.0
- Dokka version: 1.4.30

**Comment by MarcinAman** [comment]
already fixed by: https://github.com/Kotlin/dokka/issues/1787 will be released soon with next version
