### ISSUE TITLE
Search bar is broken in dokkaHtml in 1.4.30

### ISSUE THREAD

**Issue by AzimMuradov** [Kotlin/dokka#1816]
**Describe the bug**

In `dokkaHtml` in the new **1.4.30** release ***search bar*** doesn't work properly (doesn't work at all).

![image](https://user-images.githubusercontent.com/31899809/113090884-7458f700-91f3-11eb-9875-d547d7033ae4.png)

**Expected behaviour (screenshot from 1.4.20)**

![image](https://user-images.githubusercontent.com/31899809/113090962-9c485a80-91f3-11eb-8208-51d751308256.png)

**To Reproduce**

To reproduce this bug, you just need to download [this](https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka/dokka-gradle-example) dokka-gradle-example and replace dokka version with **1.4.30**.

**Dokka configuration**

Configuration of the example above:

```kotlin
import org.jetbrains.dokka.gradle.DokkaTask
import java.net.URL

plugins {
    kotlin("jvm") version "1.4.30"
    id("org.jetbrains.dokka") version ("1.4.30")
}

repositories {
    mavenCentral()
    jcenter()
    maven("https://dl.bintray.com/kotlin/kotlin-eap")
    maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")
}

dependencies {
    implementation(kotlin("stdlib"))
    testImplementation(kotlin("test-junit"))
}

tasks.withType<DokkaTask>().configureEach {
    dokkaSourceSets {
        named("main") {
            moduleName.set("Dokka Gradle Example")
            includes.from("Module.md")
            sourceLink {
                localDirectory.set(file("src/main/kotlin"))
                remoteUrl.set(URL("https://github.com/Kotlin/kotlin-examples/tree/master/" +
                        "gradle/dokka/dokka-gradle-example/src/main/kotlin"
                ))
                remoteLineSuffix.set("#L")
            }
        }
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.8.0
- Dokka version: 1.4.30

**Additional context**

I think it's just a broken link to some `js/json` file, because this is what the documentation directories look like in **1.4.20**:

![image](https://user-images.githubusercontent.com/31899809/113091392-77a0b280-91f4-11eb-9c84-9ba0d387937d.png)

And this is how they look in **1.4.30**:

![image](https://user-images.githubusercontent.com/31899809/113091433-8be4af80-91f4-11eb-99f6-d05075490757.png)

**Comment by MarcinAman** [comment]
Thats weird, i've just generated the output for a sample project and it works. Could you send me a zip with this broken search bar?

**Comment by AzimMuradov** [comment]
I changed the script according to code above and ran `./gradlew :clean :dokkaHtml`.

[dokka-gradle-example.zip](https://github.com/Kotlin/dokka/files/6235114/dokka-gradle-example.zip)

**Comment by AzimMuradov** [comment]
I use Google Chrome Version 89.0.4389.90

**Comment by kamildoleglo** [comment]
The search works correctly. Please make sure you use an HTTP server for serving those files
