### ISSUE TITLE
External documentation is broken when documenting Gradle multi-module projects

### ISSUE THREAD

**Issue by twyatt** [Kotlin/dokka#1825]
**Describe the bug**

External documentation links (via [`externalDocumentationLink`](https://kotlin.github.io/dokka/1.4.30/user_guide/gradle/usage/#configuration-options)) don't appear to work in combination with [`dokkaHtmlMultiModule` task](https://github.com/Kotlin/dokka#multi-module-projects).

**Expected behaviour**

External documentation links are properly linked.

**Screenshots**

_Click screenshots (below) to be taken to corresponding published page._
Note: `Message.Udp` is class from external project, [KoAP](https://github.com/JuulLabs/koap).

**Works** for individual module documentation (`./gradlew :example1:dokkaHtml`):

[![Screen Shot 2021-04-06 at 10 56 57 PM](https://user-images.githubusercontent.com/98017/113817628-8246d480-972b-11eb-93ce-3a01961b7dbb.png)](https://twyatt.github.io/dokka-external-documentation-test/example1/example1/[root]/-example1/index.html)

**Broken** for multi-module documentation (`./gradlew dokkaHtmlMultiModule`):

[![Screen Shot 2021-04-06 at 10 59 35 PM](https://user-images.githubusercontent.com/98017/113817868-db166d00-972b-11eb-895c-698eca3edcb0.png)](https://twyatt.github.io/dokka-external-documentation-test/multimodule/example1/example1/[root]/-example1/index.html)

**To Reproduce**

1. Configure external documentation (via [`externalDocumentationLink`](https://kotlin.github.io/dokka/1.4.30/user_guide/gradle/usage/#configuration-options))
2. Configure multi-module Dokka documentation generation with [`dokkaHtmlMultiModule` task](https://github.com/Kotlin/dokka#multi-module-projects)
3. Run `./gradlew dokkaHtmlMultiModule`

Reproduced in the following GitHub repository: https://github.com/twyatt/dokka-external-documentation-test

You can demo the issue via GitHub Pages (where documentation is published):
- [`example1`](https://twyatt.github.io/dokka-external-documentation-test/example1/) (**works**, using `dokkaHtml` task)
- [`example2`](https://twyatt.github.io/dokka-external-documentation-test/example2/) (depends on `example1` module, **works**, using `dokkaHtml` task)
- [`multimodule`](https://twyatt.github.io/dokka-external-documentation-test/multimodule/) (**broken**, using `dokkaHtmlMultiModule` task)

**Dokka configuration**

```Kotlin
// ...

plugins {
    kotlin("multiplatform") version "1.4.31" apply false
    id("org.jetbrains.dokka") version "1.4.30"
}

allprojects {
    // ...

    tasks.withType<org.jetbrains.dokka.gradle.DokkaTask>().configureEach {
        dokkaSourceSets {
            configureEach {
                externalDocumentationLink(
                    url = "https://juullabs.github.io/koap/docs/",
                    packageListUrl = "https://juullabs.github.io/koap/docs/koap/package-list"
                )
            }
        }
    }
}

tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(buildDir.resolve("dokkaHtmlMultiModule"))
}
```

**Installation**
- Operating system: macOS and Ubuntu 18.04 via GitHub Actions
- Build tool: Gradle v6.7
- Dokka version: 1.4.30

**Comment by MarcinAman** [comment]
Please change the configured task type from `DokkaTask` to `DokkaTaskPartial`. Since it is not that clear i'll docs will be updated in https://github.com/Kotlin/dokka/pull/1826
