### ISSUE TITLE
Dokka 0.10.1 is incompatible with Gradle 7.0

### ISSUE THREAD

**Issue by colinrtwhite** [Kotlin/dokka#1834]
**Describe the bug**
Dokka 0.10.1 fails to run with Gradle 7.0 due to the following error:

```
  - Type 'DokkaTask' property 'configuration.collectKotlinTasks' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'DokkaTask' property 'configuration.name' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'DokkaTask' property 'dokkaRuntime' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
```

Example run: https://github.com/coil-kt/coil/runs/2310591877

It looks like the deprecation was reported [here](https://github.com/Kotlin/dokka/issues/515) in Gradle 6.0. The deprecated functionality was removed in Dokka 7.0.

**Expected behaviour**
Dokka 0.10.1 (the latest non-alpha version) should run successfully on Gradle 7.0. I'm unable to upgrade to the latest alpha versions due to several breaking changes in those versions.

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
The error can be reproduced by updating [this project](https://github.com/coil-kt/coil) to Gradle 7.0 and running `./assemble_docs.sh`.

**Dokka configuration**
https://github.com/coil-kt/coil/blob/master/build.gradle.kts#L71

**Installation**
- Operating system: Any
- Build tool: Gradle 7.0
- Dokka version: 0.10.1

**Additional context**
Add any other context about the problem here

**Comment by MarcinAman** [comment]
Hi, could you point us to the changes that are blocking your migration? Maybe we could help you out with upgrading dokka

**Comment by colinrtwhite** [comment]
@MarcinAman The main issue preventing me from upgrading is the GFM format has significantly changed between `0.10.1` and `1.4.x`. Here's a comparison of my docs before/after upgrading to `1.4.30`:

<img alt="Screen Shot 2021-04-13 at 2 00 31 PM" src="https://user-images.githubusercontent.com/5580160/114606349-c6bcfd80-9c60-11eb-9f8e-982855dc5e45.png" width=50%><img alt="Screen Shot 2021-04-13 at 2 00 12 PM" src="https://user-images.githubusercontent.com/5580160/114606361-c91f5780-9c60-11eb-92f2-48d12e060cca.png" width=50%>

- New lines for [androidJvm] (my project is androidJvm-only), Content, and More info are added. Is it possible to disable these?
- Sections are separated by 3 blank lines.
- Code is not formatted using back ticks.

Is it possible to revert to the old format or fix any of the above issues. Happy to file issues for the above. Thanks!

**Comment by MarcinAman** [comment]
Hi, it is not possible to revert to older way of rendering GFM in new dokka. Most of the codebase was rewritten from scratch

I think that fixing those issues will be a far better solution since it will enable other users to migrate. I'll split this issue into smaller ones.

**Comment by colinrtwhite** [comment]
@MarcinAman Thanks! Is it possible to push an update to the `0.10.x` branch to fix compatibility with Gradle 7.0 in the meantime?

**Comment by eneim** [comment]
Have the same issue here when updating my library to the latest Android Studio and Gradle 7. I wonder what is the use case of the new GFM format? Any library using this format we can refer to so that I can somehow migrate my doc website to use that new format instead of rolling back to Gradle 6.x?

**Comment by MarcinAman** [comment]
@colinrtwhite Due to limited resources, no. We won't release new version of old dokka.

**Comment by colinrtwhite** [comment]
@MarcinAman Understood, I'll move forward on migrating to the Dokka 1.4.30 HTML task. Any chance you know what might be causing https://github.com/Kotlin/dokka/issues/1860? It's blocking me from updating.

**Comment by MarcinAman** [comment]
I’ll try to investigate it tomorrow :)
