### ISSUE TITLE
CI: Java 11 or Java 12

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/dokka#1837]
**Question**
Why do you use sometime in the CI Java 11 and in the snapshot tests Java 12?

https://github.com/Kotlin/dokka/blob/c20d1170254d2251d868dd114c599020d42dbb72/.github/workflows/gradle-test.pr.yml#L15

https://github.com/Kotlin/dokka/blob/c20d1170254d2251d868dd114c599020d42dbb72/.github/workflows/s3-snapshots.yml#L20

**Comment by kamildoleglo** [comment]
No particular reason, although this helps us check for issues in in different JDK versions and honestly we don't see a point to bump that

**Comment by hfhbd** [comment]
Maybe you could use a matrix with different java version instead?
