### ISSUE TITLE
Module.md - Kotlin code sample with annotation fails

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/dokka#1838]
**Describe the bug**
If a code sample inside the Module.md contains an annotation, like `@ExperimentalTime` this sample and all following content is missing.

I checked out the sample code from https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka/dokka-gradle-example/src/main/kotlin.

**Expected behaviour**
Code sample containing the annotation

**Screenshots**
<img width="1894" alt="Bildschirmfoto 2021-04-12 um 00 42 08" src="https://user-images.githubusercontent.com/22521688/114323982-0cc27600-9b28-11eb-936e-5b6be8a89456.png">

**To Reproduce**
```markdown
# Module Dokka Gradle Example

This is an example of how you can write module documentation with Dokka.

## Testing Kotlin code

Sample 1/2

````kotlin
fun sample1() {

}
````
````markdown
Sample 2/2

````kotlin
@ExperimentalTime
fun sample2() {

}
````
````markdown
# Package demo

This package contains a few examples of Dokka usage.

````

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
import org.jetbrains.dokka.gradle.DokkaTask
import java.net.URL

plugins {
    kotlin("jvm") version "1.4.32"
    id("org.jetbrains.dokka") version ("1.4.30")
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testImplementation(kotlin("test-junit"))
}

tasks.withType<DokkaTask>().configureEach {
    dokkaSourceSets {
        configureEach {
            moduleName.set("Dokka Gradle Example")
            includes.from("Module.md")
            val sourceSetName = name
            println(sourceSetName)
            sourceLink {
                localDirectory.set(file("src/$sourceSetName/kotlin"))
                remoteUrl.set(URL("https://github.com/Kotlin/kotlin-examples/tree/master/" +
                        "gradle/dokka/dokka-gradle-example/src/main/kotlin"
                ))
                remoteLineSuffix.set("#L")
            }
        }
    }
}

```

**Installation**
- Operating system: macOS 11
- Build tool: Gradle v7.0
- Dokka version: 1.4.30

**Comment by IgnatBeresnev** [comment]
Partially fixed in upcoming 1.6.20. The fix will solve the majority of problems, although some corner cases may still arise
