### ISSUE TITLE
Performance regression in 1.9.30

### ISSUE THREAD

**Issue by czyzby** [Kotlin/dokka#1840]
**Describe the bug**
We recently updated from Dokka 1.4.10.2 to 1.4.30 in [libktx/ktx](https://github.com/libktx/ktx/). Our snapshot upload task used to take [about 7 minutes](https://github.com/libktx/ktx/runs/2324457102) on the GitHub CI (see the _Upload snapshot to Maven Central_ section). After updating the Dokka version, [one of the builds](https://github.com/libktx/ktx/runs/2324735604) was stuck for 50 minutes on one of the modules (`vis`) and had to be cancelled to avoid pushing stale releases. [Another pipeline](https://github.com/libktx/ktx/runs/2325026786) failed after 13 minutes at the same step with an error:

```
Execution failed for task ':vis:dokkaHtml'.
> GC overhead limit exceeded
```

**Expected behaviour**
The performance should be about the same or better. GC-related errors should not be raised.

**To Reproduce**
Run the `./gradlew dokkaHtml` task in the [libktx/ktx](https://github.com/libktx/ktx/) repository. Compare the performance between the `develop` branch and one of the tags like `1.9.14-b1`.

**Dokka configuration**
- Operating system: Linux
- Build tool: Gradle v6.8.3
- Dokka version: 1.4.30

**Additional context**
The performance regression greatly affects building time in CI environment.

**Comment by vmishenev** [comment]
@czyzby Is this still actual for new versions of Dokka?
[libktx/ktx ](https://github.com/libktx/ktx/blob/master/gradle.properties#L5) uses Dokka 1.5.30.

**Comment by czyzby** [comment]
The snapshot version no longer builds javadoc archives with Dokka. I think I might have turned it off because of this issue. I can update to a recent stable release to check, but the performance is no longer a problem for that particular project. For what it's worth, generating Dokka documentation for the website does not seem to fail even with 1.5.30.

**Comment by czyzby** [comment]
Just by running it locally, I can tell you that `1.17.10` is much faster on the KTX codebase. I think the only issue might be that Gradle tasks are normally not supposed to have that many debug/info logs, but I guess it's also fine for debugging/troubleshooting in CI if necessary. Haven't noticed any issues with the generated documentation either, and the newer theme does look nicer. I'm closing this issue, thanks.
