### ISSUE TITLE
Search bar is not working on version 1.4.30 with HTML backend.

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1847]
Search bar is not working on version 1.4.30 with HTML. I have tried both on my project and on the example project provided by 
https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka/dokka-multimodule-example

EDIT: It works on version 1.4.20 but not on 1.4.30.

**Comment by kamildoleglo** [comment]
Please use an HTTP server, effectively a duplicate of  https://github.com/Kotlin/dokka/issues/1588

**Comment by DanielRibeiroMaciel-TomTom** [comment]
Is this also something you want to explain in dokka documentation?
