### ISSUE TITLE
Using Markdown files per module doesn't work on multimodule projects

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1848]
I am using Dokka version 1.4.30
When I run dokkaHtml, the module documentations take in and process the markdown files as expected and I can see them in the per-module documentation correctly.
But when I run dokkaHtmlMultiModule, the output of that contains all modules but the modules themselves ignore the markdown files, I don't see the markdown output in my HTML docs.

**Comment by kamildoleglo** [comment]
Hi, you should change your Dokka configuration to configure `dokkaHtmlPartial` instead of `dokkaHtml` tasks, the documentation might not have been updated yet

**Comment by DanielRibeiroMaciel-TomTom** [comment]
I have changed from
```
        tasks.dokkaHtml {
            dokkaSourceSets {
                configureEach {
                    File(projectDir, "README.md").takeIf { it.exists() }?.let {
                        includes.from(it.absolutePath)
                    }
                }
            }
        }
```
to
```
        tasks.dokkaHtmlPartial {
            dokkaSourceSets {
                configureEach {
                    File(projectDir, "README.md").takeIf { it.exists() }?.let {
                        includes.from(it.absolutePath)
                    }
                }
            }
        }
```

It finds `tasks.dokkaHtml` but not `tasks.dokkaHtmlPartial`.

**Comment by DanielRibeiroMaciel-TomTom** [comment]
Using `tasks.withType<org.jetbrains.dokka.gradle.DokkaTask>().configureEach {` instead of `tasks.dokkaHtmlPartial { dokkaSourceSets { configureEach {` fixes the problem
