### ISSUE TITLE
Is it possible to add a README.md file to the parent multimodule project?

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1849]
Hi!

I am currently able to add markdown files to modules of a multimodule project - but I would also like to add a markdown file to the landing page (the which list of modules).

Also, is it possible to remove the list of modules altogether on a multimodule project? And use only a list of packages instead? The modules themselves are uninteresting to our customers, the packages provide enough organization.

Kind regards,
Daniel

**Comment by DanielRibeiroMaciel-TomTom** [comment]
Thanks for the reply.
@hfhbd We're a multimodule project, so we're already using the `README.md` for individual modules.
So unfortunately we can't "misuse" the `README.md` file in modules because we're already "using" them.

**Comment by rnett** [comment]
It is now in 1.4.32: see #1804.  You add an include to the `DokkaMultiModuleTask`.
