### ISSUE TITLE
gfm: No break before oveloaded function on class summary page

### ISSUE THREAD

**Issue by petr-panteleyev** [Kotlin/dokka#185]
Version 0.9.15. On class summary page no BR is generated between the end of previous overloaded function description block and the next one.

Example can be seen [here](https://petr-panteleyev.github.io/persistence-kt/persistence-kt/org.panteleyev.persistence/-d-a-o/) 
See Summary for `delele` and `insert`.

**Comment by slang03** [comment]
Can confirm. Same problem with:

- `jekyll`
- `markdown`

The issue is not present when using `html` as output format

**Comment by slang03** [comment]
For anyone who needs a quick fix:

```bash
find ./build/ -type f -name index.md -exec sed -i 's/\.`operator fun/\.<br>`operator fun/g' {} \;
find ./build/ -type f -name index.md -exec sed -i 's/\.`fun/\.<br>`fun/g' {} \;
```

**Comment by michaelbayles** [comment]
Can confirm still an issue on `0.9.17` and `0.9.18`

**Comment by Kordyjan** [comment]
This is about old gfm format which was dropped in 1.4.0
