### ISSUE TITLE
kotlinx-html-jvm is not on Maven Central

### ISSUE THREAD

**Issue by stoyicker** [Kotlin/dokka#1859]
**Describe the bug**
kotlinx-html-jvm-0.7.2 is found on [jcenter](https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/) but not on Maven Central.

**Expected behaviour**
As per [instructions for CLI usage](https://github.com/Kotlin/dokka/blob/5afe512c669e68aea3712ac37b67d005657cf60a/docs/src/doc/docs/user_guide/cli/usage.md), this artifact should be on maven central.

If I'm not mistaken, this also affects projects using Dokka via buildsystem (e.g. Gradle plugin) without jcenter defined as a repository - which is likely the case for many projects trying to migrate away from it due to[ its shutdown in the comng months](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

I'm not exactly sure if the solution here would be to update said instructions, publish the artifact to maven central, or something else entirely.

**Comment by MarcinAman** [comment]
Those are not our artefacts, so we can't publish them to maven central. This issue is already present on their repository: https://github.com/Kotlin/kotlinx.html/issues/173 . For now you can use their space packages repository: https://github.com/kotlin/kotlinx.html/wiki/Getting-started
