### ISSUE TITLE
Dokka 0.9.15 Gradle plugin task does not execute after source updates

### ISSUE THREAD

**Issue by srackham** [Kotlin/dokka#186]
Dokka 0.9.15, Kotlin 1.1.3, Gradle 4.0.

I'm experiencing what appears to be a regression since version 0.9.14.
The gradle `dokka` task fails to execute after the source is edited,
I have to delete the built docs to force task execution and I have
to delete the previously built documentation to force a rebuild:

```
$ vi src/main/kotlin/demo/HelloWorld.kt   <---- EDIT SOURCE

$ ./gradlew dokka

BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date           <---- NO DOC REBUILD

$ rm -rf build/dokka/                     <---- REMOVE DOCS

$ ./gradlew dokka

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed             <---- DOC REBUILD
```

The problem does not exist in version 0.9.14.

**Comment by semoro** [comment]
Fixed in [0.9.16](https://github.com/Kotlin/dokka/releases/tag/0.9.16)
