### ISSUE TITLE
Merge multiproject (composite build) docs

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1864]
How do I merge multiproject docs? Is that currently possible? We're using 1.4.30.
If not, is there a workaround? In older versions of dokka it was possible to add external files to the classpath, but It is not clear to me how I could do that in the newer dokka rewrite. Especially if I still want the modules from the composite project to appear as modules in the merged dokka documentation?

It would already help if it was possible to just add the sources of the secondary project to the dokka classpath of the parent project.

**Comment by kamildoleglo** [comment]
Yes, it's supported by default, please see http://kotlin.github.io/dokka/1.5/user_guide/gradle/usage/#multi-module-projects

**Comment by kamildoleglo** [comment]
As for composite builds - as long as you add output of the DokkaPartial tasks from those composite builds to the root DokkaMultiModule task via childDokkaTasks it shouldn't be a problem (we've not tested that one yet though)

**Comment by DanielRibeiroMaciel-TomTom** [comment]
@kamildoleglo note I am asking about multiproject and not multimodule. I am already using `dokkaHtmlMultiModule` task.
But we also have composite builds (multiple projects, each containing multiple modules).

**Comment by DanielRibeiroMaciel-TomTom** [comment]
I will try the `childDokkaTasks` solution, thanks.

**Comment by kamildoleglo** [comment]
Sure, but AFAIK you can use the tasks from composite builds like ordinary ones (at least their output and that's what we're after)

**Comment by IgnatBeresnev** [comment]
I'll close the question as resolved, hopefully you were able to figure it out.

In case anyone else has the same question or it's still relevant, please consult [Dokka's documentation](https://kotlinlang.org/docs/dokka-gradle.html), it might have answers

**Comment by shyr** [comment]
@DanielRibeiroMaciel-TomTom Hi, Daniel. Did you succeed in merging multiple documents? I am struggling with the same issue.
