### ISSUE TITLE
Unable to generate documentation for kapt generated sources

### ISSUE THREAD

**Issue by F43nd1r** [Kotlin/dokka#1865]
**Describe the bug**
Dokka ignores sourcesets added by kapt (`build/generated/source/kaptKotlin/release`)

**Expected behaviour**
Dokka should allow adding generated source roots

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
tasks.withType<DokkaTask> {
    dokkaSourceSets.configureEach {
        sourceRoot(buildDir.resolve("generated/source/kaptKotlin/release/"))
    }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v7.0
- Dokka version: 1.4.30

**Comment by MarcinAman** [comment]
Fixed by: https://github.com/Kotlin/dokka/pull/1832

It will be present in next release (it should be public by the end of a week)
