### ISSUE TITLE
HTML Frontend: left hand sidebar should expand modules/packages on click

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1869]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/32281897/115484525-d3fd5d80-a207-11eb-9ff0-6f9c9635a2eb.png)

IMO, clicks in the highlighted area should expand the module/package, not just clicks on the little arrow at the end.  It's just empty space at the moment, and those arrows are small.

**Comment by rnett** [comment]
With the new HTML style, this applies to all links in the navigation sidebar.  Currently, only the text is clickable, while IMO it should be the entire row, especially since the whole row is highlighted.

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
