### ISSUE TITLE
HTML: Platform indications not shown for multiplatform project w/ only commonMain

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1873]
**Describe the bug**
I have a multiplatform module in a multi-module project: https://github.com/rnett/krosstalk/tree/main/core/krosstalk.

All sources are in `commonMain`, and are thus present on all platforms.  However, I see no platform indicators:
![image](https://user-images.githubusercontent.com/32281897/115660589-15b60300-a2f1-11eb-84b9-973e09588e98.png)

**Expected behaviour**
Platform indicators for the multiplatform module.

**To Reproduce**
See https://github.com/rnett/krosstalk CI

**Dokka configuration**
https://github.com/rnett/krosstalk/blob/main/build.gradle.kts

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.8.3
- Dokka version: 1.4.30

**Comment by aajtodd** [comment]
Seeing the same issue with much of [awslabs/aws-sdk-kotlin](https://github.com/awslabs/aws-sdk-kotlin)

**Comment by IgnatBeresnev** [comment]
Implemented in 1.8.10, description: https://github.com/Kotlin/dokka/issues/2847. Please let me know if I understood it wrong and your bug request is different
