### ISSUE TITLE
Option to show platform indicators for all platforms in multi module project

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1874]
**Is your feature request related to a problem? Please describe**
I have a multi module project where some modules are multiplatform, but some are single platform.  I would like the ability to show platform indicators on the single-platform modules as well, since it is very relevant info.

**Describe the solution you'd like**
A configuration option, probably true by default, to show platform indicators for all platforms in the multi-module project.

**Additional context**
This may be done already but just not showing up because of #1873.

**Comment by IgnatBeresnev** [comment]
Implemented in 1.8.10, description: #2847. Please let me know if I understood it wrong and your feature request is different
