### ISSUE TITLE
Dokka version 1.4.32

### ISSUE THREAD

**Issue by headsvk** [Kotlin/dokka#1875]
**Question**
Hello,
The documentation states we can include dokka like this:
`id("org.jetbrains.dokka") version "1.4.32"`

However, it doesn't work as there's no version 1.4.32, the latest seems to be 1.4.30.
https://plugins.gradle.org/plugin/org.jetbrains.dokka

Is it a bug in the documentation or has the repository changed?
Thanks

**Comment by kamildoleglo** [comment]
1.4.32 should be released in a few hours

**Comment by kamildoleglo** [comment]
Released
