### ISSUE TITLE
HTML: Package description runs into "On this page"

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1881]
**Describe the bug**
The package description text will run up against the "On this page" indicator.

![image](https://user-images.githubusercontent.com/32281897/115800326-3a60b800-a38f-11eb-9b16-6f9a982f56cf.png)

**Expected behaviour**
There is some space between the UI elements.

**Installation**
- Operating system: Windows
- Build tool: Gradle v6.8.3
- Dokka version: 1.4.32

**Comment by IgnatBeresnev** [comment]
This looks like it's from the old UI and is not relevant anymore, so I'll close the issue.

Please let me know if I understood it wrong and it exists with the [new format](https://kotlinlang.org/api/kotlinx.coroutines/).
