### ISSUE TITLE
Line break in javadoc comment of enum entry is missing a space

### ISSUE THREAD

**Issue by asfalcone** [Kotlin/dokka#1895]
**Describe the bug**
```
 /**
 * class level docs
 */
public enum AnEnumType {
    /**
     * content being refreshed, which can be a result of
     * invalidation, refresh that may contain content updates, or the initial load.
     */
    REFRESH,
    /**
     * Load at the start
     */
    PREPEND,
    /**
     * Load at the end.
     */
    APPEND

    fun foo()
}
```
Text of enum entry contains "result ofinvalidation"

**Expected behaviour**
Text of enum entry contains "result of invalidation"

**Screenshots**
![image](https://user-images.githubusercontent.com/1848683/116136637-8d44b300-a6a0-11eb-9ac1-81bcb6016119.png)

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v6.8.0/Maven/Cli/3rd party plugin
- Dokka version: 1.4.30

**Comment by owengray-google** [comment]
There is a case where this seems to be inserting more spaces than we'd want.

Many of our java sources (like [Fragment.java](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/Fragment.java;drc=9dd08b4a19659015b864573860df4e9eedb277e9;l=1640)) have docs like:
```
    /**
     * Returns the cached LayoutInflater used to inflate Views of this Fragment. If
     * {@link #onGetLayoutInflater(Bundle)} has not been called {@link #onGetLayoutInflater(Bundle)}
     * will be called with a {@code null} argument and that value will be cached.
     * <p>
     * The cached LayoutInflater will be replaced immediately prior to
     * {@link #onCreateView(LayoutInflater, ViewGroup, Bundle)} and cleared immediately after
     * {@link #onDetach()}.
     *
     * @return The LayoutInflater used to inflate Views of this Fragment.
     */
```
Which we are now getting rendered as 
```
...argument and that value will be cached. </p>
      <p> The cached LayoutInflater will be replaced...
```
With a space between `<p>` and `The cached...`

<p> appears to be the consensus way to insert line breaks in rendered javadoc. Developers seem to like putting them on their own line for clarity, and to make source docs parallel rendered doc.
If there's alternate guidance for this, we can look at changing how this is done in source.

I think what we'd like here might be for spaces to not be inserted if one of the lines being concatenated contains only html tags?

A similar case
```
    /**
     * (this is a real function, vastly simplified from the source in Fragment.java).
     *
     * <p>
     * If the host of this fragment is an 
```
Which becomes
```
      <p>(this is a real function, vastly simplified from the source in Fragment.java) </p>
      <p> If the host of this fragment is an
```
With extra spaces before the`</p>` and after the `<p>`.
