### ISSUE TITLE
intellij does not show param description

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#190]
Following an example
```kotlin
interface Person {
   /**
     * The last name of the person.
     */
   val name: String
}

/**
 * My description, bla bla..
 *
 * @constructor
 * @param firstName The first name of the person.
 * @param name The last name of the person.
 */
class Student(val firstName: String, override val name: String) : Person
```
There are two things which are wrong in this example IMO. 
1. I have to repeat the documentation of the constructor parameter `name` in `Student`, even though a documentation is given in `Person` . Unfortunately my suggestion in #151 was implemented in another way (which does not solve the problem as you can see). I hope you reconsider to implement it the other way round (or both). If the documentation of a constructor parameter is missing and it is a property in the same time, then it should automatically take over the documentation of the property.

2. intellij does not show the documentation of the property firstName - I guess #151 has only implemented the behaviour in dokka but not in the intellij-plugin. Right now I still have to copy the documentation to serve a nice API-documentation to consumers

**Comment by Kordyjan** [comment]
If I understand it correctly, this is about a bug in IntelliJ, which is not using dokka in any way.

**Comment by robstoll** [comment]
IMO dokka should be aligned with intellij as it is not very user friendly if I have to provide more documentation just because the two tools are not in sync

**Comment by kamildoleglo** [comment]
I agree, however those are two completely separate projects and we can do nothing about it. 
The request for the `intellij-plugin` should be created in their repository

**Comment by robstoll** [comment]
I agree that I have to create an issue for the second point but the first still holds I guess. I am going to verify it (some time in the future) and write here again if it isn't already fixed
