### ISSUE TITLE
Indicator on "On this page" menu doesn't move when clicking on menu items.

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1903]
The blue indicator doesn't move when clicking around on items. The scrollbar moves, but not the indicator.

![image](https://user-images.githubusercontent.com/72128546/116980490-951add80-acc6-11eb-939d-10aa35a25d73.png)

**Comment by DanielRibeiroMaciel-TomTom** [comment]
(It is a minor problem, but an issue nonetheless, so better log it, but no rush to fix I suppose.)

**Comment by IgnatBeresnev** [comment]
Thanks for reporting it!

Looks like this issue is specific to the old UI which has since been revamped, so closing this for now
