### ISSUE TITLE
Maven plugin doesn't link kotlin-stdlib-js classes

### ISSUE THREAD

**Issue by svitalsky** [Kotlin/dokka#1906]
**Describe the bug**
When generating KDoc with Dokka via dokka-maven-plugin (1.4.32) for a Kotlin/JS project, the classes from kotlin-stdlib-js are not linked and are instead displayed as &lt;ERROR CLASS>, i.e. for `fun HTMLElement.component(label: String, init: () -> Unit)` we get KDoc as `fun <ERROR CLASS>.component(label: String, init: () -> Unit)`. When generating the KDoc with Dokka Gradle plugin it works OK, however that is not an option in the project.

**Expected behaviour**
Classes from kotlin-stdlib-js should be linked/displayed properly.

**Screenshots**
With Gradle
![with-gradle](https://user-images.githubusercontent.com/17103067/117288186-815cac00-ae6b-11eb-96ca-5f4f6374982f.png)

With Maven
![with-maven](https://user-images.githubusercontent.com/17103067/117288190-81f54280-ae6b-11eb-8bc2-bab70b2ef0c5.png)

**To Reproduce**
Create Kotlin/JS project.
Create function using as a receiver or parameter some class from kotlin-stdlib-js.
Document the function.
Create KDoc documentation using dokka-maven-plugin.

**Dokka configuration**

```Xml
            <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>1.4.32</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>dokka</goal>
                        </goals>
                    </execution>
                    <configuration>
                        <suppressObviousFunctions>true</suppressObviousFunctions>
                    </configuration>
                </executions>
            </plugin>

```

**Installation**
- Operating system: Windows and Linux
- Build tool: dokka-maven-plugin
- Dokka version: 1.4.32

**Are you willing to provide a PR?**
I don't have any.

**Comment by MarcinAman** [comment]
Error classes are a result of missing jars on classpath. Could you share your project with us?

**Comment by svitalsky** [comment]
@MarcinAman: I cannot share the project, however I can provide MWE instead:

This is MWE with Gradle that works just fine: `gradle build` builds the project, `gradle dokkaHtml` generates documentation with the stdlib-js classes linked.
[with-gradle.tar.gz](https://github.com/Kotlin/dokka/files/6438395/with-gradle.tar.gz)

This is MWE with Maven: `mvn package` builds the project, however `mvn dokka:dokka` creates documentation with ERROR CLASSes, that is stdlib-js is not linked into the generated documentation.
[with-maven.tar.gz](https://github.com/Kotlin/dokka/files/6438396/with-maven.tar.gz)

Hope that helps.

**Comment by MarcinAman** [comment]
Okey, the issue is a wrong platform passed to kotlin analysis. Please add js as platform like:

```
<configuration>
    <suppressObviousFunctions>true</suppressObviousFunctions>
    <platform>js</platform>
 </configuration>
```

Unfortunately i don't think it is possible to set this property by default like in gradle since maven doesn't handle information about sourcesets and parsing it from... something (maybe last kotlin's stdlib?) is not reliable to say at least :D
