### ISSUE TITLE
Using an annotation in code blocks breaks Dokka parsing

### ISSUE THREAD

**Issue by IngoHaumann-TomTom** [Kotlin/dokka#1910]
Using Kotlin annotations in code blocks, breaks the parsing and messes up the output. We have to escape the leading `@` in order for Dokka to produce the expected output. All other Markdown tools we use do not have this issue and rightfully show the back slash in their output when we escape the annotation.

**Expected behaviour**
Anything between triple back ticks is added to the documentation verbatim.

**To Reproduce**
Use the following snippet: (I'm using an image as I cannot escape triple back ticks here.)
![image](https://user-images.githubusercontent.com/67146340/117645100-7c10a180-b18a-11eb-8fc8-dd80f7f624f5.png)

**Screenshots**
The above produces this output:
![image](https://user-images.githubusercontent.com/67146340/117637914-95adeb00-b182-11eb-9f93-9279e4a67dd4.png)

**Installation**
- Operating system: Linux
- Build tool: Gradle v7.0
- Dokka version: 1.4.32

**Comment by jakobkmar** [comment]
The behaviour for me is that markdown just completly breaks after an annotation and everything after it is missing from the generated output. Also, escaping it does not work anymore.

**Comment by IgnatBeresnev** [comment]
Partially fixed in upcoming 1.6.20. The fix will solve the majority of problems, although some corner cases may still arise
