### ISSUE TITLE
Line break inside of {@link} breaks generated JavaDoc links

### ISSUE THREAD

**Issue by thebnich** [Kotlin/dokka#1911]
In Java, links can be added using the `@link` tag. If the comment line is wrapped after the `@link` tag, the link is broken and no text appears at all.

For example, consider the following in a `.java` file:
```
/**
 * This is a comment linking to {@link
 * androidx.fragment.app.Fragment}.
 */
```

**Expected behaviour**
> This is a comment linking to [Fragment](url).

**Actual output**
> This is a comment linking to .

**To Reproduce**
`./gradlew dokkaHtml`

**Comment by MarcinAman** [comment]
Oh :(
I was able to reproduce it with 1.4.32, for now the work-around would be just to inline the tag

**Comment by andrewlewis** [comment]
We ran into this issue when trying out dokka with the [ExoPlayer](https://github.com/google/ExoPlayer) documentation.

[Here](https://github.com/google/ExoPlayer/blob/9c27cfc/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L1037-L1038) is an example:

```
  /**
   * Reason why playback is suppressed even though {@link #getPlayWhenReady()} is {@code true}. One
   * of {@link #PLAYBACK_SUPPRESSION_REASON_NONE} or {@link
   * #PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS}.
   */
```

... which renders like:

![link-split](https://user-images.githubusercontent.com/107897/130134938-f2d7c20a-92b3-42fe-bb84-1cd062f31adf.png)

[Here's](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.PlaybackSuppressionReason.html) how it shows up with our current javadoc generation.

Our auto formatting system wraps within @link tags like this so putting it on one line will be difficult. We'd like to migrate to Dokka as soon as possible so it would be great if you could prioritize this. Thanks!
