### ISSUE TITLE
Gradle Plugin Portal still shows 1.4.30 as the latest version for Dokka Gradle plugin

### ISSUE THREAD

**Issue by izeye** [Kotlin/dokka#1918]
Dokka Gradle plugin 1.4.32 is available, but Gradle Plugin Portal still shows 1.4.30 as the latest version for Dokka Gradle plugin somehow.

See https://plugins.gradle.org/plugin/org.jetbrains.dokka

**Comment by MarcinAman** [comment]
We are present primarily on mavenCentral, but i don't see a reason not to publish artefacts to gradle plugin portal. The version that you see was a work-around but we can continue to publish there. 

As this is not crucial i'll do it within a few days

**Comment by sschuberth** [comment]
> As this is not crucial i'll do it within a few days

It *is* somewhat crucial to publish to the Gradle plugin portal, as when using the recommended [plugin DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) to apply plugins, Maven Central is not searched by default.

**Comment by vmishenev** [comment]
We have published Dokka 1.6.0 (the latest version at this moment) on the Gradle plugin portal. Next versions will be presented there as well.
