### ISSUE TITLE
Dokka ignores perPackageOption.matchingRegex

### ISSUE THREAD

**Issue by breandan** [Kotlin/dokka#1919]
**Describe the bug**

When I configure the [`matchingRegex`](https://github.com/Kotlin/dokka/blob/5afe512c669e68aea3712ac37b67d005657cf60a/runners/maven-plugin/src/main/kotlin/DokkaMojo.kt#L69) option [in my project](https://github.com/breandan/kotlingrad/blob/1f24b592249ceb7de486aa686c6a4c5c8c39bb03/build.gradle.kts#L72), however Dokka appears to generate [documentation for all packages](http://breandan.net/kotlingrad/kotlingrad/index.html), regardless of what regex is used. I have tried various regex patterns, e.g. `.*edu.*`, `kotlingrad`, `edu.umontreal.kotlingrad`.

**Expected behaviour**

Dokka should only generate documentation for packages matching the regex set in `matchingRegex`.

**Screenshots**

http://breandan.net/kotlingrad/kotlingrad/index.html

**To Reproduce**

Run `./gradlew dokkaHtmlMultiModule --no-daemon --no-parallel --stacktrace -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2G"` in the [parent project](https://github.com/breandan/kotlingrad).

**Dokka configuration**

```Kotlin
subprojects {
  apply<DokkaPlugin>()

  tasks.withType<DokkaTaskPartial> {
    dokkaSourceSets.configureEach {
      jdkVersion.set(11)

      sourceLink {
        localDirectory.set(file("core/src/main/kotlin"))
        remoteUrl.set(URL("https://github.com/breandan/kotlingrad/blob/master/core/src/main/kotlin"))
        remoteLineSuffix.set("#L")
      }

      sourceLink {
        localDirectory.set(file("samples/src/main/kotlin"))
        remoteUrl.set(URL("https://github.com/breandan/kotlingrad/blob/master/samples/src/main/kotlin"))
        remoteLineSuffix.set("#L")
      }

      // This does not seem to work...
      perPackageOption {
        matchingRegex.set("edu.umontreal.kotlingrad")
      }

      externalDocumentationLink("https://ejml.org/javadoc/")
    }
  }
}
```

**Installation**
- Operating system: Linux
- Build tool: Gradle v7.0.2
- Dokka version: 1.4.32

**Comment by MarcinAman** [comment]
Per package options doesn't work this way. Idea behind those is to configure settings on a per package basis. So for example if you would like to skip deprecated only in some package (or group of packages). The configuration that you pasted there doesn't do anything, since it only applies a default per package options to your package. 

I see that you would like to document only a subset of a module. You can do it with:
```
perPackageOption {
// Match all packages and suppress them 
    matchingRegex.set("(.*?)")
    suppress.set(true)
}
perPackageOption {
// unsuppress only the ones that we care about
    matchingRegex.set("core.*") //Match packages you care about
    suppress.set(false)
}
```

Btw i see you configure `DokkaTaskPartial`, do you want to generate docs for multimodule?

**Comment by breandan** [comment]
Thank you, now I understand.

> Btw i see you configure `DokkaTaskPartial`, do you want to generate docs for multimodule?

Yes, it seems to work on multimodule Gradle builds. Is there a problem here?

**Comment by MarcinAman** [comment]
No, but you will need to generate multimodule docs. It is not wrong, i am just wondering whether you want to generate multimodule docs instead of just for a specific module

**Comment by breandan** [comment]
Our project structure is setup as follows: the [core API](https://github.com/breandan/kotlingrad/tree/master/core) is located in a separate module from the [code samples](https://github.com/breandan/kotlingrad/tree/master/samples) under the same namespace (`edu.umontreal.kotlingrad.*`). I am trying to link API endpoints in the `core` module to the `samples` module using Dokka's `@samples` annotation. Do I need a multimodule build for this to work, or can I link to code outside an included module?

**Comment by MarcinAman** [comment]
Oh, in this case it is not possible so i think you are correct in using multimodule ☺️

**Comment by kamildoleglo** [comment]
@breandan I think you can do that without the multimodule. Just run `dokkaHtml` on the coreApi and point the `samples` (configuration option http://kotlin.github.io/dokka/1.5/user_guide/gradle/usage/) to the `code samples` dir and you should be good to go 👍
