### ISSUE TITLE
How do you supply module descriptions in dokka multi-module?

### ISSUE THREAD

**Issue by Sintrastes** [Kotlin/dokka#1925]
**Question**
I have a multi-module gradle project (dokka 1.4.32) with three modules: "core", "android", and "desktop". At the root of my project, I created a `modules.md` file formatted as follows:

```
# Module core

Core documentation

# Module android

Android documentation

# Module desktop

Desktop documentation
```

and in my `build.gradle.kts` configuration for dokkaMultiModule:

```
tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(buildDir.resolve("dokkaCustomMultiModuleOutput"))
    includes.from("modules.md")
}
```

However, instead of adding the description text to the appropriate module under "all modules" in the generated index.html, this markdown file just gets rendered at the top of the file like so:

![dokka](https://user-images.githubusercontent.com/4064213/118662068-b64af600-b7bd-11eb-99e9-0f178fda6c4d.PNG)

Am I doing this right? The documentation [here](https://kotlinlang.org/docs/kotlin-doc.html#module-and-package-documentation) does not seem to be working for me in 1.4.32.

**Comment by MarcinAman** [comment]
They have to be defined for each module independently. Here is an example: https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka/dokka-multimodule-example

And the configuration: https://github.com/Kotlin/kotlin-examples/blob/25040fe92994ab46ebac6a6450d3ad1d3e870af1/gradle/dokka/dokka-multimodule-example/parentProject/childProjectA/build.gradle.kts#L15

**Comment by essmigel** [comment]
you just have to configure the dokkaHtmlPartial and use the latest version of Dokka,
for me after using the dokka version of 1.5.30 and configure the dokkaHtmlPartial, every things worked for me

dokkaHtmlPartial{
    dokkaSourceSets {
        // configure here
    }
}
