### ISSUE TITLE
Where is android example

### ISSUE THREAD

**Issue by aitazhixin** [Kotlin/dokka#1927]
I am using dokka-gradle-plugin:1.4.32 and dokka-android-gradle-plugin:0.9.18.
But, the dokka task can not be found, is there any example for AndroidStudio gradle?

**Comment by IgnatBeresnev** [comment]
Hi! Generally speaking, android projects should be configured the same way as non-Android ones.

Please have a look at Gradle examples: [examples/gradle](https://github.com/Kotlin/dokka/tree/master/examples/gradle)

For more information, see [Dokka's documentation](https://kotlinlang.org/docs/dokka-get-started.html), it has recently been updated to include more examples

I'll close the issue as it has been some time and I hope you were able to figure it out on your own, but let us know if you have any further questions
