### ISSUE TITLE
CSS files are not found when single html file is generated from a class

### ISSUE THREAD

**Issue by Armaxis** [Kotlin/dokka#1934]
**Describe the bug**
We have updated to `1.4.32` from `0.9.x` and while verifying the generated docs noticed an issue with a file that contained only `typealias` definitions inside a package. 
It was displayed without any styling applied, and console showed multiple errors loading `css` and `js` files.
Apparently, when a Kotlin file contains only `typealias` definitions, Dokka generates a single `html` file for it instead of a regular folder. This makes the file appear on a same level as other folder, and it messes up the relative paths to styles and scripts.

**Expected behaviour**
Styles should be picked no matter where the file is located.

**Screenshots**

### Index page

![image](https://user-images.githubusercontent.com/2152942/119412170-199ec180-bcb1-11eb-896b-8c388c025733.png)

### Demo page - displayed properly

![image](https://user-images.githubusercontent.com/2152942/119412205-24595680-bcb1-11eb-9ad3-c4789206f142.png)

### Bug page - broken 

![image](https://user-images.githubusercontent.com/2152942/119412238-32a77280-bcb1-11eb-911e-0f8a235afb3a.png)

### Chrome Console

![image](https://user-images.githubusercontent.com/2152942/119412356-5bc80300-bcb1-11eb-937f-7c2511b162c0.png)

### File structure of generated docs

![image](https://user-images.githubusercontent.com/2152942/119412443-8023df80-bcb1-11eb-81e7-8d20be0a563c.png)

**To Reproduce**
I made a fork of `dokka-gradle-example` where the [bug is reproducible](https://github.com/Armaxis/kotlin-examples/tree/master/gradle/dokka/dokka-gradle-example)

Or you can apply this patch to your local copy:

```
Index: gradle/dokka/dokka-gradle-example/Module.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gradle/dokka/dokka-gradle-example/Module.md	(revision 25040fe92994ab46ebac6a6450d3ad1d3e870af1)
+++ gradle/dokka/dokka-gradle-example/Module.md	(revision b039ac5299d225cb1b93597edec52d201e22c9e8)
@@ -5,3 +5,7 @@
 # Package demo
 
 This package contains a few examples of Dokka usage.
+
+# Package bug
+
+This package contains only one typealias.
\ No newline at end of file
Index: gradle/dokka/dokka-gradle-example/src/main/kotlin/bug/Alias.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gradle/dokka/dokka-gradle-example/src/main/kotlin/bug/Alias.kt	(revision b039ac5299d225cb1b93597edec52d201e22c9e8)
+++ gradle/dokka/dokka-gradle-example/src/main/kotlin/bug/Alias.kt	(revision b039ac5299d225cb1b93597edec52d201e22c9e8)
@@ -0,0 +1,6 @@
+package bug
+
+typealias FancyString = String
+
+// Uncomment object definition and bug will disappear
+//object Alias
\ No newline at end of file
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.8.0
- Dokka version: 1.4.32

**Comment by MarcinAman** [comment]
Nice catch! Thanks for the reproducable example
