### ISSUE TITLE
Upgrade to Kotlin 1.5.10 leads to :dokka ClassCastException

### ISSUE THREAD

**Issue by akarnokd** [Kotlin/dokka#1935]
**Describe the bug**
After upgrading to Kotlin 1.5.10, now I get the following exception with the :dokka plugin:

Could not determine the dependencies of task ':dokka'.
> class org.gradle.api.internal.file.CompositeFileCollection$1 cannot be cast to class java.util.List
> at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:71)
> Caused by:
> at org.jetbrains.dokka.gradle.DokkaTask.extractClasspathAndSourceRootsFromKotlinTasks(main.kt:239)
	at org.jetbrains.dokka.gradle.DokkaTask.getInputFiles(main.kt:369)

Worked with 1.4.32 before.

**Expected behaviour**
Works

**Screenshots**
N/A

**To Reproduce**
Build this branch:

https://github.com/akarnokd/kotlin-flow-extensions/tree/dependabot/gradle%2Fkotlin_version-1.5.10

**Dokka configuration**
Default config.

```Kotlin

```

**Installation**
- Operating system: Windows & Linux
- Build tool: Gradle v6.9
- Dokka version: 1.4.30

**Additional context**
N/A.

**Are you willing to provide a PR?**
Unlikely.

**Comment by MarcinAman** [comment]
Could you please specify:
- where is your dokka plugin applied in project
- how its version is managed

**Comment by akarnokd** [comment]
This is [my buildscript referencing the kotlin plugin](https://github.com/akarnokd/kotlin-flow-extensions/blob/dependabot/gradle/kotlin_version-1.5.10/build.gradle):

```groovy
buildscript {
    ext.kotlin_version = '1.5.10'

    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "biz.aQute.bnd:biz.aQute.bnd.gradle:5.3.0"
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.8.0'
        classpath "gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:0.15.0"
    }
}

apply plugin: 'kotlin'
```

There is nothing else specified related to dokka, no direct calls or explicit version specified anywhere in my project.

**Comment by akarnokd** [comment]
I think I found the problem: com.vanniktech:gradle-maven-publish-plugin:0.8.0 could be depending on an earlier dokka version which then fails with the newer kotlin plugin. Upgrading it to 0.15.1 and specifying the latest dokka plugin no longer crashes.

**Comment by MarcinAman** [comment]
Yes, they depend on old dokka (0.9.17) as gradle is displaying in `./gradlew buildEnvironment`. I've checked out kotlin 1.5.10 with dokka 1.4.32 and it works. We will have a 1.5.0 release soon (probably in about a month) so all the newest features will be supported
