### ISSUE TITLE
Cannot generate dokka with gradlew in Android Studio

### ISSUE THREAD

**Issue by anhmiuhv** [Kotlin/dokka#194]
Trying to generate dokka on my linux mint. Got this:
https://gist.github.com/anhmiuhv/2bf307b89359d807ac627419efe2e072

it works fine on my Mac.

**Comment by Tapchicoma** [comment]
Can you check if related answer on SO is possible reason?

https://stackoverflow.com/questions/43902679/compilereleasekotlin-fails-with-java-lang-classnotfoundexception-com-sun-tools

**Comment by semoro** [comment]
Looks like it unrelated to Dokka, but an exception from kotlin gradle plugin during kapt run. And seems related to posted stackoverflow question.
