### ISSUE TITLE
Versioning takes up exponential space

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1940]
**Describe the bug**
If you naively use multi-version documentation, it quickly takes up extremely large amounts of space.  If you generate multi-version docs, then save those docs for use in future versions, each version contains all version before it, recursively.  I.e.
```
0.2.12
   0.2.11
      0.2.10
         ...
      0.2.9
         ...
      0.2.8
         ...
       ...
   0.2.10
      0.2.9
         ...
      0.2.8
         ...
       ...
   0.2.9
      0.2.8
         ...
       ...
   0.2.8
         ...
       ...

```

I suspect you could work around this by generating the "saved" docs without any past versions (and only using them for the current version), but I have yet to have time to test this.

**Comment by rnett** [comment]
A big part of the problem is that if you have an older version with the same version number as the current version, it is still included in the stored older versions.  If you update docs multiple times per version (like say with snapshots) this eats a lot of space, and there's no reason to do it since it's not selectable anyways.

**Comment by MarcinAman** [comment]
Uh, thats unfortunate. I guess a work-around for now is to write a small gradle script that would delete previous, nested versions before generating an output for the newest one

**Comment by rnett** [comment]
Yeah, that's working fine for me at the moment (although I'm doing it in CI).
