### ISSUE TITLE
Brief parsing with `i.e.`

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/dokka#1945]
Using Dokka, 1.4.32 and Kotlin 1.4.32, we have this class:

```kotlin
public interface UserTokenProvider {

  /**
   * The user token, i.e. "Bearer xyz". Throw an exception if not available.
   */
  @Throws(Exception::class)
  public suspend fun token(): String
}
```

The generated documentation get's stripped at the quotes:

```
abstract suspend fun token(): String
Content copied to clipboard
The user token, i.e.
```

The rest of the documentation is cut off. It would be great if either dokka parses this correctly or raised a warning.

**Comment by MarcinAman** [comment]
This issue is more about the way that dokka parses first line than the quotes. I think the problem here is that we assume that first sentence finishes after `i.e.` since this is the first dot followed by a white character. 

Possibly relates to https://github.com/Kotlin/dokka/issues/1939 since nbsp after dot would solve it

**Comment by msink** [comment]
Wait, in KDoc "brief", or "summary" is defined not the same way as in JavaDoc:

KDoc (https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax)
> By convention, the first paragraph of the documentation text (the block of text until the first blank line) is the summary description of the element, and the following text is the detailed description.

JavaDoc (https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)
> This sentence ends at the first period that is followed by a blank, tab, or line terminator, or at the first tag

Then real error is that either KDoc definition must be corrected, or brief in Dokka must be parsed as described for KDoc, not for JavaDoc.
