### ISSUE TITLE
Create custom tasks for plugin

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [Kotlin/dokka#1947]
**Question**
How can I create my own `dokkaMyExtension`? Like: `dokkaGfm`or `dokkaJekyll`. 

I'm trying to create a plugin for Docusaurus: https://github.com/GetStream/Dokkasaurus, but the only way I found to include this so far was to use like this: 
```
dependencies {
    dokkaPlugin(io.getstream:dokkasaurus:[version])
}
```

The problem with this approach is that is breaks my task `./gradlew javadocJar` with the following error:
```
Conflicting overrides: [Extension: org.jetbrains.dokka.javadoc.JavadocPlugin/dokkaJavadocPlugin, Extension: io.getstream.dokkasaurus.DokkasaurusPlugin/renderer]
```

I would like to create a multi module task with a custom output.

**Comment by msink** [comment]
something like
```
tasks.register<DokkaTask>("dokkaDocusaurus") {
    dependencies {
        plugins("com.github.leandroBorgesFerreira.tools:dokka-docusaurus")
    }
    dokkaSourceSets {
        configureEach {
            outputDirectory.set(rootProject.rootDir.resolve("dokka"))
            noStdlibLink.set(true)
            suppressObviousFunctions.set(true)
            suppressInheritedMembers.set(false)
        }
    }
    pluginsMapConfiguration.set(mapOf(
        "org.jetbrains.dokka.base.DokkaBase" to """{ "separateInheritedMembers": true }"""
    ))
}
```

See https://github.com/msink/kotlin-libui/commits/dokka

But I haven't actually tried it as multimodyle, maybe it's more complicated.

**Comment by leandroBorgesFerreira** [comment]
hey @msink thanks for the help!

I tried:
```
tasks.register('dokkasaurus', DokkaTask) {
    dependencies {
        plugins(Dependencies.dokkasaurus)
    }
}
```

Dokka is correctly added to my project... Am I missing something?

**Comment by leandroBorgesFerreira** [comment]
Nevermind ☝️.

Just the import was incorrect 🤦

**Comment by kamildoleglo** [comment]
You probably have to import `DokkaTask` (also doesn't `register` require a `KClass<T>`, you'd then have to use `DokkaTask::class`).

Moreover,  AFAIK `dokkaPlugin` adds this plugin to every dokka task, that's why it's breaking your `javadoc` task (and the rest of them too). There are separate methods for each task, like `dokkaHtmlPlugin` or `dokkaGfmPlugin`

**Comment by kamildoleglo** [comment]
Multi-module will be somewhat harder than single-module though. We're using templating to render multi-module content, so you'd want to apply the plugin to each `dokkaDocusaurusTemplatePlugin` (or however you want to call it) and then probably to the parent `dokkaDocusaurisMultiModulePlugin`

**Comment by leandroBorgesFerreira** [comment]
Hi @kamildoleglo. I'm not using Kotlin, then I just need to use DokkaTask for the KCkass. 

When I try to configure the `plugins` in groovy it fails with: 
```
Cannot set the value of read-only property 'plugins' for task ...
```

Do you know how would it be in Groovy instead of Kotlin?

**Comment by leandroBorgesFerreira** [comment]
I'm using groovy in my build.gradle, so the KClass is only `DokkaTask`. 

Something like:
```
tasks.register<DokkaTask>("dokkasaurus") {
    dependencies {
        plugins(Dependencies.dokkasaurus)
    }
}
```

But with groovy and couldn't translate that. 
So far I have this:
```
tasks.register('dokkasaurus', DokkaTask) {
    dependencies {
        plugins = classpath Dependencies.dokkasaurus
    }
}

```

But it looks like it doesn't work that way

**Comment by kamildoleglo** [comment]
I think it's just `DokkaTask.class` then

**Comment by leandroBorgesFerreira** [comment]
In the end I could simply use:
```
dokkaHtmlPlugin(Dependencies.dokkasaurus)
dokkaHtmlPartialPlugin(Dependencies.dokkasaurus)
```
And the Javadoc generation worked just fine =]. It substitute the HTML generation, but that's not a problem. 

 Thanks for the help @msink and @kamildoleglo!
