### ISSUE TITLE
Questions about advanced documentation sources filtering

### ISSUE THREAD

**Issue by Den-Rimus** [Kotlin/dokka#1949]
**Question**

1. Is it possible to somehow configure class name filter? E.g. I want documentation to skip `Stub*.kt` files. `perPackageOptions` does not pick that up, obviously.
2. Is it possible to configure `DokkaCollectorTask` for only a set of modules to collect documentation from (and not all that have dokka plugin enabled)?
3. Can we set filtering options (like `perPackageOption`) for `DokkaCollectorTask` and not in submodule tasks? E.g. my sources might or might not have packages like `internal`, `license`, `di` , etc that I want to skip from being documented. It would be nice to set this filter in one place than to apply it everywhere in submodules.

**Screenshots**
N/A

**Installation**
- Operating system: macOS 11.4
- Build tool: Gradle v6.7.1
- Dokka version: 1.4.32

**Additional context**
Add any other context about the problem here

**Comment by MarcinAman** [comment]
Hi, 
1) No, but you can use `suppressedFiles` to pick files to suppress. Eg. you can list all files matching your condition and add them to this list.
2) Yes, you can remove modules  by using `removeChildTask` or `removeSubprojectChildTasks`
3) No but you can configure all subprojects using `subprojects` block from gradle and then just apply basic configuration in 1 place
