### ISSUE TITLE
Mojos to be added to Maven plugin to cover the rest of output formats + outputDir parameter

### ISSUE THREAD

**Issue by shirmanov** [Kotlin/dokka#195]
Could you please add mojos to Maven plugin to allow mardown output to be specified as a goal in command line, like dokka:markdown, dokka:gfm, dokka:jekyll

Also it would be really helpful to decorate outputDir parameter as a property to allow overriding pom configuration: mvn dokka:dokka -DoutputDir=Temp

**Comment by semoro** [comment]
Why you need mojos for all of that formats? Is outputFormat configuration property is not enough?

**Comment by Kordyjan** [comment]
It is done in 1.4.0
