### ISSUE TITLE
Support number types for annotation parameter values

### ISSUE THREAD

**Issue by fsladkey** [Kotlin/dokka#1950]
## Support number types for annotation parameter values

First of all, first issue. Thanks for this great tool!

I'm looking to change the representation of number annotation parameter values and it looks like they are all treated as strings. For example, using something like the following snippet, the annotation parameter value for `bar` is `dokka.model.StringValue(value = "100.toLong()")`. 

```kotlin
@Target([AnnotationTarget.VALUE_PARAMETER])
annotation class Foo(bar: Long)

fun baz(@Foo(bar = 100) arg: Int): Int = 1
```

I'd like something like `dokka.model.NumberValue(value = 100)` or `dokka.model.LongValue(value = 100)` so that I can represent it differently than I would a string value.

I can potentially look at the format of the string, but this seems brittle. Let me know if I've missed an existing workaround or am otherwise confused.

I'm open to submitting a PR if that would be helpful, I have a branch where I experimented with this.

Thanks!

**Comment by MarcinAman** [comment]
Hi, what is the use case that you would like to cover by adding more specific types ? 
Also: are Number/Long values the only thing that you would like to see added? How about doubles?
