### ISSUE TITLE
Java project not configured unless kotlin plugin added

### ISSUE THREAD

**Issue by garfieldnate** [Kotlin/dokka#1952]
**Question**

I am unable to use the Dokka gradle plugin to generate HTML documentation for a Java project, meaning one that does *not* use the Kotin plugin. I have also tried configuring `dokkaSourceSets` manually, but I always get this output:

    > Task :lib:dokkaHtml
    Initializing plugins
    Dokka is performing: documentation for lib
    Validity check
    Creating documentation models
    Exiting Generation: Nothing to document

The dokka configuration I tried is the following:

    tasks {
        dokkaHtml {
            dokkaSourceSets {
                configureEach {
                    sourceRoots.from(
                            file("lib/src")
                    )
                }
            }
        }
    }

I'm uploading the minimum breaking example here:
[mbe_dokka.zip](https://github.com/Kotlin/dokka/files/6599239/mbe_dokka.zip)

The example is not multi-module, but rather a single Java project (which doesn't use the Kotlin plugin).

**Installation**
- Operating system: macOS 10.15.7
- Build tool: Gradle v7.0.2 (kotlin DSL)
- Dokka version: 1.4.32

**Additional context**
At my company, we use a mono-repo containing projects from many teams in a multi-project gradle build. Some projects use Kotlin, others use Java. I wanted to generate one documentation website for the mono-repo, and I saw that dokka supports projects that mix Java and Kotlin. So I added the dokka plugin, configured all projects to use the plugin, and ran `dokkaHtmlMultiModule`. To my surprise, the output only contained the Kotlin modules. I checked the documentation for `dokkaSourceSets` and found the following note: 

    By default, sourceRoots are taken from Kotlin Plugin and kotlinTasks

🤔  But that won't work on a project that doesn't use the Kotlin plugin, meaning that the dokka plugin does not work on Java projects by default.

I wasn't sure whether to file this as a question or a bug or a feature request, but of course ideally the plugin would figure out the source sets from a Java project automatically.

**Comment by kamildoleglo** [comment]
I'm actually surprised that it runs up to this point, but yeah, Dokka wasn't meant to be run on Java projects without Kotlin plugin. It will work when you add the Kotlin plugin though. You don't have to run it for compilation or anything, you just have to have it. 
If you don't want to add the plugin to the existing modules you can always create separate ones just for the sake of documentation, apply the Kotlin plugin there and point them to the correct sources

**Comment by MarcinAman** [comment]
You can do it by creating a custom module and add classpath to it:

```
tasks {
    dokkaHtml {
        dokkaSourceSets {
            create("main"){
                sourceRoots.from(
                    file("src/main")
                )
                classpath.from(compileJava.get().classpath)
            }
        }
    }
}
```
