### ISSUE TITLE
links to inherited properties

### ISSUE THREAD

**Issue by msink** [Kotlin/dokka#1954]
**Describe the bug**

Inherited properties link in class index table targets the same cell.

**Expected behaviour**

Should target separate page for property.\
Actually page is created, but linked only from class where it was defined.

Inherited functions works properly, don't know why there is difference at all.

**To Reproduce**

```
open class Parent() {
    open fun a() {}
    open fun b() {}
    val c: Boolean get() = true
}

class Children() : Parent() {
    override fun b() {}
    val d: Boolean get() = true
}
```
Create Html or Md documentation from this,
 - in Html click on `Children / properties / c` - it just higlights same cell, instead of redirecting to `Parent / c`.
 - in Md format - link is just plain broken.

**Dokka configuration**
1.4.32

**Comment by msink** [comment]
Digging a little deeper - when it comes to renderer `ContentDRILink.address` really contains `/Children/c/#/PointingToDeclaration/` instead of `/Parent/c/#/PointingToDeclaration/`

When rendering link to `Children.a` `ContentDRILink.address` is `/Parent/a/#/PointingToDeclaration/` - correctly.

**Comment by msink** [comment]
Well, if `Parent` defined in `commonMain` and `Children` in `nativeMain` - links to inherited functions are broken too,
on page `-children/index.md` link to `a` is broken in the same way as link to `c`:

```
| [a](index.md#879662226%2FFunctions%2F123127132) | [native]<br>open fun [a](index.md#879662226%2FFunctions%2F123127132)() |
| [c](index.md#100800539%2FProperties%2F123127132) | [native]<br>val [c](index.md#100800539%2FProperties%2F123127132): Boolean |
```

**Comment by MarcinAman** [comment]
Fair point. DRI for the property should be the most specific override (so basically the lowest node in the inheritance tree that overrides) or a place of declaration (if is not overriden). I think that would make the linking quite logical
