### ISSUE TITLE
I didnot get README.md in documentation.

### ISSUE THREAD

**Issue by ashleshasharma-kiwi** [Kotlin/dokka#1955]
**Describe the bug**
I was working on 0.10.1 and able to generate docs with README.md but once I upgraded to 1.4.32, it only show class documentation. I tried to customize the task but still didn't get README.md.
**Expected behaviour**
I'm working on a library so I defined the integration steps in README.md file. So my expectation after version upgrade is same to show README.doc at the root level which I was getting in version 0.10.1.
**Screenshots**
This is how I added the README.md in task.
![Capture](https://user-images.githubusercontent.com/12180943/121028397-6ad8a600-c7c5-11eb-82ef-ed5d0ae08124.PNG)

**To Reproduce**
No specific steps, I just want to add readme.md in version 1.4.32. I'm working on Kotlin-dsl

**Installation**
- Operating system: Windows
- Build tool: Gradle v5.6.4
- Dokka version: 1.4.32

**Comment by MarcinAman** [comment]
Hi, in newer dokkas (1.4.X +) we use [module and package documentation](https://kotlinlang.org/docs/kotlin-doc.html#module-and-package-documentation) which is a specially structured file to document modules and packages. there is no way to include a readme by itself but you can include it as a module documentation to be displayed on root page (assuming that you are working with single module project, but same is true for multimodule). 

Here is a working example: https://github.com/Kotlin/kotlin-examples/blob/25040fe92994ab46ebac6a6450d3ad1d3e870af1/gradle/dokka/dokka-gradle-example/build.gradle.kts#L18
