### ISSUE TITLE
Javadoc overview-tree not generated

### ISSUE THREAD

**Issue by leon-li1** [Kotlin/dokka#1958]
**Question**
I am not able to see the tree overview when I click the to see the "tree" link in the top left corner of the generated Javadocs. Am I missing anything or is this not supported yet? And is there a way to disable this link if the tree can't be generated?

**Screenshots**
![image](https://user-images.githubusercontent.com/30182031/121260337-332e3480-c87f-11eb-9249-ca4cf2bff2cc.png)
![image](https://user-images.githubusercontent.com/30182031/121261130-4ab9ed00-c880-11eb-8c89-9caf36439951.png)

**Installation**
- Operating system: Windows
- Build tool: Maven
- Dokka version: 1.4.32

**Comment by MarcinAman** [comment]
Hi, there is already an issue reported on the same subject: https://github.com/Kotlin/dokka/issues/1692#issuecomment-763192428
Please add a thumbs up there :D
