### ISSUE TITLE
ExternalDocumentationLink not working

### ISSUE THREAD

**Issue by poojaviswam** [Kotlin/dokka#1966]
**Question**

Tried to integrate Dokka for one of my **Android Projects**(Kotlin). Able to generate Html and Javadoc files.
But when tried to add external links, that linking is not working. (Links to Android and Kotlin docs are working automatically)

**Installation**
- Operating system: Windows
- Dokka version: 1.4.32

**Additional context**

- build.gradle

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'org.jetbrains.dokka'
}
```
```
dokkaJavadoc.configure {
        dokkaSourceSets {
            named("main") {
                outputFormat.set('javadoc')
                noAndroidSdkLink.set(false)
                reportUndocumented.set(false)
                skipDeprecated.set(true)
                externalDocumentationLink {
                    url.set(URL('http://reactivex.io/RxJava/3.x/javadoc/'))
                }
                externalDocumentationLink {
                    url.set(URL('https://twilio.github.io/twilio-video-android/docs/5.13.0/'))
                }
                externalDocumentationLink {
                    url.set(URL('https://bumptech.github.io/glide/javadocs/4110/'))
                }
            }
        }
    }
```

- build.gradle(top-level)

```
buildscript {
    ext.kotlin_version = "1.5.0"
    ext.dokka_version = "1.4.32"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.2.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        def nav_version = "2.3.5"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:$dokka_version"

   
    }
}
```

Tried the following also, but didn't work

```
 externalDocumentationLink {
                    url =  URL("http://reactivex.io/RxJava/3.x/javadoc/")
                }
```
```
 externalDocumentationLink {
                    url = new  URL("http://reactivex.io/RxJava/3.x/javadoc/")
                }
```
Can you please support me on this? 

Thank you.

**Comment by kamildoleglo** [comment]
Most likely your configuration is not being passed to dokka becuase it's wrong. I'd strongly recommend switching to `.kts` build files, which will give you meaningful error messages. 
What I see at the first glance is `outputFormat.set('javadoc')` which is no longer present, so it shouldn't be there at all. 
BTW `.configure` is not needed, but can stay. As for the external links, since this is Groovy, I think you want `url.set(new URL('https://twilio.github.io/twilio-video-android/docs/5.13.0/'))`

**Comment by poojaviswam** [comment]
Thank you @kamildoleglo for the quick response.

As per the doc https://kotlin.github.io/dokka/1.4.32/user_guide/gradle/usage/#android , initially, I have added only 
```
dokkaHtml.configure {
    dokkaSourceSets {
        named("main") {
            noAndroidSdkLink.set(false)
        }   
    }
}
```
when running` gradlew dokkaHtml` returned the following exception

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:extractDeepLinksDebug'.
> > Unable to make field private final java.lang.String java.io.File.path accessible: mo
> dule java.base does not "opens java.io" to unnamed module @6081aba8


After few trials , I made the code working by giving `outputFormat.set('javaHtml') ` or giving   `outputDirectory.set(buildDir.resolve("dokka"))` (please refer below)

I am trying the code in a basic Android application, there are no many complications. 

The final code working for me is attached below, **but the external link not working again**

```
dokkaHtml.configure {
        dokkaSourceSets {
            named("main") {
                outputDirectory.set(buildDir.resolve("dokka"))
                noAndroidSdkLink.set(false)
                reportUndocumented.set(false)
                skipDeprecated.set(true)
                externalDocumentationLink {
                    url.set(new URL("http://reactivex.io/RxJava/3.x/javadoc/"))
                }
            }
        }
    }
```

**Comment by kamildoleglo** [comment]
> Unable to make field private final java.lang.String java.io.File.path accessible: mo
dule java.base does not "opens java.io" to unnamed module @6081aba8

I think this is a bug in the Kotlin compiler, because I saw something similar some time ago. Which JDK version do you have? 

Also, could you please share your project with me or create a minimal reproducible example?

**Comment by poojaviswam** [comment]
[SampleKdocApllication.zip](https://github.com/Kotlin/dokka/files/6656218/SampleKdocApllication.zip)
This is a very basic application, I have integrated Dokka in one of my live projects.  and also please post how to avoid general class and variables undocumented getting displayed.

**Comment by kamildoleglo** [comment]
[SampleKdocApllication.zip](https://github.com/Kotlin/dokka/files/6658759/SampleKdocApllication.zip)
Fixed that for you. Also I'd recommend using the HTML format instead of the javadoc one. The javadoc format is only useful when you have a shared codebase with Java and you want your app to be used from Java code. 

> how to avoid general class and variables undocumented getting displayed

Not sure what you mean by that, by mostly you want everything that you don't want to be documented to be protected/private , since public things are part of the public API that is being documented

**Comment by poojaviswam** [comment]
Thank you @kamildoleglo for the great support.

**Comment by kamildoleglo** [comment]
No problem, you can also join the Kotlin Slack, there is a dokka channel with some helpful people ☺️  https://surveys.jetbrains.com/s3/kotlin-slack-sign-up
