### ISSUE TITLE
Support HTML entities in Markdown renderer

### ISSUE THREAD

**Issue by CommanderTvis** [Kotlin/dokka#1972]
**Is your feature request related to a problem? Please describe**
HTML entities supported by many Markdown engines aren't rendered by Dokka.

**Describe the solution you'd like**
Support HTML entities in Markdown renderer.

![image](https://user-images.githubusercontent.com/38042667/122673642-931bc800-d1fb-11eb-92a3-222c0620ad91.png)

**Comment by MarcinAman** [comment]
After #2005 this should be resolved:
![image](https://user-images.githubusercontent.com/15652452/124943732-094a6800-e00d-11eb-814d-41667d292572.png)

Or in GFM:
![image](https://user-images.githubusercontent.com/15652452/124943801-16ffed80-e00d-11eb-9430-394e8a7f9e4e.png)
