### ISSUE TITLE
How to use dokka to append javadoc.jar to maven publication of library

### ISSUE THREAD

**Issue by Den-Rimus** [Kotlin/dokka#1979]
**Question**
We want our SDK users to be able to see quick documentation (aka 'F1' key with caret on class/method in Jetbrains IDE) in editor.
Afaik, for that we need to collect kdoc and package it as additional artifact.
So far looks like this does not work: javadoc.jar present, it is linked as a documentation source in IDE but documentation is not available in editor.

Is there some error in out setup?

**Screenshots**
N/A

**Installation**
- Operating system: macOS 11.4
- Build tool: Gradle v7.0.2
- Dokka version: 1.4.32

**Additional context**
- Sample project available [here](https://github.com/Den-Rimus/DokkaJavadocJar)
- You need to execute `chmod +x publish_mylibrary1.sh ; ./publish_mylibrary1.sh` in project root
- Uncomment code marked with `// TODO: uncomment me!` in app module (in `Main.kt`, `JavaMain.java` and `build.gradle.kts` files)
- Make gradle sync.

Somehow partial doc is available - but only from Java classes. Please see more in app module code mentioned above.

**Comment by kamildoleglo** [comment]
Closing as duplicate: https://github.com/Kotlin/dokka/issues/215
