### ISSUE TITLE
How to output docs without module named folder?

### ISSUE THREAD

**Issue by arslancharyev31** [Kotlin/dokka#198]
Good day. I'm trying to generate docs in project level `\docs` folder. However, it generates an additional folder with module name, so the final path looks like `\docs\<module-name>\`. Is there a way to generate docs directly to `docs` folder?

**Comment by semoro** [comment]
Now - no way, you can use copy task, to put it to `docs`

**Comment by fuzzyweapon** [comment]
I did this by not passing in a module name to the fatjar and setting the output folder to `\docs` the other day.  (wasn't what I was looking for, but I was trying to fool around with it to get it to output `\docs\<module-name>` instead of `\docs\-<module-name>`)

**Comment by semoro** [comment]
If you module-name start with an upper-case letter it will be replaced with `-${it.toLowerCase()}`, it is general path policy for Dokka, as on some OS-es paths are case-insensitive
