### ISSUE TITLE
Task dokkaJavadoc in rel. 1.4.32 exhausted 8096MB memory

### ISSUE THREAD

**Issue by taotao100** [Kotlin/dokka#1981]
I used the dokkaJavadoc Task of rel. 1.4.32 to generate javadocs in our projects, it is very superise even I specified the gradle property as below, the task can exhausted the heap in Jenkins JVM.

org.gradle.jvmargs=-Xmx8096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

I tried also other 1.4.X rel., but I still had no success to get the task running in 8GB configuration.

I have to downgrade to rel 0.10.1, the elder version works well under even smaller memory footprint than 3G.

**Comment by MarcinAman** [comment]
Hi, we already have an issue about memory consumption: https://github.com/Kotlin/dokka/issues/1405
