### ISSUE TITLE
Unable to hide unhertied functions from parent class in child class in multimodule android application

### ISSUE THREAD

**Issue by TheReprator** [Kotlin/dokka#1982]
HI Team,

First thanks for this framework
I am trying to hide the parent class methods, which is not  being used in child class,  It's showing me as per screenshot.
<img width="884" alt="dokka" src="https://user-images.githubusercontent.com/10286587/123096402-b1c4cd80-d44c-11eb-881f-dfadcbd4c041.png">

but it should only show setContentview but it's showing all parent class methods.

I had tried my best way to hide it in multimodule application but still it fails

Repository:
  https://github.com/TheReprator/Wipro/tree/dokaa

Implementation: 
  https://github.com/TheReprator/Wipro/blob/dokaa/build.gradle.kts

Looking forward for a solution.

Regards,
Vikram Singh

**Comment by MarcinAman** [comment]
Hi, you are not configuring correct dokka task. `DokkaHtml` is a task for the single module projects. Please read [our documentation ](https://kotlin.github.io/dokka/1.4.32/user_guide/gradle/usage/#multi-module-projects
) or follow [the example](https://github.com/Kotlin/kotlin-examples/blob/25040fe92994ab46ebac6a6450d3ad1d3e870af1/gradle/dokka/dokka-multimodule-example/parentProject/childProjectA/build.gradle.kts#L12).


In your case the configuration could look like this:
```
subprojects {
    plugins.apply("org.jetbrains.dokka")

    tasks.named<org.jetbrains.dokka.gradle.DokkaTaskPartial>("dokkaHtmlPartial") {
        dokkaSourceSets.configureEach {
            noAndroidSdkLink.set(true)
            suppressInheritedMembers.set(true)
        }
    }
}
```
