### ISSUE TITLE
how to create a separate tabs for  inherited and private functions

### ISSUE THREAD

**Issue by TheReprator** [Kotlin/dokka#1985]
Hi Team,

I want to know how to create a separate tabs for  inherited and private functions.

Repo: https://github.com/TheReprator/Wipro/blob/master/build.gradle.kts

Regards,
Vikram Singh

**Comment by msink** [comment]
```diff
     tasks.named<org.jetbrains.dokka.gradle.DokkaTaskPartial>("dokkaHtmlPartial") {
         dokkaSourceSets.configureEach {
             //noAndroidSdkLink.set(true)
             suppressInheritedMembers.set(true)
         }
+        pluginsMapConfiguration.set(mapOf(
+            "org.jetbrains.dokka.base.DokkaBase" to """{ "separateInheritedMembers": true }"""
+        ))
     }
```

**Comment by TheReprator** [comment]
thanks, hence closing the issue.

**Comment by TheReprator** [comment]
Well, it didn't worked,

End result is as follows,

<img width="927" alt="noAndroidSdkLink" src="https://user-images.githubusercontent.com/10286587/123251820-3ffe8980-d509-11eb-82d4-f4b87602006d.png">

Regards,
Vikram Singh

**Comment by MarcinAman** [comment]
It doesn't work because you suppressed them above
