### ISSUE TITLE
Using dokkaHtml on externa project

### ISSUE THREAD

**Issue by dfroze** [Kotlin/dokka#1986]
**Question**
How can I configure a gradle project to generate document for an external main project? I need to keep the main android project clean and completely separated, without including other classpaths/plugins/dependencies. That is why a separated project for gradle scripts was created.

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.5.0
- Dokka version: 1.4.32

**Additional context**
So far, I've gotten to:
documentation.gradle:
```
tasks.dokkaHtml.configure {
    outputDirectory.set(new File(buildDir.absolutePath, "dokka"))
    dokkaSourceSets {
        register("customName") {
            displayName = "MainProject"
            sourceRoots.from(new File(absolute_path_to_main_project))
            jdkVersion.set(8)
        }
    }
}
```
with build.gradle:
```
android {
    buildToolsVersion BuildConfig.buildTools
    compileSdkVersion BuildConfig.compileSdk

    defaultConfig {
        minSdkVersion BuildConfig.minSdk
        targetSdkVersion BuildConfig.targetSdk
    }
}
```
But the above does not generate the documentation. It creates the directory, but empty. 
I've tried separately with dokka CLI (and it worked), but would like to use gradle in order to automatically get all it's dependencies and anything else that requires automatically (and also add links to android SDK classes)

Any ideas what I am missing?

**Comment by kamildoleglo** [comment]
If you create a new project entirely please consider switching to `.kts` build files, this will help you and us debug it. What I see from the first look is the assignment operator for the `displayName` which may fail the entire config, please change that to `set()`. If that doesn't help please try manually unsuppressing the sourceset, like so: 

```
 register("customName") {
            displayName .set("MainProject")
            sourceRoots.from(new File(absolute_path_to_main_project))
            suppress.set(false)
  }
```,
although don't think it will make a difference

**Comment by dfroze** [comment]
Hi @kamildoleglo , 

The ` suppress.set(false)  ` didn't worked (yes, I've even updated `displayName` to use `set`). I've even updated to be similar to the example below, **but it's almost as if there is no sourceRoot set, empty of content.**

Tried using https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka/dokka-gradle-example instead (to test and see if at least it works) and managed to generate the documentation (yeeee!)

The gradle project already contains other scripts and will require quite some work to migrate it to `.kts` (especially cause I'm new to it).  Until then, I would still like to make this work.

**Comment by dfroze** [comment]
In the end, I've managed to convert the base of the project to `kts`  and have mixed modules instead (couldn't update the other ones)
