### ISSUE TITLE
Docs on method on class page oddly cut off.

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1996]
**Describe the bug**
The docs of a method are cut off oddly when viewed from the class page.  It's not length related, as there are other methods with longer docs that are shown fine.

**Expected behaviour**
Method docs aren't artificially cut off on the class page.

**Screenshots**
Class page:
![image](https://user-images.githubusercontent.com/32281897/124345090-741e1e00-db8b-11eb-80cd-5eb4b1d3b533.png)

Method detail:
![image](https://user-images.githubusercontent.com/32281897/124345095-7da78600-db8b-11eb-86c2-9569cf52f13d.png)

**To Reproduce**
https://github.com/rnett/kotlin-future-testing
See https://rnett.github.io/kotlin-future-testing/snapshot/-kotlin%20-future%20-testing/com.rnett.future.testing/-kotlin-future-testing-extension/index.html

**Dokka configuration**
https://github.com/rnett/kotlin-future-testing/blob/main/build.gradle.kts#L104

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.0.2
- Dokka version: 1.4.32

**Comment by msink** [comment]
Currently the new version of Dokka always uses the JavaDoc summary definition, instead of KDoc, see https://github.com/Kotlin/dokka/issues/1945#issuecomment-864658502
On Kotlin sourses KDoc definition must me used (or KDoc definition changed, which is unlikely)

**Comment by MarcinAman** [comment]
This is because there is a dot at the end of this phrase. We already have issue on that: https://github.com/Kotlin/dokka/issues/1945, so please give it a thumbs up 👍
