### ISSUE TITLE
Dokka inherits empty documentation from super methods with default implementation

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/dokka#1997]
**Describe the bug**

In `kotlinx.coroutines` we have class `CoroutineName` that implements [`CoroutineContext.Element`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/-coroutine-context/-element/).

In its `Functions` section, it lists all supertype methods without documentation: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-name/index.html

**Expected behaviour**

Non-overridden methods from super-types are not listed (preferably) or listed with inherited documentation.
In the `CoroutineName` example, only `toString` should be present.

**To Reproduce**
`./gradlew dokkaHtmlMultiModule`

**Dokka configuration**

`kotlinx.coroutines` project, HTML multimodule setup: https://github.com/Kotlin/kotlinx.coroutines/blob/c5b168063bfaf3bce995b49dabd69f38464887b6/gradle/dokka.gradle.kts 

Branch `new-dokka-and-knit`, these changes are not yet in our `master` and `develop` branches.

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.8.0
- Dokka version: 1.5.0-dev-106

**Comment by qwwdfsad** [comment]
The very same issue is relevant for enums: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-debug/kotlinx.coroutines.debug/-state/-r-u-n-n-i-n-g/index.html

**Comment by qwwdfsad** [comment]
No longer reproducible on live site because I've rebuilt it with `suppressInheritedMembers `

**Comment by kamildoleglo** [comment]
Proposed https://github.com/Kotlin/dokka/issues/2034
