### ISSUE TITLE
Feature request: suppress componentN() methods from JavaDoc.

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/dokka#201]
They're there for Kotlin users and are auto-generated, so will never have documentation. They clutter up the javadocs regardless.

**Comment by mikehearn** [comment]
My mistake - they get docs when `@property` is used. However they're still useless to Java devs who have no syntactical support for them and their code would thus always be clearer using the real property names. It'd still be good to suppress them in JavaDoc output (or have the compiler mark them synthetic).

**Comment by madorb** [comment]
Agreed, this was very unexpected when i packed as javadoc

**Comment by kamildoleglo** [comment]
Probably fixed by https://github.com/Kotlin/dokka/pull/1758
