### ISSUE TITLE
@sample Unresolved *.java

### ISSUE THREAD

**Issue by d-txy** [Kotlin/dokka#2032]
```kotlin
// Demo.kt
// Fun.java

interface Demo {
    /**
     * @sample com.*.java.Fun.getUserInfo
     */
    fun getUserInfo(): String
}
```

@sample show // Unresolved

**Comment by IgnatBeresnev** [comment]
It's not very clear what the problem/proposal is exactly, but the `@sample` tag requires a fully qualified name. Please see https://github.com/Kotlin/dokka/issues/2656#issuecomment-1239517614

I'll close the issue for now as a duplicate/won't fix, but please let us know if you have any details to share or if I understood you wrong
