### ISSUE TITLE
Javadoc generated by Dokka does not show up in quick documentation lookup in Intellij IDEA

### ISSUE THREAD

**Issue by vbieleny** [Kotlin/dokka#2033]
**Describe the bug**
When a Javadoc generated by Dokka is imported in IntelliJ IDEA or Android Studio, it does not show up in quick documentation lookup for Kotlin files. It does show up for Java files, but only for methods and not for classes.

**Expected behaviour**
When I do quick documentation lookup with Ctrl + Q for some part of a code, I should be able to see Javadoc associated with it.

**Screenshots**
This is how the quick documentation lookup shows up
![image](https://user-images.githubusercontent.com/16362204/126522393-f981c843-07c0-4856-ae18-9ceead872406.png)

This is how it should show up
![image](https://user-images.githubusercontent.com/16362204/126522442-f83fc27e-d9ab-4fe4-9527-259c462fadb4.png)

Intellj IDEA does have Javadoc JAR associated with the library
![image](https://user-images.githubusercontent.com/16362204/126522622-dbf37768-2f5a-4a9d-aee7-5ef0cbd92e9d.png)

**To Reproduce**
Example project: https://github.com/vbieleny/dokka-javadoc-test

1. Open the project in Intellij IDEA
2. Execute task `publishToMavenLocal` in `library` module
3. Open `App.kt` in `app` module and check the quick documentation lookup by pressing Ctrl + Q for the relevant code

**Dokka configuration**

```Kotlin
dokkaJavadoc {
    dokkaSourceSets {
        named("main") {
            sourceRoots.from(file("src/main/java"))
        }
    }
}
```

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.1.1
- Dokka version: 1.5.0

**Additional context**
This happens in IntelliJ IDEA as well as in Android Studio, while generating Javadoc by using standard Javadoc tool works fine and documentation shows up in quick documentation lookup (only for Java files of course).

**Are you willing to provide a PR?**
If it's a bug, then I might, but I would need help with it.

**Comment by IgnatBeresnev** [comment]
Some investigation into the current behaviour can be found in https://github.com/Kotlin/dokka/issues/2297#issuecomment-1006486425

**Comment by IgnatBeresnev** [comment]
Closing this in favour of an older issue with more likes and information: https://github.com/Kotlin/dokka/issues/215
