### ISSUE TITLE
Consider supporting split packages

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#2037]
Dokka right now doesn't handle split packages by design. At some point in the future this behaviour should probably change since in some edge cases it leads to unresolved links.

Example of such behaviour is present here, in `ApolloResponse`: https://apollographql.github.io/apollo-android/kdoc/apollo-runtime/com.apollographql.apollo3/-apollo-client/query.html

**Comment by vmishenev** [comment]
I closed it in favor of #3425.
