### ISSUE TITLE
JavaDoc output doesn't emit nested generics properly

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/dokka#204]
For Kotlin code like this:

`data class Foo(override val amount: Bar<Baz<Thing>>)`

the c'tor is rendered in the JavaDoc as:

`Foo(a.b.c.Bar<a.b.c.Baz> amount)`

The fact that Baz is itself generic got lost in translation.

**Comment by GaborPeto** [comment]
Has there been any progress regarding this?

**Comment by kamilok1965** [comment]
Not yet I'm afraid, but I hope we'll fix this soon while writing a new version of the javadoc format

**Comment by Kordyjan** [comment]
Javadoc has been completely rewritten. This issue should be fixed from 1.4.0-rc onwards.
