### ISSUE TITLE
DefaultPsiToDocumentableTranslator translates PsiArrays to unexpected type

### ISSUE THREAD

**Issue by fsladkey** [Kotlin/dokka#2041]
### `DefaultPsiToDocumentableTranslator` translates `PsiArrays` to unexpected type

I noticed that the `DefaultPsiToDocumentableTranslator` translates most types as I expect, but for `PsiArray`s, the resulting DRI will always be `kotlin.Array` regardless of the source language. For example, Java source `int[] numbers` will be assigned a type of `kotlin.Array`. I'm not 100% sure what type would be expected here, but it would be great to distinguish it from actual Kotlin arrays.

Here's a test case I wrote in `JavaTest.kt` which illustrates the unexpected type.

```kotlin
@Test
fun javaArrayType() {
    inlineModelTest(
        """
        |public class Foo {
        |  public void bar(int[] baz) {}
        |}
        """, configuration = configuration
    ) {
        with((this / "java" / "Foo").cast<DClass>()) {
            with((this / "bar").cast<DFunction>()) {
                val paramType = this.parameters.first().type as GenericTypeConstructor
                assertNotEquals("kotlin", paramType.dri.packageName)
            }
        }
    }
}
```

If it's useful, my particular use case is to identify arrays of Java primitives and convert them to Kotlin `IntArray`s (or equivalent for other types) when displaying Kotlin docs for Java sources. Let me know if I've misinterpreted anything or if you have any suggestions. Thanks!

[Relevant source](https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt#L463)

**Installation**
- Operating system: macOS/Linux
- Build tool: Gradle
- Dokka version: 1.5.0

**Comment by MarcinAman** [comment]
I think this is partially correct because there are 2 cases present:
- type is `byte[]`, `char[]`, `short[]`, `int[]`, `long[]`, `boolean[]` they are converted in compiler into their equivalents from `Arrays.kt`
- other types are compiled into `Array<out T>`

So our approach is only partially correct. We should add those 'special' cases from point 1
