### ISSUE TITLE
First @param in KDoc block from class constructor ends up in generated HTML class constructor documentation

### ISSUE THREAD

**Issue by AristotelispetrosBobas-TomTom** [Kotlin/dokka#2044]
**Describe the bug**

The first parameter of a class constructor ends up in the general block of documentation about the class constructor.

**Expected behavior**

The constructor documentation should not show this parameter/piece of text.

**Screenshots**

![screenshot](https://i.ibb.co/82zKPNw/Screenshot-from-2021-07-27-16-53-37.png)

**To Reproduce**

```
/**
* Dummy text.
*
* @param exampleParameter dummy parameter.
*/
class Example(private val exampleParameter: Int) {
}
```

**Installation**
Operating system: Linux
Build tool: Gradle v7.0
Dokka version: 1.4.32

**Comment by msink** [comment]
Already reported in #1930
