### ISSUE TITLE
Cannot get rid of <ERROR CLASS>

### ISSUE THREAD

**Issue by dfroze** [Kotlin/dokka#2054]
HI,
I am trying to separate the gradle scripts from the android project. So far so good. The only problem left is that in the documentation generated, I am getting <ERROR CLASS> for android SDK elements (such as `Context`).

I've tried different approaches, but all failed so far.
The structure:
 - path A - there is the project containing kts scripts
 - path B - android project

In path A, there is:
`<path A>/build.gradle.kts`:
```
buildscript {
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:4.1.3")
        classpath("org.jfrog.buildinfo:build-info-extractor-gradle:4.24.4")
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.5.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.30")

    }
}
```
`<path A>/_documentation_/build.gradle.kts`:
```
plugins {
    id("org.jetbrains.dokka")
    id("com.android.library")
    id("kotlin-android")
    id("kotlin-kapt")
    kotlin("android")
}

tasks.withType<org.jetbrains.dokka.gradle.DokkaTask>().configureEach {
    moduleName.set("Android Project")
    dokkaSourceSets {
        register("customName") {
            displayName.set("Project")
            sourceRoots.from(File("<path B>").absolutePath)
            jdkVersion.set(8)
            skipEmptyPackages.set(true)
            includeNonPublic.set(false)
            suppress.set(false)
            noAndroidSdkLink.set(false)
        }
    }
}

android {
    defaultConfig {
        minSdkVersion(21)
        setCompileSdkVersion(30)
    }
}
```

`<path A>/_documentation_/src/main/AndroidManifest.xml`:
```
<manifest package="com.project"/>

```
The manifest file and android SDK version configuration was added because I've noticed the following code in dokka:
```
        .run {
            if (noAndroidSdkLink.getSafe() || !project.isAndroidProject()) this
            else this +
                    ExternalDocumentationLink.androidSdk() +
                    ExternalDocumentationLink.androidX()
        }
```
And I thought this might be the cause for getting `<ERROR CLASS>`, but it seemed it was not enough.

Any ideas why it does not get the external documentation for android SDK? Am I missing something?

Thank you

**Comment by MarcinAman** [comment]
Do you get ERROR CLASS for all elements referenced from android sdk or only some? Is it possible to get some sample of those / reproducable project? I suspect that this issue is based on the fact that dokka for whatever reason doesn't get correct classpath from gradle and passes this incorrect data to kotlin analysis that spills errors.

**Comment by dfroze** [comment]
Yes, for all elements from android sdk. I've created a basic project (with Activity) in Android Studio and managed to generate the same behavior (error class) for android sdk elements. 

Shared an example here: https://drive.google.com/file/d/1RitVNNkx_qvM_-dycNBiXbyjsl3-CWb-/view?usp=sharing
It has 2 projects:
- gradle-scripts  - from inside, run ` ./gradlew _documentation:dokkaHtml` 
- MyApplication - in MainActivity there 2 methods `android_param()` and `java_param()`

In the documentation generated you should see the \<ERROR CLASS\> for those class methods .

**Comment by MarcinAman** [comment]
Are those projects somehow connected?
I think that those errors are a result of empty classpath therefore dokka doesn't know anything about classes that are used as a dependency of documented project. 
In this repository structure it is not that easy to pass classpath, the only solution i can think of is having a task that prints classpath in project and parsing output in documentation project but this smells

**Comment by dfroze** [comment]
Hi @MarcinAman, thank you for the answer. Those two project are connected only though that path through that task from `gradle-scripts`. The important part is to have the heavy gradle scripts separated from the main project to avoid extra dependencies as much as possible.

Why does it get empty classpath? Do I need to add a classpath to gradle-scripts?

Can you please details a bit `having a task that prints classpath in project and parsing output in documentation project `? The problem I am faced with is that it should not appear "ERROR CLASS" in the documentation. Thus, I need to either remove/replace it or fix it.

**Comment by MarcinAman** [comment]
Actually there is an easier solution if we care only about links to android:
```kotlin
repositories {
    mavenCentral()
    google()
}


tasks.withType<org.jetbrains.dokka.gradle.DokkaTask>().configureEach {
    moduleName.set("Android project v1")
    dokkaSourceSets {
        configureEach {
            suppress.set(true)
        }
        val main by getting {
            displayName.set("Android project")
            sourceRoots.from(File("${rootDir.absolutePath}/../MyApplication/").absolutePath)
            skipEmptyPackages.set(true)
            includeNonPublic.set(false)
            suppress.set(false)
            noAndroidSdkLink.set(false)
        }
    }
}
```

**Comment by dfroze** [comment]
Hi @MarcinAman , that works perfect. Thank you for the help and fast reply.
