### ISSUE TITLE
Generated package-level javadoc truncates all documentation after the first sentence.

### ISSUE THREAD

**Issue by whbboyd** [Kotlin/dokka#2055]
**Describe the bug**
Generated javadoc includes only the first sentence of package-level documentation on the package page. All package-level documentation after the first sentence is dropped, and does not appear anywhere in the generated javadoc.

**Expected behaviour**
The package page for a given package should include all the documentation written for that package.

**Screenshots**
From the reproduction example project, javadoc has only the first sentence of documentation:
![screenshot ](https://i.imgur.com/hjK0noz.png)
Compare the generated kotlindoc, which contains the entire package documentation:
![screenshot](https://i.imgur.com/NRRzclf.png)

**To Reproduce**
Reproduction example project is at https://github.com/whbboyd/dokka-javadoc-bug

**Installation**
- Operating system: Linux
- Build tool: Maven 3.6.0/OpenJDK 11.0.12
- Dokka version: 1.5.0 (also reproduced with 1.4.32)

**Are you willing to provide a PR?**
If I can be pointed to likely culprit code, I can take a crack at writing a PR.

**Comment by cptartur** [comment]
Any updates on this? Seems like this issue is still present as of Dokka 1.7.10, and the only solution seems to be not to use full stops at all in docs which is not ideal.

**Comment by IgnatBeresnev** [comment]
The fix will be shipped in the next release
