### ISSUE TITLE
dokkaHTML integration

### ISSUE THREAD

**Issue by bashbug** [Kotlin/dokka#2056]
**Question**
How do you integrate the dokkaHTML generated KDoc files / API reference into a full documentation?

**What I would like to achieve**
A full documentation contains for example:
- Get started
- Changelog
- API reference

**Problem/Limitation**
Additional Markdown files can only be added on module/package level (see https://kotlinlang.org/docs/kotlin-doc.html#module-and-package-documentation and https://github.com/Kotlin/dokka/issues/1955#issuecomment-856743179)

Is there some way to achieve this in a non hacky way?

**Comment by MarcinAman** [comment]
Yes, you need to write yourself a dokka plugin, that would take whatever content you would like to add and insert it into our [pages model](https://kotlin.github.io/dokka/1.5.0/developer_guide/data_model/#page-model). This should be a fairly simple plugin where you should write a page transformer. 

Here is an example of how such transformers look like: https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt
And a template for dokka plugin: https://github.com/Kotlin/dokka-plugin-template
I think in this case it would be sufficient to just create a `ContentPage` with changelog that is copied from the file.

**Comment by bashbug** [comment]
Thanks @martinbonnin for you response!

I followed your suggestions:

> you need to write yourself a dokka plugin.

```
class CustomPagesPlugin: DokkaPlugin() {
	val CustomPagesTransformer by extending {
		CoreExtensions.pageTransformer with CustomPagesTransformer()
	}
}
```

> where you should write a page transformer.
> Here is an example of how such transformers look like: https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/transformers/pages/sourcelinks/SourceLinksTransformer.kt

However the interface of CoreExtensions.pageTransformer has no DokkaContext as parameter.

```
class CustomPagesTransformer(val context: DokkaContext) : PageTransformer
```

Unfortunately for me it is not fairly simple to get this working. Is there any existing plugin I could orient myself?

**Comment by MarcinAman** [comment]
Instead of `with` use `providing` like: 

```
val CustomPagesTransformer by extending {
    CoreExtensions.pageTransformer providing ::CustomPagesTransformer
}
```

As there are not that many community-made dokka plugins right now i'd advice looking at our own ones in plugins directory, like:
- https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/DokkaBase.kt
- https://github.com/Kotlin/dokka/blob/master/plugins/gfm/src/main/kotlin/org/jetbrains/dokka/gfm/GfmPlugin.kt

You probably won't find exactly the same thing you are doing, but those can come handy when coming up with your own solution.
