### ISSUE TITLE
includeNonPublic does not work (version 0.9.15)

### ISSUE THREAD

**Issue by darkstone** [Kotlin/dokka#206]
I've tried using this option, and does not work. Is there a version of the dokka documenation for this plugin which is public, and is *not* misleading?

Here is what I had in my build: 

```
dokka {
    outputDirectory = "$buildDir/apidocs"
    outputFormat = 'html'
    includes = ['Module.md']
    jdkVersion = 8

    includeNonPublic = false
}
```

**Comment by semoro** [comment]
Documentation for 0.9.15 is here 
https://github.com/Kotlin/dokka/tree/0.9.15

This option will be added in 0.9.16.
But, anyway, it set to `false` by default in 0.9.15
