### ISSUE TITLE
multiplatform example wrong, includes does not exist

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#2062]
**Describe the bug**
https://kotlin.github.io/dokka/1.5.0/user_guide/gradle/usage/#multiplatform

`includes.from` does not exist (does not compile)

**Expected behaviour**
examples work

**Screenshots**
![image](https://user-images.githubusercontent.com/5557885/128727214-6e116db3-50dc-405b-b8ca-90427aed7f36.png)

**To Reproduce**
copy example

**Installation**
- Build tool: Gradle v7.1.1
- Dokka version: 1.5.0

**Are you willing to provide a PR?**
Yes just need a pointer where to look for the corresponding documentation. I struggle to find things on https://kotlin.github.io/dokka/1.5.0/user_guide/gradle/usage/#multiplatform

**Comment by MarcinAman** [comment]
fixed in https://github.com/Kotlin/dokka/commit/3df13a1bb6b5bab0f7d99c7b5e5fc2d8a64c47e9
