### ISSUE TITLE
How to solve <ERROR CLASS> in Kotlin/JS

### ISSUE THREAD

**Issue by floribe2000** [Kotlin/dokka#2070]
**Question**
I'm working on a multi-module/multiplatform gradle project. There is one "common" module using Kotlin/Multiplatform, mutliple Kotlin/JVM projects and two Kotlin/JS projects.
Everything is working fine for the Multiplatform and JVM projects. However, in the JS projects I always get the mentioned <ERROR CLASS> issues when referencing anything that is part of a dependency, it doesn't matter if it is from another project or from an external library like kotlin-react.

I am using the gradle version catalog feature but it does not seem like that's the problem, replacing the version catalog with the regular dependency notation doesn't change anything.

This is the dokka config in gradle:
```Kotlin
tasks {
    dokkaHtmlPartial.configure {
        dependsOn(assemble)
        dokkaSourceSets.configureEach {
            includeNonPublic.set(true)
            reportUndocumented.set(true)
        }
    }
}
```

This is an example of a function where I see <ERROR CLASS> in the generated html (extension function for a react-router type):
`fun RouteResultProps<*>.params() = URLSearchParams(location.search)`

And this is the result in the output of the `dokkaHtmlMultiModule` task:
![grafik](https://user-images.githubusercontent.com/43866194/129374717-8199dbb5-181a-45c2-b66c-461085f3a13b.png)

I saw a similar issue with Android in multiple issues but it seems like the cause is a different one. At least I was unable to resolve it by using solutions that worked in these cases.

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.1.1
- Dokka version: 1.5.0

**Comment by vmishenev** [comment]
How did you set up dependencies for the JS module? 
I can't reproduce your problem in multi-module projects.
![image](https://user-images.githubusercontent.com/9636937/129620567-b2def72d-29d3-4baa-bf11-457374da8b6b.png)

**Comment by floribe2000** [comment]
This is the setup in one of the two sub-projects that are not working.
The second sub-project is basically the same, except for a few dependencies.

```Kotlin
plugins {
    kotlin("js")
    kotlin("plugin.serialization")
    idea
}

kotlin {
    js(IR) {
        browser()
        binaries.executable()
        compilations.all {
            compileKotlinTask.kotlinOptions.freeCompilerArgs += "-Xopt-in=kotlin.RequiresOptIn"
        }
    }
}

dependencies {
    implementation(projects.common)
    implementation(projects.frontendWrappers)

    //React, React DOM, React router + Wrappers
    implementation(libs.bundles.frontend.basics)
    implementation(libs.bundles.frontend.http)

    // npm dependencies
    val reactVersion = libs.versions.react.get()
    implementation(npm("react", reactVersion))
    implementation(npm("react-dom", reactVersion))
    implementation(npm("react-is", reactVersion))

    //Coroutines
    implementation(libs.kotlin.coroutines)

    // Serialization
    implementation(libs.kotlin.serialization)
}

tasks {
    dokkaHtmlPartial.configure {
        dependsOn(assemble)
        dokkaSourceSets.configureEach {
            includeNonPublic.set(true)
            reportUndocumented.set(true)
            suppressInheritedMembers.set(true)
            includes.from("packages.md")
            sourceLink {
                localDirectory.set(file("src/main/kotlin"))
                remoteUrl.set(URL("https://github.com/floribe2000/Projektarbeit-IN/tree/master/frontend/src/main/kotlin"))
                remoteLineSuffix.set("#L")
            }
        }
    }
}
```

I am using the gradle version catalog feature, that's the config for the module in question. I removed the config for the jvm projects since they are working fine:
```
[libraries]
# Kotlin basics
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-minor" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-major" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Kotlin JS dependencies
wrapper-react-core = { module = "org.jetbrains.kotlin-wrappers:kotlin-react", version.ref = "kotlinReact" }
wrapper-react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom", version.ref = "kotlinReact" }
wrapper-react-router = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom", version = "5.2.0-pre.204-kotlin-1.5.0" }
wrapper-kotlin-styled = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled", version = "5.3.0-pre.204-kotlin-1.5.0" }
ktor-client-js = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }

[bundles]
frontend-basics = ["wrapper-react-core", "wrapper-react-dom", "wrapper-react-router", "wrapper-kotlin-styled"]
frontend-http = ["ktor-client-js", "ktor-client-serialization", "kotlin-coroutines"]
```

When printing the classpath used by dokka everything looks fine, all libs are listed there. May the IR compiler be the cause of these issues?
