### ISSUE TITLE
Javadoc links are mangled

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/dokka#2072]
**Describe the bug**
When I use Gradle's javadoc location, all the links are hardcoded with `/index.html` in the path, breaking the links ultimately. If I remote that from the URL supplied to the external docs link, it fails to index them (so it appears index.html is needed there).

**Expected behaviour**
I would expect Dokka to strip this suffix or provide an API to transform URLs

**Screenshots**
<img width="745" alt="image" src="https://user-images.githubusercontent.com/1361086/129464027-7eb98908-3143-479a-aa96-cbd9e18f5731.png">

**To Reproduce**
In the above screenshot clicking the `@CacheableTask` link takes you to `https://docs.gradle.org/7.1.1/javadoc/index.html/org/gradle/api/tasks/CacheableTask.html` but it should actually be `https://docs.gradle.org/7.1.1/javadoc/org/gradle/api/tasks/CacheableTask.html`

Run `./deploy_website` on this project and see the dokka output in the deployed site: https://github.com/slackhq/keeper. You can also see it on the project site here: https://slackhq.github.io/keeper/0.x/keeper-gradle-plugin/com.slack.keeper/

**Dokka configuration**

```Kotlin
tasks.withType<DokkaTask>().configureEach {
  outputDirectory.set(rootDir.resolve("../docs/0.x"))
  dokkaSourceSets.configureEach {
    skipDeprecated.set(true)
    suppressInheritedMembers.set(true)
    externalDocumentationLink {
      url.set(URL("https://docs.gradle.org/${gradle.gradleVersion}/javadoc/index.html"))
    }
    externalDocumentationLink {
      packageListUrl.set(URL("https://developer.android.com/reference/tools/gradle-api/7.0/package-list"))
      url.set(URL("https://developer.android.com/reference/tools/gradle-api/7.0/classes"))
    }
  }
}
```

**Installation**
- Operating system: macOS Big Sur
- Build tool: Gradle v7.1.1
- Dokka version: 1.5.0

**Comment by ZacSweers** [comment]
Another example where this happens is referencing kotlinx-coroutines at `https://kotlin.github.io/kotlinx.coroutines/index.html`

**Comment by vmishenev** [comment]
You need specify your link like:
```kotlin
    externalDocumentationLink {
      url.set(URL("https://docs.gradle.org/${gradle.gradleVersion}/javadoc/"))
    }
```
The trailing slash is required! 
Dokka doesn't index the URL, so `index.html` is unnecessary. It only indexes a package list from `java.net.URL(url, "package-list")"` by default, in this case `https://docs.gradle.org/${gradle.gradleVersion}/javadoc/package-list`
