### ISSUE TITLE
Feature request: Add option to exclude platform tags from GFM

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/dokka#2073]
**Is your feature request related to a problem? Please describe**
I have a JVM-only project and, while the tags are nice, they are redundant in my project since it's JVM only and I'd like to reduce noise in the docs view.

**Describe the solution you'd like**
An option to disable, such as `displayPlatformTags.set(false)`. I think it would be even better to just automatically omit these in non-multiplatform projects.

**Describe alternatives you've considered**
There's no alternatives right now

**Additional context**
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1361086/129464105-5b13f030-79c5-4a00-89c2-868d3a9f9f57.png">

**Comment by MarcinAman** [comment]
Hi, this issue was already reported in: https://github.com/Kotlin/dokka/issues/1921
