### ISSUE TITLE
Include custom stylesheets with Maven?

### ISSUE THREAD

**Issue by lamergameryt** [Kotlin/dokka#2075]
**Question**
I've been trying to include custom stylesheets with Maven, but there isn't any obvious way to do so. This is my current configuration:
```xml
<configuration>
   <perPackageOptions>
      <packageOption>
         <matchingRegex>xyz\.lamergameryt\.lamerutils\.samples.*</matchingRegex>
         <suppress>true</suppress>
      </packageOption>
   </perPackageOptions>
   <samples>
      <dir>src/main/kotlin/xyz/lamergameryt/lamerutils/samples</dir>
   </samples>
</configuration>
```

I've tried following the [documentation](https://kotlin.github.io/dokka/1.5.0/user_guide/base-specific/frontend/), but I'm unsure how to implement it.

Could someone clarify how to include custom stylesheets in Maven?

**Installation**
- Operating system: Windows
- Build tool: Maven
- Dokka version: 1.5.0

**Comment by vmishenev** [comment]
You can follow [Dokka documentation: Maven](https://kotlin.github.io/dokka/1.5.0/user_guide/maven/usage/).
Moreover I have created the maven project example with custom format https://github.com/Kotlin/dokka/tree/maven-dokka-customFormat-example/examples/maven/dokka-customFormat-example
