### ISSUE TITLE
What's the best way to transform CustomTagWrapper or TagWrapper?

### ISSUE THREAD

**Issue by anatawa12** [Kotlin/dokka#2084]
**Question**
What's the best way to transform CustomTagWrapper or TagWrapper?
I want to add a custom tag so I want to transform CustomTagWrapper, TagWrapper, or Documentable. However Documentable doesn't have a method to copy with documentation, DocumentableTransformer can't transform documentation for non-modules, and it looks no plugin point for transforming CustomTagWrapper, TagWrapper. It looks what we can do is I need to try to cast ContentPage to each type, Documentable to each type, and call the copy function. So, what's the recommended way to transform CustomTagWrapper or TagWrapper or there is no way?

**Screenshots**
N/A

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.1
- Dokka version: 1.5.0

**Additional context**
N/A

**Comment by MarcinAman** [comment]
What would you like to achieve by adding / transforming tag? 

Right now the only way is casting and using copy: https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/transformers/pages/annotations/SinceKotlinTransformer.kt
although it would be nice to have something like `modified` on documentable, but i fear that this would serve a fairly limited amount of people and could probably be replaced with an visitor class that with all methods preimplemented like we will have in next version: https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/transformers/documentables/DocumentableReplacerTransformer.kt
it also has the benefit of being 'lazy' therefore we can save at least some of the memory

**Comment by anatawa12** [comment]
I found transformDocumentationNode and it works. I'm sorry to my research not enough.

**Comment by anatawa12** [comment]
https://github.com/Kotlin/dokka/blob/9be7ac19b3ad38c80c78f39443eb2f55b3b699c6/plugins/base/src/main/kotlin/transformers/pages/annotations/SinceKotlinTransformer.kt looks good for me. thank you
