### ISSUE TITLE
link to other class specified in super class gets lost in sub class

### ISSUE THREAD

**Issue by robstoll** [Kotlin/dokka#210]
Consider the following example:
```
package abc;
/**
 * @property a Some text [B]
 */
class A(val a: String) {
}
class B
```
```
package xyz;
class Z(a: String): A(a)
```
Unfortunately dokka is not able to create the link in the documentation of Z::a because class B is not imported within the file of class Z. 

Btw. it seems to work correctly for inherited methods

**Comment by Kordyjan** [comment]
As far as I know, this is fixed after 1.4.0-rc.
