### ISSUE TITLE
Do not truncate contents of Module and Package "includes" (modules.md).

### ISSUE THREAD

**Issue by R-lagoman** [Kotlin/dokka#2108]
**Is your feature request related to a problem? Please describe**
Currently the contents for `Module` and `Package` (https://kotlinlang.org/docs/reference/kotlin-doc.html#module-and-package-documentation) are truncated in the final `index.html` output, showing only characters until the first dot.
I don't know if this is some kind of intentional limitation or an error, but for me it does not align with javadoc behavior, where you can specify a complete overview html (see for example https://docs.oracle.com/en/java/javase/16/docs/api/index.html).

**Describe the solution you'd like**
Include all the contents in the final output, including lists, links, dots and whatever markdown defined for `Module` and `Package` in the referenced files.

**Are you willing to provide a PR?**
Providing a PR is not possible right now.

**Comment by IgnatBeresnev** [comment]
I believe this has been fixed in #2055, so I'll close the issue for now. @R-lagoman please let us know if you're still experiencing the issue
