### ISSUE TITLE
Sync failed with Kotlin 1.5.30 and dokka on classpath: KOTLIN_STAT_LABEl_PROPERTY

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/dokka#2109]
**Describe the bug**
After updating to Kotlin 1.5.30 with the described configuration it is not possible to do any gradle task anymore.
[KotlinGradleBug.zip](https://github.com/Kotlin/dokka/files/7092967/KotlinGradleBug.zip)

**Expected behaviour**
A successful gradle task

**To Reproduce**
Open attached project and do any gradle task (sync, build etc)

**Dokka configuration**

```Kotlin
plugins {
    kotlin("jvm") version "1.5.30" apply false
    id("org.jetbrains.dokka") version "1.5.0"
}

buildscript {
    dependencies {
        classpath("org.jetbrains.dokka:dokka-base:1.5.0")
    }
}

repositories {
    mavenCentral()
}

subprojects {
    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "org.jetbrains.dokka")

    repositories {
        mavenCentral()
    }
}
```

**Installation**
- Operating system: macOS 12, Ubuntu 20.04
- Build tool: Gradle 7.2
- Dokka version: 1.5.0

**Are you willing to provide a PR?**
Nope, I dont know the cause.

**Comment by MarcinAman** [comment]
Could you try the dev build from here: https://github.com/Kotlin/dokka/issues/2092

**Comment by hfhbd** [comment]
@MarcinAman this build works.
