### ISSUE TITLE
Add indentation between text and code blocks in raw descriptions

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2118]
For the text in a raw description missed indentation between text and code blocks [code example](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/src/ThreadContextElement.kt#L80):

![image](https://user-images.githubusercontent.com/7689049/132244120-a68d82d1-332b-4b4d-b130-db16bfd8ef71.png)

I expect something like this: https://www.jetbrains.com/help/idea/debug-your-first-kotlin-application.html#examining-code

**Installation**
- Dokka version: 1.5.30-dev-117

**Comment by vmishenev** [comment]
Fixed in #2190
