### ISSUE TITLE
Dark mode switches only once

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2124]
The dark mode switcher works only on the first click. The next click doesn't change the state of `dokka-dark-mode` property.
![Sep-07-2021 15-57-02](https://user-images.githubusercontent.com/7689049/132348544-93c8ed65-d8bf-46f5-a448-4841c9998adf.gif)

**Installation**
- Dokka version: 1.5.30-dev-117

**Comment by MarcinAman** [comment]
I've fixed it in samples PR: https://github.com/Kotlin/dokka/pull/2116/files#diff-c71038da8216846a0c6e96cd9d7a826d505ad13188cdb78514f6afcc4c35f567R42
