### ISSUE TITLE
Using dokka in android studio

### ISSUE THREAD

**Issue by priya5713** [Kotlin/dokka#214]
here is code for app level gradle ,but using this file i can not generate output file in html and i add at project level task like but this is not working and i can not generate the out put file.

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'org.jetbrains.dokka'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "com.bindingadapterutills.libtest"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    dataBinding.enabled = true
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    kapt 'com.android.databinding:compiler:2.3.3'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.0.1'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.0'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.0'
   
}


kapt {
    generateStubs = true
}

````

and project level:

```
task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}
```

**Comment by semoro** [comment]
Use `type: org.jetbrains.dokka.gradle.DokkaAndroidTask `

**Comment by priya5713** [comment]
Javadoc folder is created using "DokkaAndroidTask" but its empty

**Comment by mradzinski** [comment]
I can confirm that applying `org.jetbrains.dokka-android` and configuring Dokka like

```
dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}
```
Ends up with an empty Javadoc folder in Android and no error reported during the task (`generation completed successfully`)

**Comment by semoro** [comment]
Make sure that you are applying Dokka plugin to module where app is located 
For default Android project:
```
build.gradle <- classpath goes here 
app: 
 build.gradle <- task & apply goes here 

```

**Comment by rajasone** [comment]
hi, i create a new task.gradle file and place the following dokka task in it but it's not building here is the error, help please

**Could not get unknown property 'org' for project ':app' of type org.gradle.api.Project.** 

```
apply plugin: 'org.jetbrains.dokka-android' // dokka documentation/

task dokka(overwrite: true, type: org.jetbrains.dokka.gradle.DokkaAndroidTask) {

    outputFormat = 'html'
    outputDirectory = "$buildDir/dokka"
    // Do not create index pages for empty packages
    skipEmptyPackages = true

    //Do not output deprecated members. Applies globally, can be overridden by packageOptions
    skipDeprecated = false

    //No default documentation link to kotlin-stdlib
    noStdlibLink = false
}
```

**Comment by semoro** [comment]
@rajasone Why you need to `overwrite`, just use 
```
dokka { /* params */ }
```

Please, make sure that Dokka added to plugin classpath

**Comment by rajasone** [comment]
@semoro thanks for reply, i already added classpath,  if i don't add `overwrite: true`  it complains `Cannot add task ':app:dokka' as a task with that name already exists.`

**Comment by semoro** [comment]
@rajasone Which Gradle version are you using?

**Comment by rajasone** [comment]
@semoro my gradle version is  `4.1`

**Comment by semoro** [comment]
Is it Groovy Gradle of Kotlin DSL? 
Seems strange

**Comment by budius** [comment]
I'm having the same issue on my Android library (Android Studio / gradle 4.4 / dokka 0.9.17). The Same error:

> Could not get unknown property 'org' for project ':app' of type org.gradle.api.Project

My idea is to have 2 Dokka tasks. One as part of the `uploadArchives` for the maven repo and the other for a HTML generation for our website.

At the end I managed to do it with a very weird hack. Instead of using: 
```
task dokkaHtml(type: org.jetbrains.dokka.gradle.DokkaAndroidTask) {
```
I've ended up doing this:
```
task dokkaHtml(type: dokka.class) { // ¯\_(ツ)_/¯
```

I'm sure there's a perfectly logical reason for it and I hope that this helps for the fix.

**Comment by semoro** [comment]
@budius Is you using `org.jetbrains.dokka-android`?

**Comment by rajasone** [comment]
@budius thanks your hack works like a charm :)

**Comment by RaymondChan1** [comment]
Very useful workaround.
