### ISSUE TITLE
Some Java getters and setters are not documented

### ISSUE THREAD

**Issue by fsladkey** [Kotlin/dokka#2140]
### Some Java getters and setters are not documented

Java getter / setter methods for a field of the same name are not included in `DClass`. For example, methods `getFoo` / `setFoo` which get / set a field `foo` are not included in the functions property on `DClass`.

This makes sense for Kotlin documentation of Java classes, but for Java docs it would be great to include these methods.

The following failing test case (added to `JavaTest.kt` during debugging) shows what's happening

```kt
@Test
fun `getters and setters should be documented`() {
    inlineModelTest(
        """
        |public final class Foo {
        |
        |  public int a;
        |  public int c;
        |
        |  public int getA() {
        |    return a;
        |  }
        |
        |  public void setA(int a) {
        |    this.a = a;
        |  }
        |
        |  public int getB() {
        |    return c;
        |  }
        |
        |  public void setB(int b) {
        |    c = b;
        |  }
        |}
        """, configuration = configuration
    ) {
        with((this / "java" / "Foo").cast<DClass>()) {
            // fails, actual is listOf("getB", "setB")
            assertEquals(listOf("getA", "setA", "getB", "setB"), functions.map { it.name })
        }
    }
}
```

To get the test passing, it's easy enough to make the following change in `DefaultPsiToDocumentableTranslator` but I suspect this creates issues for Kotlin docs further down the pipeline and would need to be handled elsewhere. If anyone could point me in the right direction there I'd be happy to take a stab at it and open a PR.

```diff
         private fun PsiClass.splitFunctionsAndAccessors(): Pair<MutableList<PsiMethod>, MutableMap<PsiField, MutableList<PsiMethod>>> {
             val fieldNames = fields.map { it.name to it }.toMap()
             val accessors = mutableMapOf<PsiField, MutableList<PsiMethod>>()
             val regularMethods = mutableListOf<PsiMethod>()
             methods.forEach { method ->
                 val field = method.getPropertyNameForFunction()?.let { name -> fieldNames[name] }
                 if (field != null) {
                     accessors.getOrPut(field, ::mutableListOf).add(method)
-                } else {
-                    regularMethods.add(method)
                 }
+                regularMethods.add(method)
             }
             return regularMethods to accessors
         }
```

Let me know if there's any other way of accessing this information from `DClass` that I might have missed, or any other work-arounds, suggestions, or corrections.

Thanks! :)

**Installation**
- Operating system: macOS
- Dokka version: master branch

**Comment by MarcinAman** [comment]
I'd say that the behaviour is correct as most often users are not interested in seeing getters/setters everywhere. Therefore they are hidden in properties:

```kotlin
    @Test
    fun `getters and setters should be documented`() {
        inlineModelTest(
            """
        |public final class Foo {
        |
        |  public int a;
        |  public int c;
        |
        |  public int getA() {
        |    return a;
        |  }
        |
        |  public void setA(int a) {
        |    this.a = a;
        |  }
        |
        |  public int getB() {
        |    return c;
        |  }
        |
        |  public void setB(int b) {
        |    c = b;
        |  }
        |}
        """, configuration = configuration
        ) {
            with((this / "java" / "Foo").cast<DClass>()) {
                val propertyA = properties.find { it.name == "a" }
                val propertyC = properties.find { it.name == "c" }

                //In functions, we would like to have only real functions, without getters/setters
                assertEquals(listOf("getB", "setB"), functions.map { it.name })

                //getters/setters belong to their corresponding properties
                assertEquals("getA", propertyA?.getter?.name)
                assertEquals("setA", propertyA?.setter?.name)
                assertNull(propertyC?.getter)
                assertNull(propertyC?.setter)

                //All functions are available via a union between getter/setter from properties and functions
                assertEquals(
                    listOf("getA", "setA", "getB", "setB").sorted(),
                    (functions.map { it.name } + properties.flatMap { listOfNotNull(it.getter?.name, it.setter?.name) }).sorted()
                )
            }
        }
    }
```

**Comment by andrewlewis** [comment]
@MarcinAman We'd like to migrate ExoPlayer javadoc generation to be based on Dokka and need to have getters/setters documented. The codebase is written in Java. Here is an example from our current javadoc where it's useful to have the setter documented: [PlayerView.setPlayer](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#setPlayer(com.google.android.exoplayer2.Player)).

Please could you reconsider this, or possibly providing an option to include getters/setters in javadoc?

**Comment by MarcinAman** [comment]
@andrewlewis I see that ExoPlayer is a library maintained by google. Will you use their plugin or our "stock" dokka?

**Comment by andrewlewis** [comment]
We will use the plugin (but based on my limited understanding, this issue would need to be fixed in dokka?).

**Comment by fsladkey** [comment]
Thanks @MarcinAman! Didn't realize those were accessible through the properties themselves, that solves the problem for us, sorry for the trouble!

@andrewlewis, thanks for following up here! With this example from Marcin we're good to go and can make the change on our side without any Dokka changes. I'm taking a look at it right now.
