### ISSUE TITLE
Add missing margin to h4 in HTML output

### ISSUE THREAD

**Issue by jakobkmar** [Kotlin/dokka#2143]
Every HTML heading tag (both bigger and smaller than h4) has a vertical margin in both directions - except `h4`.

To make the rendered HTML more readable, it would be a good improvement if `h4` has this spacing as well.

**Comment by AzimMuradov** [comment]
> Every HTML heading tag (both bigger and smaller than h4) has a vertical margin in both directions - except `h4`.
> 
> To make the rendered HTML more readable, it would be a good improvement if `h4` has this spacing as well.

I think its already fixed: 742f96bdf5c0b842e68dfaf43f4ab3446e87e3df

It's just not part of the 1.5.30 release. As you can see in the [dokka-base sources](https://repo1.maven.org/maven2/org/jetbrains/dokka/dokka-base/1.5.30/dokka-base-1.5.30-sources.jar) there is an old version of the `style.css` file in the `dokka/styles` folder.

**Comment by jakobkmar** [comment]
Ah I see, the 1.5.30 release branch is not even with the master branch at the time of the 1.5.30 release - thank you for pointing this out.

**Comment by IgnatBeresnev** [comment]
I'll close this as fixed for now, do let us know if you keep seeing this.
