### ISSUE TITLE
Unable to resolve dokka in buildSrc

### ISSUE THREAD

**Issue by ThanosFisherman** [Kotlin/dokka#2157]
**Question**
I'm trying to create a reusable version of maven publish instructions for my library. I try to put some code in buildSrc and everything seems to work fine except for the dokka plugin `DokkaTask` cannot be resolved even though I've added the dokka plugin in plugins{} block in build.gradle.kts

Any idea why is this happening and how I can fix this?

**Installation**
- Operating system: macOS/Linux
- Build tool: Gradle v7.2
- Dokka version: 1.5.30

**Comment by MarcinAman** [comment]
I think you got the answer on slack ☺️

**Comment by ThanosFisherman** [comment]
True 😊

**Comment by unredundant** [comment]
Could you still post it here? This is not very helpful for anyone searching for this online
