### ISSUE TITLE
Is it possible to @suppress only a property's setter?

### ISSUE THREAD

**Issue by agramian** [Kotlin/dokka#2158]
**Question**

I would like to expose the getter and suppress the setter for a property in the generated documentation.
Below is the way I have attempted to achieve this but it doesn't seem to work.
```
    var property: Int
        /** @suppress */
        private set
```
Is it possible to hide/exclude only a property's setter while making its getter visible? 

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.7.1
- Dokka version: 1.5

**Comment by MarcinAman** [comment]
Why would you like to hide the setter? Dokka in the default html format doesn't render setters/getters until they are annotated with some documented annotations. 

Also: in this case the setter is private so it really shouldn't be visible as by default we include only public api

**Comment by agramian** [comment]
I would like to hide the setter because as you say it is private and shouldn't be visible to the public api.

I am using Dokka in the default html format as far as I can tell and it is rendering class properties with a separate getter and setter.  There is no annotation I have added to the properties.

```
dokkaHtml {
    dokkaSourceSets {
        named("main") {
            noAndroidSdkLink.set(false)
            perPackageOption {
                matchingRegex.set("some_regex")
                suppress.set(true)
            }
        }
    }
}
```

Yes in the example I provided the setter is private and I am expecting it to be hidden as you are saying but it is shown.

Please let me know if there is any additional information that you need to help to understand/resolve.
