### ISSUE TITLE
Relative link from module markdown

### ISSUE THREAD

**Issue by strangesource** [Kotlin/dokka#2162]
**Describe the bug**
I'm using a `.md` file to document my module, as described at https://kotlinlang.org/docs/reference/kotlin-doc.html#module-and-package-documentation

I would like to link to a resource located within the documentation (e.g. a package documentation or a specific class but relative links are not generated correctly.

For the following markdown
```
Have a look at [this link](./testmodule/com.example.app/index.html)
```

no link is generated but `this link` is completely truncated while the link is displayed as plain text:

```
Have a look at ./testmodule/com.example.app/index.html
```

This does work if the link starts with e.g. `https://` but in that case I can't use relative URLs

**Expected behaviour**
A link is created for relative URLs just like for absolute URLs.

**Dokka configuration**
No specific configuration required. Just run `dokkaHtml`

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.7.1
- Dokka version: 1.5.30

**Comment by MarcinAman** [comment]
I think that your issues are more or less the same as in: https://github.com/Kotlin/dokka/issues/1863 as you would like to somehow link to the insides of documentation by class or relative path

**Comment by strangesource** [comment]
Thanks for clarifying, was not able to find that issue.
