### ISSUE TITLE
Gfm adding consecutive ~~ for deprecated code

### ISSUE THREAD

**Issue by stevenzeck** [Kotlin/dokka#2177]
**Describe the bug**
When running Gfm against code marked with `@Deprecated`, it adds consecutive `~~` in certain cases.  Take this example:

```
data class Test(
    val var1: Int? = null,
    val var2: String? = null
) {
    /**
     *
     * @param var3 A parameter
     */
    @Deprecated("This is deprecated")
    fun test(var3: Int) {
    }
}
```

This produces a test.md file (among other md files) with the following contents:

```
# test

[androidJvm]\
~~fun~~ [~~test~~](test.md)~~(~~~~var3~~~~:~~ [Int](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-int/index.html)~~)~~

## Parameters

androidJvm

| | |
|---|---|
| var3 | A parameter |
```

**Expected behaviour**
I think ideally there would only be `~~` at the beginning and end of this entire line:  `fun test(var3: Int)`.  It looks like however it is being parsed, it is passing in each of these when being sent to buildText, so each is surrounded with ~~:
- fun
- test
- (
- var3
- :
- )

**Screenshots**
N/A

**To Reproduce**
You can use that data class example above and generate Gfm docs from it.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
        tasks.named("dokkaGfmPartial") {
            dokkaSourceSets {
                configureEach {
                    reportUndocumented.set(false)
                    skipEmptyPackages.set(false)
                    skipDeprecated.set(false)
                }
            }
        }
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.8.0
- Dokka version:  1.5.32

**Additional context**
N/A

**Are you willing to provide a PR?**
I can try if someone points me in the right direction.  I've tried setting this up locally to debug against an Android project, but couldn't do anything other than get it to log.

**Comment by stevenzeck** [comment]
I wouldn't mind trying to help fix this. I've gone through the code a bit; is there a test that can be created that takes raw Kotlin and can output the HTML and/or markdown as a String?  https://github.com/Kotlin/dokka/blob/master/plugins/gfm/src/test/kotlin/renderers/gfm/SimpleElementsTest.kt#L73 only covers how it renders, not how it parses.

**Comment by vmishenev** [comment]
Yes, e.g. there is https://github.com/Kotlin/dokka/blob/master/plugins/base/src/test/kotlin/signatures/SignatureTest.kt
I think for GFM format you can add GFM plugin to `pluginOverrides`.

**Comment by vmishenev** [comment]
#2622 Now we have strikethrough only for declaration names and not for the whole signature as before.
