### ISSUE TITLE
Dokka Gradle Plugin should not bundle kotlin-stdlib & kotlin-reflect

### ISSUE THREAD

**Issue by semoro** [Kotlin/dokka#219]
Dokka plugin should depend on kotlin-stdlib & kotlin-reflect instead of bundling it inside the plugin.

Otherwise, it causes poisoning of Gradle ClassLoader with old kotlin libraries and results in interfering with other plugins.

**Comment by 3flex** [comment]
kotlin-compiler as well?

**Comment by semoro** [comment]
Dokka Gradle plugin doesn't bundle kotlin-compiler, 
kotlin-compiler only bundled in Dokka FatJar, and it's necessary for Dokka to work.

**Comment by udalov** [comment]
See https://youtrack.jetbrains.com/issue/KT-21369
