### ISSUE TITLE
Sample body is not embeded to documentation

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2199]
I have a code block
```Kotlin
package org.jetbrains.qa

/**
 * Hello, Sample
 * @sample org.jetbrains.qa.runSample
 */
fun withSample(a: Int): Int{
    return a + 1
}

fun runSample(){
    withSample(41)
}
```

Regarding KDoc descriptions: https://kotlinlang.org/docs/kotlin-doc.html#sample-identifier Iexpect that the body of `runSample` will be embedded to output, but as result I have just plane text function name
![image](https://user-images.githubusercontent.com/7689049/138314045-a228505d-8819-4a04-a5c1-cf47bb34ce67.png)

During the documentation generation process I see:

```
Transforming pages
Cannot find descriptor for package org
Cannot find PsiElement corresponding to org.jetbrains.qa.runSample
Rendering
Running post-actions
```

**Installation**
- Dokka version: 1.5.31, 1.6.0-RC-dev-126

**Comment by MairwunNx** [comment]
@atyrin the same problem.

```
Cannot find descriptor for package com
Cannot find PsiElement corresponding to com.mairwunnx.annotations.ValueXXXUnitSample
```
