### ISSUE TITLE
Make PrimitiveJavaType WithExtraProperties so it can be @NonNull

### ISSUE THREAD

**Issue by owengray-google** [Kotlin/dokka#2207]
`data class PrimitiveJavaType(val name: String) : Bound()`
`sealed class Bound : Projection(), AnnotationTarget`

But to actually be able to annotate a `Documentable` requires that it be a `WithExtraProperties`.

`@NonNull String[]` should be annotated, but it is a `PrimitiveJavaType` (an array). (I don't think any other `Bound` is appropriate for the type, though I could be wrong.)

This seems like a one-line change, but I don't know if it might have any other implications.
I can put up a PR for this if necessary.

Dokka version: 1.6.0-dev-122

**Comment by vmishenev** [comment]
In case `@NonNull String[]` an annotation can be keep in `extra` of DProperty or DParameter or something else. 
`PrimitiveJavaType` represents a java type like `Bound` in kotlin. Likewise, `Bound` has no `extra`.

**Comment by owengray-google** [comment]
I believe that Bound is not just being used to represents type bounds, but also type projections.
For example, the following test:

```
    @Test
    fun `Type-target annotations work on unresolved return types`() {
        val paramString = """
            |annotation class Squark
            |fun foo(): @Squark String? = null
        """.render().returnType()
        val paramUnresolved = """
            |annotation class Squark
            |fun foo(): @Squark Unresolved? = null
        """.render().returnType()

        assertThat(paramString.data.type.data.name).isEqualTo("String")
        assertThat(paramUnresolved.data.type.data.name).isEqualTo("<ERROR CLASS>")

        for (param in listOf(paramString, paramUnresolved)) {
            assertThat(param.data.annotationComponents.size).isEqualTo(1)
            assertThat(param.nullable).isTrue()
            assertThat(param.data.annotationComponents.single().name).isEqualTo("Squark")
        }
    }
```

This passes for the `String` version, then fails for the `Unresolved` version--because the `@Squark` is thrown away, because `UnresolvedBound`s can't have annotations.
I don't believe it should be failing on the Unresolved version. I believe that `UnresolvedBound` should be `WithExtraProperties`, as should `PrimitiveJavaType`.
While conceptually `Bound`s might make sense to not be annotatable, the places that these `Bound` types are showing up makes it seem that they should be annotatable.
