### ISSUE TITLE
External documentation links to nested classes are incorrect for Android documentation.

### ISSUE THREAD

**Issue by adesentenac** [Kotlin/dokka#221]
When dokka generates links to subclasses, or interfaces in classes, from external documentation (for example for Android), instead of outputting a . for the last separator, it outputs a /

i.e. instead of creating a link to https://developer.android.com/reference/android/view/GestureDetector.SimpleOnGestureListener.html it generates a link to https://developer.android.com/reference/android/view/GestureDetector/SimpleOnGestureListener.html
(note that the correct case is GestureDetector.Simple... and the incorrect is GestureDetector/Simple...)

Idem for interfaces, instead of: https://developer.android.com/reference/android/view/View.OnClickListener.html it generates: https://developer.android.com/reference/android/view/View/OnClickListener.html

The same issue appears when using custom external documentation (in my case to Exoplayer classes).

**Comment by adesentenac** [comment]
I've created a pull request to fix this issue, and also handling external documentations which uses dash instead of parenthesis and commas as separators between parameters, like: https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onPlayerStateChanged-boolean-int-

Let me know if you see anything wrong with my fix.

**Comment by kamildoleglo** [comment]
AFAIK this has been fixed in the `1.4.10.2` release,  please feel free to reopen if the issue persists
