### ISSUE TITLE
How to set dakkaSourceSet configuration for MultiModule configuration?

### ISSUE THREAD

**Issue by mandrachek** [Kotlin/dokka#2217]
**Question**
How to set dakkaSourceSet configuration for MultiModule configuration?

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.0.2
- Dokka version: 1.5.30

**Additional context**
I'm attempting (using gradle groovy, not kotlin script), set suppress to false for my partial tasks.  Following the [example](https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-multimodule-example/parentProject/childProjectA/build.gradle.kts), I attempted this:

```tasks.withType(DokkaTaskPartial).configureEach {
    dakkaSourceSets {
        configureEach {
            suppress.set("false")
        }
    }
}
```

but this fails with:

Could not create task ':myproject:dokkaHtmlPartial'.
> Could not find method dakkaSourceSets() for arguments [build_5rsybuifwh9ll0w4t6h36vf99$_run_closure3$_closure26@49bf352b] on task ':myproject:dokkaHtmlPartial' of type org.jetbrains.dokka.gradle.DokkaTaskPartial.

**Comment by vmishenev** [comment]
You have made a typo: ~~d**a**kkaSourceSets~~ --> d**o**kkaSourceSets

**Comment by mandrachek** [comment]
@vmishenev - ok, still, with the typo fixed, it cannot find DokkaTaskPartial (both with and without the import, it fails)

```groovy
import org.jetbrains.dokka.gradle.DokkaTaskPartial

tasks.withType(DokkaTaskPartial).configureEach {
    dokkaSourceSets {
        configureEach {
            suppress.set(false)
        }
    }
}
```

Without the import:
```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'DokkaTaskPartial' for root project 'OnScene' of type org.gradle.api.Project.
```

With the import:
```
unable to resolve class org.jetbrains.dokka.gradle.DokkaTaskPartial
 @ line 33, column 1.
   import org.jetbrains.dokka.gradle.DokkaTaskPartial
```

I enumerated the tasks, and found DokkaTaskPartial_Decorated.  Same results with and without the import.  So for now, I've had to do it this way:

```groovy
tasks.forEach {
    def parts = it.class.name.split("\\.")
    def lastName = parts[(parts.length-1)]
    if (lastName.startsWith("DokkaTaskPartial")) {
        it.configure {
            dokkaSourceSets {
                configureEach {
                    suppress.set(false)
                }
            }
        }
    }
}
```

**Comment by AlexisRiksman-TomTom** [comment]
@mandrachek : Did you put the 'tasks.withType<>' part inside the 'subprojects' section?

**Comment by mandrachek** [comment]
`tasks.withType<>` is kotlin. I'm using a gradle build script, and I put it in a dokka.gradle that's applied from all my modules.

**Comment by vmishenev** [comment]
A task of `DokkaTaskPartial` type  is only for child projects. You can not configure the task in a root project.
You should configure the task in every child project (for example, use gradle cross project configuration via the `subprojects {}`)
