### ISSUE TITLE
Add documentation for json CLI

### ISSUE THREAD

**Issue by owengray-google** [Kotlin/dokka#2223]
Right now, dokka's primary CLI documentation is [here](https://kotlin.github.io/dokka/1.6.0/user_guide/cli/usage/).

We have been forced to use the json option instead of the CLI as described on that page, because of 
```
Execution failed for task ':docs-tip-of-tree:dackkaDocs'.
> A failure occurred while executing androidx.build.dackka.DackkaWorkAction
   > Process 'command '$CHECKOUT/prebuilts/jdk/jdk11/linux-x86/bin/java'' could not be started because the command line exceed operating system limits.
```

Basically, the `-classpath` argument for a `sourceSet` is getting passed ~750 androidx and kotlin artifacts, classes.jar and dependencies, so that we can resolve references. With a ~180 character path each, this is getting near the 2^17 character limit (130k) that many terminals have for commands.

We are now using the json option, and it appears to be working fine, but it has some clear API differences from the normal CLI method, such as the `-src` CLI option being the equivalent of `sourceRoots`, or the `packageListUrl`s requiring `file://` be prepended if they are local.

It would be valuable to have documentation for the json option for the CLI.
(If there is any, I can't find it. I think it deserializes to a [DokkaConfiguration](https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/configuration.kt) but that source file doesn't contain information about e.g. the `file://` difference)

**Comment by vmishenev** [comment]
You are right. JSON configuration is deserialization to a [DokkaConfiguration](https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/configuration.kt).
I have added the sample configuration. The values of particular parameters are the same as in the CLI options.
All `*Url` parameters must correspond to the URI scheme (`file://` for local), the same for CLI.
