### ISSUE TITLE
Unable to hide/suppress k-doc in mixed(java+kotlin) project

### ISSUE THREAD

**Issue by macharya** [Kotlin/dokka#2227]
In my project, I've both kotlin and java files, I am trying to hide a package, I tried @hide @hidden @Suppress still cant hide a java class or public method. Added following 3 libs to my build.gradle and nothing seems to work. Also, what's the right way to use the package option in build.gradle not .kts. followed https://github.com/Kotlin/dokka/issues/492 but that did not solve this problem. Any help?

    classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.4.30"
    classpath "org.jetbrains.dokka:kotlin-as-java-plugin:1.4.30"
    classpath "org.jetbrains.dokka:android-documentation-plugin:1.4.30"

**Comment by vmishenev** [comment]
You can use `@suppress` to hide a method from the documentation.
Support of a package level will be in Dokka 1.6. (#2206)  

Now `matchingRegex` can be used to hide a package.  See [example](https://kotlin.github.io/dokka/1.5.30/user_guide/gradle/usage/)

**Comment by bashbug** [comment]
I have the same issue with dokka 1.5.31

**Problem**
@hide works for all java functions/classes/etc. Except for functions which have a return value.

**How to reproduce**
Add to https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-kotlinAsJava-example/src/main/kotlin/demo the following java class.
- setB() is hidden.
- getA() is shown, even with the @hide tag
```
public class JavaClass {
    private String a;
    private String b;
    JavaClass(String a){
        this.a = a;
    }

    /**
     * @hide
     */
    public void setB(String b) {
        this.b = b;
    }

    /**
     * @hide
     */
    public String getA() {
        return a;
    }
}
```

Is this also fixed @vmishenev with the upcoming 1.6 release?

**Comment by macharya** [comment]
@bashbug how is @hide working for your java classes/methods? I tried 1.5.31 and still can't hide the java methods or class. Tried all three of these but no luck

    classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.5.31"
    classpath "org.jetbrains.dokka:kotlin-as-java-plugin:1.5.31"
    classpath "org.jetbrains.dokka:android-documentation-plugin:1.5.31"

**Comment by vmishenev** [comment]
@bashbug I suppose this fix will be in the next version after Dokka 1.6.
Dokka handles `setB` and `getA` as a setter and a getter so #2158 will fix the bug.
@macharya Can you share your project configuration and code sample with `@hide`?

**Comment by CharlesG-Branch** [comment]
@macharya I recently into a similar issue — was able to resolve the issue by doing:
```
buildscript {
    //...
    dependencies {
        //...
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.4.30"
    }
}
```

Then 
```
dependencies {
    dokkaJavadocPlugin("org.jetbrains.dokka:android-documentation-plugin:1.4.30")
    //...
}
```

@vmishenev I think including this in https://github.com/Kotlin/dokka/tree/master#android would go a long way in clearing up confusion.
