### ISSUE TITLE
Dokka generate R and Buildconfig files in Android

### ISSUE THREAD

**Issue by balanegrero** [Kotlin/dokka#224]
Dooka generate documentation for R and buildConfig files, they shouldn't be generate or how to exclude them?
This is the code I am using:

classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.15"

apply plugin: 'org.jetbrains.dokka-android'

dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/dokkaJavaDoc"

    // Do not create index pages for empty packages
    skipEmptyPackages = true

    //Do not output deprecated members. Applies globally, can be overridden by packageOptions
    skipDeprecated = false

    //No default documentation link to kotlin-stdlib
    noStdlibLink = false
}

**Comment by rajasone** [comment]
Hi, i am using following class path, am using mentioned solution but still dokka is generating comments for android R and third party libraries, any suggestions???

classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.16"
apply plugin: 'org.jetbrains.dokka-android' // dokka documentation/

```
task dokka(overwrite: true, type: org.jetbrains.dokka.gradle.DokkaTask) {
outputFormat = 'html'
outputDirectory = "$buildDir/dokka"

// Do not create index pages for empty packages
skipEmptyPackages = true

//Do not output deprecated members. Applies globally, can be overridden by packageOptions
skipDeprecated = false

//No default documentation link to kotlin-stdlib
noStdlibLink = false
}
```

**Comment by semoro** [comment]
Please, use `org.jetbrains.dokka.gradle.DokkaAndroidTask`

**Comment by radityagumay** [comment]
@semoro 

when using `DokkaAndroidTask`, i got this error.

```
* What went wrong:
Element 'dokka' of type 'org.jetbrains.dokka.gradle.DokkaTask_Decorated' from container 'org.gradle.kotlin.dsl.TaskContainerScope@43061eb2' cannot be cast to 'org.jetbrains.dokka.gradle.DokkaAndroidTask'.
```

**Version**
`org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17`

**Comment by radityagumay** [comment]
Apparently using "org.jetbrains.dokka:dokka-gradle-plugin:0.10.1" fix the issue.

**Comment by GuilhE** [comment]
Still [happens](https://github.com/Kotlin/dokka/issues/958) with 0.10.1
