### ISSUE TITLE
Version switcher not working anymore in 1.6.0

### ISSUE THREAD

**Issue by jakobkmar** [Kotlin/dokka#2243]
I have just updated to Dokka 1.6.0 (which looks great btw), but now the version switcher is not working anymore (no switcher at all, it just displays the current version as text).

![image](https://user-images.githubusercontent.com/52456572/143065909-5f3d5167-4639-47d6-8620-2ac5f788d4ae.png)

This is how I applied the versioning plugin: (in the `build.gradle.kts` of the root project, it is a multi module project)
```kt
tasks {
    dokkaHtmlMultiModule {
        // ...

        pluginConfiguration<VersioningPlugin, VersioningConfiguration> {
            version = project.version.toString()
            olderVersionsDir = projectDir.resolve("dokka/old-builds")
        }
    }
}
```
which worked in 1.5.31.

Do I have to change anything?

**Comment by vmishenev** [comment]
In 1.6 there are a  change:
You should enable the plugin in parent project and all submodules to render a versions navigation on all pages by
```
dependencies {
    //...
    dokkaPlugin("org.jetbrains.dokka:versioning-plugin:1.6.0")
}
```
You can see the example: https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-versioning-multimodule-example

**Comment by vmishenev** [comment]
Versioning plugin should be a `dokkaPlugin`-dependency in every project where Dokka is used. 
In example we implicitly generate the documentation for all projects therefore every project has Dokka gradle plugin with enabled  versioning plugin.

Note: For multi-module projects the `dokkaHtmlMultiModule` task of a root project joins already generated (sub)documentations from child projects. Every child project independently generates own documentation.

**Comment by jakobkmar** [comment]
Alright, I was just confused because of the IntelliJ Dependency list
![image](https://user-images.githubusercontent.com/52456572/143083100-9e12a22a-761d-43cb-85d1-41537000e6b4.png)
which shows the versioning plugin as a real project dependency.

But having a look into the gradle module metadata showed me, that it is not really a dependency.
