### ISSUE TITLE
Html Multimodule: include markdown: Local Images Support

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/dokka#2244]
**Describe the bug**
I have a multimode project. Each module has a `README.md` markdown file, which is displayed on GitHub as well as in Dokka. Now I want to include some local images in the readme file. Markdown works fine, but Dokka does not copy the images, resulting into a `?` in the rendered HTML page.

**Expected behaviour**
1. copy the images into dokka folder
2. adopt the paths from the markdown file to the internal images folder
3. See the image instead a `?`

**Screenshots**
<img width="1920" alt="Bildschirmfoto 2021-11-23 um 18 55 32" src="https://user-images.githubusercontent.com/22521688/143078634-f17568ac-3562-4253-869a-64284c762af7.png">

**To Reproduce**
1. open sample project [dokkaTest.zip](https://github.com/Kotlin/dokka/files/7590176/dokkaTest.zip)
2. `./gradlew dokkaHtmlMultiModule`

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
plugins {
    kotlin("jvm") version "1.6.0" apply false
    id("org.jetbrains.dokka") version "1.6.0"
}

buildscript {
    dependencies {
        classpath("org.jetbrains.dokka:dokka-base:1.6.0")
    }
}

subprojects {
    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "org.jetbrains.dokka")

    tasks {
        withType<org.jetbrains.dokka.gradle.DokkaTaskPartial>().configureEach {
            suppressInheritedMembers.set(true)
            dokkaSourceSets.configureEach {
                includes.from("README.md")
            }
        }
    }
}

tasks.dokkaHtmlMultiModule {
    includes.from("README.md")
}

```

**Installation**
- Operating system: macOS 12.0.1 (21A559)
- Build tool: Gradle v7.3.0
- Dokka version: 1.6.0

**Additional context**

**Are you willing to provide a PR?**
With help, sure

**Comment by AlexisRiksman-TomTom** [comment]
Try copying the images yourself, by adding some code to your `configureEach` block:

                /* Copy .svg and .png images, referenced in the module or package documentation,
                 * to the documentation output.
                 */
                doLast {
                    val dir = Paths.get(
                        rootProject.rootDir.absolutePath,
                        "build/docs/html",
                        project.name,
                        "images"
                    ).toFile()
                    fileTree("${project.projectDir}/images").matching {
                        include(listOf("*.png", "*.svg"))
                    }.forEach {
                        if (!dir.exists()) {
                            dir.mkdirs()
                        }
                        it.copyTo(Paths.get(dir.toString(), it.name).toFile(), true)
                    }
                }

**Comment by vmishenev** [comment]
You should configure Dokka to copy images. Please see https://kotlin.github.io/dokka/1.6.0/user_guide/base-specific/frontend/
For example
```kotlin
            pluginConfiguration<org.jetbrains.dokka.base.DokkaBase, org.jetbrains.dokka.base.DokkaBaseConfiguration> {
                customAssets = listOf(file("img.png"))
            }
```
The `img.png` will be located in `images/img.png`.

**Comment by hfhbd** [comment]
Thanks, it works!
This is my build setup now:
```kt
plugins {
    kotlin("jvm") version "1.6.0" apply false
    id("org.jetbrains.dokka") version "1.6.0"
}

buildscript {
    dependencies {
        classpath("org.jetbrains.dokka:dokka-base:1.6.0")
    }
}

repositories {
    mavenCentral()
}

subprojects {
    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "org.jetbrains.dokka")

    repositories {
        mavenCentral()
    }

    extensions.configure<org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension>("kotlin") {
        explicitApi()
    }

    tasks {
        withType<org.jetbrains.dokka.gradle.DokkaTaskPartial>().configureEach {
            suppressInheritedMembers.set(true)
            dokkaSourceSets.configureEach {
                includes.from("README.md")
            }
        }
    }
}

tasks.dokkaHtmlMultiModule {
    includes.from("README.md")
    pluginConfiguration<org.jetbrains.dokka.base.DokkaBase, org.jetbrains.dokka.base.DokkaBaseConfiguration> {
        val images = subprojects.mapNotNull {
            file("${it.projectDir}/images")
                .takeIf { it.exists() && it.isDirectory }
                ?.walk()
                ?.filter { it.isFile }
                ?.toList()
        }.flatten()
        customAssets = images
    }
}
```
