### ISSUE TITLE
How to register another custom generation extension (Plugin)

### ISSUE THREAD

**Issue by jakobkmar** [Kotlin/dokka#2247]
In the class `DokkaGenerator` Dokka does the following:
```kt
context.single(CoreExtensions.generation).run {
    logger.progress("Dokka is performing: $generationName")
    generate()
}
```
which, due to `single`, only allows for one registered extension on `CoreExtensions.generation`.

Additionally, this extension point is already taken up by `AllModulesPageGeneration` and `SingleModuleGeneration`.

How can I register another generation extension, to generate custom files?

**Comment by vmishenev** [comment]
You can override the extension by another, for example https://github.com/Kotlin/dokka/blob/master/plugins/all-modules-page/src/main/kotlin/AllModulesPagePlugin.kt#L35.
 But using this extension point does not seem a good idea for your case . It is better to generate custom files by the another ways:
 1. Use the `CoreExtensions.postActions` point extension like it is implemented to copy the previously documentation https://github.com/Kotlin/dokka/blob/master/plugins/versioning/src/main/kotlin/versioning/VersioningPlugin.kt#L49 
 2. Use your own html preprocessor like `AssetsInstaller`. See https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/DokkaBase.kt#L221

**Comment by jakobkmar** [comment]
Thank you <3, that's what I need!
