### ISSUE TITLE
Version plugin does not create dropdown

### ISSUE THREAD

**Issue by unredundant** [Kotlin/dokka#2250]
**Describe the bug**
Hey, I'm trying to figure out the Dokka versioning plugin, and there seems to be bug (or missing documentation) as I do not see a dropdown anywhere in my generated documentation. 

**Expected behaviour**
From the documentation, it is not particularly clear, but I would assume that the area with `2.0.0-beta-SNAPSHOT` is where the dropdown should exist.  

**Screenshots**
<img width="510" alt="Screen Shot 2021-11-26 at 6 55 02 PM" src="https://user-images.githubusercontent.com/5607577/143661636-79dc9272-de39-4615-833b-71ff98de181e.png">

I have a folder that has two versions as you can see here.  

<img width="314" alt="Screen Shot 2021-11-26 at 6 56 55 PM" src="https://user-images.githubusercontent.com/5607577/143661679-b21e7e49-5ad3-4c6f-ba09-031ef108ee9f.png">

**To Reproduce**

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
// Root build.gradle.kts
buildscript {
  dependencies {
    classpath("org.jetbrains.dokka:versioning-plugin:1.6.0")
  }
}

tasks.dokkaHtmlMultiModule.configure {
  val version = project.version.toString()
  outputDirectory.set(rootDir.resolve("dokka/$version"))

  pluginConfiguration<org.jetbrains.dokka.versioning.VersioningPlugin, org.jetbrains.dokka.versioning.VersioningConfiguration> {
    setVersion(version)
    olderVersionsDir = rootDir.resolve("dokka")
  }
}

// each child module build.gradle.kts
tasks.dokkaHtmlPartial.configure {
  dokkaSourceSets {
    configureEach {
      includes.from("Module.md")
    }
  }
}
``` 

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.3
- Dokka version: 1.6.0

**Additional context**
I _think_ I am technically not following the plugin directions by having _all_ of my versions in a single directory instead of one for the most recent and a parent dir for the older versions, but that seemed needlessly complicated and didn't seem to have any impact when I went that route, so I left it this way.  

**Are you willing to provide a PR?**
This is currently a draft, and contains some other changes, but should be useful if you want to use it to triage https://github.com/bkbnio/kompendium/pull/115

**Comment by vmishenev** [comment]
You have not enabled the versioning plugin. Also you should enable the plugin in all subprojects when you use dokka.
Please see https://github.com/Kotlin/dokka#applying-plugins 
and example project https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-versioning-multimodule-example 
```kotlin
    dependencies {
       dokkaPlugin("org.jetbrains.dokka:versioning-plugin:1.6.0")
    }
```

**Comment by unredundant** [comment]
ah... silly mistake on my part.  Thank you.
