### ISSUE TITLE
Inconsistency with CLI params and json/gradle

### ISSUE THREAD

**Issue by asfalcone** [Kotlin/dokka#2261]
**Describe the bug**
Inconsistency with CLI params and json/gradle. 
`-globalLinks` for example exists as a command line argument but doesn't exist in Gradle or config.json 

Further, Gradle params link from: https://kotlin.github.io/dokka/1.6.0/user_guide/cli/usage/#example-using-json is broken

**Expected behaviour**
These are 1:1 consistent

**Comment by asfalcone** [comment]
Documentation was added via: https://github.com/Kotlin/dokka/issues/2223  but contains the broken link

**Comment by BarkingBad** [comment]
Working on that

**Comment by BarkingBad** [comment]
After some consideration: we can remove the global options, however, in some cases, they can be very very useful for end-user, especially external links. What are the reasons we have to make API concise 1:1? If it is really confusing for users, then we can remove it, though it will enlarge all users' CLI commands.

Secondly, is the "broken link" you are talking about the `Gradle ones`?
![obraz](https://user-images.githubusercontent.com/32793002/146411947-cc07a622-12ff-4474-ab8a-efc3fec880b1.png)

For now, it seems to be working, redirecting user to this [page](https://kotlin.github.io/dokka/1.6.0/user_guide/gradle/usage/#configuration-options)

**Comment by asfalcone** [comment]
Link looks good now. 

-globalLinks should be available in gradle/config.son

**Comment by BarkingBad** [comment]
Oh sorry, I misinterpreted you because these settings were implemented in gradle/json, but have been removed in the past year I wasn't in the project, so I thought you want me to remove them from CLI as well.
