### ISSUE TITLE
Dokka not generating new documentation after changing Kotlin file

### ISSUE THREAD

**Issue by JWT007** [Kotlin/dokka#227]
I am having a problem with updating the Dokka output during an incremental build ... I will say right from the start that I am a newbie with both :smile_cat: 

If I change a Kotlin file in my source... for example by adding a public function:

`fun foo: String = "HELLO"`

.. and then run the gradle task 'dokka'

```
16:46:15: Executing task 'dokka'...

:foo:foo-bar:compileKotlin
:foo:foo-bar:compileJava UP-TO-DATE
:foo:foo-bar:processResources UP-TO-DATE
:foo:foo-bar:classes UP-TO-DATE
:foo:foo-bar:jar UP-TO-DATE
:dokka UP-TO-DATE

BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date
16:46:15: Task execution finished 'dokka'.
```

It seems that dokka does not trigger the incremental build (as the javadoc task does)...even if I do build the JAR first, the generated Dokka output is not updated unless I do a full clean first.

**Comment by semoro** [comment]
Duplicates #186
