### ISSUE TITLE
Multi-Module Dokka from the root project in Gradle?

### ISSUE THREAD

**Issue by will-ca** [Kotlin/dokka#2271]
**Question**

No matter what I tried, I couldn't get multi module Dokka working from the root project.

Project hierarchy in Gradle:

```
SomeProject/
├── build.gradle.kts ← Can't use tasks.dokkaHtmlMultiModule here.
├── settings.gradle.kts
├── TopProjectA
│   └── build.gradle.kts
└── TopProjectB
    ├── build.gradle.kts ← Need to use tasks.dokkaHtmlMultiModule here instead.
    ├── SubProjectB1
    │   └── build.gradle.kts
    └── SubProjectB2
        └── build.gradle.kts
```

I am new to both Dokka and Gradle.

Code used:

```Kotlin
subprojects {
    apply(plugin = "org.jetbrains.dokka")
}

tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(file("../${BuildConfig.dokkaOutpath}"))
}
```

Is this a limitation of Dokka, or am I doing something wrong?

**Installation**
- Operating system: Linux
- Build tool: Gradle v7.0.2
- Dokka version: 1.5.30

**Comment by vmishenev** [comment]
It is important to apply kotlin plugin before dokka in all subprojects as well. Anyway I need more details: a log, configuration gradle scripts. 
Please take a look at example https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-versioning-multimodule-example/build.gradle.kts It can help you.

**Comment by will-ca** [comment]
@vmishenev 

Regarding the exampling you linked, how would one configure `tasks.dokkaHtmlMultiModule` from the top level script you linked?

```Kotlin
tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(file("somePath"))
}
```

The name isn't available from the top-level script.

**Comment by vmishenev** [comment]
@will-ca 
> The name isn't available from the top-level script.

because of ` apply false`.

You could write
```
plugins {
    kotlin("jvm") version "1.6.0"
    id("org.jetbrains.dokka") version ("1.6.0")
}
repositories {
    mavenCentral()
}
// The versioning plugin should be applied in all submodules
subprojects {
    repositories {
        mavenCentral()
    }
    apply {
        plugin("org.jetbrains.kotlin.jvm")
        plugin("org.jetbrains.dokka")
    }
    val dokkaPlugin by configurations
    dependencies {
       dokkaPlugin("org.jetbrains.dokka:versioning-plugin:1.6.0")
    }
}
tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(file("somePath"))
}
```
