### ISSUE TITLE
How run dokka task only for inspection - undocumented?

### ISSUE THREAD

**Issue by Damned163** [Kotlin/dokka#2275]
How run dokka task/params only for inspection - undocumented?
thx
- Operating system: macOS
- Build tool: Gradle v7.1.0
- Dokka version: 1.6

**Comment by IgnatBeresnev** [comment]
Hi! Can you please give us more info on what it is you're trying to do? Do you want to run dokka just to validate params and make sure everything's configured correctly, but not generate any documentation?

If you can describe your use case, perhaps we could figure something out :)
