### ISSUE TITLE
How can I add custom format in android dokka?

### ISSUE THREAD

**Issue by NohaSamir** [Kotlin/dokka#2279]
**Question**
How can I add custom format in android dokka? 

I follow this [example](https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-customFormat-example/build.gradle.kts#L21) but DokkaBase not resolved

```
apply plugin: 'org.jetbrains.dokka-android'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.18"
        classpath("org.jetbrains.dokka:dokka-base:1.6.0")
    }
}

task dokkaHtml(type:  org.jetbrains.dokka.gradle.DokkaAndroidTask) {
    outputFormat = 'html'
    outputDirectory = "$rootDir/docs"
    noStdlibLink = false
    
    pluginConfiguration<org.jetbrains.dokka.base.DokkaBase, org.jetbrains.dokka.base.DokkaBaseConfiguration> {
        customStyleSheets = listOf(file("logo-styles.css"))
        customAssets = listOf(file("ktor-logo.png"))
    }
}
```

**Installation**
- Operating system: Windows
- Android Dokka version: '0.9.18'

**Comment by vmishenev** [comment]
You use the different version of Dokka plugins in dependencies `0.9.18` and `1.6.0`. They are incompatible. 
`dokka-android-gradle-plugin` does not exist in 1.4.x+ version of Dokka.

We should use 
```
plugins {
    id("org.jetbrains.dokka") version "1.6.0"
}
```
like in the example.

Also please have a look at [migration guide](runners/gradle-plugin/MIGRATION.md)
