### ISSUE TITLE
Add indentation between text and code blocks in methods overloads

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2288]
For the code blocks with method overloads, some indentation is missed.

For the code block
```Kotlin
/**
 * KNative class
 */
class Native {

    /**
     * Accept as param [platform.posix.DIR]
     */
    fun native(platformParam: platform.posix.DIR): platform.posix.FTS {
        return platform.posix.FTS(NativePtr.NULL)
    }


    /**
     * Accept as param [platform.posix.DIR] and boolean flag
     */
    fun native(platformParam: platform.posix.DIR, flag: Boolean): platform.posix.FTS {
        return platform.posix.FTS(NativePtr.NULL)
    }

    /**
     * Accept as param [platform.posix.DIR], boolean flag anf integer order
     */
    fun native(platformParam: platform.posix.DIR, flag: Boolean, order: Int): platform.posix.FTS {
        return platform.posix.FTS(NativePtr.NULL)
    }
}
```

Generated documentation looks like this:
![image](https://user-images.githubusercontent.com/7689049/147119854-3f3a1dd4-224b-4414-a723-8587eb3adb0c.png)

If the methods descriptions will be the same it will miss any space between blocks:
![image](https://user-images.githubusercontent.com/7689049/147119969-5f8e5120-1969-4da3-9ba3-36b6e4e01d75.png)

**Installation**
- Dokka version: 1.6.10

**Comment by vmishenev** [comment]
It is a feature)
We merge fun signatures with the same descriptions. It is very useful for stdlib: http://dokka-snapshots.s3.eu-central-1.amazonaws.com/master/stdlib/9a61f49/kotlin-stdlib/kotlin.collections/all.html
