### ISSUE TITLE
Dokka complaining about unsolved link in inherited documentation.

### ISSUE THREAD

**Issue by JWT007** [Kotlin/dokka#229]
If I defined a documented interface:

```
import java.util.LinkedList

interface Foo {

  /** Says hello - [LinkedList]. */
  fun sayHello() : String

}
```

And a class which implements this interface and provides an implementation for the interface method 'sayHello':

```
class FooBar : Foo {

  override fun sayHello(): String {
    return "Hello!"
  }

}
```

During the Build dokka reports an unresolved link to the 'List' class in the implementation class.

Unresolved link to LinkedList in doc comment of 
FooBar$sayHello() (FooBar.kt:5)

**Comment by robstoll** [comment]
Still happens with 0.9.16 :disappointed: 
I haveplenty of such use cases and the link in the resulting HTML file just points to `href="#"`

**Comment by arturbosch** [comment]
We are having this issue with 0.9.17 at detekt:
`Unresolved link to A-Za-z0-9 in doc comment of io.gitlab.arturbosch.detekt.rules.naming.VariableNaming (VariableNaming.kt:15)`

**Comment by semoro** [comment]
@arturbosch 

Looks like complete unrelated, as `A-Za-z0-9` is not proper link target, looks like you have `[A-Za-z0-9]` in KDoc which treated as a link 

See https://youtrack.jetbrains.com/issue/KT-24840

**Comment by arturbosch** [comment]
@semoro yes, exactly this, thanks for clarification!
