### ISSUE TITLE
Setting copyright in gradle plugin parameter

### ISSUE THREAD

**Issue by jimlyas** [Kotlin/dokka#2296]
**Is your feature request related to a problem? Please describe**
No

**Describe the solution you'd like**
It would be easier add parameter like `copyright` in configuration 

**Describe alternatives you've considered**
If it such a hassle, maybe a disclaimer in the documentation if it can not be done automatically

**Additional context**

**Are you willing to provide a PR?**
No

**Comment by AlexisRiksman-TomTom** [comment]
Try using a custom footer message, as in:
```
    pluginConfiguration<DokkaBase, DokkaBaseConfiguration> {
        footerMessage = "Copyright @ 2022 Me Myself & I."
    }
```

**Comment by jimlyas** [comment]
Thanks, after adding `dokka-base` plugin and adding that line, **it works**!
