### ISSUE TITLE
Automatic suppression of documentation for some Object method?

### ISSUE THREAD

**Issue by JWT007** [Kotlin/dokka#230]
If I extend some Object methods such as:

override fun equals(other: Any?): Boolean
override fun hashCode(): Int
override fun toString(): String

They are then included in the generated Dokka output.  

Normally though I don't always want to see these in my API documentation and end up putting a `/** @suppress */` on every one of these methods.

Sometimes (in rare cases) I do want to provide additional information in the documentation about the special implementation of these methods but 99.9% percent of the time I don't.

Would it be possible to automatically suppress generation of output for these Object methods if no custom documentation is provided?

**Comment by Kordyjan** [comment]
It is implemented in 1.4.0

**Comment by wei120698598** [comment]
> It is implemented in 1.4.0

How to set it?

**Comment by ZacSweers** [comment]
@Kordyjan could you elaborate? I don't see any documentation for suppressing these and still see it automatically in 1.4.10

**Comment by pavankumarvvijapur** [comment]
@Kordyjan can u share some more details on how to tackle this ?

**Comment by MarcinAman** [comment]
I don't think that it was implemented :)

If one of you would have some spare time i encourage you to give it a shot ☺️

**Comment by kamildoleglo** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/1758
