### ISSUE TITLE
Can't configure Dokka from precompiled script

### ISSUE THREAD

**Issue by chkpnt** [Kotlin/dokka#2301]
**Describe the bug**
I'm unsure if this is a Gradle or a Dokka issue, but I can't configure Dokka from a precompiled script with Dokka 1.6.10. It seems Dokka can't find any sourceset.

**Expected behaviour**
Dokka should generate docs.

**To Reproduce**
I've modified your example "dokka-gradle-example" to use a precompiled script: https://github.com/chkpnt/dokka-gradle-example/commit/ca5f7998ac9a7bb458e99b783e7ad00fe847acbf

When you run the task `printSourceSetInformationFromPrecompiledScript`, you see that the sourceSets are available. But Dokka fails with `GradleDokkaSourceSetBuilder with name 'main' not found.`

**Dokka configuration**
Configuration of dokka used to reproduce the bug:

```Kotlin
tasks.withType<DokkaTask>().configureEach {
    dokkaSourceSets {
       named("main") {
            moduleName.set("Dokka Gradle Example")
            includes.from("Module.md")
            sourceLink {
                localDirectory.set(file("src/main/kotlin"))
                remoteUrl.set(URL("https://github.com/chkpnt/dokka-gradle-example/tree/master/src/main/kotlin"))
                remoteLineSuffix.set("#L")
            }
        }
    }
}
```
But it has to be in a precompiled script.

If you comment out the configuration, Gradle doesn't fail. But still nothing is generated.

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.3.0
- Dokka version: 1.6.10

**Additional context**
I didn't have this issue with Dokka 0.10.1: https://github.com/chkpnt/truststorebuilder-gradle-plugin/blob/0.5.1/buildSrc/src/main/groovy/truststorebuilder-docs.gradle#L27-L30

**Are you willing to provide a PR?**
I don't know the cause. But if you give me enough hints and it's only a small bug, sure...

**Comment by vmishenev** [comment]
Please add `implementation(kotlin("gradle-plugin", "1.6.10"))` in your precompiled script plugin.
Dokka extracts the information about sourcesets from Kotlin Gradle Plugin.

**Comment by chkpnt** [comment]
Thanks, that was indeed the missing piece.
