### ISSUE TITLE
Copy @property documentation into primary constructor @param

### ISSUE THREAD

**Issue by gradha** [Kotlin/dokka#232]
In the following documentation `@property` and `@param` have to be specified twice to document both the property and the constructor parameter.

```
/**
 * Doc test.
 *
 * @param value Holds something.
 * @property value Holds something.
 */
class DocText(val value: Int)
```

It would be nice if the `@property` content was _copied_ into the `@param` _space_ if none was explicitly documented. In this way the IDE can show this documentation text for both the property and the constructor parameter.

**Comment by yole** [comment]
It's copied the other way round. You can remove `@property`.

**Comment by gradha** [comment]
Doesn't seem work for me in Android Studio Beta 6. Maybe it's fixed in the RC?

**Comment by unlimitedsola** [comment]
@yole doesn't work in Intellij IDEA 2017.3.1 EAP

**Comment by MariusVolkhart** [comment]
Works in `2019.2`

**Comment by kamilok1965** [comment]
Hi @gradha, is this still relevant?

**Comment by gradha** [comment]
> Hi @gradha, is this still relevant?

Not any more. In Android Studio 3.5 it works for me as @yole mentioned, removing `@property`. Thanks.

**Comment by SpertsyanKM** [comment]
Using dokka 1.6.10 with Android Studio Arctic Fox 2020.3.1 patch 4.

@param description is not copied to the corresponding property

**Comment by TheMrMilchmann** [comment]
Can someone clarify what the intended behavior is? The documentation doesn't seem to be copied either way with dokka 1.7.10 either.
