### ISSUE TITLE
Don't warn on missing documentation for Object methods

### ISSUE THREAD

**Issue by asfalcone** [Kotlin/dokka#2341]
Dokka should not warn about missing documentation on toString(), equals(), hashCode(). Documenting these methods generally not useful.

Example failures today:

No documentation for androidx.navigation.NavGraph$toString() (NavGraph.kt:361)
No documentation for androidx.navigation.NavGraph$equals(kotlin.Any) (NavGraph.kt:380)
No documentation for androidx.navigation.NavGraph$hashCode() (NavGraph.kt:390)
No documentation for androidx.navigation.NavDestination$toString() (NavDestination.kt:510)
No documentation for androidx.navigation.NavDestination$equals(kotlin.Any) (NavDestination.kt:532)
No documentation for androidx.navigation.NavDestination$hashCode() (NavDestination.kt:558)

**Comment by IgnatBeresnev** [comment]
Hm, interesting. I can't seem to find `No documentation for` substring when performing a full-text search on current dokka's codebase, so not sure where this is coming from.

Is there any more context you could provide or a way to reproduce it?

**Comment by asfalcone** [comment]
Thanks, my mistake. This behavior must have been removed (older bug referencing this string as well #463)!
