### ISSUE TITLE
Dokka Gradle plugin has the same output files being generated by multiple tasks

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/dokka#2346]
This doesn't seem to affect operation but confused some other code I have. In a sub-module the directory `build/dokka/gfm` is an output of both that submodule's `dokkaGfm` task, and also the root project's `:dokkaGfmCollector` task. Ditto for some other tasks. I don't think that's quite right - an output file should be controlled by a single task, no?

**Comment by IgnatBeresnev** [comment]
It seems to be consistent with how `*Collector` tasks work and can be explained by the default value of `outputDirectory`. 

Collector tasks exist only for parent projects (important), and they call non-collector tasks of the same format for all subprojects. So your parent project has a `gfmCollector` task, and when you execute it it will call `gfm` tasks for subprojects, and collect their output (thus `*Collector` name).

Default value of Dokka's `outputDirectory` can be configured for each project (including subprojects) individually. Default value is the following:

```
$buildDir/dokka/${taskName.removePrefix("dokka").decapitalize()}
```

So for `dokkaGfmCollector` task the default output directory is `dokka/gfmCollector`. For `dokkaGfm` it's just `gfm`.

If you want to have the same output directory for both collector and non-collector tasks, you can override (set) the default value of `outputDirectory` for Dokka tasks. 

I do agree that it can be confusing though, thanks for bringing that up.

I'll close the issue as won't fix as, unfortunately, too many people depend on default behaviour and there's very little we can do about it at this point. We'll keep this usability quirk in mind when designing new API for when Dokka is integrated into the Kotlin Gradle plugin though.

___

As a side note, can you share your use case for using `dokkaGfmCollector` task? Why not `dokkaGfmMultiModule`?
