### ISSUE TITLE
`gradle build` fails with FileNotFoundException

### ISSUE THREAD

**Issue by eriwen** [Kotlin/dokka#235]
The development instructions on the README state that one should be able to run `./gradlew build` from the root, however, this fails with a `FileNotFoundException`. 

## Context
See exception details and environment here: https://gradle.com/s/r4yohoh5fd2yg

## Reproduction Steps
```
git clone https://github.com/Kotlin/dokka.git
cd dokka
./gradlew build
```

## Possible Fix
The `generatePom` task requires the `$buildDir` to exist, but it doesn't yet. I'm going to submit a PR that declares the task outputs in such a way that it is guaranteed to exist without affecting other behavior.

**Comment by semoro** [comment]
Fixed in [0.9.16](https://github.com/Kotlin/dokka/releases/tag/0.9.16)
