### ISSUE TITLE
Empty parentheses in signatures are redundant for enum entries

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#2355]
Also, parentheses are absent for enum constructor in a description: http://dokka-snapshots.s3.eu-central-1.amazonaws.com/master/stdlib/c44bf54/kotlin-stdlib/kotlin.native.concurrent/-future-state/index.html

**Comment by IgnatBeresnev** [comment]
> Also, parentheses are absent for enum constructor in a decroption

Not sure what you mean, can you give some details or maybe an example? Current link is https://dokka-snapshots.s3.eu-central-1.amazonaws.com/2466-enum-entry-ordering/stdlib/6dcdfee/kotlin-stdlib/kotlin.native.concurrent/-future-state/index.html

I don't see anything wrong on that page

**Comment by vmishenev** [comment]
Th signature of enum constructor is `enum class FutureState(val value: Int)`
https://github.com/JetBrains/kotlin/blob/6a670dc5f38fc73eb01d754d8f7c158ae0176ceb/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Future.kt#L13 but Dokka renders `enum class FutureState`
It leads to magic arguments in the entries, e.g.  `INVALID(0)`
