### ISSUE TITLE
Handle <var> tag

### ISSUE THREAD

**Issue by owengray-google** [Kotlin/dokka#2358]
**Describe the bug**
On [input like](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/FragmentTransaction.java;l=655)
```
     * Used with custom Transitions to map a View from a removed or hidden
     * Fragment to a View from a shown or added Fragment.
     * <var>sharedElement</var> must have a unique transitionName in the View hierarchy.
```
The `<var>` section is rendered as a `Text DocTag`.

**Expected behaviour**
The `<var>` section should be rendered as [a Var DocTag](https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/model/doc/DocTag.kt#L357).  

**Screenshots**
<img width="1212" alt="Screen Shot 2022-02-11 at 2 16 42 PM" src="https://user-images.githubusercontent.com/56644404/153656385-2ca4a27f-0636-4623-a4ea-fa8098fba77e.png">

**Dokka configuration**
Configuration of dokka used to reproduce the bug
`1.6.10-dev-141`

**Comment by IgnatBeresnev** [comment]
JFYI: this should be fairly easy to fix, #2345 is a good example
