### ISSUE TITLE
No Dokka generated for Classes with no package.

### ISSUE THREAD

**Issue by JWT007** [Kotlin/dokka#237]
If I create a simple class at the root of my source tree, it is ignored by Dokka.

If I move this class to package "a" it is then processed.

(I know this is bad practice - just was testing something for another issue and noticed this)

NOTE: dokka-maven-plugin 0.9.15

**Comment by semoro** [comment]
Already reported as #166 🙂

**Comment by JWT007** [comment]
Thanks. I searched but missed it I guess.
