### ISSUE TITLE
Dokka (KDoc) link to method parameter not working

### ISSUE THREAD

**Issue by JWT007** [Kotlin/dokka#238]
I created a simple class for testing with KDoc markup to link to a method parameter:

```
package a

class Foo {
  /**
   * Just a [Foo] method to say hello to [name].
   * @param name the name
   */
  fun sayHello(name: String) {
    println("Hello there $name!")
  }
}
```

When running this with the dokka-maven-plugin 0.9.15 I see this in my output:

[WARNING] Can't find node by signature a.Foo$sayHello(kotlin.String)/name
[WARNING] Can't find node by signature a.Foo$sayHello(kotlin.String)/name

In the generated documentation there is no parameter link.

According to the documentation this should be possible (https://kotlinlang.org/docs/reference/kotlin-doc.html#linking-to-elements).

**Comment by semoro** [comment]
Which output format are you using?

**Comment by JWT007** [comment]
currently I am generating both dokka and javadoc

```
<executions>
  <execution>
    <phase>pre-site</phase>
    <goals>
      <goal>dokka</goal>
      <goal>javadoc</goal>
    </goals>
  </execution>
</executions>
```
I haven't explicitly configured the outputFormat so I assume it is using the 'html' default.

**Comment by semoro** [comment]
Please, try with https://jitpack.io/#kotlin/dokka/9c1d23b8bf

**Comment by semoro** [comment]
OK. Reproduced, specific for `asJava` mode (`javadoc` format)

**Comment by JWT007** [comment]
:) I tried to use your jitpack build ... but there is no POM at https://jitpack.io/com/github/kotlin/dokka/9c1d23b8bf

Build failed. See the log at jitpack.io

**Comment by semoro** [comment]
Yes, I know, that's why I crossed out my message. 🙂

**Comment by Xerus2000** [comment]
Hello, will you ever fix this?

**Comment by xerus2000** [comment]
Please, finally fix this!

**Comment by Noctiflore** [comment]
This would be really useful, as this usage is recommended in [official coding conventions](
https://kotlinlang.org/docs/reference/coding-conventions.html#documentation-comments) and, as @JWT007 already said, in KDoc documentation.

**Comment by kamildoleglo** [comment]
Fixed a long time ago, fix confirmed on `1.4.20`

**Comment by Noctiflore** [comment]
Just tested on 1.4.20, not working here.

**Comment by kamildoleglo** [comment]
Strange, I must have tested the wrong thing then. Anyway, fixed by https://github.com/Kotlin/dokka/pull/1713
