### ISSUE TITLE
djsaj

### ISSUE THREAD

**Issue by Abrdjalw** [Kotlin/dokka#2383]
**Is your feature request related to a problem? Please describe**
You can also paste a link to the relevant issue

**Describe the solution you'd like**
A clear and concise description of what you want to happen

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered

**Additional context**
Add any other context or screenshots about the feature request here

**Are you willing to provide a PR?**
Providing a PR can drastically speed up the process of introducing this feature.

**Comment by IgnatBeresnev** [comment]
Hi :) It seems like this was created accidentally. If you want to create an issue we can work on / discuss, please pay attention to submitted info, thanks
