### ISSUE TITLE
Support Mermaid diagrams

### ISSUE THREAD

**Issue by rocketraman** [Kotlin/dokka#2384]
**Is your feature request related to a problem? Please describe**
Need to add inline diagrams to Kotlin documentation. The diagram "source" is managed directly within the documentation string, so it is versioned and maintained together with the code rather than as an external resource.

**Describe the solution you'd like**
A great way to include diagrams inline in documentation, and have them be versioned along with the codebase, is to use the [mermaid](https://mermaid-js.github.io/mermaid/#/) ASCII syntax for various diagram types.

If dokka supported mermaid diagrams, perhaps as a plugin, it would solve the problem of including inline diagrams in documentation.

**Describe alternatives you've considered**
Alternative is to store the mermaid sources elsewhere in the source tree, and then modify the build tooling to generate the corresponding bitmaps, and then link to those bitmaps in the documentation string. This is certainly possible, but requires a lot of extra ceremony and thinking about diagram naming conventions and so forth.

**Additional context**
Discussed in Slack here: https://kotlinlang.slack.com/archives/C0F4UNJET/p1645179899461169
Supported now by GitHub: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Are you willing to provide a PR?**
Unfortunately, no.

**Comment by rocketraman** [comment]
FYI community plugin released: https://github.com/glureau/dokka-mermaid.

**Comment by IgnatBeresnev** [comment]
The author of the mentioned [Dokka Mermaid plugin](https://github.com/glureau/dokka-mermaid) is an active community member, so hopefully the plugin will be supported for years to come. I would advise using it if you need support for Mermaid diagrams.

At the moment there's little reason for Dokka to provide it out of the box, so I'm closing the issue for now, with possibility of being re-opened if anything changes.
