### ISSUE TITLE
Can I use Dokka in a Java project

### ISSUE THREAD

**Issue by ivangarzab** [Kotlin/dokka#2390]
**Question**
Can I use this lib in a Java-only Android project?  The ideal would be to _not_ integrate Kotlin into my project!

**Additional context**
Apologies if this question is a dupe :) perhaps adding something to the FAQs would be convenient for this topic.

**Comment by IgnatBeresnev** [comment]
Hi! 

You can certainly try :) Dokka has support for mixed projects (kotlin+java), but Java support isn't polished and you might encounter bugs (feel free to submit issues btw).

You'd also probably need to add dokka's `kotlin-as-java` plugin to see signatures in Java instead of Kotlin.

**Comment by IgnatBeresnev** [comment]
Hopefully I answered your question, let us know if you have any more, we'd be happy to help :)
