### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by Jakeeyturner** [Kotlin/dokka#2394]
**Question**
Hi there,

I'm just wondering if there's a release schedule for dokka and when the next release might be?

Thank you!

**Comment by IgnatBeresnev** [comment]
Hi! 

Dokka generally tries to follow Kotlin's release schedule, so you can expect a new version of dokka to be released some time after Kotlin. The timeframe depends on testing and the amount of bugs we find.

We're working on a release candidate now (it's out for Kotlin), it's a bit overdue

Hopefully I answered your question, let us know if you have any more :)
