### ISSUE TITLE
Can classes or methods be dropped from documentation based on annotation

### ISSUE THREAD

**Issue by tripolkaandrey** [Kotlin/dokka#2404]
**Question**
We are developing a framework in Java and want to use Dokka for generating documentation instead of Javadoc. In the codebase, there are things that should not appear in documentation as they are only for internal usage. We enforced this by using Doclet API and special annotation `@Internal` which could be applied to methods, classes and etc. Is there a way to enforce described behaviour using Dokka?

**Comment by tripolkaandrey** [comment]
@IgnatBeresnev Thank you for your previous answer. I have followed the resources you supplied and run into an issue. My plugin is not picked by ServiceLoader. I have checked it by debugging code and manually looking through plugins picked up by DokkaContext. I am developing a pre-compiled script in buildSrc of a standalone config repository that is used across many projects in my organisation. Here is [the link](https://github.com/SpineEventEngine/config/pull/337/files) to the PR where I am configuring Dokka.

**Comment by IgnatBeresnev** [comment]
Just wanted to share a good example of such a plugin implemented [in aws-sdk-kotlin project](https://github.com/awslabs/aws-sdk-kotlin/blob/078b70a6f4e041b442b32f1ea089a418a2b19d3b/dokka-aws/src/main/kotlin/aws/sdk/kotlin/dokka/transformers/FilterInternalApis.kt).

Instead of looking for the documentation tag, it looks for the annotation just like you wanted to:
```kotlin
val <T> T.internalAnnotation where T : WithExtraProperties<out Documentable>
    get() = extra[Annotations]?.let { annotations ->
        annotations.directAnnotations.values.flatten().firstOrNull {
            it.dri.toString() == "aws.sdk.kotlin.runtime/InternalSdkApi///PointingToDeclaration/"
        }
    }
```

**Comment by tripolkaandrey** [comment]
Thank you for your response. 
I have used your first answer to find the solution on my own. If anybody else wants to implement excluding by annotation, you can check it out [here](https://github.com/SpineEventEngine/dokka-tools/tree/master/dokka-extensions).
