### ISSUE TITLE
How to render constants values in KMM project?

### ISSUE THREAD

**Issue by yuanguozheng** [Kotlin/dokka#2408]
How to render constants values in KMM project?
I found a pull request(https://github.com/Kotlin/dokka/pull/1489) that dokka can render constant's value.
But when I use dokka in KMM project, the value of the constant is not rendered.
Anythings else to config in build.gradle.kts?

My config:
```kotlin
tasks.withType<DokkaTask>().configureEach {
    offlineMode.set(true)
    dokkaSourceSets {
        registering {
            this.jdkVersion.set(8)
            noJdkLink.set(true)
            noAndroidSdkLink.set(true)
            noStdlibLink.set(true)
            this.sourceRoots.from(file("src/commonMain/kotlin"))
        }
    }
}
```

**Comment by vmishenev** [comment]
This should be enough.
Can you provide a code snippet with the constant to reproduce?

**Comment by yuanguozheng** [comment]
@vmishenev Any suggestions?

**Comment by IgnatBeresnev** [comment]
Hi! Judging by the PR name (`Add default values for primitive properties`), it only adds displays values for primitive constants. So I think it doesn't work for Strings.

If you change String to any primitive type, it'll be displayed as expected:
![2022-04-01_14-28-00](https://user-images.githubusercontent.com/22685910/161254687-55e63fab-0985-407b-a5f1-ffd97f37209a.png)

**Comment by yuanguozheng** [comment]
@IgnatBeresnev Thanks. Hope this feature will be available soon!

**Comment by IgnatBeresnev** [comment]
Indeed, it has many likes, so chances are good :)

I'll close the issue for now. Let us know if there's any more questions
