### ISSUE TITLE
Missing space between link and bold

### ISSUE THREAD

**Issue by Arthur-Milchior** [Kotlin/dokka#2446]
**Describe the bug**

As an example, look at the source https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/operators/Share.kt#L390 and more specifically the line:
>  Returns a flow that invokes the given [action] **after** this shared flow starts to be collected

**Screenshots**

On https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/index.html you'll get the sentence

> Returns a flow that invokes the given actionafter this shared flow starts to be collected (after the subscription is registered).

![2022-04-18-123230_601x142_scrot](https://user-images.githubusercontent.com/357361/163796263-79726455-439a-47cb-ac76-ecee8196bb93.png)

**Expected behaviour**

There should be a space between "action" and "after". (I checked, this line was last modified two years ago, so it's not just that some recent change did not propagate to the documentation website)

**Dokka configuration**

No idea. It's the one used by the official kotlin documentation website

**Are you willing to provide a PR?**

Probably not. No idea where to start looking

**Comment by IgnatBeresnev** [comment]
Thank you for reporting it, surprised we haven't noticed it earlier and don't have test to check this particular case :)

I've been able to reproduce it with a simple example
```
/**
 * A _simple_ [List] example
 */
class Example {}
```

It seems like the space gets lost if there's a link after some text formatting (bold/italic/etc).

**Comment by Arthur-Milchior** [comment]
You are welcome. Glad it was easy to reproduce, hopefully it'll make debugging easier.
Good luck with that

**Comment by IgnatBeresnev** [comment]
I've had some time to debug it, thinking it was an easy for somewhere in the HTML renderer. Unfortunatley, this looks a bit scary to fix now for 1.6.21 as it might introduce more bugs, so we'll get back to it later.

I'll post some technical details down below to help fixing this in the future.

Take the following kdoc as an example:
```kotlin
/**
 * A _simple_ [List] example
 */
```

It breaks down into
```kotlin
[0] = LeafAstNode TEXT, "A"
[1] = LeafAstNode WHITE_SPACE, " "
[2] = CompositeAstNode EMPH, "_simple_" -- later "simple" is turned into text and _ symbols are substituted for style
[3] = LeafAstNode WHITE_SPACE, " "
[4] = CompositeAstNode SHORT_REFERENCE_LINK, with 3 children: [, List, ]
```

What happens is [MarkdownParser#mergedLeafNode](https://github.com/Kotlin/dokka/blob/ec2bf8a57c744008c30d03c4aec0921a091faa81/plugins/base/src/main/kotlin/parsers/MarkdownParser.kt#L467) tries to merge consecutive leaf nodes into a single leaf node, which is supposed to turn

```kotlin
[0] = LeafAstNode TEXT, "A"
[1] = LeafAstNode WHITE_SPACE, " "
```
into a single
```kotlin
[0] = LeafAstNode TEXT, "A " (notice the whitespace at the end)
```

It does so only for **consecutive** leaf nodes, so `[Composite, Leaf, Leaf, Composite]` turns into `[Composite, Leaf, Composite]`. However, if all the leaf nodes between the consecutive ones are evaluated to empty text, there's an `if` that just ignores it: 
```kotlin
if (text.substring(startOffset, endOffset).transform().trim().isNotEmpty()) {
    ... merging logic ...
}
return null
```

^ This is the first place to fix. I've removed this `if` to see what happens -- tests pass, but the problem doesn't go away.

Even if we leave this single white space leaf node be (that is not remove it), there's another place that removes elements with single whitespaces down the road: [DocTagsFromIElementFactory#getInstance](https://github.com/Kotlin/dokka/blob/cc6b2991df60f43607c8271d9657be89b3463a69/plugins/base/src/main/kotlin/parsers/factories/DocTagsFromIElementFactory.kt#L43), which calls `parseWithNormalisedSpaces`, which in turn calls [parseWithNormalisedSpaces](https://github.com/Kotlin/dokka/blob/cc6b2991df60f43607c8271d9657be89b3463a69/plugins/base/src/main/kotlin/translators/parseWithNormalisedSpaces.kt). That's the second place where whitespaces get lost.

I haven't dug into it further, but there may be more problems related to this.

**Comment by atyrin** [comment]
Also relevant issue: #1975

**Comment by IgnatBeresnev** [comment]
Let's close this as a duplicate in favour of #1975 - it has more info on reproducing it.

Once again thanks for the report!
