### ISSUE TITLE
Make text gray for inactive tabs

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#2447]
![image](https://user-images.githubusercontent.com/9636937/163843900-f84067e7-7029-4bdd-baae-63b424f71765.png)
**VS**
![image](https://user-images.githubusercontent.com/9636937/163844236-0fc176cd-6fff-423e-81a2-73a2fde87112.png)

**Comment by IgnatBeresnev** [comment]
Closing as not relevant anymore as it was redesigned in #2576
