### ISSUE TITLE
Support MathJax 

### ISSUE THREAD

**Issue by thomasnield** [Kotlin/dokka#245]
It would be helpful if there was support for [MathJax](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference). 

This would be enormously helpful for data science library documentation, and expressing mathematical equations over pieces of code. I know @kyonifer did a hack in [Koma](https://github.com/kyonifer/koma) using [MkDocs](http://www.mkdocs.org/) but it is not streamlined, and relies on pip and Python builds.

**Comment by Kordyjan** [comment]
MathJax support is an example plugin that is distributed with dokka.
