### ISSUE TITLE
Documentation on mouse hover

### ISSUE THREAD

**Issue by ThomasCZ** [Kotlin/dokka#2459]
I am creating library that will be published on maven, but I am not able to see any code documentation in project that is using the library. I tried publish result of `dokkaJavadoc` and `dokkaHtml` from [your example](https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-library-publishing-example/build.gradle.kts), documentation is available on maven, but not visible on mouse hover. It works only when I publish my source code, but I do not want to do that. It is library for Android and I am using Android Studio 2021.1.1 Patch 3. Could you please help me how can I create documentation that will be visible on mouse hover? Thanks

This is what I want. I my case, documentation is missing.

![wanted](https://user-images.githubusercontent.com/7516715/164627980-fffb947c-f31e-4a3a-bb9c-50853591f70b.png)

**Comment by IgnatBeresnev** [comment]
Hi! Yes, unfortunately, this is a known issue: https://github.com/Kotlin/dokka/issues/2033

At the moment we're focusing on the primary html format for web browsers and on making it stable. After that, we'll work on `javadoc` format and hopefully this issue will be resolved.

**Comment by IgnatBeresnev** [comment]
I'll close this for now to avoid duplicate issues, but let us know if you have any more questions :)
