### ISSUE TITLE
Release timeline for update of kotlin 1.6.21

### ISSUE THREAD

**Issue by rishavjayswal** [Kotlin/dokka#2462]
**Question**
We wish to upgrade to Springboot 2.6.7 which uses Kotlin 1.6.7. Can you please tell us the timeline for your relase for the same Kotlin version?

https://docs.spring.io/spring-boot/docs/2.6.7/reference/html/dependency-versions.html#appendix.dependency-versions

**Comment by IgnatBeresnev** [comment]
Dokka `1.6.21` is scheduled to be released on Monday, it's being tested now.

Generally, we try to follow Kotlin's release schedule closely, but some delay is expected to give us time to test compatibility and the release itself. Still, best case scenario is a from a few days to a week, depending on the release :)

> We wish to upgrade to Springboot 2.6.7 which uses Kotlin 1.6.21

I believe you can upgrade to Kotlin `1.6.21` (and thus Spring boot `2.6.7`) already, it should work with dokka `1.6.20` just fine. And then upgrade dokka only when `1.6.21` is released
