### ISSUE TITLE
Is it possible to silence logging?

### ISSUE THREAD

**Issue by tripolkaandrey** [Kotlin/dokka#2495]
**Question**
Dokka logs a lot of information at the `INFO` level. Is it possible to silence all this output?

**Screenshots**
Output after running `dokkaHtml`:
<img width="404" alt="dokkaHtml logs" src="https://user-images.githubusercontent.com/54888768/167609699-31f1c261-b5ba-48f7-8cd5-f3edd705463e.png">

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.4.2
- Dokka version: 1.6.20

**Comment by IgnatBeresnev** [comment]
Hi! Unfortunately, at the moment it's not possible for gradle/maven runners, only the CLI runner has that option, but I don't expect you to use it.

There are several similar requests (#2169, #1894, #1690), so Dokka logging definitely needs to be revisited, we'll keep it in mind.
