### ISSUE TITLE
Not able to create documentation for private field and functions

### ISSUE THREAD

**Issue by pr-gupta** [Kotlin/dokka#250]
I want to include documentation for private fields as well. On using `includeNonPublic = false`, gradle throws an error as 
`Error:(50, 0) Could not set unknown property 'includeNonPublic' for task ':dokka' of type org.jetbrains.dokka.gradle.DokkaTask.`

```
dokka {
    outputFormat = 'html'
    outputDirectory = "$buildDir/javadoc"

    // These tasks will be used to determine source directories and classpath
    kotlinTasks {
        defaultKotlinTasks() + [':moduleName:compileKotlin']
    }
    includeNonPublic = true
}

```

**Comment by semoro** [comment]
It's bug in docs
Please, try `0.9.16-eap-1` from https://bintray.com/kotlin/kotlin-eap/dokka

**Comment by semoro** [comment]
Is issue resolved at this time?

**Comment by que1roz** [comment]
I'm using version 0.9.17 and can confirm that private properties and functions are not being generated!
