### ISSUE TITLE
Suboptimal (non-incremental) input properties for gradle tasks

### ISSUE THREAD

**Issue by ramonwirsch** [Kotlin/dokka#251]
The Gradle Dokka Task includes `kotlinCompileBasedClasspathAndSourceRoots` as inputProperty that includes the full names of all dependencies of the libraries (Jars, classes). This means that if only the name of a Jar changes (because a CI-Server increases the build number), all Dokka Outputs are invalidated and generated anew.

The Java Javadoc Task solves this by not declaring the classpath as custom object as input, but a fileCollection, which can be configured to only check the file contents and ignore path and filename changes. 

If I find time I will start working on a pull request to fix this.

**Comment by semoro** [comment]
Looks like that should be fixed by a10c1f852813ea1c0e4f15b3c25a7a5388bbc996
