### ISSUE TITLE
Some questions and problems

### ISSUE THREAD

**Issue by mahozad** [Kotlin/dokka#2513]
**Question**
I have a few questions.

- How can I replace `andoridJvm source` string with something like `GitHub` in sources tab of the documentation?
![Screenshot (36)](https://user-images.githubusercontent.com/29678011/170513484-9722961f-b1a6-4668-8fb4-ff366d279170.png)

- How can I set a custom favicon (which may be different from the logo in the page header) for the document?
My current  solution is to name an image file `logo-icon.svg` and add it as an asset in the Dokka settings. But I want to name the image file something else like `favicon.svg` and also want to be able to use other formats like PNG as well.

- Do you think it would be better for the methods in Dokka Gradle plugin to be converted to properties and also avoid [double negative names](https://refactoring.com/catalog/removeDoubleNegative.html)?
So, for example, `noAndroidSdkLink.set(false)` be renamed to something like `useAndroidSdkLink = true` or `isAndroidSdkLinkEnabled = true` or `enableAndroidSdkLink = true` or similar.

- I really liked the previous theme of Dokka HTML. Can I somehow enable it for my docs?

-  Updating the files defined as custom assets or styles is not reflected in the output when I re-run the dokkaHtml task. So, I had to run Gradle clean and then run dokkaHtml again.

- Configuring the plugin options is not easy. On Windows it is even harder because the paths should either be normalized or escaped:

  ```kotlin
  pluginsMapConfiguration.set(
      mapOf("org.jetbrains.dokka.base.DokkaBase" to
                  """{ 
                         "customStyleSheets": ["${file("dokka/logo-styles.css").path.replace('\\','/')}"],
                         "customAssets" : [
                             "${file("dokka/logo.svg").path.replace('\\', '/')}",
                             "${file("dokka/logo-icon.svg").path.replace('\\', '/')}"
                         ],
                         "separateInheritedMembers": true
                  }"""
      )
  )
  ```

  Is there any better way to do this?

- Another problem:
![Screenshot (37)](https://user-images.githubusercontent.com/29678011/170542564-cd8014c6-a6c8-4df8-a469-0e17070183c8.png)

**Installation**
- Operating system: Windows 11
- Build tool: Gradle v7.0.2
- Dokka version: 1.6.21

**Comment by mahozad** [comment]
Thank you very much. Your solutions worked.

So, for the favicon, if you'd like, maybe I can implement it. I'd be glad to help if I can.

**Comment by IgnatBeresnev** [comment]
Thanks for creating separate issues, I appreciate it!

I'll close this one and give my comments in the corresponding issue
