### ISSUE TITLE
Applying Kotlin to java plugin only in java files

### ISSUE THREAD

**Issue by Wyvest** [Kotlin/dokka#2514]
**Question**
Is it possible to only apply the kotlin-to-java plugin only when processing java class files?

Currently, my Dokka setup is this:
```
plugins {
    kotlin("jvm") version "1.6.20"
    id("org.jetbrains.dokka") version "1.6.20"
    java
}
dependencies {
    ...
    dokkaHtmlPlugin("org.jetbrains.dokka:kotlin-as-java-plugin:1.6.20")
}
 tasks.dokkaHtml.configure {
        outputDirectory.set(buildDir.resolve("dokka"))
        dokkaSourceSets {
            configureEach {
                jdkVersion.set(8)
                //reportUndocumented.set(true)
            }
        }
    }
```

I would like to show Kotlin files in Kotlin and Java files as Java.

**Installation**
- Operating system: macOS
- Build tool: Gradle 7.4
- Dokka version: 1.4.30

**Additional context**
n/a

**Comment by IgnatBeresnev** [comment]
Hi! If you have mixed kotlin/java classes within the same module, I don't think it's possible at the moment out of the box.

It might be possible with a custom Dokka plugin - I can give you more specific directions if you want to implement something like this.

If you, however, have separate Kotlin-only and Java-only modules, you could apply `kotlin-as-java` plugin conditionally - apply `kotlin-as-java` plugin only to pure-java modules. You can automate it, just look if `kotlin` plugin is applied in gradle configuration. [PluginManager](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.PluginManager.html) has some good utility methods for this
