### ISSUE TITLE
 Could not create domain object 'androidTestRelease' (GradleDokkaSourceSetBuilder)

### ISSUE THREAD

**Issue by tprochazka** [Kotlin/dokka#2518]
Dokka 1.6.10 was working correctly, but when I update to 1.6.20 or 1.6.21 I'm getting just this:

```
* What went wrong:
Execution failed for task ':sample-android-library:dokkaJavadoc'.
> Error while evaluating property 'unsuppressedSourceSets' of task ':sample-android-library:dokkaJavadoc'       
   > Could not create domain object 'androidTestRelease' (GradleDokkaSourceSetBuilder)

```

I have no custom setup, I just apply Dokka plugin to my project.

I even did not found something like "unsuppressedSourceSets" in GradleDokkaSourceSetBuilder

**Comment by tprochazka** [comment]
It will be probably just duplicate of this issue
https://github.com/Kotlin/dokka/issues/2452

**Comment by IgnatBeresnev** [comment]
Thanks for sharing your fix :)
