### ISSUE TITLE
Absent class annotations with @MustBeDocumented

### ISSUE THREAD

**Issue by vsukharev** [Kotlin/dokka#2527]
Shouldn't MustBeDocumented annotations be displayed for the classes? 
The example below shows annotations for methods and parameters, but not for the class (this is kinda unexpected)
```
@MustBeDocumented
annotation class Baz

@Baz
class App2 {
    @Baz
    fun withParams(@Baz str1: String, str2: String): Boolean {
        return str1 == str2
    }
}
```
output HTML:

<img width="561" alt="Screenshot 2022-06-10 at 00 01 30" src="https://user-images.githubusercontent.com/5513072/172952899-0498a209-d95d-4784-8ff1-3655b012bf2c.png">

**Comment by IgnatBeresnev** [comment]
Hi! Thanks for the report, it was simply forgotten :) 

The fix was a rather trivial one-liner. Added some tests to make sure it doesn't happen again
