### ISSUE TITLE
Include md.page not working

### ISSUE THREAD

**Issue by paragones** [Kotlin/dokka#257]
I have tried to add a module.md on my project but unfortunately it is not being added the generated documentation: I just copied an example from the [dokka-gradle-example](https://github.com/JetBrains/kotlin-examples/tree/master/maven/dokka-maven-example). 

Here's my code:

my top Build file:

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        ext.kotlin_version = '1.2.0'
        ext.dokka_version = '0.9.15'
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.0.1'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath "org.jetbrains.dokka:dokka-gradle-plugin:${dokka_version}"
    
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }

My project build file:

    apply plugin: 'com.android.application'
    
    apply plugin: 'kotlin-android'
    
    apply plugin: 'kotlin-android-extensions'
    
    apply plugin: 'org.jetbrains.dokka'
    
    android {
        compileSdkVersion 26
        defaultConfig {
            applicationId "com.example.hellodokka"
            minSdkVersion 18
            targetSdkVersion 26
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }
    
    dokka {
        outputFormat = 'html'
        outputDirectory = "$buildDir/html"

        includes = ['Module.md']
    }
    
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
        implementation 'com.android.support:appcompat-v7:26.1.0'
        implementation 'com.android.support.constraint:constraint-layout:1.0.2'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.1'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    }

**Comment by semoro** [comment]
Please, make sure that your Module.md located in the same directory as build.gradle & that it named exactly as in includes

**Comment by semoro** [comment]
Is issue resolved?

**Comment by paragones** [comment]
Yes, thank you!

**Comment by arvkmr** [comment]
I am facing the same problem and there is nothing in the logs to know if my module.md file is being detected or not. I am fairly certain I have it in correct place but I still don't see it being included. I am on 0.10.1 any ways to debug the problem here?

**Comment by kamilok1965** [comment]
I'm not sure if there is. Can you provide your project or an MRE?

**Comment by Keith-Albright-Bose** [comment]
For anyone dealing with this... I found a work-around... use inline html in the markdown included via includes.
```<a href="url">link text</a>```
