### ISSUE TITLE
Dokka not generating anything in multi-module project

### ISSUE THREAD

**Issue by PolyRocketMatt** [Kotlin/dokka#2583]
**Describe the bug**
Following the Dokka multi-module guide (found [here](https://kotlin.github.io/dokka/1.4.32/user_guide/gradle/usage/)), Dokka generates empty directories for all my modules.

Running the dokkaHtml task for each module separately also generates empty directories.

**Expected behaviour**
Dokka should (according to the documentation) perform the dokkaHtmlPartial task in each module and link them. 

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
Steps to reproduce the behavior, ideally with an example project

**Dokka configuration**
Configuration of dokka used to reproduce the bug

Root build.gradle.kts
```Kotlin
plugins {
    id("org.jetbrains.dokka") version "1.7.10"
}

allprojects {
    buildDir = (parent?.buildDir ?: rootFolder).resolve(name)

    repositories {
        mavenCentral()
        maven { url = uri("https://papermc.io/repo/repository/maven-public/") }
    }
}

subprojects {
    apply(plugin = "org.jetbrains.dokka")
}

tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(buildDir.resolve("dokkaCustomMultiModuleOutput"))
}
```

Module build.gradle.kts
```Kotlin
plugins {
    kotlin("jvm") version "1.6.10"
    id("org.jetbrains.dokka") version "1.7.10"
}

tasks.dokkaHtmlPartial.configure {
    failOnWarning.set(true)
}
``` 

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.4.2
- Dokka version: 1.7.10

**Additional context**
/

**Are you willing to provide a PR?**
/

**Comment by vmishenev** [comment]
I suppose 
```
subprojects {
    apply(plugin = "org.jetbrains.dokka")
}
```
is not needed in `build.gradle.kts`.

Can you check? Otherwise can you provide your project?

**Comment by PolyRocketMatt** [comment]
I cannot provide the project, but removing

```Kotlin
subprojects {
    apply(plugin = "org.jetbrains.dokka")
}
```

did not resolve the issue. The output (I didn't notice earlier) does state the following:

> Task :Service:dokkaHtmlPartial
Initializing plugins
Dokka is performing: documentation for <Module>
Validity check
Creating documentation models
Exiting Generation: Nothing to document

**Comment by IgnatBeresnev** [comment]
> Exiting Generation: Nothing to document

Your project does have some Kotlin/Java code, it's not just empty packages, right? If so, then there might be some problem with configured source sets. There's also [an example repository](https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-multimodule-example) you can have a look at, it should work.

If nothing helps, could you please create a small sample project to reproduce the problem? We might be missing some small, but important detail.

**Comment by PolyRocketMatt** [comment]
[Here](https://github.com/PolyRocketMatt/OxygenTmp) is a cloned version of the project with the actual structure of the project. The project does have code in it and sources seem to be properly set (build, etc works)

**Comment by PolyRocketMatt** [comment]
Any update on this?

**Comment by vmishenev** [comment]
Thank you for the sample.
You need to add Kotlin Gradle Plugin into a root project. Dokka uses the plugin to extract information about source sets.

**Comment by YSakhno** [comment]
> You need to add Kotlin Gradle Plugin into a root project. Dokka uses the plugin to extract information about source sets.

Can this be added to the documentation? Currently the [Multi-project configuration](https://kotlinlang.org/docs/dokka-gradle.html#multi-project-configuration) section specifically has code snippets **without** the Kotlin plugin applied _anywhere_ (be it in the root- or sub-projects).

Without this specific requirement, the reason to have Kotlin plugin in the root project (if the root project does not contain source code) is not so apparent.
