### ISSUE TITLE
How do I select a Java file？

### ISSUE THREAD

**Issue by 2017398956** [Kotlin/dokka#2590]
**Question**
when I  select a kotlin file ,like this:
     sourceRoots.setFrom(file("./xxx/xxx.kt"))
it works well.
But when i select a java file :
    sourceRoots.setFrom(file("./xxx/xxxx.java"))
it not woking .

Task:dokkaHtml

**Installation**
- Operating system: macOS 12.4
- Build tool: Gradle v7.3.3
- Dokka version: 1.7.10
- IDE:Android Studio Chipmunk | 2021.2.1 Patch 1

**Comment by IgnatBeresnev** [comment]
Hi! Not sure why the behaviour is different for kotlin and java files.

Out of curiosity, is there any specific reason you need to select only one file? 

It works if you specify the folder path, like 
```kotlin
sourceRoots.setFrom(file("./xxx/xxx"))
```

**Comment by 2017398956** [comment]
> Hi! Not sure why the behaviour is different for kotlin and java files.
> 
> Out of curiosity, is there any specific reason you need to select only one file?
> 
> Pretty sure it works if you specify the folder path, like
> 
> ```kotlin
> sourceRoots.setFrom(file("./xxx/xxx"))
> ```

Yes, a java folder path is ok but  I only need partly java files of some folders , if using the whole folder is too many classes to my users.

**Comment by daymxn** [comment]
> 

FWIW, you can also utilize `perPackageOption.matchingRegex` to filter files, which could be useful if you're needing a portion of files in a directory. Although, if you only need one or two files- it would definitely be overkill.

**Comment by 2017398956** [comment]
> > > Hi! Not sure why the behaviour is different for kotlin and java files.
> > > Out of curiosity, is there any specific reason you need to select only one file?
> > > Pretty sure it works if you specify the folder path, like
> > > ```kotlin
> > > sourceRoots.setFrom(file("./xxx/xxx"))
> > > ```
> > 
> > 
> > Yes, a java folder path is ok but I only need partly java files of some folders , if using the whole folder is too many classes to my users.
> 
> FWIW, you can also utilize `perPackageOption.matchingRegex` to filter files, which could be useful if you're needing a portion of files in a directory. Although, if you only need one or two files- it would definitely be overkill.

I've tried with this:

`tasks.withType(DokkaTask.class).configureEach { /*...*/
    dokkaSourceSets {
        moduleName.set("test")
        named("main"){
            sourceRoots.setFrom(file("./xxx/utils/"))
        }
        configureEach {  /* configure all source sets */
            includeNonPublic.set(false)
            skipDeprecated.set(false)
            reportUndocumented.set(true)
            skipEmptyPackages.set(true)
            noStdlibLink.set(true)
            noJdkLink.set(true)
            noAndroidSdkLink.set(true)
            perPackageOption {
                matchingRegex.set("^\\S{0,}PhoneUtil.java\$")
            }
        }
    }
}`

but it still doesn't work.

**Comment by 2017398956** [comment]
I solved the problem by modifying the source file (org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator).
Anyone who needs it can replacing the file xxxxx/.gradle/caches/modules-2/files-2.1/org.jetbrains.dokka/dokka-base/1.7.10/219488e3e446fd30b6bda2472c4b99903ecc0e73/dokka-base-1.7.10.jar by
[dokka-base-1.7.10.jar.zip](https://github.com/Kotlin/dokka/files/9250634/dokka-base-1.7.10.jar.zip)

**Comment by IgnatBeresnev** [comment]
Fixed in #2604, will be released in 1.7.20
