### ISSUE TITLE
Automatic dark mode

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/dokka#2591]
Follow up from https://github.com/Kotlin/dokka/issues/1731

The dark mode is nice 👏 . Would be nice to have an "automatic mode" that detects the current OS setting. This seems to be possible. See [this stackoverflow question](https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript) for a possible implementation.

The dark mode would be a 3 way setting:
- light
- dark
- auto

**Comment by IgnatBeresnev** [comment]
This would be nice to have! 

If anyone wishes to contribute, I believe the code for enabling dark mode is [here](https://github.com/Kotlin/dokka/blob/16552790069070c6a5435f37523173b1be6a4652/plugins/base/src/main/resources/dokka/scripts/platform-content-handler.js#L31).

> Would be nice to have an "automatic mode" that detects the current OS setting

Not sure how to add a 3rd auto option, there's a single toggle button atm. Would you expect the button to have 3 states or would you rather see it in the configuration settings? 

I think if you open up Dokka for the first time, it could choose light/dark mode based on OS theme, and then if the person decides to switch it to something else - remember that choice.

**Comment by martinbonnin** [comment]
> Not sure how to add a 3rd auto option, there's a single toggle button atm. Would you expect the button to have 3 states or would you rather see it in the configuration settings?

Not sure TBH. Apple documentations have a 3-state "chooser":

<img width="205" alt="Screenshot 2022-07-28 at 13 51 36" src="https://user-images.githubusercontent.com/3974977/181498727-a86c2e7f-482f-4605-80a3-adcc23f864f1.png">

Looks like Android documentation is light mode only. [Our own docs](https://www.apollographql.com/docs/kotlin/) do what you suggest below.


> I think if you open up Dokka for the first time, it could choose light/dark mode based on OS theme, and then if the person decides to switch it to something else - remember that choice.

Makes sense, probably the easiest way to implement it and would work in the vast majority of use cases 👍

**Comment by pt2121** [comment]
First time contributing here, I put in a PR which should do what you mentioned:
> I think if you open up Dokka for the first time, it could choose light/dark mode based on OS theme, and then if the person decides to switch it to something else - remember that choice.
Please let me know what you think.
