### ISSUE TITLE
@See or link usage

### ISSUE THREAD

**Issue by MakarenkoVlad** [Kotlin/dokka#2595]
Is there any correct way to link functions/classes in doc and then see this link in gfm markdown?

**Comment by IgnatBeresnev** [comment]
Hi! Yeah, there doesn't seem to be anything special about it. What sort of problem are you having with it?

Code:
```
/**
 * @see [IllegalArgumentException] exception
 */
class Class {}
```

Produces:

---

//[dokka-debug-kts](../../../index.md)/[me.beresnev.dokka.debug.internal](../index.md)/[Class](index.md)

# Class

[jvm]\
class [Class](index.md)

## See also

jvm

| | |
|---|---|
| [kotlin.IllegalArgumentException](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-illegal-argument-exception/index.html) | exception |

## Constructors

| | |
|---|---|
| [Class](-class.md) | [jvm]<br>fun [Class](-class.md)() |
