### ISSUE TITLE
How to include the maven module's documentation?

### ISSUE THREAD

**Issue by T-baby** [Kotlin/dokka#260]
How to include the maven module's documentation when generating the document?

**Comment by lennartj** [comment]
Duplicate of #267

**Comment by semoro** [comment]
@lennartj Not sure that it is a duplicate. 
@T-baby Please, clarify

**Comment by lennartj** [comment]
You are quite right - I am a tad unsure too. 

I just presume that what T-baby describes as "Maven Module" documentation is the Maven Site Documentation.... because I don't know what other type of documentation is generated in a standard Maven build.

**Comment by T-baby** [comment]
I'm sorry, maybe I didn't describe it very well. I would like to ask if there are a lot of subprojects in a maven project, and dokka generates a single copy of each subproject when generating the document, and I want to integrate the documents of these subprojects.

Such as:

<modules>
	<module>modules/core</module>
	<module>modules/api</module>
</modules>

<plugin>  
    <groupId>org.apache.maven.plugins</groupId>  
    <artifactId>maven-javadoc-plugin</artifactId>  
    <version>2.9.1</version>  
    <configuration>  
        <aggregate>true</aggregate>  
    </configuration>  
</plugin>

**Comment by lennartj** [comment]
Ah. You are interested in the aggregated site and Javadoc documentation corresponding to the capabilities of the maven site and javadoc plugins. Check.

Then I think this corresponds to 2 issues:

1. Make the Dokka plugin be a report plugin to fit better into the Maven site plugin structure (i.e. to make Javadoc documentation for *1* module). This would be #267 .
2. Use the Dokka plugin to generate aggregate reports / sites. This is a separate - although related - item.

Sounds like a fair description?

**Comment by T-baby** [comment]
I'll try it first. thx.
