### ISSUE TITLE
Is there a way to support in more than one language? (for multiple languages)

### ISSUE THREAD

**Issue by kjt0429** [Kotlin/dokka#2607]
**Question**
Is there a way to support in more than one language?
(like doxygen Support for multiple languages)

https://doxygen.nl/manual/langhowto.html

**Comment by IgnatBeresnev** [comment]
Hi! Unfortunately, there's no way that I know of right now. It'll be a good feature in the future, although it's not planned at the moment.

**Comment by kjt0429** [comment]
@IgnatBeresnev Thanks for your reply!
