### ISSUE TITLE
Markdown not properly applied to Java files

### ISSUE THREAD

**Issue by kjt0429** [Kotlin/dokka#2615]
**Describe the bug**
Markdown not properly applied to Java files

**Expected behaviour**
Markdown properly applied to Java files

**Screenshots**

**To Reproduce**
Steps to reproduce the behavior, ideally with an example project

```
// temp.java

/**
 * Title A~~<br> 
 * Title B~~
 *
 * Body description~
 */
class A
{
  ...
}
```

I expected like below.

Title A~~
Title B~~

but showing

Title A~~ Title B~~

Even looking at the html file, it was checked that the br-tag disappeared. It only happens in .java files.

**Dokka configuration**
- default

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.6.0
- Dokka version: 1.7.10

**Additional context**
Add any other context about the problem here

**Are you willing to provide a PR?**
Providing a PR can drastically speed up the process of fixing this bug

**Comment by IgnatBeresnev** [comment]
Hi! Java's Javadoc format does not support Markdown, it only supports HTML-like tags, so this is the intended behaviour

[This page](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#sourcefiles) has a lot of examples of what's possible with Javadoc. 

In your particular case, this should work:
```java
/**
 * Title A~~
 * <p>
 * Title B~~
 */
```

Also worth noting that Javadoc support is not ideal at the moment, and not all tags may work.

**Comment by IgnatBeresnev** [comment]
JFYI: `<br>` should probably be supported as an html tag, it's mentioned in https://github.com/Kotlin/dokka/issues/2262 already

Closing this issue since `<br>` is not related to the description about markdown support.
