### ISSUE TITLE
Missing indent when rendering HTML webpage with bold text

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/dokka#2623]
Originally, the bug is reported here: https://github.com/Kotlin/kotlinx.coroutines/issues/3404

The indent itself is present in the site's HTML but is not properly rendered, probably due to CSS-styles.
Dokka version is 1.6.21, Kotlin 1.7.10.

I've passed through the original bug-reporting template, so feel free to ask me any additional questions about the setup

**Comment by IgnatBeresnev** [comment]
I'll close this as a duplicate in favour of https://github.com/Kotlin/dokka/issues/1975, which has more cases

Long story short, it's a case of "optimization gone wrong" when parsing and merging markdown leaf nodes (some investigation https://github.com/Kotlin/dokka/issues/2446#issuecomment-1101476609), and fixing it is like playing Jenga - I tried and it all fell apart.

So unfortunately no quick and easy fix, but it's in our backlog
