### ISSUE TITLE
KDocs + Dokka Inline Markdown code blocks not working

### ISSUE THREAD

**Issue by rattanshiv12** [Kotlin/dokka#2624]
**Describe the bug**
I am trying to create code blocks with KDocs inline markdown in a few Kotlin classes, but it doesn't seem to be working as expected. I have tried wrapping the code in 3 back-ticks, which doesn't create a code block at all. I have also tried indenting the code with 4 spaces, which seems to add non-code lines into the code block. Lastly I have tried doing both (wrapping in back-ticks and also indenting the code lines) which creates the code block but for some reason appends a backslash to the end of each line.

**Expected behaviour**
Markdown syntax should accept all 3 of the above syntaxes as code block, and it should not be appending a backslash at the end of each line in the code block.

**Screenshots**
Wrapping in backticks and indenting:
<img width="819" alt="Screen Shot 2022-08-12 at 11 20 35 AM" src="https://user-images.githubusercontent.com/36639521/184386908-79b99188-61e1-4c7b-99e0-03cdecc35e74.png">

**To Reproduce**
You can use the test script in this PR: https://github.com/square/okhttp/pull/7414 to generate the docs locally.

This is one of the Kotlin files which has this issue: https://github.com/yschimke/okhttp/blob/docs_test/okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v7.5.1
- Dokka version: 1.6.21

**Comment by IgnatBeresnev** [comment]
Proper support of code blocks in gfm format was implemented in 1.7.0, so please update to the latest version and see if your problem is gone. It should automatically add the backticks and not have any trailing slashes

**Comment by rattanshiv12** [comment]
@IgnatBeresnev Yes, I updated to 1.7.10 and the issue is resolved. Thank you!
