### ISSUE TITLE
path is not work

### ISSUE THREAD

**Issue by LeeBaeng** [Kotlin/dokka#2648]
**Question**
i'm development Ktor Server for Linux+Windows JVM Platform.
and i want make api document for clinet developer.
so i use dokka. 

i want just only include about apis in dokka.
i don't want include anything about server's structure.

so i did edit build.gradle's sourceLink/path. but it's not work.
something is wrong?

this is my build.gradle's option.
```gradle
dokkaJavadoc{
    moduleName.set("Server API Document")

    dokkaSourceSets{
        outputDirectory.set(new File("$buildDir/javadoc"))

        named("main") {
            sourceLink {
                path = "src/main/kotlin/com/mserver/apis" // original path = "src/main/java"
                lineSuffix = "#L"
            }
        }
    }
}
```
i try like it [src/main/java/com/mserver/apis, src/main/kotlin/com/mserver/apis]  and more.
but it's not work.
how can i do it?

(i did search it on google. they said use packageOption. but it can't find in my project(if i include packageOption in my gradle, it say "Error")

**Screenshots**
If applicable, add screenshots to help explain your problem

**Installation**
- Operating system: Windows
- Build tool: I Don't know. maybe it used IntelliJ IDEA 2022.1.3's Default
- Dokka version: 1.7.10

**Additional context**
Add any other context about the problem here

**Comment by IgnatBeresnev** [comment]
Hi! 

`sourceLink` configuration property is used to display links to source files from web documentation. See "Sources" block [on this page](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/as-coroutine-dispatcher.html)

If you want to limit source files for which documentation is generated, there's a number of ways to do that.

1. use `matchingRegex` to include or suppress certain packages
```kotlin
val dokkaHtml by getting(DokkaTask::class) {
    dokkaSourceSets {
        configureEach { 
            // Allows to customize documentation generation options on a per-package basis
            // Repeat for multiple packageOptions
            // If multiple packages match the same matchingRegex, the longuest matchingRegex will be used
            perPackageOption {
                // will match kotlin and all sub-packages of it
                matchingRegex.set("kotlin($|\\.).*")
            }
            // Suppress a package
            perPackageOption {
                matchingRegex.set(""".*\.internal.*""") // will match all .internal packages and sub-packages
                suppress.set(true)
            }
        }
    }
}
```

2. use `sourceRoots` to limit sources:

```kotlin
val dokkaHtml by getting(DokkaTask::class) {
    dokkaSourceSets {
        configureEach { 
            // By default, sourceRoots are taken from Kotlin Plugin and kotlinTasks, following roots will be appended to them
            // Repeat for multiple sourceRoots
            sourceRoots.from(file("src"))
        }
    }
}
```

[See documentation](https://kotlin.github.io/dokka/1.7.10/user_guide/gradle/usage/#configuration-options) for full list of configuration options with some explanation

**Comment by IgnatBeresnev** [comment]
Closing as answered. Let us know if you have any further questions
