### ISSUE TITLE
Samples are rendered only with fqn reference

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2656]
1. Create a function containing a sample in a non-root package
```Kotlin
package org.jetbrains.qa.kdoc.rendering

fun sample() {
    val x = 100
    println(x + 100)
}
```
2. Reference the sample from a KDoc (the functions in the same package, so the function is resolved)
```Kotlin
package org.jetbrains.qa.kdoc.rendering

/**
 * Function with sample.
 * @see [sample]
 * @sample [sample]
 */
fun withSample(a: Int): Int{
    return a + 1
}

/**
 * Function with sample
 * @see [org.jetbrains.qa.kdoc.rendering.sample]
 * @sample [org.jetbrains.qa.kdoc.rendering.sample]
 */
fun withSampleFqdn(a: Int): Int{
    return a + 1
}
```
3. Render the dokka

For the first function the sample is not rendered (that's the issue)
<img width="524" alt="image" src="https://user-images.githubusercontent.com/7689049/188686689-b29491f2-26f0-4e23-992e-d19aa1f3dc3f.png">
For the second with fqn everything is fine:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/7689049/188686803-d57cf029-789a-4fa6-938b-35cc9391e316.png">

For the `@see` param the same scenario works fine

- Dokka version: 1.7.10/master

#2032 might be relevant

**Comment by vmishenev** [comment]
The behaviour corresponds to [KDoc specification for @sample](https://kotlinlang.org/docs/kotlin-doc.html#sample-identifier). It is complicated to find a needed scope since sample sources is taken from a separated folder by design.
