### ISSUE TITLE
Question: How can I make dokka ignore a certain set of files?

### ISSUE THREAD

**Issue by jahirfiquitiva** [Kotlin/dokka#266]
I know many people would say everything should be documented but I am getting warnings for files that are not really needed to document for specific reasons and I would like to know if there's a way to tell Dokka to ignore them, or if you could add such feature.

Thanks in advance

**Comment by semoro** [comment]
You could ignore whole packages, or disable those warnings for it, is this suitable for you?

**Comment by jahirfiquitiva** [comment]
@semoro 
Thanks for the reply
Disabling the warnings is good enough. But can they be disabled per file? (not whole package)

**Comment by semoro** [comment]
Sad, but it also per-package.

**Comment by jahirfiquitiva** [comment]
@semoro 
Is it already implemented anyway? I could use it for now, but if you are going to work on implementing this, I would prefer it to be per file/class if possible.
Maybe using some kind of annotation or something?

**Comment by jahirfiquitiva** [comment]
@semoro 
Thank you. I will use this for now, but I really put some hopes in the other way happening in a future release

**Comment by jahirfiquitiva** [comment]
@semoro 

Hello

I am just trying to use what you told me to, but it isn't working. This is my configuration in `build.gradle` and there's a small screenshot at the end, showing that it still reports undocumented things for the packages I have explicitly tell to not report.

Can you please help me? Thanks in advance :)

```groovy
task generateDocs(type: org.jetbrains.dokka.gradle.DokkaAndroidTask) {
    outputFormat = 'html'
    outputDirectory = "./docs"
}

dokka {
    linkMapping {
        dir = "src/main/kotlin"
        url = "https://bitbucket.org/vez/vez-android/src/"
    }
    outputs.upToDateWhen { return false }
    skipEmptyPackages = true
    skipDeprecated = true

    skipEmptyPackages = true
    skipDeprecated = true
    packageOptions {
        prefix = "io.vez.app.applications"
        reportUndocumented = false
    }
    packageOptions {
        prefix = "io.vez.app.constants"
        reportUndocumented = false
    }
    packageOptions {
        prefix = "io.vez.app.data"
        reportUndocumented = false
    }
}
```

![screenshot_3](https://user-images.githubusercontent.com/10360816/36054919-03931306-0dc7-11e8-923d-132d52e98f4b.png)

**Comment by semoro** [comment]
That should work, will check

**Comment by semoro** [comment]
You need to specify it for all tasks
```
task generateDocs(type: org.jetbrains.dokka.gradle.DokkaAndroidTask) {
    outputFormat = 'html'
    outputDirectory = "./docs"

    skipEmptyPackages = true
    skipDeprecated = true
    packageOptions {
        prefix = "xx.vez.app.applications"
        reportUndocumented = false
    }
    packageOptions {
        prefix = "xx.vez.app.constants"
        reportUndocumented = false
    }
    packageOptions {
        prefix = "xx.vez.app.data"
        reportUndocumented = false
    }
}

dokka {
    linkMapping {
        dir = "src/main/kotlin"
        url = "https://bitbucket.org/vez/vez-android/src/"
    }
    outputs.upToDateWhen { return false }

    skipEmptyPackages = true
    skipDeprecated = true
    packageOptions {
        prefix = "xx.vez.app.applications"
        reportUndocumented = false
    }
    packageOptions {
        prefix = "xx.vez.app.constants"
        reportUndocumented = false
    }
    packageOptions {
        prefix = "xx.vez.app.data"
        reportUndocumented = false
    }
}
```

**Comment by harishrpatel** [comment]
Is there a better way to make prefix as an array so that we don't need bunch of packageOptions blocks? I have about 10-15 packages that I would like to ignore.

**Comment by semoro** [comment]
@harishrpatel 
Workaround for you: 
``` Gradle
dokka {
   for (def pkg : ["abc", "cda", /* other prefixes */]) {
      packageOptions {
          prefix = pkg
          reportUndocumented = false
      }
   }
}
```

**Comment by semoro** [comment]
@harishrpatel Please, report separate issue

**Comment by semoro** [comment]
Closing issue, as original question answered
