### ISSUE TITLE
Move text under @depracation tag to Deprecation block in Java sources

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2668]
For the Java code like:

```Java
public class DeprecatedJClass {
    /**
     * Don't do anything
     * @deprecated
     * This method is no longer acceptable to compute time between versions.
     * <p> Use {@link DeprecatedJClass#getStringMethodNew()} instead.
     */
    @Deprecated(since = "18.0.2", forRemoval = true)
    public void getStringMethod(){}
    public void getStringMethodNew(){}
}
```

The HTML output look like:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/7689049/189980383-d197587e-7de6-46c4-977b-c2de29b5aada.png">

It seems like it would be nice to move the text from the Depreciation paragraph to the Deracation table to have everything in one place.

**Comment by IgnatBeresnev** [comment]
* It's likely that @berezinant will tackle this problem as part of his onboarding. It's a good issue because it deals with the common `content` layer, but the result is visible in HTML
* I'll help, we'll do pair programming
