### ISSUE TITLE
Include HTML assets in multi-module project?

### ISSUE THREAD

**Issue by fwendland** [Kotlin/dokka#2671]
**Question**
Is it possible to include custom HTML assets in a multi-module project?

**Installation**
- Operating system: Linux
- Build tool: Gradle v7.5.1
- Dokka version: 1.7.10

**Additional context**
I want to replace HTML assets in my multi-module project. I've followed the documentation [[1](https://kotlin.github.io/dokka/1.7.10/user_guide/gradle/usage/#applying-plugins), [2](https://kotlin.github.io/dokka/1.7.10/user_guide/base-specific/frontend/#modifying-assets)] and configured each module to use my custom assets. This works great. However, I don't seem to be able to configure the `dokkaHtmlMultiModule` task to also use my custom assets.

So far I've tried to add the `pluginConfiguration` to each `DokkaTask` and to each `DokkaTaskPartial`, which didn't work.

Do you have any suggestion? Is it at all possible to add custom assets to the `dokkaHtmlMultiModule` task?

**Comment by hfhbd** [comment]
I did use this workaround in the past, but I don't know, if it still works: https://github.com/Kotlin/dokka/issues/2244#issuecomment-981107265

**Comment by fwendland** [comment]
Hi @hfhbd,

Thank you. I must have missed this one in my search :flushed: I have a look and let you know.

**Comment by fwendland** [comment]
Thanks @hfhbd, you're workaround from #2244 still works :)
