### ISSUE TITLE
Dokka doesn't generate documents for protobuf generated code

### ISSUE THREAD

**Issue by iseki0** [Kotlin/dokka#2675]
**Question**
Why Dokka doesn't generate documents for protobuf generated code, even I create a customized sourceSet and add the target path to `sourceRoot` ?

**Installation**
```kotlin
id("org.jetbrains.dokka") version "1.7.10"
```
```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.2.1 (Eclipse Adoptium 18.0.2.1+1)
OS:           Windows 10 10.0 amd64
```
**Additional context**

```kotlin

tasks.withType<DokkaTask>{
    doLast {
        println(dokkaSourceSets["protobufGenerated"].sourceRoots.toList()) // the following source path printed
    }
    dokkaSourceSets.create("protobufGenerated"){
        sourceRoot("build/generated/source/proto/main/kotlin")
        sourceRoot("build/generated/source/proto/main/java")
    }

}

```

Before I execute the task `:dokkaHtml` , I have checked the files were generated.

**Comment by IgnatBeresnev** [comment]
Hi! Do you have a project where we can reproduce the issue? It would speed things up as we wouldn't have to configure it outselves

**Comment by IgnatBeresnev** [comment]
I completely forgot that generated files are suppressed by default. Try setting `suppressGeneratedFiles` configuration property to `false`:

```kotlin
tasks.withType<DokkaTask>().configureEach {
    dokkaSourceSets.configureEach {
        suppressGeneratedFiles.set(false)
    }
}
```

Do let us know if it helps.

**Comment by IgnatBeresnev** [comment]
I'll close the issue as resolved as it's most likely `suppressGeneratedFiles` that is suppressing generated files, but do let us know if it's still relevant.
