### ISSUE TITLE
How to change package names and other details being displayed

### ISSUE THREAD

**Issue by SumukhaK** [Kotlin/dokka#2725]
I have a two part question. Let us assume I'm building a SDK for a restaurant maintenance, i will have different packages like api, model, network etc. In generated documentation can i show something like apis, input models etc instead of com.example.restaurant.api, com.example.restaurant.model ?

Secondly is there any way to categories APIs listed instead of plain listing of APIs. Lets say I have public RestaurantManager class which exposes APIs, instead of just class name and api methods being shown in the doc, when user clicks on class name, can i show categories like Inventory under them apis used for inventory management, Staffing under which i can show addStaff, removeStaff etc methods and so on ?

**Comment by IgnatBeresnev** [comment]
Unfortunately, this is not possible to do out of the box and it's unlikely to be implemented. Dokka documents API as is, preserving packages and structure that will be seen by the library users.

You can re-organize your classes and functions, for instance, by extracting all Staff-related functions into a separate `RestaurantStaffManager` class - this will probably lead to better decomposition and cleaner code. 

Alternatively, you can try to write a [Dokka plugin](https://kotlin.github.io/dokka/1.7.20/developer_guide/introduction/) to customize the output the way you won't, but it won't be easy.
