### ISSUE TITLE
Support Hugo

### ISSUE THREAD

**Issue by neonailol** [Kotlin/dokka#273]
It would be nice if dokka supported generating fully featured [Hugo](https://gohugo.io/) sites

**Comment by yole** [comment]
Dokka is a tool for generating documentation from code. Anything beyond that is out of scope for the project. Note that you can integrate Dokka-generated documentation into sites generated with any static site generator; kotlinlang.org does exactly that.

**Comment by neonailol** [comment]
@yole if i build this feature, i.e. generating markdown that supported by hugo, is there a chance that it can be merged into dokka? or is there way to make plugins for dokka with custom generation scenario, that i can redistribute via maven?

**Comment by yole** [comment]
We would prefer not to maintain support for a system which we do not use, do not understand, and which is not widely used by our target audience.

**Comment by semoro** [comment]
@neonailol You can make Dokka plugin

But be aware of: 
1. Dokka internals wasn't documented
2. Dokka API not stable yet

**Comment by neonailol** [comment]
@yole thanks for reply, dokka support jekyll, and hugo is second most popular static generator, according to [stats](https://www.staticgen.com/), consider looking into future :)
@semoro thanks, i saw the code, it's far from good, is there any guidelines that this project follows? about code style, docs, and all other things.

**Comment by dschuermann** [comment]
I started working on a hugo extension: https://github.com/cotechde/dokka-hugo-extension

It is not finished but it's a good start.

**Comment by dschuermann** [comment]
My extension works now good enough that we are using it for https://www.cotech.de/reference/hw-security/
