### ISSUE TITLE
GFM Format in single file

### ISSUE THREAD

**Issue by thekingrenz23** [Kotlin/dokka#2731]
**Question**
Is there in anyway the generated GFM format is in one file

ALL.md

**Additional context**
I want to convert the generated GFM to pdf using pandoc. Since the generated markdown are in separate files links are broken when converted to pdf

**Comment by thekingrenz23** [comment]
closing this thread since I have found a way to make this one work

**Comment by tex0l** [comment]
@basurahan I want to do something similar for another purpose: I would like to embed the markdown file into a vuepress, but as a single file. Could you please explain how you solved your issue as this might help me? :)
