### ISSUE TITLE
dokka for ios

### ISSUE THREAD

**Issue by vampire184** [Kotlin/dokka#2746]
**Question**
hello bro, dokka have any plans to support ios? I'm studying dokka recently, and I want to know how to use dokka to generate documentation from switf or object-c annotations. Or give me some advice, if I want to achieve this function, where should I start? Thanks!

**Comment by vampire184** [comment]
docC will generate an intermediate product in json format, I was wondering if it is possible to use this intermediate product as data input, and then perform data processing at the <SourceToDocumentableTranslator> extension point?

**Comment by IgnatBeresnev** [comment]
Not out of the box, unfortunately. You could write your own Dokka plugin and try to implement it, but it doesn't look like an easy task

**Comment by vampire184** [comment]
emm... that's quite a challenge, thanks!

**Comment by MiloMustacheN6A** [comment]
Dokka is a documentation engine for Kotlin that generates documentation in different formats, such as HTML, Markdown, and Javadoc. As of my knowledge cutoff in September 2021, Dokka does not have plans to support Swift or Objective-C annotations for generating documentation.

However, if you want to achieve this functionality, you could consider developing a custom plugin for Dokka that supports Swift or Objective-C annotations. A plugin is a component that extends the functionality of Dokka to generate documentation for specific programming languages or frameworks.

To get started, you can refer to the Dokka documentation on developing plugins at https://github.com/Kotlin/dokka/blob/master/docs/PLUGINS.md. You can also look at the existing plugins for Dokka to understand how they work and how to develop a plugin for a new language or framework.

Keep in mind that developing a plugin for Dokka requires knowledge of Kotlin and the target programming language or framework. It may also require knowledge of the Dokka API and its architecture. Therefore, it is recommended that you have some experience in developing Kotlin applications and working with the Dokka documentation engine before developing a custom plugin.
