### ISSUE TITLE
output format 'kotlin-website' make markdown files instead html files

### ISSUE THREAD

**Issue by mgcation** [Kotlin/dokka#275]
It make `index.md`

But in `index.md`, its syntax is html, and link to `*/index.html`.

but there is no `*/index.html`. only `*/index.md`

**Comment by semoro** [comment]
Why you even use `kotlin-website` format? 
You can try `kotlin-website-html` format, but use it at your own risk as it purposed to be used only on `kotlinlang.org`.

**Comment by mgcation** [comment]
I just test all of format, and I found it look like bug

but if is was intended, I have nothing more to say about it.
