### ISSUE TITLE
How to use dokka in Java project

### ISSUE THREAD

**Issue by greenlaw110** [Kotlin/dokka#2757]
**Question**

I tried to use dokka with a [Java project](https://github.com/osglworks/java-version/blob/dokka/pom.xml), however it looks like it does not recognize kdoc style javadoc.

For example for the following javadoc:

```
    /**
     * Returns version tag: a full version string.
     *
     * When {@link #buildNumber} exists the version tag is composed of
     * {@link #projectVersion} a {@link #buildNumber} with the following
     * pattern:
     *
     * `${patched-projectVersion}-${patched-buildNumber}`
     *
     * Where `patched-projectVersion` could be one of the following:
     *
     * * If `projectVersion` ends with `-SNAPSHOT`, then `"v" + projectVersion`
     * * Otherwise, `"R" + projectVersion`
     *
     * `patched-buildNumber` is `"b" + buildNumber`
     *
     * If {@link #buildNumber} is not defined then the version tag is the
     * `patched-projectVersion` as described above
     *
     * @return a version tag as described
     */
```

It generates:

```
Returns version tag: a full version string. When [buildNumber](https://github.com/Kotlin/dokka/issues/Version.html#buildNumber) exists the version tag is composed of [projectVersion](https://github.com/Kotlin/dokka/issues/Version.html#projectVersion) a [buildNumber](https://github.com/Kotlin/dokka/issues/Version.html#buildNumber) with the following pattern: `${patched-projectVersion}-${patched-[buildNumber](https://github.com/Kotlin/dokka/issues/Version.html#buildNumber)}` Where `patched-projectVersion` could be one of the following: * If `projectVersion` ends with `-SNAPSHOT`, then `"v" + projectVersion` * Otherwise, `"R" + projectVersion` `patched-buildNumber` is `"b" + buildNumber` If buildNumber is not defined then the version tag is the `patched-projectVersion` as described above
```

**Screenshots**

<img width="944" alt="image" src="https://user-images.githubusercontent.com/216930/204056094-845acfcb-e2e5-4d7d-a5a7-321fbde75e36.png">

**Installation**
- Operating system: macOS
- Build tool: Maven
- Dokka version: 1.7.20

**Additional context**

StackOverflow question: https://stackoverflow.com/questions/74275046/dokka-mess-up-markdown-in-javadoc

**Comment by IgnatBeresnev** [comment]
I'm not sure what you mean by `kdoc style javadoc` - it should be either `KDoc` (for documenting Kotlin code) or `javadoc` (for documenting Java code), but not both at the same time :) 

KDoc is closer to Markdown, while Javadoc is closer to HTML. Both formats have specification in one form or another that states which tags/constructions are allowed and which aren't.

Using backticks to format code is from the Markdown world, so it works perfectly in KDocs. However, it's not a valid way to format code in Javadocs as it uses <code>` and `<pre>` tags for it.

Perhaps, I misunderstood you and you're trying to do something else? Could you give us more details about the use case / initial problem?

**Comment by IgnatBeresnev** [comment]
The problem seems to come from mixing KDoc/Javadoc comments in one place, so I'll close the question as resolved.

Let us know if I misunderstood you and this is indeed a bug, we'll happily re-open the issue.
