### ISSUE TITLE
DokkaHtml only generate documentation in App module in app bundles

### ISSUE THREAD

**Issue by manuellopera** [Kotlin/dokka#2758]
**Describe the bug**
I try generate documentation in my android app bundle and only generate documentation in module "app".
My appbundle has:
- App module
- 16 dynamic feature
- 1 android library

**Expected behaviour**
I think that executing "gradlew dokkaHtml" in root project directory was enough to generate documentation in all my dynamic feature.

**Screenshots**
I have in all dynamic feature implementation plugins like that screenshots
![image](https://user-images.githubusercontent.com/94481971/204312792-4ff08770-36ac-4958-804c-a50bb425ea5b.png)
In general gradle file I implement dokka classpath 
![image](https://user-images.githubusercontent.com/94481971/204313777-59c09a1f-e7ba-45b7-813e-fe01ac98b144.png) 

**To Reproduce**
I launch "gradlew dokkaHtml" in Windows cmd in Android Studio project root.

**Dokka configuration**
Only implements, see screenshots
```Kotlin

```

**Installation**
- Operating system: Windows 10
- Build tool: Gradle 7.2.1
- Dokka version: 1.7.20

**Additional context**

**Are you willing to provide a PR?**
The project where i try generate dokka documentation is private, not personal, sorry :(

**Comment by IgnatBeresnev** [comment]
If you have a multi-project Gradle build, you need to run `dokkaHtmlMultiModule`, not `dokkaHtml`. Does it help?

If it doesn't help, could I ask you to create a simple app project that can reproduce the problem? So a small project with the same structure (app module, dynamic features, etc) as in your real project. It would help with debugging and fixing the problem a lot.

**Comment by manuellopera** [comment]
I try execute dokkaHtmlMultiModule, but allways return

* What went wrong:
Task 'dokkaHtmlMultiModule' not found in root project 'Dokkatest'.

And in every dynamic print in terminal:
Disabling ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM option because this is a dynamic-feature module. Dynamic-feature module is not supported by ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM yet.

I create this project [https://github.com/manuellopera/Dokkatest](url) with a dynamic feature to test.

In my project in Android Studio build both module documentation, but i dont know if them was built with dokkaHtml or dokkaHtmlMultiModule.

**Comment by IgnatBeresnev** [comment]
Thanks for taking the time to create a reproducer!

`*MultiModule` tasks are only created for parent projects that have the Dokka plugin applied. In your project, Dokka is applied only within the `app` and `dynamicfeature` subprojects, that's why you don't have the task in your root project.

Add the Dokka plugin to your **root** `build.gradle`:

```
plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
    id 'com.android.dynamic-feature' version '7.3.1' apply false

    // here
    id 'org.jetbrains.dokka' version '1.7.20'
}
```

After that, you should be able to run `./gradlew dokkaHtmlMultiModule`:

![2023-01-03_04-31-24](https://user-images.githubusercontent.com/22685910/210296807-95aab44d-4dc5-4ef6-9e71-2ba58672461f.png)

**Comment by IgnatBeresnev** [comment]
Hopefully the problem was resolved, let us know if you have any further problems or questions
