### ISSUE TITLE
Using by lazy without defining return type leads <ERROR CLASS> in docs

### ISSUE THREAD

**Issue by dgngulcan** [Kotlin/dokka#276]
In the generated document, type of a property that is instantiated with `by lazy` is shown as `<ERROR CLASS>` like below,

**In the codebase class**
```
val center by lazy { 
    getCenterLatLng(listOf(northEast, southWest))
}
```
`getCenterLatLng` returns a `LatLng` object

**In the documentation**
```
val center: <ERROR CLASS>
```

And when I explicitly define the type
```
val center: Latlng by lazy { 
    getCenterLatLng(listOf(northEast, southWest))
}
```
it is generated as expected in the documents
```
val center: LatLng
```

Is it something expected or can types be read through by lazy scope?

**Comment by semoro** [comment]
It should behave same in both cases, and show correct return type

Please, make sure that Dokka class-path is correct and contains kotlin-stdlib

**Comment by dgngulcan** [comment]
Thanks!
