### ISSUE TITLE
HTML: Add anchor for headlines in the include/module headings

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/dokka#2769]
**Is your feature request related to a problem? Please describe**
I added a module page with different levels of headings but I am unable to create a link to each headline, which I can share and reference to.

**Describe the solution you'd like**
Add a link to each heading from the module files which is shareable and reference-able inside the md file.

**Describe alternatives you've considered**
Nothing

**Additional context**
<img width="1440" alt="Bildschirm­foto 2022-12-11 um 13 38 01" src="https://user-images.githubusercontent.com/22521688/206904015-0d3badc7-2a37-4023-8334-e5b8b4cebd0b.png">
repro
[untitled1.zip](https://github.com/Kotlin/dokka/files/10202195/untitled1.zip)

**Are you willing to provide a PR?**
With help sure

**Comment by vmishenev** [comment]
We already have #2249
