### ISSUE TITLE
[jvm] tag appearing everywhere in the generated markdown format

### ISSUE THREAD

**Issue by Siddharthbhatheja3011** [Kotlin/dokka#2782]
Whenever I generate markdown format (GFM or Jekyll) using dokka, it generates the documentation with "[jvm]" tag appearing everywhere in every field as show in the screenshot below. Does anyone has any idea why this is happening and what can I do to fix it. I'm using dokka version 1.7.20 on a pure kotlin project, and I have just added "id("org.jetbrains.dokka") version ("1.7.20")" in the Gradle file.
<img width="305" alt="Screenshot 2022-12-19 at 13 01 01" src="https://user-images.githubusercontent.com/118519406/208372007-65420c72-11b7-447e-ad71-e38729fdb489.png">

**Comment by IgnatBeresnev** [comment]
As has been mentioned above, it's expected in certain scenarios, and I believe it's always present in the Markdown documentation.

Without additional information, there's little we can do to help or clear it up, so I'm closing the issue as stale.

If anyone else experiences this problem or has the same question, please provide more details about your project/documentation, and we'll be able to assist.

**Comment by kingori** [comment]
I have same issue. In my case, I applied dokka in gradle convention plugin module and it contains only kotlin code and it's not a multiplatform module.

// build.gradke.kts
```
import org.jetbrains.dokka.DokkaConfiguration
import org.jetbrains.dokka.Platform
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `kotlin-dsl`
    `kotlin-dsl-precompiled-script-plugins`
    id("org.jetbrains.dokka") version "1.9.10"
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    compileOnly(libs.buildscript.android.gradle)
    compileOnly(libs.buildscript.kotlin.gradle)
    ...
}

tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        freeCompilerArgs = freeCompilerArgs + "-Xcontext-receivers"
    }
}

gradlePlugin {
    plugins {
        register("foo") {
            id = "foo"
            implementationClass = "bar.foo"
        }
        ...
    }
}

tasks.dokkaGfm.configure {
    notCompatibleWithConfigurationCache("https://github.com/Kotlin/dokka/issues/2231")
    outputDirectory.set(File("docs"))
    moduleName.set("convention")

    dokkaSourceSets {
        configureEach {
            skipEmptyPackages.set(true)
            documentedVisibilities.set(setOf(DokkaConfiguration.Visibility.PUBLIC))
            includes.from("module.md")
            includeNonPublic.set(false)
            noJdkLink = true
            reportUndocumented = false
            platform.set(Platform.jvm)
            noStdlibLink = true
        }
    }
}

val javadocJar: TaskProvider<Jar> by tasks.registering(Jar::class) {
    dependsOn(tasks.dokkaGfm.get())
    archiveClassifier.set("javadoc")
    from(tasks.dokkaGfm.get().outputDirectory)
}
```
