### ISSUE TITLE
Custom/more output formats

### ISSUE THREAD

**Issue by happeens** [Kotlin/dokka#279]
I'm currently looking for a way to generate swagger/OpenAPI definition files from my projects, which are mostly Spring projects written in Kotlin. I've looked at multiple possible solutions for this, and one of the most attractive to me would be to have them generated from documentation/comments on the controller methods. They would need to be marked as endpoints somehow, but apart from that the documentation could probably contain all the information needed for this. Currently, with this project, I see a few ways to go about this:

* Fork this project and create a custom output format that suits my needs
* Create a new project and depend on this one, pulling the methods I need for parsing all comments
* Parse the output from this project and extract the needed information
* Allow for a way to add custom output formats to this project

And so, my question is: Is there anything planned in the way of custom or more output formats? It might even be enough to have a sort of intermediary output format that can be parsed more easily by other programs (such as yaml or json), so that the information can be used for more things than just generating finished documentation. If there is no interest in this at all, I will probably fork this project or depend on it to achieve my goal, but if there is, I would be open to contributing.

Also, if there's an easier way to achieve what I'm looking for with this project, I'm all ears.

**Comment by semoro** [comment]
There is possibility to add custom output formats in this project

See how Markdown format [works](https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/Formats/MarkdownFormatService.kt)

**Comment by happeens** [comment]
Thanks a lot, this is pretty much exactly what we needed. I still think it would be cool to have the option of a parseable intermediary output format, but this definitely solves our problems. Thus, I think this issue can be closed.
