### ISSUE TITLE
Inner java class miss the `inner` modifier in signature

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2793]
```Java
public class JavaClassWithNested {
    public class Inner{}
    public static class Nested{}
}
```

Will generate documentation like

<img width="565" alt="image" src="https://user-images.githubusercontent.com/7689049/209553895-aa4c8257-6728-4bc2-beec-71430b19fbc7.png">

The signature for class `Inner` should contain `inner` keyword.

**Comment by IgnatBeresnev** [comment]
Notes for those looking to contribute:

The `inner` keyword is rendered correctly for Kotlin inner classes, so there's support for it, but it's missing from our Java source code parser.

Java's inner classes already have the static modifier in the model, but it looks like `KotlinSignatureProvider` renders only Kotlin-specific ones (`ExtraModifiers.KotlinOnlyModifiers`), and `Inner` is one of them.

So we need to add the `ExtraModifiers.KotlinOnlyModifiers.Inner` additional modifier to the parsed Java class if it's static:

```
extra = PropertyContainer.withAll(
    AdditionalModifiers(setOf(ExtraModifiers.KotlinOnlyModifiers.Inner).toSourceSetDependent())
)
```

You can check for the Java's static modifier by using `psi.hasModifier(JvmModifier.STATIC)`

The code for parsing Java classes [can be found here](https://github.com/Kotlin/dokka/blob/1.7.20/plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt#L365-L388).

See [CONTRIBUTING.md](https://github.com/Kotlin/dokka/blob/master/CONTRIBUTING.md) and [Developer Guides](https://kotlin.github.io/dokka/1.7.20/developer_guide/introduction/) to get started.
