### ISSUE TITLE
Automatically resolve dependency versions of Dokka's own plugins via Gradle platform (BOM)

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#2812]
If the user has applied Dokka, they should be able to add Dokka's own plugins (such as versioning, mathjax, android, etc) without specifying the version. For example:

```gradle
dependencies {
    dokkaPlugin("org.jetbrains.dokka:mathjax-plugin")
}
```

The version should be resolved automatically through [Gradle platforms](https://docs.gradle.org/current/userguide/platforms.html)

**Comment by whyoleg** [comment]
Fixed in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html)
