### ISSUE TITLE
Unclear error when applying java plugin to dependency

### ISSUE THREAD

**Issue by mathjeff** [Kotlin/dokka#282]
Full reproduction case at https://github.com/mathjeff/dokka-tests/tree/master/unclear-error-when-applying-java-plugin-to-dependency

Essentially, there are two projects:

  jefflib1, which applies the java plugin
  jefflib2, which applies the dokka-android plugin and depends on jefflib1

Running the command `find -name build | xargs rm -rf && ./gradlew` fails with a confusing error:

  Could not determine the dependencies of task ':jefflib2:dokka'.
  > Could not resolve all files for configuration ':jefflib2:debugCompileClasspath'.
     > Failed to transform file 'jefflib1.jar' to match attributes {artifactType=android-classes} using transform JarTransform
        > Transform output file /usr/local/google/workspace/dokka-tests/temp/jefflib1/build/libs/jefflib1.jar does not exist.

Thoughts?
Thanks

**Comment by semoro** [comment]
Workaround for your test project:

```
 dokka {
      kotlinTasks { [] } // Disable Kotlin-Android based autoconfiguration
      sourceDirs = project.files('src/main/java')
      classpath =
              new ArrayList<File>(project.tasks['assemble'].outputs.files.files)
  }
```

**Comment by hzsweers** [comment]
Should note this prevents use of dokka entirely on android gradle plugin 3.1, probably also 3.x
