### ISSUE TITLE
Remove the dependency on internal Gradle API

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#2822]
Dokka depends on classes from `org.gradle.api.internal` for which there are no guarantees about backward compatibility and proper deprecation as demonstrated by #2816

It looks like `TaskDependencyInternalWithAdditions` can be replaced with Gradle's `dependsOn` for setting up task dependencies.

**Comment by atyrin** [comment]
For `DokkaMultiModuleTask` and `DokkaCollectorTask` tasks Dokka has API methods for adding and removing child tasks (`addChildTask(s)`/`removeChildTask(s)`, `addSubprojectChildTasks`/`removeSubprojectChildTasks` ). These methods may accept path/task/project as a parameter. The list of such child tasks is stored as a `Set<String>` of paths in the parent task (`childDokkaTaskPaths` in `AbstractDokkaParentTask`).
Child task == task on which the parent task depends.

This internal storage of child tasks is used in cases when the list of all dependency tasks is requested with the `getTaskDependencies(): TaskDependencyInternal`. That's the place where internal packages are used -- to override the method and access to `TaskDependencyInternal`.

We can eliminate the logic and replace the internal storage with `dependsOn`from `DefaultTask`. That will remove the requirement to override `getTaskDependencies`.
But there are disadvantages: 
1. This is a `Set<Object>` that is not safe.
2. It is not allowed to use `remove` method on the set. Only the full re-write with `setDependsOn`.
Together, they lead to the necessity of writing a little of extra code for checking types/filtering.

**Comment by aSemy** [comment]
This is related to #2700 

Currently the Dokka Gradle plugin uses task references to access generated docs between subprojects, which is [not recommended by Gradle](https://docs.gradle.org/current/userguide/cross_project_publications.html)

> ### Don’t reference other project tasks directly
>
> A frequent anti-pattern to declare cross-project dependencies is:
> 
> ```kotlin
> dependencies {
>    // this is unsafe!
>    implementation project(":other").tasks.someOtherJar
> }
> ```
>
> This publication model is _unsafe_ and can lead to non-reproducible and hard to parallelize builds. This section explains how to _properly create cross-project boundaries_ by defining "exchanges" between projects by using _variants_.

Directly referencing other tasks from other projects causes problems with the Gradle Configuration Cache #2231 and prevents docs aggregation #2612.

To migrate to the recommended Gradle method of sharing output between subprojects, the Dokka Gradle Plugin should

1. For each Dokka-enabled subproject create appropriate [Configurations](https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_configuration) for _providing_ and _consuming_ generated documentation
2. The _providing_ Configuration will be filled using the docs generation task
3. The _consuming_ Configuration will add dependencies on other subprojects.

Then, the aggregation task can use the _consuming_ configuration as a task input. Gradle will automatically retrieve the docs, and trigger the docs generation tasks as needed.

There is a practical example, based on aggregating JaCoCo test reports, in the Gradle docs: https://docs.gradle.org/7.3/samples/sample_jvm_multi_project_with_code_coverage.html

**Comment by IgnatBeresnev** [comment]
@aSemy indeed, what you're proposing sounds very reasonable, and would help with the mentioned issues :+1:

As you've probably understood by now, we are not Gradle experts and there are many issues with the plugin, so implementing and reviewing it will take time.

At the moment I'm concerned by the fact that the internal API can be removed/changed in any release, which can limit our compatibility with the previous/future versions of Gradle. So I'd like to first try to get rid of the internal API by using the stable `dependsOn` alternative.

After that, the more general issue of task reference/dependency can be addressed. I believe there's some discussion about it in #1752

Do you see any problems with this approach it or maybe you have some concerns that we don't see?

**Comment by aSemy** [comment]
> Do you see any problems with this approach or maybe you have some concerns that we don't see? 

I'm not saying "don't do it", because pragmatically trying to patch the existing setup is less work than trying overhaul it. The critique I have is that replacing an internal API with a misuse of the task dependency API doesn't really help the Dokka Gradle plugin - it's still incompatible with projects that follow the Gradle spec. I want to use it, but I can't.

> I don't think any of your current PRs cover this problem, right?

All of [the Gradle Plugin PRs](https://github.com/Kotlin/dokka/pulls?q=is%3Aopen+-label%3A%22Infrastructure%22+author%3AaSemy+is%3Apr) have been building up to fixing this :)

**Comment by IgnatBeresnev** [comment]
> The critique I have is that replacing an internal API with a misuse of the task dependency API doesn't really help the Dokka Gradle plugin - it's still incompatible with projects that follow the Gradle spec

For sure, it's not meant to be a replacement for the proper fix. Replacing `TaskDependencyInternal` with `dependsOn` doesn't improve things from the outside, the plugin is still incompatible, but at least it will be stable and a new Gradle release will not break it.

**Comment by IgnatBeresnev** [comment]
@aSemy we have a question, maybe you can help us and explain what the proper way of doing it is

`AbstractDokkaParentTask` has a lot of methods like `addChildTask`, `removeChildTask`, `removeSubprojectChildTasks`, etc. Right now they all work because the parent task has a list of child tasks inside of it, so we can add to it and remove from it. 

When it's refactored the proper way with Configurations, I understand that it will be impossible to support these methods (`addChildTask`, `removeChildTask`, etc), so we will have to delete them. Am I correct?

If we'll have to delete them, it might break some user projects, for instance [in this case](https://github.com/cashapp/redwood/blob/e2176cfd6c00b92aa120d293abf4be3df2215dc5/redwood/build.gradle#L23-L29).

So we want to deprecate these methods now with warning, to give people time to migrate. But we don't know what solution to propose instead. Or is there none? How is this situation usually handled the idiomatic way?

**Comment by whyoleg** [comment]
Should be not an issue in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html)
