### ISSUE TITLE
Document private functions and parameters

### ISSUE THREAD

**Issue by Jonathan8GO** [Kotlin/dokka#2831]
I want to document private functions, I know that by default Dokka does not document them, but I would like to change this configuration.

**Installation**
- Operating system: Windows
- Build tool: Gradle v3.7.7
- Dokka version: 1.7.20

**Comment by IgnatBeresnev** [comment]
You can do that via the `documentedVisibilities` Gradle configuration option.

See documentation to learn how to do that, it has some examples: https://kotlinlang.org/docs/dokka-gradle.html#configuration-examples
