### ISSUE TITLE
Configuration options to modify dokka multi-module main page

### ISSUE THREAD

**Issue by ShivamPokhriyal** [Kotlin/dokka#2838]
**Question**

Currently `dokkaHtmlMultiModule` main page has the following:

page title - `All Modules:`
content and sidebar navigation - list of all sub modules.

**I'm looking for the capability to modify the above 2 things in the main page. Change the page title, and reorder the sub-module list in the sidebar nav and body.**

**Screenshots**

Attached the screenshot of the [dokka-multimodule-example](https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-multimodule-example) 
I'd basically want to change 
- All Modules: text
- reorder childProjectA and childProjectB. 

<img width="600" alt="Screenshot" src="https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-multimodule-example/demo.png">

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.3.1
- Dokka version: 1.7.10

**Additional context**
Add any other context about the problem here

**Comment by IgnatBeresnev** [comment]
It is currently not possible to configure this out of the box.

You can write a Dokka plugin to do that though, but it's not easy and I'm not sure I would recommend it. See [Developer Guides](https://kotlin.github.io/dokka/1.7.20/developer_guide/introduction/) for more info. You would probably need to modify the [Page/Content](https://kotlin.github.io/dokka/1.7.20/developer_guide/architecture/data_model/page_content/) model via a [PageTransformer](https://kotlin.github.io/dokka/1.7.20/developer_guide/architecture/extension_points/core_extensions/#pagetransformer), and change the `name` property of `MultimoduleRootPageNode`, and reorder first level elements inside `NavigationNode`.
