### ISSUE TITLE
Can't find node by signature, defined in other project

### ISSUE THREAD

**Issue by mathjeff** [Kotlin/dokka#284]
Full reproduction case at https://github.com/mathjeff/dokka-tests/tree/master/import-from-other-project-not-found

Essentially there are two projects.

project JefflibA contains class com.jeffclass.JeffClass which defines a static string field, STATIC_FIELD
project JefflibB contains class com.jeffclass2.JeffClass2 which references com.jeffclass.JeffClass#STATIC_FIELD

However, dokka doesn't resolve the reference and instead prints "Can't find node by signature com.jeffclass.JeffClass$STATIC_FIELD"

The reference is found when coming from within the same project, however.

**Comment by kamilok1965** [comment]
This bug willl be fixed in the upcoming release, 0.9.18.
You will need to add to your project jefflibB `build.gradle` file something like this: 
```
 evaluationDependsOn(":jefflibA")
 afterEvaluate {
   dokka {
     classpath = configurations.compile
     externalDocumentationLink {
       packageListUrl = new URL("file://${project(":jefflibA").buildDir}/dokka/jefflib-a/package-list")
       url = new URL("file://${project(":jefflibA").buildDir}/dokka/jefflib-a/")
     }
   }
 }
```
