### ISSUE TITLE
Dokka 1.7.20+ ignores sourceLinks block on android library projects

### ISSUE THREAD

**Issue by Claudemirovsky** [Kotlin/dokka#2876]
**Describe the bug**
On dokka v1.7.20 and 1.8.10, the `sourceLinks` block is ignored on ANDROID library projects, but seems to work as expected on JVM libraries.

**Expected behaviour**
The source link for methods should appear on generated docs of android library projects.

**Screenshots**
This screenshot shows the documentation generated by the `jvm-lib-working` branch of the attached file. Thats the expected behaviour in android-library projects. 
![JVM-LIB-WORKING](https://user-images.githubusercontent.com/63046606/219350358-cec492c7-02d7-4b53-965c-4b41fb14bdcb.png)

This is the actual behaviour, it does not show the [sources] link. This screenshot shows the documentation generated by the `android-lib-bug` branch of the attached file.
![ANDROID-LIB-BUG](https://user-images.githubusercontent.com/63046606/219350398-653f4cd8-d435-4373-b9e5-8dd4b07a8284.png)

This screenshot was taken while using dokka 1.7.10 on the `android-lib-bug` branch of the attached file. Note that a "sources" tab appears as expected for this version.
![ANDROID-DOKKA-1 7 10](https://user-images.githubusercontent.com/63046606/219350415-a2614ede-3093-40c2-bb76-4e429ef9e62f.png)

**To Reproduce**
See [dokka-bug.zip](https://github.com/Kotlin/dokka/files/10755145/dokka-bug.zip)
In it there are two branches, `jvm-lib-working` and `android-lib-bug`, so you can switch between the functional and the non-functional state.

Step 1: Enter the project directory
Step 2: Switch to `android-lib-bug` branch
Step 3: Run `./gradlew :lib:dokkaHtml`
Step 4: Verify generated docs at `lib/build/dokka/html`

**Dokka configuration**
Configuration of dokka used to reproduce the bug

Copy-pasted from the attached project.
```Kotlin
tasks.withType<DokkaTask>().configureEach {
    dokkaSourceSets.configureEach {
        offlineMode.set(true)
        sourceLink {
            localDirectory.set(file("src"))
            remoteUrl.set(URL("https://httpbin.org/anything"))
            remoteLineSuffix.set("#L")
        }
    }
}
```

**Installation**
- Operating system: GNU/Linux Debian Bookworm
- Build tool: Gradle v7.6
- Dokka version: 1.7.20+

**Additional context**
As i said, this bug only happens on dokka 1.7.20 and 1.8.10, from 1.7.10 down the `sourceLinks` block isnt ignored on android library projects.
Although I have no proof, I suspect that this bug is related to [this PR](https://github.com/Kotlin/dokka/pull/2476).

**Are you willing to provide a PR?**
Unfortunately for the time being I don't have enough knowledge to fix it.

**Comment by IgnatBeresnev** [comment]
There's a similar [report in Kotlin Community Slack](https://kotlinlang.slack.com/archives/C0F4UNJET/p1682089594959959?thread_ts=1681743607.949469&cid=C0F4UNJET) by @covercash2: 

> it’s only our Android modules that aren’t linking source docs correctly. it ended up that we do need it to be localDirectory.set(projectDir.resolve("src/main/java"), and in our Kotlin-only module the source code is linked properly. however, all our other modules have Android dependencies and do not link correctly. i’m not certain this is the problem, but it seems to be the only difference i can find

**Comment by sargunv** [comment]
Works for me on 2.0.0-Beta in a multiplatform project with an Android target, but not in a pure Android project. I wonder why?

**Comment by whyoleg** [comment]
Probably should not be an issue in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html).
If you will still receive the same/similar error with DGPv2 please create a new issue.
