### ISSUE TITLE
Unresolved link to a declaration from another source set

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#2877]
```kt
            // /src/commonMain/main.kt
            class A
            
            // /src/jvmMain/main.kt
            /**
            * link to [A]
            */
             class B
 ```

**Comment by maikelvdh** [comment]
Thanks @vmishenev for addressing this problem! We are also impacted by this particular problem, is it an option to produce a 1.8.21 release @IgnatBeresnev by chance? Thanks a lot!

**Comment by IgnatBeresnev** [comment]
@maikelvdh this will be part of 1.8.20 (which is the next release, ~2-4 weeks from now, depending on how things go), but you probably meant to ask about `1.8.11`?

We don't have any plans for a separate 1.8.10 bugfix release like 1.8.11, but if you absolutely cannot wait for 1.8.20, we can publish a dev build that you'll be able to use in the meantime, although it might come with other bugs :)
