### ISSUE TITLE
kotlin.collections mapped as <ERROR CLASS>

### ISSUE THREAD

**Issue by petersamokhin** [Kotlin/dokka#290]
There is my code:
```
/**
 * blah-blah-blah
 */
private val audioBytes: ArrayList<Byte> = ArrayList()
```

And the kdoc:
<img width="708" alt="screen shot 2018-03-26 at 13 19 28" src="https://user-images.githubusercontent.com/20628184/37900935-5911945c-30f8-11e8-8628-f3b49394a551.png">

`kotlin.collections.ArrayList` used.

Dokka: `org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.16`, Kotlin: `1.2.31`.

**Comment by semoro** [comment]
How you configured Dokka?

**Comment by petersamokhin** [comment]
@semoro 
`"org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.16"`

```
dokka {
    outputFormat = 'html'
    outputDirectory = "$buildDir/javadoc"

    sourceRoot {
        path = ""
        platforms = ["JVM"]
    }

    sourceDirs += files('opme/src/main/kotlin')

    packageOptions {
        prefix = "kotlin"
        skipDeprecated = false
        reportUndocumented = true
        includeNonPublic = true
    }

    externalDocumentationLink {
        url = new URL("https://developer.android.com/reference/")
        packageListUrl = new URL("https://developer.android.com/reference/android/support/package-list")
    }
}
```

**Comment by semoro** [comment]
Does kotlin-plugin apply to project where is Dokka being configured?

**Comment by petersamokhin** [comment]
#### Project-level `build.gradle`:
```groovy
// ...
buildscript {
    // ...
    dependencies {
        // ...
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.16"
        // ...
    }
}
// ...
apply plugin: 'org.jetbrains.dokka-android'
apply from: 'javadoc.gradle'
// ...
```

#### `javadoc.gradle`:
You can see it in my previous message ([link](https://github.com/Kotlin/dokka/issues/290#issuecomment-376919388))

**Comment by semoro** [comment]
If the issue still not resolved you can try sending me Gradle logs with `--debug` option

**Comment by kamilok1965** [comment]
Hi @petersamokhin, is this still relevant?
