### ISSUE TITLE
Dokka ignores module and packages documentation

### ISSUE THREAD

**Issue by dscoppelletti** [Kotlin/dokka#2902]
**Describe the bug**
Dokka ignores module and packages documentation from the README.md configured in build.gradle

**Expected behaviour**
Dokka should generate documentation for the module e for the packages picking from README.md

**To Reproduce**
Sample project http://github.com/dscoppelletti/dokka-sample

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```
dokkaHtml {
    configure {
        outputDirectory.set(project.file('dokka'))
        moduleName.set(project.name)
        moduleVersion.set(project.version)
        suppressObviousFunctions.set(false)
        suppressInheritedMembers.set(true)
        offlineMode.set(true)
        dokkaSourceSets {
            named('main') {
                documentedVisibilities.set([
                        DokkaConfiguration.Visibility.PUBLIC,
                        DokkaConfiguration.Visibility.PROTECTED])
                skipDeprecated.set(false)
                reportUndocumented.set(false)
                skipEmptyPackages.set(true)
                platform.set(Platform.jvm)
                noJdkLink.set(true)
                noAndroidSdkLink.set(true)
                suppressGeneratedFiles.set(true)
                includes.from('README.md')
            }
        }
        pluginsMapConfiguration.set([
                "org.jetbrains.dokka.base.DokkaBase": """{
"footerMessage" : "Copyright(C) ${copyrightYear} <a href='${developerUrl}'>${developerName}</a>",
"customStyleSheets" : [ "${project.file('etc/logo-styles.css')}" ]
}"""
        ])
    }
}
```

**Installation**
- Operating system: macOS 13.2.1
- Build tool: Gradle 7.5
- Dokka version: 1.7.20

**Comment by IgnatBeresnev** [comment]
Hi! I would strongly suggest to move to Kotlin build scripts :)) 

If you add the following import to the `build.gradle` file, it'll work:
```
import org.jetbrains.dokka.Platform
```

The problem is likely that the Groovy script cannot find the type for `platform.set(Platform.jvm)` and is thus failing with some internal error, not applying the rest of the settings. Not sure if it's the default behaviour of groovy scripts or if it's caused by Dokka's configuration parsing
