### ISSUE TITLE
[Question] Export docs from different modules

### ISSUE THREAD

**Issue by jahirfiquitiva** [Kotlin/dokka#292]
Hello

I am wondering if there's an easy way to generate different modules docs with a single task

My project modules are basically:
```
app
commons
model
|-local
|-remote
viewmodels
```

And I would like to generate the docs from all of them

Thanks in advance :grinning:

**Comment by semoro** [comment]
There was a discussion on how to achieve that in #157

**Comment by Kordyjan** [comment]
Since 1.4.0 there are two task for that `dokkaHtmlMultimodule` and `dokkaHtmlCollector`. We are constantly working on improving them. See #1265 and #1387 .
