### ISSUE TITLE
dokka documentation format

### ISSUE THREAD

**Issue by pavithapichai** [Kotlin/dokka#2922]
i have generated documentation in HTML format for my android project using dokka. can anyone tell me if i want to create documentation in PDF or word, is that format available in dokka? or anyother tool or any other way
can anyone suggest?

**Comment by IgnatBeresnev** [comment]
Hi! At the moment, Dokka only has HTML and Markdown output formats, there's no way to generate documentation in PDF or Word formats out of the box.

 If you really to have your API reference in PDF or Word, you could either convert the generated HTML website into PDF or write a custom output format, but the latter is not easy to do (see [Developer Guides](https://kotlin.github.io/dokka/1.8.10/developer_guide/introduction/) for how to get started)

**Comment by pavithapichai** [comment]
Thanks for your quick reply! it seems this product so reliable

can we expect dokka will support doc and PDF format? Is it possible?

**Comment by IgnatBeresnev** [comment]
> can we expect dokka will support doc and PDF format? Is it possible?

I don't think we can say for sure :) Maybe one day, but not in the foreseeable future. I know there are community plugins for generating documentation in JSON and other non-standard formats, so maybe someone will actually implement it sooner.
