### ISSUE TITLE
Add documentation on how to add custom output formats

### ISSUE THREAD

**Issue by fbenz** [Kotlin/dokka#293]
Dokka makes it easy to add custom output formats, but only after ones figures out how to do it and it took me quite some time to figure it out. Therefore, I suggest to add documentation on how to add custom output formats and I'm willing help. My suggestion is to add a separate Markdown file and link to it in the main Readme.

My experience on building a custom output format is summarised in a [Medium post](https://medium.com/@flbenz/how-does-kotlins-documentation-engine-dokka-work-and-can-it-be-extended-5e83dc663ef7). The resulting Dokka extension `spring-auto-restdocs-dokka-json` can be found [here](https://github.com/ScaCap/spring-auto-restdocs/tree/master/spring-auto-restdocs-dokka-json).

After I finished the Dokka extension, I also found https://github.com/Kotlin/dokka/issues/279 and https://github.com/Kotlin/dokka/issues/288. Even this information would have helped me to get started.

What do you think?

**Comment by mkrussel77** [comment]
When I try to use the `dokkaFatjar` property, I get an Unresolved reference error.

```
val dokka by tasks.getting(org.jetbrains.dokka.gradle.DokkaTask::class) {
    dokkaFatjar = "myvalue"
```

`Unresolved reference: dokkaFatjar`

So the previous tickets seem to be out of date.

**Comment by Kordyjan** [comment]
New dokka has its own plugin system. PR with its documentation: #1412
