### ISSUE TITLE
Whitespace between two formatted elements is lost

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/dokka#2942]
**Describe the bug**
<https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-shared-flow/try-emit.html> is formatted on Firefox 109.0.1 as "`SUSPEND`**and**", but in the actual KDoc, there's a space between the two elements.

**Expected behaviour**
A space should be displayed.

**Screenshots**
![Screenshot 2023-03-27 at 12-11-51 tryEmit](https://user-images.githubusercontent.com/52952525/227912640-8fdd673a-0ff8-4f19-9cf5-d60a55d519df.png)

**To Reproduce**
<https://github.com/Kotlin/kotlinx.coroutines/tree/1.6.4>

**Comment by IgnatBeresnev** [comment]
Thanks for the report! I believe this was [fixed](https://github.com/Kotlin/dokka/pull/2640) in Dokka 1.7.20, and the API reference should be updated with the next coroutines release

We can wait until then to make sure it's really gone

**Comment by IgnatBeresnev** [comment]
Thanks for the report! I believe this was [fixed](https://github.com/Kotlin/dokka/pull/2640) in Dokka 1.7.20, and the API reference should be updated with the next coroutines release

We can wait until then to make sure it's really gone

**Comment by IgnatBeresnev** [comment]
It has indeed been fixed :tada: 

![2023-05-19_23-33-41](https://github.com/Kotlin/dokka/assets/22685910/209941cd-6d22-481d-82f6-091b4584ef6d)

Closing the issue as completed then
