### ISSUE TITLE
With maven, how to specify that only generate docjar, without the html resources in directory `dokkaJavadocJar` 

### ISSUE THREAD

**Issue by light0x00** [Kotlin/dokka#2945]
**Question**
With maven, how to specify that only generate `jardoc.jar`, without the html resources in directory `dokkaJavadocJar` .

For my purporse, to generate javadoc, is only for satisfing the rule of the Maven Central.  
It's not useful for me, the directory `dokkaJavadocJar` 

**Screenshots**
<img width="324" alt="image" src="https://user-images.githubusercontent.com/29830476/228158947-1c358fd2-96ee-4a59-9dd7-f6e2b4c21886.png">

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v6.8.0/Maven/Cli/3rd party plugin
- Dokka version: 1.8.10

**Additional context**

**Comment by IgnatBeresnev** [comment]
I don't think there's a way to do that or if it even makes sense :)

The contents of the `javadoc.jar` are the contents of the directory `dokkaJavadocJar`. It works the same way as any other `.jar` generating task would: first build whatever you need to package, then package it. 

For instance, when you run `mvn package`, it first compiles the code (creating a `classes` directory just like `dokkaJavadocJar`), and only then it creates a `.jar` with that compiled code.

If the `dokkaJavadocJar` directory is annoying you, you can delete it manually, via a script or a Maven plugin once the `javadoc.jar` has been built. I'm not sure there's another way to achieve what you want though
