### ISSUE TITLE
How to configure KDoc/dokka for both private and overridden methods?

### ISSUE THREAD

**Issue by dpergarc** [Kotlin/dokka#2955]
**Question**
How can I set-up the build.gradle file in order to generate documentation regarding both private and overridden methods? Please, find attached some screenshots with the example I am trying at the moment.

**Screenshots**
Current build.gradle file configuration for Intellij IDEA:
![image](https://user-images.githubusercontent.com/100282902/229489191-2785625a-4683-454d-a23a-9876d46be1e5.png)

The kotlin file used as an example:
![image](https://user-images.githubusercontent.com/100282902/229489486-a05ff71e-ddf3-4b7b-8d3d-b56d25aee8f5.png)

**Installation**
- Operating system: Windows
- Build tool: Gradle
- Dokka version: 1.8.10
- Development IDE: Both Intellij IDEA and Android Studio

**Additional context**
None for now.

**Comment by IgnatBeresnev** [comment]
What exactly isn't working with your example and configuration?

If you can't see the private method, it might be a groovy-script related problem where Gradle/Groovy cannot resolve the visibility enum. Try changing it to

```groovy
documentedVisibilities.set([
    org.jetbrains.dokka.DokkaConfiguration.Visibility.PUBLIC,
    org.jetbrains.dokka.DokkaConfiguration.Visibility.PRIVATE
])
```

**Comment by dpergarc** [comment]
Hi @IgnatBeresnev,

Thank you very much for your reply! We suspected it was a Gradle/Groovy file "issue", so we have changed it to a .kts one, since most examples are written in that format.

Right now, everything is working fine, but in any case, we will take notes of your response in case we need it in the nearby future.

Kind regards.
Daniel.
