### ISSUE TITLE
Missing spaces on Markdown

### ISSUE THREAD

**Issue by SebastianAigner** [Kotlin/dokka#2957]
See "context/does not" on
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/flow-on.html

<img width="1458" alt="Screenshot 2023-04-05 at 19 39 31" src="https://user-images.githubusercontent.com/2178959/230160367-6fa12048-2ef3-40c4-be82-c2cafb271083.png">

**Comment by IgnatBeresnev** [comment]
It has indeed been fixed :tada: 

![2023-05-19_23-27-57](https://github.com/Kotlin/dokka/assets/22685910/f3b1b4bb-85df-4469-9ea6-c41705b124a0)

Closing the issue as completed
