### ISSUE TITLE
'Throws' clause is too large

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/dokka#2959]
Take a look at the page for serializer() function: https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/serializer.html

It has several overloads, each with `@throws` in KDoc. When rendered, word `Throws` is large than the overload name itself, which ultimately distracts attention and puzzles users. IMO it shouldn't be that big. Maybe it should be as big as a level 3 or 4 header (see `Constraints` for the last overload on the same page).

**Comment by IgnatBeresnev** [comment]
It was changed in Dokka 1.7.20, I believe. Now it looks the following way (I'll explain how to get the link to the preview in DMs):

![image](https://user-images.githubusercontent.com/22685910/231267087-1c755b89-27fd-4646-80ac-5d8564c3daac.png)

Is this an acceptable solution? :)

**Comment by sandwwraith** [comment]
Yes!
It seems you have to merge your PR with update so I can stop filing obsolete bugs(

**Comment by IgnatBeresnev** [comment]
@sandwwraith the API reference for serialization has been updated, can you please have a look and say if the issue is still relevant?
