### ISSUE TITLE
HTML: Sidebar not visible on mobile

### ISSUE THREAD

**Issue by aSemy** [Kotlin/dokka#2965]
## Describe the bug

Affects Dokka 1.8.10

1. Open a Dokka site on a mobile device (or use dev tools to simulator a mobile view [Chrome](https://developer.chrome.com/docs/devtools/device-mode/) [Firefox](https://firefox-source-docs.mozilla.org/devtools-user/responsive_design_mode/) [Safari](https://www.browserstack.com/guide/use-safari-devtools-to-view-mobile-web-pages))
2. Open the sidebar
3. The sidebar is white, and is not visible

## Expected behaviour

Side bar is visible

#### Coroutines

<img width="428" alt="image" src="https://user-images.githubusercontent.com/897017/232702722-c32a31df-975f-4c18-8420-f19e0c4a8c48.png">

https://kotlinlang.org/api/kotlinx.coroutines/

#### Gradle

<img width="427" alt="image" src="https://user-images.githubusercontent.com/897017/232701904-ab1310f2-83e7-48e7-9eab-ae0f3ae2a551.png">

https://docs.gradle.org/nightly/kotlin-dsl/index.html

#### Dokkatoo 

https://adamko-dev.github.io/dokkatoo/

<img width="403" alt="image" src="https://user-images.githubusercontent.com/897017/232702056-3a37e621-2383-4f34-a3ef-16a03c016338.png">

Note that the sidebar is visible in landscape mode

<img width="893" alt="image" src="https://user-images.githubusercontent.com/897017/232702299-5667fcf7-e9f0-41df-8b50-7cae86a871ba.png">

## Installation

- Dokka version: 1.8.10

**Comment by IgnatBeresnev** [comment]
Fixed, and it will be released in 1.9.0 :tada:
