### ISSUE TITLE
Gradle plugin: `pluginsConfiguration` contains absolute path, creating remote build cache misses

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/dokka#2978]
Hi 👋 

Trying to enable remote build cache on apollo-kotlin, dokkaHtml creates a lot of cache misses ([build scan](https://ge.apollographql.com/c/v5yyebb65cybm/ecqifubpevz3q/task-inputs?cacheability=cacheable,overlapping-outputs,validation-failure)).

This is due to custom assets containing absolute paths. For an example, dumping the value of `pluginsConfiguration` in `apollo-annotations`:

```kotlin
tasks.named("dokkaHtml") {
  doLast {
    println(inputs.properties.get("pluginsConfiguration"))
  }
}
```

Dumps this:

```
[PluginConfigurationImpl(fqPluginName=org.jetbrains.dokka.base.DokkaBase, serializationFormat=JSON, 
values={"customStyleSheets":["/Users/mbonnin/git/apollo-kotlin/dokka/style.css","/Users/mbonnin/git/
apollo-kotlin/dokka/prism.css","/Users/mbonnin/git/apollo-kotlin/dokka/logo-styles.css"],"customAssets":
["/Users/mbonnin/git/apollo-kotlin/dokka/apollo.svg"],"separateInheritedMembers":false,"footerMessage":
"© 2023 Copyright","mergeImplicitExpectActualDeclarations":false,"templatesDir":null})]
```

Related to https://github.com/Kotlin/dokka/issues/2700

**Comment by whyoleg** [comment]
Should not be an issue in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html)
