### ISSUE TITLE
What is the state of this library?

### ISSUE THREAD

**Issue by hzsweers** [Kotlin/dokka#299]
This library is currently not compatible with modern android builds, and seems to only be released on an ad-hoc basis. The current 0.9.17 milestone has not seen any progress in months either, there are a list of outstanding unacknowledged issues and PRs, and as a user I am hesitant to depend on this. At the same time though, this is the tool recommended in kotlin documentation for doc generation. Is there any plans to pick up more active development or release cycles?

**Comment by semoro** [comment]
Please, report a problem with android compatibility separately. There are actual plans on contributing more time to Dokka, but I can't tell when it happens. Currently, I'm the only maintainer of Dokka and don't work full-time on it.

**Comment by hzsweers** [comment]
It's already been reported separately - https://github.com/Kotlin/dokka/issues/282

That's unfortunate to hear, as it seems this should be a core component of Kotlin's offering for library developers.

**Comment by semoro** [comment]
So, as the question answered, closing now.
