### ISSUE TITLE
option to display all elements of a Class at the same time (DokkaHTML)

### ISSUE THREAD

**Issue by tryadelion** [Kotlin/dokka#2991]
Within the DokkaHtml results, the different elements (Types, Constructors, Functions, Properties, Parameters) come in a tabulated structure that hides the unselected ones.
I'd like, if possible, to be able to tell Dokka to display them all at once, for readability and ease of use, without the tabbed structure.

**Comment by IgnatBeresnev** [comment]
This was actually implemented in 1.8.10 for class-like declarations (classes, interfaces, enums, etc) - there's now a single "Members" tab.

See this for example: https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-contextual-serializer/

Would you say it's sufficient?

**Comment by tryadelion** [comment]
seems like that would do it, will test tomorrow.

**Comment by IgnatBeresnev** [comment]
Hopefully, the silence means that it indeed was what you were looking for :)

I'll close this issue as implemented, but please tell us if you meant something else and we'll reopen it.
