### ISSUE TITLE
@constructor, @sample doesn't work

### ISSUE THREAD

**Issue by KenjiOhtsuka** [Kotlin/dokka#300]
I'm using Dokka 0.9.16.

I used `@Constructor` tag like the sample in https://kotlinlang.org/docs/reference/kotlin-doc.html as follows.

There, I wrote `print 1`, but in the output html, I can't found such description.

Regarding to `@sample`, I used it as follows, I wrote `test4` but I couldn't found any sample description in the document.

```
package kdoc

/**
 * This is **sample** class
 *
 * em tag *em*,
 * strong tag **strong**
 *
 * [Google](http://google.com)
 *
 * @see AnotherSample
 * @see test2
 *
 * @constructor print 1
 */
class Sample {
    init {
        println(1)
    }

    /**
     * First test method for KDoc
     *
     * this method has parameter [a]
     *
     * @param a good parameter
     */
    fun test1(a: Int) {
        1 + 1
    }

    /**
     * Second test method for KDoc
     *
     * @Deprecated aaaa
     * @since 0.0.1
     * @author Kenji Otsuka
     * @sample test4 this is sample
     * @return Unit
     */
    fun test2() {

    }


    /**
     * Third test method for KDoc
     *
     * @suppress
     */
    fun test3() {

    }

    /**
     * This method uses [test2]
     */
    fun test4() {
        test2()
    }
}
```

### Class output

![sample1](https://user-images.githubusercontent.com/1572810/39412224-08cbd5b2-4c54-11e8-802e-5de407e04e52.PNG)

### test2

I expected `@sample` tag output

![sample2](https://user-images.githubusercontent.com/1572810/39412227-0c17a606-4c54-11e8-9a5d-a00753b72142.PNG)

### init description

![sample3](https://user-images.githubusercontent.com/1572810/39412228-0f94988e-4c54-11e8-8faf-ae26bdabc943.PNG)

**Comment by semoro** [comment]
1. I see, `@constructor` doesn't work as your class have an only implicit no-arg constructor, this is a bug 
2. In the document that you pointed, it showed, that `@sample` tag is `@sample <identifier>`, no description for sample tag supported yet.

**Comment by KenjiOhtsuka** [comment]
when I added argument to the constructor it appears.

**Comment by KrystianUjma** [comment]
@semoro @KenjiOhtsuka creater PR [here](https://github.com/Kotlin/dokka/pull/417)
