### ISSUE TITLE
Can pkgOptions be combined into one block being applied to an array of packages

### ISSUE THREAD

**Issue by harishrpatel** [Kotlin/dokka#301]
In Issue #266, a workaround was posted to do this, but can there be a proper way to pass in array of packages to pkgOptions? It will be real helpful when we are trying to apply the same options for 10-15 packages.

<pre>
dokka {
   for (def pkg : ["abc", "cda", /* other prefixes */]) {
      packageOptions {
          prefix = pkg
          reportUndocumented = false
      }
   }
}
</pre>

**Comment by achmyr** [comment]
Hi @semoro, is this still a viable issue? If so, I have a simple fix for it, but need to know if it would be appropriate just to to have `prefix = "abc,cda"` or some other delimiter to conform with CLI parameters?
Thanks,
Alex

**Comment by kamilok1965** [comment]
I think prefix that takes a `List` would be nice. We don't necessarily have to have an identical API in the CLI and Gradle or Maven (we should be able to achieve the same functionality though. Maybe a `List` in Gradle and String delimited with commas in CLI?  
If you want to fix this however, please wait a little more and create a PR to `dev-0.11.0`, as the internal model changed almost completely

**Comment by kamildoleglo** [comment]
Dokka 1.4.20+ has a regex instead of prefix, so this should be fairly easy to accomplish
