### ISSUE TITLE
Unable to build KDoc under JDK9

### ISSUE THREAD

**Issue by matteo-grella** [Kotlin/dokka#303]
With Java 9.0.1

```
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

When trying to build the KDoc using dokka 0.9.16 with the maven plugin:

```
 <plugin>
    <groupId>org.jetbrains.dokka</groupId>
    <artifactId>dokka-maven-plugin</artifactId>
    <version>${dokka.version}</version>
    <executions>
        <execution>
            <phase>prepare-package</phase>
            <goals>
                <goal>dokka</goal>
                <goal>javadoc</goal>
                <goal>javadocJar</goal>
            </goals>
            <configuration>
                <includes>
                    <file>packages.md</file>
                </includes>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I get the following error:

`[ERROR] Failed to execute goal org.jetbrains.dokka:dokka-maven-plugin:0.9.16:dokka (default) Execution default of goal org.jetbrains.dokka:dokka-maven-plugin:0.9.16:dokka failed: Plugin org.jetbrains.dokka:dokka-maven-plugin:0.9.16 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.8.0 at specified path /usr/local/java/jdk-9.0.1/../lib/tools.jar -> [Help 1]`

**Comment by semoro** [comment]
Fixed in 0.9.17, duplicates #272
