### ISSUE TITLE
Maven dokka:help

### ISSUE THREAD

**Issue by binkley** [Kotlin/dokka#3035]
**Is your feature request related to a problem? Please describe**
I'd like to get command line help in Maven when using Dokka.

**Describe the solution you'd like**
Ideally, I can run `mvn dokka:help` to see descriptions of goals for the Maven Dokka plugin. This is common practice with many Maven plugins, though not an enforced guideline from Apache.

**Describe alternatives you've considered**
Manual researching in the web.

**Are you willing to provide a PR?**
Possibly. I can check if it is quick to do.

**Comment by aSemy** [comment]
A help task [should be generated](https://github.com/Kotlin/dokka/blob/bb1c1514b5c4e94fd823517d9b94b1b264c99b4c/runners/maven-plugin/build.gradle.kts#L58-L85), but perhaps it was lost during #2911

**Comment by binkley** [comment]
That was fast! 😃 
Thanks 🙏
