### ISSUE TITLE
AGP 4.1? is that correct?

### ISSUE THREAD

**Issue by chrisjenx** [Kotlin/dokka#3037]
**Question**
Is this a Typo? 

> "Update Kotlin Gradle Plugin to 1.8.10 and Android Gradle Plugin to 4.1.3."

**Additional context**
Currently AGP 8.0.x is current release, this is about 6 major versions behind?

**Comment by aSemy** [comment]
Hi 👋, I'm just a contributor so this isn't an official response, but I thought I'd try answering.

[AGP skipped versions 5 and 6](https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html), so Dokka isn't _that_ far behind. 

Additionally, Dokka doesn't make much use of AGP. It's only used in DGP (Dokka Gradle Plugin) to determine some defaults for creating the configuration that's provided to actual Dokka Generator. 

https://github.com/Kotlin/dokka/blob/26112637ba3511afc218fbe0ead6f72421ac7c77/runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt#L17-L28

So even if DGP didn't support the latest AGP, those defaults could be set manually instead. Which would be very inconvenient, but not breaking.

However, I believe that ApplicationVariant and LibraryVariant are deprecated in AGP 8, and are to be removed in AGP 9, so it will be more of an issue soon. https://developer.android.com/build/releases/gradle-plugin-roadmap#agp_80_mid-2022

[Dokka has an Android integration test project](https://github.com/Kotlin/dokka/tree/master/integration-tests/gradle/projects/it-android-0) - this should probably be updated to target newer AGP versions

**Comment by chrisjenx** [comment]
Makes sense, yeah those old VariantAPIs are replaced in favor of the better DSL ones which are a little easier to use and much more friendly defered execution and config cache. 

No worries, it seems to work for us using AGP 8, so I guess I might update the project if it comes a problem when 9.0 comes along (First half of 2023... I guess they need to update there roadmap, lol)

Cheers

**Comment by IgnatBeresnev** [comment]
Hi! Yeah, @aSemy's answer was pretty much on point :) We also didn't know about the AGP 9 plans, we should indeed keep it in mind, thanks!

In that regard, we only care that the officially supported versions are supported by Dokka as well, you can find the compatibility matrix [on kotlinlang](https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin).

<img width="909" alt="image" src="https://github.com/Kotlin/dokka/assets/22685910/fa5887e0-5c6c-4a15-8678-3935d4b2a661">

Unfortunately, at the moment we don't have the resources to update AGP proactively ourselves, so for now it indeed just works and it's good enough, we don't update it unless we have to (like in the previous release). Ideally, one day we'll get to addressing Android-related issues as they've been piling up, and we can figure something out with AGP then :)

I'll close the issue as resolved, let us know if you have any further questions
