### ISSUE TITLE
Multiplatform: docs don't contain KDoc attached to expect members

### ISSUE THREAD

**Issue by Egorand** [Kotlin/dokka#307]
I've got an `expect class` in a common module with KDoc for class and its members. The JVM module contains the `actual class`, and when I run Dokka over that module I don't see the docs. The only way to make this work is to copy KDoc into the `actual class`, which I'd like to avoid. Am I missing any configuration steps, or it's something that isn't supported yet?

**Comment by semoro** [comment]
Currently multiplatform is not supported yet.

**Comment by Egorand** [comment]
Thanks @semoro! Any ETA on when it's gonna be available?

**Comment by KrystianUjma** [comment]
it works, multiplatform release is coming soon.
