### ISSUE TITLE
Dokka 1.9.0 incompatible with templates from previous version

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3084]
**Describe the bug**
I have a project with Dokka 1.8.20 that uses customized templates. I've updated the project to Dokka 1.9.0 and regenerated the documentation. The UI is broken
<img width="700" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/c2aed95b-a29d-41bc-86d3-c0103beb1822">

If there is no way to keep the previous templates compatible (after changes in #2836) then I expect a migration guide.
But probably we have to estimate number of users of such templates.

**Installation**
- Dokka version: 1.9.0

**Comment by IgnatBeresnev** [comment]
Added a section about it to the 1.9.0 release notes. 

Unfortunately, the changes were necessary, and there's not much else we can do about it now, so I'll close the issue
