### ISSUE TITLE
Dokka 1.9.0 version label/dropdown is not centered

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3085]
**Describe the bug**
With label
<img width="420" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/71c9dd41-dcba-4b0a-95b1-dd0ca49e628c">
With dropdown
<img width="337" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/54053eb5-fab5-47f9-a004-5c9ad0e78bea">

The label with the version moved up a bit. 

Or is it a design decision?

**Comment by atyrin** [comment]
Oh, I see. It is similar to the [kotlilang.org](https://kotlinlang.org)
<img width="160" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/e25675c4-b840-4e86-b14b-2d3bf1811a4f">

If I'm correct, feel free to close the issue.

**Comment by IgnatBeresnev** [comment]
I didn't actually think that the version drop-down would be affected..

@zoobestik @nikpachoo do you think it's OK or is it not desired / expected?

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
