### ISSUE TITLE
Dokka 1.9.0 samples is not rendered

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3087]
**Describe the bug**
Samples are rendered as plain text
<img width="564" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/180654d1-dd86-461a-a8ab-748fa175402b">

For 1.8.20 I see `<script src="https://unpkg.com/kotlin-playground@1"></script>` in the `<head/>`. In 1.9.0, there is no such dependency.

**Installation**
- Dokka version: 1.9.0

**Comment by gleb-skobinsky** [comment]
This issue references dokka 1.9.0. How can I get access to this version? The latest version that I can add successfully to gradle scripts is 1.8.20, nor can I find 1.9.0 in the releases section on Github.

**Comment by IgnatBeresnev** [comment]
@gleb-skobinsky it hasn't been released it, we're still in the process of testing it and fixing various regressions. Unfortunately, we came across some serious problems, so I can't promise any specific timeline for when it's going to be released, but we're fairly close :)
