### ISSUE TITLE
An extra space before Java declarations without access moidifier

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3095]
The annotation

```Java
@interface JavaAnnotationWithSpace{}
```

rendered in Dokka as
<img width="746" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/bc64521c-98ee-4c20-99f3-1832bbc9a9a8">

But fine for 

```Java
public @interface JavaAnnotationWithSpace{}
```

NB: For rendering such declaration extra settings required
```kotlin
tasks.dokkaHtml.configure {
    dokkaSourceSets {
        configureEach {
             // ...
            documentedVisibilities.set(
                setOf(
                    // ...
                    org.jetbrains.dokka.DokkaConfiguration.Visibility.PACKAGE
                )
            )
        }
    }
}
```

**Installation**
- Dokka version: 1.9.0 / 1.8.20

**Comment by IgnatBeresnev** [comment]
* It's likely that @berezinant will tackle this problem as part of his onboarding. It's a good issue because it deals with the common `content` layer, but the result is visible in HTML
* I'll help, we'll do pair programming
