### ISSUE TITLE
Documentation is not generated on 1.8.20 with KMP Multimodule project

### ISSUE THREAD

**Issue by Nek-12** [Kotlin/dokka#3107]
**Describe the bug**
The documentation is not generated despite the task completing successfully with Kotlin 1.9, Dokka 1.8.20 and a KMP project

**Expected behaviour**
The documentation is generated or the task fails explaining what went wrong

**Screenshots**
You can visit the javadocs site to see how it looks:
https://opensource.respawn.pro/FlowMVI/javadocs/index

**To Reproduce**
See the project https://github.com/respawn-app/FlowMVI

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
plugins {
    alias(libs.plugins.dokka)
}

subprojects {
    apply(plugin = rootProject.libs.plugins.dokka.id)

    dependencies {
        dokkaPlugin(rootProject.libs.dokka.android)
    }

    tasks {
        withType<AbstractDokkaTask> {
            val className =
                "org.jetbrains.kotlin.gradle.targets.native.internal.CInteropMetadataDependencyTransformationTask"

            @Suppress("UNCHECKED_CAST")
            val taskClass = Class.forName(className) as Class<Task>
            parent?.subprojects?.forEach {
                dependsOn(it.tasks.withType(taskClass))
            }
        }

        register<org.gradle.jvm.tasks.Jar>("dokkaJavadocJar") {
            dependsOn(dokkaJavadoc)
            from(dokkaJavadoc.flatMap { it.outputDirectory })
            archiveClassifier.set("javadoc")
        }
    }
}

tasks {
        dokkaHtmlMultiModule.configure {
            moduleName.set(rootProject.name)
            outputDirectory.set(buildDir.resolve("dokka"))
    }
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle 8.2
- Dokka version: 1.8.20
- Kotlin 1.9

**Are you willing to provide a PR?**
I don't know what's wrong to provide a PR

**Comment by IgnatBeresnev** [comment]
Would you be able to tell us what exact problem you're running into? Maybe a stacktrace or a description of what is happening?

**Comment by Nek-12** [comment]
I already described my problem in the issue description. The documentation is not generated. No stacktraces are produces. The console prints the tasks as if they were executed.

**Comment by Nek-12** [comment]
This also applies to the html documentation

**Comment by IgnatBeresnev** [comment]
I've cloned the project locally, [commented out](https://gist.github.com/IgnatBeresnev/fdbe4f66d67fa6e6757611679852944f) the scary Dokka configuration blocks, and run `./gradlew clean dokkaHtmlMultiModule --no-configuration-cache`. The documentation is successfully built:

![2023-08-16_19-42-13](https://github.com/Kotlin/dokka/assets/22685910/b85f91da-6556-4cc4-b9b2-8d49cc532746)

___

Is there any reason you're configuring `CInteropMetadataDependencyTransformationTask` and task dependencies?

**Comment by Nek-12** [comment]
Yes, because of https://github.com/Kotlin/dokka/issues/2977

**Comment by IgnatBeresnev** [comment]
[Dokka 1.9.0](https://github.com/Kotlin/dokka/releases/tag/v1.9.0) has been released, and it includes some workarounds for this problem. See the following issue for details:
* https://github.com/Kotlin/dokka/issues/3153

___

To avoid the spread of information and have updates in a single place, I'll close this issue and a few others as duplicates in favour of #3153.
