### ISSUE TITLE
Help migrate stdlib to Dokka 1.9.0

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3111]
Dokka 1.9.0 introduces some [breaking changes](https://github.com/Kotlin/dokka/issues/3099) that affect [stdlib's API reference](https://kotlinlang.org/api/latest/jvm/stdlib/) build.

The necessary changes were introduce to unblock the migration:

* [Fix and refactor Sample Transformer](https://github.com/Kotlin/dokka/pull/3102)
* [Introduce system property to ignore common builtIns for stdlib](https://github.com/Kotlin/dokka/commit/900fbccf3da483946227d99ce52b71afe0e62007)

It should now be possible to migrate stdlib to use Dokka 1.9.0 - we should make sure that it goes smoothly, and provide help if requested.

___

Definition of done: stdlib's API reference is built with Dokka 1.9.0 without any issues or new regressions.

**Comment by vmishenev** [comment]
#3118 and #3110 are related PR too.
[This is a commit ](https://github.com/vmishenev/kotlin/commit/55f5721acdefd290540fa2269f55dca933af60f8)to migrate to Dokka 1.9.0 (actually 1.9.10-dev)

**Comment by vmishenev** [comment]
#3126 is used instead of https://github.com/Kotlin/dokka/pull/3102 since a system property does not have the possibility to run tasks with different options.
