### ISSUE TITLE
Fix inconsistencies between K1 and K2

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3115]
Some existing unit tests are inconsistent with K2:
- In K1 Documentable Java field does not have modality modifiers. In K2 they have `open`.
- Order of constructors and inheritors is different in K1 and K2.
- Dokka K2 will not display anonymous members of entry anymore (see the motivation in https://github.com/Kotlin/dokka/issues/3129)
- #3179 (#3334)
- Bug in descriptors:
   - DRI of entry in annotations  should have `EnumEntryDRIExtra` (can affect generating of external link to enum entry)
   - #3128
   - #3377
- Bug in symbols:
   - #3129 
  
and so on. See other muted tests by `@OnlyDescriptors`. All `@OnlyDescriptors` applications have **a reason** parameter.

Insignificant ones:
- In K2, the name of the accessors parameter is `value`:  `isFoo(), setFoo(String isFoo)` vs `isFoo(), setFoo(String value)`. (test `JavadocAccessorNamingTest.verifySpecialIsRuleIsApplied`). It affects only as-java and javadoc plugins.

**Comment by IgnatBeresnev** [comment]
Blocked by #3129
