### ISSUE TITLE
Not rendering .md files

### ISSUE THREAD

**Issue by alexKatona** [Kotlin/dokka#315]
Hi there, 

format: html
I tried the includes where I included a readme.md but its not showing the formatted text in markdown. Is it possible to show it somehow ?

format: javadoc
here I dont even see anywhere the includes file

using the 0.9.17 version on android

    dokka {
        outputFormat = 'html'
        outputDirectory = "$buildDir/javadoc"
        reportUndocumented = false
        includes = ['readme.md']
    }

```
content:

# About
tbd
```

**Comment by semoro** [comment]
Please, check example on https://github.com/Kotlin/kotlinx.coroutines/blob/master/core/kotlinx-coroutines-io/README.md

Content after header `Package` will be shown on package page in html/javadoc

Content after header `Module` is shown on root module page in formats expect javadoc

**Comment by timmc** [comment]
I'm successfully getting package-level documentation in the `dokka:javadocJar` output, but not the module-level docs. This is how my markdown file starts:

```
# Module johnny

test test test

# Package org.timmc.johnny

...
```

So dokka is picking it up, but that first section is being ignored.

**Comment by Kordyjan** [comment]
This is an issue about markdown parsing from the old dokka. It should be here after 1.4.0-rc. If somehow it is still there feel free to reopen the issue.

**Comment by leonardoFreeTelly** [comment]
I'm getting the same issue that @timmc got. I am using `1.9.0`. 

Everything under `# Module mypackage` is not showing. Is it still an issue?
