### ISSUE TITLE
No member extensions in the index

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/dokka#3187]
**Describe the bug**
The index page of `Duration.Companion` showing members:
![image](https://github.com/Kotlin/dokka/assets/4257577/28e448e2-e090-4996-9f12-3d5ea06b5073)

The page of `Duration.Companion.days`:
![image](https://github.com/Kotlin/dokka/assets/4257577/d5466e28-a3f3-46b9-9700-cc90b9bcbfa8)

As you can see, the member extension functions `days` are not displayed in the containing object members list.

**Expected behaviour**
Member extension functions are displayed in members list of the containing class/object.

**Comment by IgnatBeresnev** [comment]
Note: The problem might be in `ExtensionExtractorTransformer`
