### ISSUE TITLE
[K2] Generic inherited members have own dedicated pages

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3196]
Generic inherited members should lead to pages of members from a superclass.

It happens due to [KT-62405]( https://youtrack.jetbrains.com/issue/KT-62405/Analysis-API-Symbols-SUBSTITUTIONOVERRIDE-have-no-overridden-symbols). 

Also, it leads to non-suppressed functions in enum: `compareTo`, `describeConstantable`, `getDeclaringClass`.

**Details**
KT-62405 results in an incorrect DRI that leads to creating a redundant page for generic inherited members.

After the fix, the following test should be added:
```kt
    @Test
    fun `generic inherited members should have correct dri`() {
        inlineModelTest(
            """
                |interface A<T> { fun x(): T }
                |interface B : A<Int> { }
                """
        ) {
            with((this / "function" / "B" / "x").cast<DFunction>()) {
                dri.classNames equals "A" 
                dri.packageName equals "function" 
                // callable ...
            }
        }
    }

```

__

User-facing: if B extends A and inherits a function, clicking on that function (inside B) leads to a separate page instead of to A (where it's declared).

**Comment by atyrin** [comment]
One more side effect: There are visible "obvious functions" `compareTo`, `describeConstable` and `getDeclaringClass` on enum pages. It should be gone in the default configuration (`suppressObviousFunctions =true`) after the fix.

**Comment by whyoleg** [comment]
In scope of #3349 there was added test which fails because of appearing of `getDeclaringClass`. Test is located in `ObviousAndInheritedFunctionsDocumentableFilterTest` in the end of file called `should not suppress toString, equals and hashcode of kotlin Enum`
