### ISSUE TITLE
documentation for mixed projects(Java + Kotlin)

### ISSUE THREAD

**Issue by lebedevsd1** [Kotlin/dokka#321]
Hello, I am having issues with generation Javadoc styled documentation for the project, containing both Kotlin and Java codebase.

Currently, I have found the only solution when you just separate sourcesets: `src/java and src/kotlin` and generate separate documentation with Javadoc and Dokka separately.
As far as I found Dokka cannot generate documentation for java properly. It misses method params and Javadoc itself is not complete.

Do you have any suggestions?

**Comment by semoro** [comment]
There are actually some problems with Javadoc, but it is planned to fix it. Please report concrete problems if possible. 
Dokka doesn't support mixing Javadoc with Dokka Javadoc, and it is not planned to be supported

**Comment by lebedevsd1** [comment]
So as far as I understand dokka cannot generate javadoc format for the Java sourcecode. There are problems with missing arguments, missing annotations, and it cannot handle any {@code/@param/@link} statments

**Comment by semoro** [comment]
Dokka should be able to handle `@code/@param/@link` and should be able to process Java sources correctly, problems with it is planned to be fixed in near future

**Comment by lebedevsd1** [comment]
@semoro is there any dates when will it be fixed?

**Comment by semoro** [comment]
@lebedevsd1 I can't give ETA

**Comment by Kordyjan** [comment]
After the rewrite (versions 1.4.0-rc and later) dokka can generate any output (html, markdown, gfm) from any sources (java, kotlin, even scala using an external plugin) in any combination.
