### ISSUE TITLE
Search dropdown stretches content more then viewport

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3214]
## Actual

After click on search, its content has more width then viewport

<details>
<summary>Screenshots</summary>

![image](https://github.com/Kotlin/dokka/assets/22685910/464d0b0f-cfb3-45bf-bbf0-2d6ab5ea53c4)

![image](https://github.com/Kotlin/dokka/assets/22685910/ce4ed57e-62d5-495f-817a-616a9b3b795a)

![image](https://github.com/Kotlin/dokka/assets/22685910/38920fb4-b1de-49b2-85c2-71026d161282)

</details>

<details>
<summary>Video</summary>

https://github.com/Kotlin/dokka/assets/22685910/1598cfae-9ab3-478a-ab5c-c6d18317370e

</details>

## Expected

Search popup content is adopted for viewport

## Details

Platform: mobile / all
Internal tracker: [KTL-977](https://youtrack.jetbrains.com/issue/KTL-977/Dokka-HTML-search-stretches-content-more-then-viewport), [KTL-1054](https://youtrack.jetbrains.com/issue/KTL-1054/There-is-no-scrolling-to-the-right-in-the-search-hints-window)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
