### ISSUE TITLE
ToC items are difficult to interact with

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3215]
## Problem

Table of Content items have a small area for interaction

## Proposed solution

It would be nice to expand the clickable zone for better user experience.

![image](https://github.com/Kotlin/dokka/assets/22685910/e0c836a7-7bd8-4032-8fe7-dfbc2f7fec00)

## Details

Platform: all
Internal tracker: [KTL-981](https://youtrack.jetbrains.com/issue/KTL-981/Dokka-HTML-Toc-items-is-hard-for-interaction)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
