### ISSUE TITLE
No hover for burger menu icon

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3218]
## Problem

No active and hover state for burger menu icons

![image](https://github.com/Kotlin/dokka/assets/22685910/14e2bd1b-bca6-4db7-9a0a-300787733d60)

## Expected

Highlight icons on tap, just like the search icon

## Details

Platform: mobile / all
Internal tracker: [KTL-987](https://youtrack.jetbrains.com/issue/KTL-987/Dokka-HTML-no-hover-for-burger-menu-icon)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
