### ISSUE TITLE
Incorrect hovers and focus states for platform filter

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3223]
## Expected

UI kit hover states should be respected:

![image](https://github.com/Kotlin/dokka/assets/22685910/4bf14b00-fa99-4332-bb32-af402c6c6f0a)

## Actual

The hover and focus states are different:

![image](https://github.com/Kotlin/dokka/assets/22685910/c2f24c24-9374-45b8-aff9-38b590a1ebf4)

## Details

Platform: desktop / all
Internal tracker: [KTL-976](https://youtrack.jetbrains.com/issue/KTL-976/Dokka-HTML-Incorrect-hovers-and-focus-states-for-platform-filter)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
