### ISSUE TITLE
Package Docs Not in Generated Javadoc

### ISSUE THREAD

**Issue by jdrider** [Kotlin/dokka#323]
I have package documentation in the included markdown file.  When dokka is used to generate html format documentation, all of the package documentation is present.  When the documentation is generated in the javadoc format, some package level docs are missing.

This documentation is defined in the following way.
```
# Package com.example.package
Example Package Description
```

**Comment by jdrider** [comment]
A reproduction project can be found here.  https://github.com/jdrider/dokka-package-description-example

In creating this example, I realized that this behavior occurs when there are Java files present in the package.  This issue is not observed when all files are Kotlin source.

**Comment by Kordyjan** [comment]
As far as I know, this issue was fixed during the rewrite of dokka (version 1.4.0-rc and later). If it is still present feel free to reopen it.
