### ISSUE TITLE
[K2] Add  a check that source roots do not intersect

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3239]
Different source sets should have disjoint source roots.
Otherwise, it causes
```
Modules are inconsistent
org.jetbrains.kotlin.utils.exceptions.KotlinIllegalStateExceptionWithAttachments: Modules are inconsistent
	at org.jetbrains.kotlin.analysis.low.level.api.fir.file.builder.LLFirFileBuilder$buildRawFirFileWithCaching$1.invoke(LLFirFileBuilder.kt:56)
```

Reproducer: add two source sets with the same source root.

**Note:** It can complicate the StdLib setting.

**Comment by IgnatBeresnev** [comment]
Filed an issue to have this check added in KGP as well: https://youtrack.jetbrains.com/issue/KT-62829/Add-a-check-that-two-source-sets-cannot-have-the-same-file-system-directory

But Dokka should also have it because it's possible to misconfigure it manually in CLI and Maven runners.
