### ISSUE TITLE
Parameter of type UByte causes error in generated documentation

### ISSUE THREAD

**Issue by TorfsD** [Kotlin/dokka#3243]
**Describe the bug**
```
fun test1(a: UByte)  {
}
```
results in 
![image](https://github.com/Kotlin/dokka/assets/67414821/0ac1cfb9-3265-4be4-a34c-52047c068ac3)

**Expected behaviour**
I would expect the UByte paramater type to be shown. 

**To Reproduce**
```
java -jar jars/dokka-cli-1.9.0.jar -pluginsClasspath "./jars/dokka-base-1.9.0.jar;./jars/analysis-kotlin-descriptors-1.9.0.jar;./jars/kotlinx-html-jvm-0.8.0.jar;./jars/freemarker-2.3.31.jar" -sourceSet "-src dokka-test" -outputDir "./dokka/html"
``` 
where dokka-test contains the test file described above.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin

```

**Installation**
- Operating system: Linux
- Build tool: Cli
- Dokka version: 1.9.0

**Additional context**
None

**Are you willing to provide a PR?**
Maybe, but I would need some pointers.

**Comment by vmishenev** [comment]
You have not assigned a classpath for your source sets. The classpath should contains a path to stdlib to find `UByte`.
See  https://kotlinlang.org/docs/dokka-cli.html#source-set-options (`classpath` option)
For example `-sourceSet "-src dokka-test -classpath ./libs/kotlin-stdlib-1.9.10.jar"`.
You can download stdlib's artifacts [here](https://central.sonatype.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/versions)

**Comment by TorfsD** [comment]
@vmishenev Thanks, that fixed it!
