### ISSUE TITLE
Compare `DokkaSourceSetImpl` by `DokkaSourceSetID` only

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3246]
## Context

This issue is a small subtask of #2620. Whereas the parent issue has a wider scope and will take more time to address, this issue should be easy and quick to resolve, but at the same time it should yield noticeable performance and other improvements.

## Background

`DokkaSourceSet` is used as a map key in `SourceSetDependent` (typealias to `Map<DokkaSourceSet, T>`), which is used in many documentable properties: `sources`, `visibility`, `modifier`, `supertypes`, `documentation` and others. `DokkaSourceSet` also contains many collection-based properties, some of which (like `classpath` and `sourceRoots`) can have quite a number of elements.

The only implementation `DokkaSourceSetImpl` is a data class, so its `equals` and `hashCode` implementations are auto-generated and compare all properties, including the huge lists.

Because of this, `DokkaSourceSet#hashCode` is called frequently enough and takes enough time to notice it when profiling Dokka (based on the research done by our Google colleagues).

Making it a non-data class can lead to breaking backward compatibility and other issues, so it should be addressed in #2620, but there's a simple quick fix for now.

## Task

In theory, `DokkaSourceSet` should be identifiable by its `DokkaSourceSet#sourceSetID`, which should be unique. However, we don't have this behaviour specified anywhere and there are no checks that verify it.

This issue can address it:

1. Specify in KDocs for `DokkaSourceSet` that it **must** be uniquely identifiable by its `sourceSetID` property, which **must** be unique across the whole project (even in a multimodule one).
2. Write a `preGenerationCheck` check that verifies that all source set ids are unique (don't forget about `AllModulesPagePlugin`).
3. Override `hashCode` and `equals` in `DokkaSourceSetImpl` to use `sourceSetID` only.

**Comment by vmishenev** [comment]
Also, `DokkaSourceSet.sourceSetID` should be stable, see https://github.com/Kotlin/dokka/issues/1943
