### ISSUE TITLE
Mobile header layout issues

### ISSUE THREAD

**Issue by d-ambatenne** [Kotlin/dokka#3270]
Header layout in general looks distorted, there are several things that can be adjusted. KTL-696 covers this point, and probably will resolve the design issue for Kotlin documentation.

![Image](https://github.com/Kotlin/dokka/assets/75973078/eb543e42-2d0e-442f-92d9-f0ddf00824da)

**Comment by IgnatBeresnev** [comment]
Mobile layout issues have been fixed recently, it needs to be checked
