### ISSUE TITLE
Small target areas

### ISSUE THREAD

**Issue by d-ambatenne** [Kotlin/dokka#3274]
To make UI element more accessible and convenient to interact with, target area of 44px is suggested.
[2.5.5 Target Size](https://www.w3.org/TR/WCAG21/#target-size) (reference)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
