### ISSUE TITLE
Search results overflow the viewport

### ISSUE THREAD

**Issue by d-ambatenne** [Kotlin/dokka#3275]
Line breaks or truncation can be used to address this.

![Image](https://github.com/Kotlin/dokka/assets/75973078/2cdc5a1a-c6d7-477f-8438-32b885cde7d9)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
