### ISSUE TITLE
Filter items low contrast

### ISSUE THREAD

**Issue by d-ambatenne** [Kotlin/dokka#3276]
Low contrast makes content not accessible for people with poor vision.

For ‘js’ item:
![Image](https://github.com/Kotlin/dokka/assets/75973078/3f5b6af1-934c-4ca8-aae0-99776fd6bf3e)

For other light grey items:
![Image](https://github.com/Kotlin/dokka/assets/75973078/969d17f7-5de6-4794-aeb9-f6d6f10dcce9)

**Comment by whyoleg** [comment]
Fixed by https://github.com/Kotlin/dokka/pull/3917 in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0)
