### ISSUE TITLE
No empty search notification

### ISSUE THREAD

**Issue by d-ambatenne** [Kotlin/dokka#3281]
Even though there is a ‘No options found’ message, the contrast is very low for it to be readable.

![Image](https://github.com/Kotlin/dokka/assets/75973078/ad9de00a-b56a-4575-9ab3-58a790cf8397)

**Comment by IgnatBeresnev** [comment]
It's still relevant in 1.9.10.

## Light theme, default

![Image](https://github.com/Kotlin/dokka/assets/22685910/22ed4505-9c09-48bb-b3b0-66739d607fc3)

## Light theme, the text is selected

![Image](https://github.com/Kotlin/dokka/assets/22685910/77fbfe71-94e0-4ad5-bd3a-4f0186142f04)

## Black theme

![Image](https://github.com/Kotlin/dokka/assets/22685910/d6f92744-61f5-48b0-afeb-5d72f85cbd9f)
