### ISSUE TITLE
add dokka to maven repo / gradle plugin repo

### ISSUE THREAD

**Issue by apatrida** [Kotlin/dokka#33]
for it to be used, this needs to happen

**Comment by yole** [comment]
Of course. We'll release it together with Kotlin M13.

**Comment by apatrida** [comment]
So today this should appear?

**Comment by yole** [comment]
Yes, if everything goes well.

**Comment by Arcnor** [comment]
Did this ever happen? I can't seem to find dokka on Maven central or Sonatype Snapshots...

**Comment by yole** [comment]
Not yet, sorry. Still on my plate.

**Comment by cy6erGn0m** [comment]
@yole I can publish it to our old bintray repo

**Comment by Suseika** [comment]
It would be great to have at least a snapshot version available in repositories. Looking forward to it.

**Comment by yole** [comment]
Done. See readme for details.

**Comment by superbobry** [comment]
Please add dokka to Gradle [plugin repo](https://plugins.gradle.org) as well.

**Comment by K0zka** [comment]
Hi! could you share the repository url, groupid, artifactid? I haven't found it in central...

**Comment by hastebrot** [comment]
@K0zka It is on Bintray's JCenter. You can use one of the plugins for Maven [1] or Gradle [2], or download the jar file directly [3]

groupId | artifactId | version
--- | --- | ---
org.jetbrains.dokka | dokka-maven-plugin | 0.9
org.jetbrains.dokka | dokka-gradle-plugin | 0.9

[1] https://github.com/Kotlin/dokka#using-the-maven-plugin
[2] https://github.com/Kotlin/dokka#using-the-gradle-plugin
[3] https://github.com/Kotlin/dokka#using-the-command-line
