### ISSUE TITLE
feature request: respect the offline flag in maven

### ISSUE THREAD

**Issue by K0zka** [Kotlin/dokka#330]
When working offline and running `mvn -o dokka:dokka` dokka still tries to download content from oracle.com and it fails.

**Comment by semoro** [comment]
What should Dokka do in that case? Not generate external links?

**Comment by K0zka** [comment]
Not generating external links to me sounds like an acceptable option, but also, are http interactions really needed to do generate links? one could do it like https://docs.oracle.com/javase/${javaVersion}/docs/api/java/lang/String.html without downloading the html from there

**Comment by semoro** [comment]
Dokka can't really determine if java.lang.String belongs to `docs.oracle.com` without downloading the list of packages that belong to `docs.oracle.com`, as you may have multiple external links (one for `docs.oracle.com`, a second one for `kotlinlang.org` and so on)

**Comment by K0zka** [comment]
ok, understand... then I can activate noStdlibLink from a profile when offline, but oracle.com will still be used. is there a way to disable all network interactions from configuration?

**Comment by semoro** [comment]
Disabling link to oracle.com will be added in 0.9.18

**Comment by K0zka** [comment]
great, thank you!
