### ISSUE TITLE
Sync logo styling with kotlinlang

### ISSUE THREAD

**Issue by d-ambatenne** [Kotlin/dokka#3305]
I would suggest using logo of the similar scale/style. This issue may be resolved via upcoming header update.

![Image](https://github.com/Kotlin/dokka/assets/75973078/71407d02-2461-4fb7-a3d2-c39acb905ab6)

[KTL-1332](https://youtrack.jetbrains.com/issue/KTL-1332/Dokka-Sync-logo-styling-with-kotlinlang)

**Comment by IgnatBeresnev** [comment]
* Try not to break compatibility
* Example of logo customization: https://hexagonkt.com/api/index.html

**Comment by berezinant** [comment]
[KTL-1332](https://youtrack.jetbrains.com/issue/KTL-1332/Dokka-Sync-logo-styling-with-kotlinlang)
