### ISSUE TITLE
[K2] Unresolved java annotation methods in KDoc

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3316]
It is blocked by [KT-62880](https://youtrack.jetbrains.com/issue/KT-62880/K2-IDE-Unresolved-java-annotation-methods-in-KDoc) 

+ synthetic Java properties, getters/setters

**Comment by IgnatBeresnev** [comment]
* It's expected that the bug has been fixed upstream and it should now work
* Update to the version that includes it (check it)
* Write a few tests
