### ISSUE TITLE
Gradle: DokkaTask: Dokka fat jar resolution issues

### ISSUE THREAD

**Issue by remal** [Kotlin/dokka#332]
Current issues:
1. You have to copy all repository declaration from project to ```buildscript``` section.
1. You can't add custom formatters in **addition** to Dokka fat jar. You have to create another fat jar instead
1. You can't make dokkaFatJar points to a project in multi-project Gradle build

Solutions:
1. Please don't use objects from ```project.buildscript``` for Dokka fat jar dependency resolution. Now it requires to copy all repository declaration from project to ```buildscript``` section.
1. Please create a separate 'dokkaFatJar' project configuration. Not detached.
1. ```dokkaFatJar``` field should contains 'dokkaFatJar' project configuration
1. ```dokkaFatJar``` field should be annotated with ```org.gradle.api.tasks.Classpath``` annotation, not ```org.gradle.api.tasks.Input```
1. Please use all resolved artifacts from 'dokkaFatJar' project configuration for class loading, not only the first one.

**Comment by semoro** [comment]
See #296, #316

This issue is effectively duplicate
