### ISSUE TITLE
Regression testing of K2 analysis, first iteration [Kotlin/JVM]

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3328]
This issue is part of a larger issue: [Migrate Dokka's analysis to K2 compiler (#2888)](https://github.com/Kotlin/dokka/issues/2888).

## Goal

The goal of the first iteration of regression testing K2 is to identify the major and most obvious problems that need to be fixed. Once the uncovered problems are fixed, the second iteration can focus on the finer details and corner cases.

Things to keep in mind:

- The focus should be on Kotlin/JVM and Java projects. KMP can also be tested if there's time, but it shouldn't be too much of a blocker.
- The HTML format is the primary one, but other formats (esp. Javadoc) can also be tested if there's time for it. 
- The produced HTML pages and their content should _ideally_ be the same as produced by K1, but there might be insignificant (from the user's perspective) differences.
- Java interop should be checked.
- Dokka should work with Android projects (AGP).
- Running Dokka on Linux / Windows / Macos should work equally well.
- Dokka should be compatible with different versions of Kotlin (KGP), there shouldn't be any difference.

## Current state

- There are known inconsistencies between the results produced by K1 and K2, see #3115
- There are known upstream bugs (coming from Analysis API), we're waiting for the fixes:
    - #3196
    - #3234
    - #3207
    - #3316
- KMP support is expected to be poor, we are mostly blocked by [KT-62696](https://youtrack.jetbrains.com/issue/KT-62696/Analysis-API-KMP-support-for-Standalone-Mode), but it might work for some projects. Not sure if there's any point in testing KMP extensively, but it's worth a try.

## Additional context

* Stability of Dokka's K2 analysis mostly depends on the stability of the K2 IDE plugin, because they share a lot of the underlying logic (Analysis API).
* The majority of bugs you see in K2 IDE are expected to be relevant for Dokka as well, and vice versa.

**Comment by atyrin** [comment]
Done. Except for the point about different host OSs for running Dokka, I doubt there are some changes, and it is a priority. I'll move the check to the next iteration.
