### ISSUE TITLE
GradleMavenPush plugin itself can't add buildscript dependencies and then apply dokka-android plugin

### ISSUE THREAD

**Issue by AlexanderLS** [Kotlin/dokka#335]
We have created [GradleMavenPush](https://github.com/Vorlonsoft/GradleMavenPush) plugin that performs upload Artifacts (Gradle Android Artifacts, Gradle Java Artifacts and Gradle Kotlin Artifacts) to Maven repositories (JCenter, Maven Central, Corporate staging/snapshot servers and local Maven repositories)

GradleMavenPush plugin itself can't add buildscript dependencies and then apply dokka-android plugin:
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17"
    }
}

apply plugin: 'org.jetbrains.dokka-android'
```

> Plugin with id 'org.jetbrains.dokka-android' not found.

Solution from [Can a plugin itself add buildscript dependencies and then apply a plugin?](https://discuss.gradle.org/t/can-a-plugin-itself-add-buildscript-dependencies-and-then-apply-a-plugin/25039) also don't work:
```
apply plugin: 'groovy'

repositories {
    jcenter()
}

dependencies {
    compile gradleApi()
    compile localGroovy()

    compile "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17"
}

apply plugin: 'org.jetbrains.dokka-android'
```

> Plugin with id 'org.jetbrains.dokka-android' not found.

Could you provide any help?

**Comment by semoro** [comment]
I'd suppose, you want to:
`plugin/build.gradle`
```
apply plugin: 'groovy'

repositories {
    jcenter()
}

dependencies {
    compile gradleApi()
    compile localGroovy()

    compile "org.jetbrains.dokka:dokka-android-gradle-plugin:0.9.17"
}
```
In project:
`use/build.gradle`
```
buildscript {
    dependencies {
       compile project(':plugin') // or maven artifact ID, if published
    }
}
apply plugin: 'org.jetbrains.dokka-android' // If you doesn't want this line, you should 
// apply plugin: 'com.yourcompany.plugin' and modifiy plugin to apply dokka plugin in it's apply
```

Please, clarify, do you want to apply Dokka Plugin to Your Plugin project, or to Your Plugin Use-Site

**Comment by semoro** [comment]
But, I think that implicity applying Dokka Plugin to project, that uses your plugin is not good idea, instead, you should not apply it, but lookup for tasks of `DokkaTask` and `DokkaAndroidTask` types, if one is present, lookup info from it

**Comment by AlexanderLS** [comment]
Hi @semoro ,

Solutions above don't work for **script** gradle plugins (only for binary gradle plugins) 

I implemented my own [solution for support Dokka in **script** gradle plugins](https://github.com/Vorlonsoft/GradleMavenPush/commit/efe80ecf10cb3d3c833d8de74b89d5bc88339ebe).

For Android Java/Kotlin Projects:
```
            task androidDokka(type: Exec) {
                downloadFile('https://jcenter.bintray.com/org/jetbrains/dokka/dokka-fatjar/0.9.17/dokka-fatjar-0.9.17.jar', 'dokka-fatjar.jar')
                def srcDirsNumber = android.sourceSets.main.java.srcDirs.size()
                def classpathNumber = android.getBootClasspath().size()
                def classpath = (classpathNumber > 0) ? android.getBootClasspath()[0] : ''
                def javaAPISpecificationLink = getJavaAPISpecificationLink()
                if (srcDirsNumber > 0) {
                    commandLine 'java', '-jar', "$buildDir/download/dokka-fatjar.jar",
                            android.sourceSets.main.java.srcDirs[0],
                            (srcDirsNumber == 2) ? android.sourceSets.main.java.srcDirs[1] : '',
                            (srcDirsNumber == 3) ? android.sourceSets.main.java.srcDirs[2] : '',
                            '-output', "$buildDir/javadoc", '-format', 'javadoc',
                            (classpathNumber > 0) ? '-classpath' : '', (classpathNumber > 0) ? classpath : '',
                            '-links', "https://developer.android.com/reference/^${android.sdkDirectory}/docs/reference/^${javaAPISpecificationLink}"
                } else {
                    commandLine 'java', '-jar', "$buildDir/download/dokka-fatjar.jar"
                }
            }

            task androidDokkaJar(type: Jar, dependsOn: androidDokka) {
                classifier = 'javadoc'
                from "$buildDir/javadoc"
            }
```

For Other Java/Kotlin Projects (not Android):

```
            task coreDokka(type: Exec) {
                downloadFile('https://jcenter.bintray.com/org/jetbrains/dokka/dokka-fatjar/0.9.17/dokka-fatjar-0.9.17.jar', 'dokka-fatjar.jar')
                def srcDirsNumber = sourceSets.main.java.srcDirs.size()
                def javaAPISpecificationLink = getJavaAPISpecificationLink()
                if (srcDirsNumber > 0) {
                    commandLine 'java', '-jar', "$buildDir/download/dokka-fatjar.jar",
                            sourceSets.main.java.srcDirs[0],
                            (srcDirsNumber == 2) ? sourceSets.main.java.srcDirs[1] : '',
                            (srcDirsNumber == 3) ? sourceSets.main.java.srcDirs[2] : '',
                            '-output', "$buildDir/javadoc", '-format', 'javadoc',
                            '-links', "${javaAPISpecificationLink}"
                } else {
                    commandLine 'java', '-jar', "$buildDir/download/dokka-fatjar.jar"
                }
            }

            task dokkaJar(type: Jar, dependsOn: coreDokka) {
                classifier = 'javadoc'
                from "$buildDir/javadoc"
            }
```

Are there any comments, sugestions from Dokka developers, if not you can close these issue? Thanks

**Comment by semoro** [comment]
Hi @AlexanderLS, 
Your solution looks a bit hacky and will potentially break in some time.
Looks like 'script' plugins can't really manage class path of Gradle by providing it's own buildscript section. 
Why it isn't possible to convert your plugin into binary plugin? 
I personally think that `apply from` shouldn't be used for plugins

**Comment by AlexanderLS** [comment]
Hi @semoro 

It's possible to convert our plugin into binary plugin, but we need script plugin, not binary. I personally don't like to add many binary plugins to the project. Gradle Script plugins - old style, but it's impossible without them in some cases. Could you recommend in any documentation our solution, because it's only solution for Dokka implementation  in Gradle Script plugins? Thanks.

### **Final Solution:**

### For both Android and not Android projects:

    static void downloadLib(String url, String path, String version, String name) {
        File file = new File("${System.properties['user.home']}/.m2/repository/${path}/${version}/${name}")
        file.parentFile.mkdirs()
        if (!file.exists()) {
            new URL(url).withInputStream { downloadStream ->
                file.withOutputStream { fileOutputStream ->
                    fileOutputStream << downloadStream
                }
            }
        }
    }

    final String dokkaFatJarVersion = '0.9.17'
    final String dokkaFatJarPath = 'org/jetbrains/dokka/dokka-fatjar'

    final def projectDokkaJavadocTask = !dokkaPlugin ? null : project.tasks.find {
        it.name == 'dokkaJavadoc'
    }
    final def projectDokkaAndroidJavadocTask = !dokkaPlugin ? null : project.tasks.find {
        it.name == 'dokkaAndroidJavadoc'
    }

    task dokkaInitializer {
        MavenPush.downloadLib("https://jcenter.bintray.com/${dokkaFatJarPath}/${dokkaFatJarVersion}/dokka-fatjar-${dokkaFatJarVersion}.pom",
                dokkaFatJarPath, dokkaFatJarVersion, "dokka-fatjar-${dokkaFatJarVersion}.pom")
        MavenPush.downloadLib("https://jcenter.bintray.com/${dokkaFatJarPath}/${dokkaFatJarVersion}/dokka-fatjar-${dokkaFatJarVersion}.jar",
                dokkaFatJarPath, dokkaFatJarVersion, "dokka-fatjar-${dokkaFatJarVersion}.jar")
    }

### For Android Java/Kotlin Projects:

    if ((projectDokkaAndroidJavadocTask == null) && (projectDokkaJavadocTask == null)) {
                task androidDokka(type: Exec, dependsOn: dokkaInitializer) {
                    final byte srcDirsJavaNumber = (android.sourceSets.main.java.srcDirs != null) ? android.sourceSets.main.java.srcDirs.size() : 0
                    final byte srcDirsKotlinNumber = (kotlinLanguage && (android.sourceSets.main.kotlin.srcDirs != null)) ? android.sourceSets.main.kotlin.srcDirs.size() : 0
                    final byte classpathNumber = (android.getBootClasspath() != null) ? android.getBootClasspath().size() : 0
                    final String classpath = (classpathNumber > 0) ? android.getBootClasspath()[0] : ''
                    final String javaAPISpecificationLink = MavenPush.getJavaAPISpecificationLink()
                    if (srcDirsJavaNumber > 0) {
                        mkdir android.sourceSets.main.java.srcDirs[0]
                        if (srcDirsJavaNumber > 1) {
                            mkdir android.sourceSets.main.java.srcDirs[1]
                        }
                    }
                    if (srcDirsKotlinNumber > 0) {
                        mkdir android.sourceSets.main.kotlin.srcDirs[0]
                    }
                    if (srcDirsJavaNumber + srcDirsKotlinNumber > 0) {
                        commandLine 'java', '-jar',
                                "${System.properties['user.home']}/.m2/repository/${dokkaFatJarPath}/${dokkaFatJarVersion}/dokka-fatjar-${dokkaFatJarVersion}.jar",
                                (srcDirsJavaNumber > 0) ? android.sourceSets.main.java.srcDirs[0] : '',
                                (srcDirsJavaNumber > 1) ? android.sourceSets.main.java.srcDirs[1] : '',
                                (srcDirsKotlinNumber > 0) ? android.sourceSets.main.kotlin.srcDirs[0] : '',
                                '-output', "${buildDir}/javadoc", '-format', 'javadoc',
                                (classpathNumber > 0) ? '-classpath' : '', (classpathNumber > 0) ? classpath : '',
                                '-links', "https://developer.android.com/reference/^${android.sdkDirectory}/docs/reference/^${javaAPISpecificationLink}"
                    } else {
                        commandLine 'java', '-jar',
                                "${System.properties['user.home']}/.m2/repository/${dokkaFatJarPath}/${dokkaFatJarVersion}/dokka-fatjar-${dokkaFatJarVersion}.jar"
                    }
                }
            }

            if (projectDokkaAndroidJavadocTask != null) {
                task projectDokkaAndroidJavadocTaskJar(type: Jar, dependsOn: projectDokkaAndroidJavadocTask) {
                    classifier = 'javadoc'
                    from projectDokkaAndroidJavadocTask.outputDirectory
                }
            } else if (projectDokkaJavadocTask != null) {
                task projectDokkaJavadocTaskJar(type: Jar, dependsOn: projectDokkaJavadocTask) {
                    classifier = 'javadoc'
                    from projectDokkaJavadocTask.outputDirectory
                }
            } else {
                task androidDokkaJar(type: Jar, dependsOn: androidDokka) {
                    classifier = 'javadoc'
                    from "${buildDir}/javadoc"
                }
            }

### For Other Java/Kotlin Projects (not Android):

    if ((projectDokkaAndroidJavadocTask == null) && (projectDokkaJavadocTask == null)) {
                task coreDokka(type: Exec, dependsOn: dokkaInitializer) {
                    final byte srcDirsJavaNumber = (sourceSets.main.java.srcDirs != null) ? sourceSets.main.java.srcDirs.size() : 0
                    final byte srcDirsKotlinNumber = (kotlinLanguage && (sourceSets.main.kotlin.srcDirs != null)) ? sourceSets.main.kotlin.srcDirs.size() : 0
                    final String javaAPISpecificationLink = MavenPush.getJavaAPISpecificationLink()
                    if (srcDirsJavaNumber > 0) {
                        mkdir sourceSets.main.java.srcDirs[0]
                        if (srcDirsJavaNumber > 1) {
                            mkdir sourceSets.main.java.srcDirs[1]
                        }
                    }
                    if (srcDirsKotlinNumber > 0) {
                        mkdir sourceSets.main.kotlin.srcDirs[0]
                    }
                    if (srcDirsJavaNumber + srcDirsKotlinNumber > 0) {
                        commandLine 'java', '-jar',
                                "${System.properties['user.home']}/.m2/repository/${dokkaFatJarPath}/${dokkaFatJarVersion}/dokka-fatjar-${dokkaFatJarVersion}.jar",
                                (srcDirsJavaNumber > 0) ? sourceSets.main.java.srcDirs[0] : '',
                                (srcDirsJavaNumber > 1) ? sourceSets.main.java.srcDirs[1] : '',
                                (srcDirsKotlinNumber > 0) ? sourceSets.main.kotlin.srcDirs[0] : '',
                                '-output', "${buildDir}/javadoc", '-format', 'javadoc',
                                '-links', "${javaAPISpecificationLink}"
                    } else {
                        commandLine 'java', '-jar',
                                "${System.properties['user.home']}/.m2/repository/${dokkaFatJarPath}/${dokkaFatJarVersion}/dokka-fatjar-${dokkaFatJarVersion}.jar"
                    }
                }
            }

            if (projectDokkaJavadocTask != null) {
                task coreProjectDokkaJavadocTaskJar(type: Jar, dependsOn: projectDokkaJavadocTask) {
                    classifier = 'javadoc'
                    from projectDokkaJavadocTask.outputDirectory
                }
            } else if (projectDokkaAndroidJavadocTask != null) {
                task coreProjectDokkaAndroidJavadocTaskJar(type: Jar, dependsOn: projectDokkaAndroidJavadocTask) {
                    classifier = 'javadoc'
                    from projectDokkaAndroidJavadocTask.outputDirectory
                }
            } else {
                task dokkaJar(type: Jar, dependsOn: coreDokka) {
                    classifier = 'javadoc'
                    from "${buildDir}/javadoc"
                }
            }

**Comment by AlexanderLS** [comment]
Hi @semoro 

We implemented Gradle Script Plugin for Dokka. 

[EasyDokkaPlugin](https://github.com/Vorlonsoft/EasyDokkaPlugin)
===============

Gradle script plugin to generate documentation by Dokka documentation engine in Javadoc format for Java, Kotlin, Android and non-Android projects. It's very easy, you don't need to add to `dependencies` section additional `classpath` or think about compatibility issues, you don't need additional repositories also.

## Usage

### 1. Have a working Gradle build

It is up to you.

### 2. Call the script

Add the following at the end of `build.gradle` of each sub-module that you wish to generate documentation:

```groovy
apply from: 'https://raw.github.com/Vorlonsoft/EasyDokkaPlugin/master/dokka.gradle'
```

### 3. Generate documentation

You can now generate documentation by Dokka documentation engine in Javadoc format:

```bash
$ gradle dokkaJavadocsJar
```

### 4. Get documentation

Get generated documentation from `${buildDir}` directory.
