### ISSUE TITLE
[K2] Javadoc links for references on inherited properties is not rendered

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3350]
```Kotlin
/**
 * @see  [java.io.StringReader.lock] see this
 * @see  [java.io.StringReader.mark] see that
 */
class ClassKDocLocation {
}
```

In K1 both links are rendered. And the first link is https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/StringReader.html#lock(). Note that `lock` is a property of parent class `Reader`(https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/Reader.html#lock)

<img width="349" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/7a848f06-6a63-4ea0-8c7b-13742361e45d">

-----

In K2 it:
<img width="388" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/1b2ab964-9dd0-44ad-bfbe-ead05f541d65">

IDE navigated
**Installation**
- Dokka version: 1.9.20

Parent: https://github.com/Kotlin/dokka/issues/3328

**Comment by atyrin** [comment]
The reverence to the issue on Analyses API: https://youtrack.jetbrains.com/issue/KTIJ-26003/K2-IDE-KDoc-references-to-base-class-members-are-not-resolved

**Comment by vmishenev** [comment]
The fix should be in https://github.com/Kotlin/dokka/pull/3337
