### ISSUE TITLE
[K2] Incorrect link for methods with parameters in Java stdlib

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3355]
```Kotlin
/**
 * @see [java.applet.AppletContext.showDocument] reference
 */
class X
```
For K1 link was: https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/java/applet/AppletContext.html#showDocument(java.net.URL)

For K2, the parameter is handled as nullable: https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/java/applet/AppletContext.html#showDocument(java.net.URL?)

That leads to incorrect navigation to javadoc.

**Installation**
- Dokka version: 1.9.20

Parent: #3328

**Comment by atyrin** [comment]
Relates to #3351 (but that issue exists in K1 as well)

**Comment by vmishenev** [comment]
Also, it is related to #2357
