### ISSUE TITLE
[K2] KMP: Platform tabs missed common for properties

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3360]
Create a KMP project:
```Kotlin
// commonMain
expect class Dokka {
    val data: String?
    fun f()
}

// platformMain
actual class Dokka {
    actual val data: String? = null
    actual fun f() {}
}
```

K2 output:
<img width="571" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/03436a3a-b108-4c36-bcd6-d64a76e8309f">

**Installation**
- Dokka version: 1.9.20

Parent: #3328

**Comment by vmishenev** [comment]
It is blocked by https://youtrack.jetbrains.com/issue/KT-64319/Analysis-API-isExpectfalse-for-property-symbol-from-expect-class
