### ISSUE TITLE
[K2] Java nested classed are shown in inheritors

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3363]
JavaParent.java
```Java
public class JavaParent {
    public static class NestedJavaParent{}
}
```
child.kt
```Kotlin
class Child: JavaParent()
```

As a result, on the `Child` page `NestedJavaParent` is shown. Not happened in K1

----
<img width="400" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/85957862-b4a5-4c7e-b947-aa70929b2845">

----
**Installation**
- Dokka version: 1.9.20

Parent: #3328

**Comment by vmishenev** [comment]
It is blocked by https://youtrack.jetbrains.com/issue/KT-64067/Analysis-API-Member-scope-has-an-inherited-nested-class-from-Java
