### ISSUE TITLE
Values on interfaces don't inherit documentation

### ISSUE THREAD

**Issue by clarfonthey** [Kotlin/dokka#337]
Minimal example:

```
interface Interface {
    /** A thing. */
    val thing: String
}

class Thing : Thing {
    override val thing: String get() = "Hello, world!"
}
```

This will show `Thing.thing` as undocumented when it should inherit the documentation from `Interface`.

**Comment by semoro** [comment]
Looks like `Thing` in your example doesn't implement `Interface`

**Comment by clarcharr** [comment]
This is what I get for hastily writing up examples. You should find it to be more accurate now.

**Comment by semoro** [comment]
Can't reproduce with Dokka 0.9.16, `outputFormat=html`, which output format are you using?

**Comment by clarcharr** [comment]
Currently using `outputFormat=html`. My example might be too minimal; I'll do some digging and get back to you on that. Might be a transitive interface issue.

**Comment by Kordyjan** [comment]
Should work correctly in 1.4.0. Feel free to reopen if the bug persists.
