### ISSUE TITLE
[K2] `List` reference leads to the stdlib collections package

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3375]
```Kotlin
/**
 * ref to [List] or [Set]
 */
fun x(){}
```

`List` link leads to https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/ instead of https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-list/ (in K1).
For `Set` the link is correct.

**Installation**
- Dokka version: 1.9.20

Parent: #3328

**Comment by atyrin** [comment]
The same case I see for KPM project and `String`.  Reproduces in common code(JVM+JS) and JS code. But ok for JVM

```
/**
 * [String]
 */
fun withString(s: String){}
```

The link from kdoc leads to https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/index.html. From signature to https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html

**Comment by vmishenev** [comment]
It is blocked by
https://youtrack.jetbrains.com/issue/KT-64190/Analysis-API-KDoc-link-leads-to-a-function-instead-of-interface

**Comment by IgnatBeresnev** [comment]
Theoretically, we could add a workaround on our side (change the priority of resolved symbols), but ideally it needs to be fixed in analysis-api.

**Comment by vmishenev** [comment]
It **can** be related to #3352

**Comment by vmishenev** [comment]
The logic of ordering should be like [in K1](https://github.com/JetBrains/intellij-community/blob/84f54ed97da66d6e24e6572345869bf1071945b6/plugins/kotlin/base/fe10/kdoc/src/org/jetbrains/kotlin/idea/kdoc/resolveKDocLink.kt#L104)
