### ISSUE TITLE
[K2] KMP: ERROR CLASS for references in the shared code if there is an intermediate level between them

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3377]
```Kotlin
// commonMain
class A

// sharedJvmAndJsMain
// Nothing

// jvmMain
fun fr(__size: opt_site_t) {}
```

K2
<img width="514" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/41e2f334-5d1b-4930-a951-431dadd50460">

In K1 it was resolved.

**Installation**
- Dokka version: 1.9.20

Parent: #3328
A similar issue in the compiler: [KT-59071](https://youtrack.jetbrains.com/issue/KT-59071) K2/MPP: internal declarations from common module are invisible in dependent source sets if there is more that one intermediate source set between

**Comment by vmishenev** [comment]
Can you provide a reproducer?
It seems `opt_site_t` is missed  in your snippet.

**Comment by atyrin** [comment]
The snippet is incorrect, sorry.

```Kotlin
// commonMain
class A

// sharedJvmAndJsMain
// Nothing

// jvmMain
fun resolve(a: A) {}
```

[k2mpp.zip](https://github.com/Kotlin/dokka/files/13684948/k2mpp.zip)

**Comment by vmishenev** [comment]
Your reproducer also has unresolved class in K1.
![image](https://github.com/Kotlin/dokka/assets/9636937/4c7d880c-b86a-4988-80c3-8a14e425efdb)
