### ISSUE TITLE
[K2] KMP: Constructors in actual class are missing keyword `actual`

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3378]
```Kotlin
// commonMain
expect class A()

actual class A{
    actual constructor(){}
    constructor(s: String): this(){}
}
```
----
K2
<img width="539" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/5c607f09-1f60-42d2-90bd-1f4ac42c994a">
----

K1
<img width="621" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/6a9aa61f-920a-420e-9501-6c3b911ec83f">
----

**Installation**
- Dokka version: 1.9.20

Parent: https://github.com/Kotlin/dokka/issues/3328

**Comment by vmishenev** [comment]
It is blocked by https://youtrack.jetbrains.com/issue/KT-64345/Analysis-API-isActualfalse-for-actual-constructor-symbol
