### ISSUE TITLE
[K2] KMP: @constructor description is not rendered for implicit actual constructor

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3379]
```kotlin
// commonMain
expect class A()

// platform
/**
 * @constructor constructor description
 */
actual class A
```

K1
<img width="457" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/de3f6b3a-a684-492e-9e7b-99f3ec106dfd">

K2
<img width="458" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/5162001a-fc38-4d7a-a4db-c55ea9d161e2">

**Installation**
- Dokka version: 1.9.20

Parent: https://github.com/Kotlin/dokka/issues/3328

**Comment by IgnatBeresnev** [comment]
Likely the same as #3452, needs to be checked.
