### ISSUE TITLE
[K2] KMP: `external` keyword is not rendered for properties

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3380]
Declare in JS source set
```Kotlin
external val x: String
```

K2 output is missing `external`
<img width="250" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/1e2b2ba7-04f2-4e3e-a33e-dd5f7bcc8083">

**Installation**
- Dokka version: 1.9.20

Parent: #3328

**Comment by IgnatBeresnev** [comment]
Technically, this needs to be investigated. Maybe the `external` keyword could be extracted from the getter, or maybe the compiler is not returning enough information
