### ISSUE TITLE
[K2] KMP: Classes with  expect/actual are missing parameters in signature

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3381]
```Kotlin
// commonMain
expect class InheritMe(param: String)

// platoform
actual class InheritMe(param: String)
```

The parameters from the primary constructor are visible only in `Constructors` block. And missed in class signature (comparing to K1)

---
K1
<img width="659" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/abc0af6c-efef-4a34-9759-4ae0e795f9b2">
---
K2
<img width="639" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/e8c3bd78-ef0a-4658-92f2-c7813a55b21e">
---

**Installation**
- Dokka version: 1.9.20

Parent: https://github.com/Kotlin/dokka/issues/3328

**Comment by vmishenev** [comment]
It is blocked by **https://youtrack.jetbrains.com/issue/KT-64344/Analysis-API-a-primary-constructor-is-missed-in-an-expect-class**

Note: Is `actual class InheritMe(param: String)` compilable? 
I get the error `Declaration must be marked with 'actual'`.
IDE transforms it to `actual class InheritMe actual constructor(param: String)`

**Comment by whyoleg** [comment]
Not reproducible at my side on current `master`
