### ISSUE TITLE
[K2] Different PageId in K1 and K2 for nested classes

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3388]
So far, I have two samples for the change with no visible side effects.

For nested classes
```Kotlin
class Parent{
    class Nested
}
```

K1: `pageids="module::/Parent.Nested/Nested/#/PointingToDeclaration//-1486420497"`
K2: `pageids="module::/Parent.Nested/Parent.Nested/#/PointingToDeclaration//-1486420497"`

For vararg arguments
```Kotlin
fun withVararg(i: Int, vararg s: String){}
```

K1: `pageids="module:://withVararg/#kotlin.Int#kotlin.Array[kotlin.String]/PointingToDeclaration//-1486420497"`
K2: `pageids="module:://withVararg/#kotlin.Int#kotlin.String/PointingToDeclaration//-1486420497"`

**Installation**
- Dokka version: 1.9.20

Parent: https://github.com/Kotlin/dokka/issues/3328

**Comment by vmishenev** [comment]
> For vararg arguments

this can affect #2881

**Comment by vmishenev** [comment]
For second case It would be nice to have https://youtrack.jetbrains.com/issue/KT-64340/Analysis-API-no-way-to-get-a-type-of-vararg-parameter

**Comment by IgnatBeresnev** [comment]
Best case scenario is that it's fixed in Analysis API, but we can add a local workaround.

**Comment by IgnatBeresnev** [comment]
Nested classes should be fixed as part of this issue
