### ISSUE TITLE
Spike: decompose `styles.css`

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3423]
`styles.css` has 1.5k lines, which is a problem for two reasons:
* It's not convenient for us internally, so the developer experience could be improved if it's broken down into smaller components.
* We allow users to override `styles.css` with their own file, which leads to copy-paste, oudated styles and difficulty with maintaining backward compatibility.

As part of stabilizing Dokka's HTML format, we want to revisit the customization of Dokka's stylesheets, which also consists of two steps:
1. Figure out what Dokka's users want to customize most often, what are the user stories here.
2. Implement it technically (most likely as providing separate `.css` files for each customizable component)

This spike exists to help figure out the details/requirements of the second step, to understand what is possible, how long it would take to implement (in case new classes need to be added or the styles need to be refactored).

It should also help figure out how to approach the decomposition of `styles.css` for internal use, i.e which separate `.css` files we need and make sense internally. These files could be for our convenience only, so we could take these internal stylesheets and compile them into a single large `styles.css` upon release.

## Goals

* Come up with a proposal on how to decompose `styles.css`:
    * Which styles could be extracted into separate files for our internal use and convenience
    * Which styles are possible to extract for user customization (theme-colors, different parts of pages, etc)
* Try to estimate the scope of changes (in terms of small/medium/large) and very approximate time estimate (in terms of a couple of days / a week / a month).

## Non-Goals

The actual implementation of the decomposition is outside the scope of this issue, as it might take significant time to implement and test it. For now we just need to try to turn known unknowns into known knowns.

**Comment by berezinant** [comment]
### What to preserve:
✅ Logo styles have been extracted into a separate file.

### What to improve:
🟧 There are some CSS variables and even a theme switch, but they do not organised into a system that can be easily exposed to users for customisation.
🟧 Combining separate css files is possible — add new files and register them, but it is not concatenated into a single file

### Problems:
❌ Styles for different components are not separated into individual files
❌ There is no linting for styles
❌ There is no linting that automatically enforces the notation for CSS classes (consistent BEM)
❌ Style minification is absent; only what comes from the plugin-base-frontend is minified

### Customisation cases
Most commonly, users customize font size, background color, spacing, syntax highlighting, and menu styles. Custom styles are often associated with `.main-content, .section-tab, navigation, .tabs, .single-tab, .search`, as well as with IDs `#sideMenu, #leftColumn, #container, #main, #theme-toggle-button, and #searchBar, #main, #container`
