### ISSUE TITLE
Research for Dokka Gradle Plugin DSL 2.0

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/dokka#3424]
Part of https://github.com/Kotlin/dokka/issues/3131

Goal is to prepare for redesigning the configuration DSL. During research we will need to gather all required information from multiple sources:
* Dokka usage in various projects (big and small), f.e. gradle, aws-sdk, ktor, apollo-graphql, okio, okhttp, spring, android/androidx (?), etc:
  * think of how these projects are going to migrate to the new DSL / plugin, maybe we can add some deprecated configurations/tasks from the old plugin that will point to the new replacements
  * different formats usages
  * how it's configured
  * usage of specific features (collectors, multi-module, etc)
  * what doesn't work (and which hacks applied to fix)
* [dokkatoo](https://github.com/adamko-dev/dokkatoo) - provides it's own Gradle configuration layer over Dokka engine (both code and current opened issues)
* [kotlinx-kover](https://github.com/Kotlin/kotlinx-kover) - have similar ideas (different formats, aggregation, etc)
* KGP/AGP - mature Gradle plugins with which Dokka users are very familiar
* Gradle docs on idiomatic configuration/DSL
* configuration cache and project isolation requirements
* internal UX researches and user interviews
* internal list of problems and wishes 
* existing issues in Dokka with the [configuration](https://github.com/Kotlin/dokka/issues?q=is%3Aissue+is%3Aopen+label%3Aconfiguration) and [gradle plugin](https://github.com/Kotlin/dokka/issues?q=is%3Aissue+is%3Aopen+label%3A%22runner%3A+Gradle+plugin%22) tags
* any other sources which will be found interesting during review (will be added to the list afterwards)
* can spend some time on prototyping

Feel free to post any additional useful source in the comments!

**Comment by IgnatBeresnev** [comment]
The research was conducted, the next steps are internal and external review. It will be published once the document is finalized
