### ISSUE TITLE
Javadoc output on Java classes - Parameters are missing

### ISSUE THREAD

**Issue by yayaa** [Kotlin/dokka#343]
Once we run `dokka` in a project that has both Java and Kotlin classes, the output -configured as javadoc- is missing parameters from all methods -constructors as well- in Java classes. It documents on Kotlin classes though. 
 
- We have the very simple configuration as following;
```groovy
dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/docs"
}
```

- All the parameters are documented with `@param`.

**Comment by DarrylBayliss** [comment]
The same behaviour can be seen with other javadoc tags like `@see` and `@deprecated` on Java classes.

**Comment by eddyfrank** [comment]
See also https://github.com/Kotlin/dokka/issues/160

**Comment by KrystianUjma** [comment]
PR created [here](https://github.com/Kotlin/dokka/pull/420)
