### ISSUE TITLE
Does Dokka support custom generators/doclets?

### ISSUE THREAD

**Issue by cjbrooks12** [Kotlin/dokka#344]
Javadoc has support for custom [Doclets](https://docs.oracle.com/javase/8/docs/technotes/guides/javadoc/doclet/overview.html), which allow users to specify the content and format of the output for themselves, rather than using the provided format(s). Javadoc will parse the source code for you, and then pass the doclet a model of the source code and associated documentation allowing you do render it however is needed. 

Does Dokka support anything like that? Being able to have Dokka use third-party generators, or even better, be used like a library rather than a CLI or build tool, would be really cool. 

Specifically, I would like to integrate Dokka with the [Orchid Static Site Generator](https://github.com/JavaEden/Orchid), having Dokka give Orchid the model of the kotlin code and let Orchid generate the pages instead of Dokka doing it for me.

**Comment by semoro** [comment]
Dokka support custom formats, see more in #279 and #288
