### ISSUE TITLE
[K2] Missed `@constructor`documentation for primary constructor without parameters

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3452]
```kt
/**
* @constructor some doc
*/
class AllKDocTagsClass
```

The documentation `some doc` for the primary constructor is missed.
In K1 it exists. 

Meanwhile, it works for `class AllKDocTagsClass(param: Int)`.
The bug is on Dokka's side.

**Comment by IgnatBeresnev** [comment]
Related (the fix might be the same): #3379

**Comment by vmishenev** [comment]
Also, there it a little consistency in QuickDoc (K1 and K2):
![image](https://github.com/Kotlin/dokka/assets/9636937/47c3fbd6-7ca4-4145-8572-f545e30bdd21)
with the empty parentheses
![image](https://github.com/Kotlin/dokka/assets/9636937/5632c631-dffd-4afc-a0dc-3e1217c2a345)
