### ISSUE TITLE
Dokka doesn't support the new unsigned types in Kotlin 1.3

### ISSUE THREAD

**Issue by juergenzimmermann** [Kotlin/dokka#348]
When you are using unsigned types like `UInt` then Dokka produces a message as follows:

```
Found an unresolved type in de.hska.kunde.service.KundeService$findVersionById(kotlin.String) (KundeService.kt:59)
```

In the produced HTML you see `<ERROR CLASS>`.

**Comment by semoro** [comment]
It will be supported with Dokka update

**Comment by floscher** [comment]
Until the next Dokka version is released, the errors can be silenced by adding `import kotlin.UInt` to the affected classes.
