### ISSUE TITLE
Preserve newlines in Java source comments

### ISSUE THREAD

**Issue by cjbrooks12** [Kotlin/dokka#349]
I understand Dokka doesn't compile Java comments as Markdown, but is it possible for newlines to be preserved from Javadoc comments? I'm working on a JSON formatter for Dokka, but it seems like newlines get removed so I can't even pass the comment text to another tool to compile the comments as markdown.

**Comment by semoro** [comment]
Right now it is not supported, looks like some extension point is required

**Comment by dschuermann** [comment]
You can check out my pull request that changes the behavior for javadoc code blocks: https://github.com/Kotlin/dokka/pull/409.

I also override this in my own fat-jar proejct here: https://github.com/cotechde/dokka-hugo-extension/tree/master/dokka-hugo/src/main/kotlin/Java

**Comment by IgnatBeresnev** [comment]
I assume this has been implemented by your PR, so closing the issue for now. Let us know if the issue is still there :)
