### ISSUE TITLE
Generate documentation for mixed java/Kotlin projects

### ISSUE THREAD

**Issue by Xerus2000** [Kotlin/dokka#352]
I've been digging around this for about half an hour now, but I just couldn't find out how to create whole JavaDoc for a mixed Java/Kotlin project. I am using Gradle Kotlin DSL and have recently ported a few classes in the codebase to Kotlin. 
However, due to users who don't want to deal with Kotlin, the Documentation should still look as before. But I am not able to get dokka to create an aggregated JavaDoc, even though it was mentioned multiple times in different places.
This is a snippet from my buildscript:

```kotlin
    val javadocTask = replace("javadoc", Javadoc::class).apply {
        title = "Software-Challenge API $version"
        val sourceSets = arrayOf("plugin", "sdk").map { project(it).sourceSets.getByName("main") }
        source(sourceSets.map { it.allJava })
        classpath = files(sourceSets.map { it.runtimeClasspath })
        setDestinationDir(deployDir.resolve("javadoc"))
    }
    create<DokkaTask>("doc") {
        dependsOn("javadoc")
        moduleName = "Software-Challenge API $version"
        val p = arrayOf("plugin", "sdk").map { project(it) }
        val sourceSets = p.map { it.sourceSets.getByName("main") }
        sourceDirs = files(sourceSets.map { it.allSource })
        classpath = files(sourceSets.map { it.runtimeClasspath })
        outputDirectory = deployDir.resolve("doc").toString()
        outputFormat = "javadoc"
        jdkVersion = 8
        externalDocumentationLink(delegateClosureOf<DokkaConfiguration.ExternalDocumentationLink.Builder> {
            this.url = URL("file:///${javadocTask.destinationDir!!.absolutePath}/")
        })
    }
```

And there is another issue: For an interface with default implementations it keeps creating documentation for `.DefaultImpls`, even though that class doesn't even exist, since everything is targeted at Java 8.

And the `externalDocumentationLink` doesn't seem to work either.

**Comment by Xerus2000** [comment]
I still have this issue and have not found any solution. It has to be possible to generate coherent javadoc for mixed proejcts! Otherwise I can't bring Kotlin into other people's projects.

**Comment by semoro** [comment]
Dokka doesn't support mixing with JavaDoc, you can use Dokka to generate JavaDoc for whole codebase incl java, but there is a number of problems this way.
About the second problem: Actually, even if you target Java 8 `.DefaultImpls` classes will be created.

**Comment by Xerus2000** [comment]
"you can use Dokka to generate JavaDoc for whole codebase incl java"

That's what I need, but how?

**Comment by semoro** [comment]
Just disable your `JavaDoc` task and provide all sources including java into Dokka

**Comment by Xerus2000** [comment]
Okay, got it to work finally, apparently `SourceSet.allJava` and `SourceSet.allSource` just return empty collections, so I had to use `SourceSet.java.sourceDirectories`, then it worked
