### ISSUE TITLE
Can't set documentation title

### ISSUE THREAD

**Issue by xerus2000** [Kotlin/dokka#353]
In Javadoc, I can set the title of the documentation in gradle using the `title` property of the Javadoc Task. Is this also possible for Dokka somehow? Because I can't find anything like it.

**Comment by semoro** [comment]
Maybe `moduleName` is what are you looking for?

**Comment by Xerus2000** [comment]
Nope, `moduleName` does nothing. Look at the javadoc here:
![image](https://user-images.githubusercontent.com/13354331/47294145-77a42d80-d60c-11e8-88ed-1df11fb34ec3.png)
The window has a title, and that is also the header of the page. It can be set using the `title` property of the Javadoc Task. 

However, if I set `moduleName` in a DokkaTask, it still looks like this:
![image](https://user-images.githubusercontent.com/13354331/47294210-ab7f5300-d60c-11e8-8ea2-a9580adeb4c6.png)
No title, no header...

**Comment by Kordyjan** [comment]
As far as I know, this was fixed during rewrite of javadoc rendering (version 1.4.0-rc and later). You can use `moduleName` for that. If the issue persists feel free to reopen the issue.
