### ISSUE TITLE
Update stdlib to the latest version of Dokka

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3535]
The version of Dokka used to build stdlib's docs should be updated to the latest `-dev` build.

1. Bump the version
2. Implement the sample re-writer interface introduced in #3108
3. Enable the `All Types` page introduced in #2887

Discuss with Ilya which branch it should target and how to proceed after the PR is sent.

**Comment by whyoleg** [comment]
Issues found during update:

1 (warning): Intersected sources `Every Kotlin source file should belong to only one source set (module).`
In Dokka K2 it will be an error.
* Source sets 'Common' and 'JS' have the common source roots: 
  * core/builtins/native (and nested files)
  * core/builtins/src (and nested files)
* Source sets 'Native' and 'Wasm-JS' have the common source roots:
  * libraries/stdlib/native-wasm/src
* Source sets 'Native' and 'Wasm-WASI' have the common source roots:
  * libraries/stdlib/native-wasm/src
* Source sets 'Wasm-JS' and 'Wasm-WASI' have the common source roots:
  * libraries/stdlib/native-wasm/src
  * libraries/stdlib/wasm/src
  * libraries/stdlib/wasm/builtins
  * libraries/stdlib/wasm/internal
  * libraries/stdlib/wasm/stubs

2 (not regression): Unable to resolve a @sample link: "samples.collections.Collections.Aggregates.minBy" (and `maxBy`) - same behaviour for previous versions and on currently deployed to kotlinlang.org - [example](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/min-by.html)

3 (regression): After updating fronted dependencies (https://github.com/Kotlin/dokka/pull/3413) samples are not runnable anymore. If to replace `scripts/main.js` in built documentation with latest Dokka (2.0.0-dev-323) with `main.js` from older Dokka (1.9.10) - samples are runnable again.

Changes are available in [dokka-2.0.0](https://github.com/whyoleg/kotlin/tree/dokka-2.0.0) branch, [diff](https://github.com/JetBrains/kotlin/compare/master...whyoleg:kotlin:dokka-2.0.0)

**Comment by whyoleg** [comment]
Dokka update for Kotlin stdlib was merged in: https://github.com/JetBrains/kotlin/commit/1c774643c9f71aa855772217a47ff81e46d17e53
