### ISSUE TITLE
Table of contents not visible on multimodule project

### ISSUE THREAD

**Issue by hamorillo** [Kotlin/dokka#3541]
**Describe the bug**
The table of contents is not generated when working with a multimodule project. 

**Expected behaviour**
The table of contents should be visible when generating docs for a multimodule project. [Example](https://kotlin.github.io/dokka/examples/dokka-multimodule-example/htmlMultiModule/index.html)

**Screenshots**
<img width="700" alt="image" src="https://github.com/Kotlin/dokka/assets/6974554/e7127c96-e599-48be-b740-ce3b77a34841">

**To Reproduce**
1. Clone the repo: https://github.com/Kotlin/dokka
2. Navigate to `dokka/examples/gradle/dokka-multimodule-example`
3. Execute: `./gradlew dokkaHtmlMultiModule`
4. The table of contents should be visible in the generated documentation

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.6
- Dokka version: 1.9.20

**Additional context**
The same occurs to me in a different project.

**Comment by whyoleg** [comment]
Hey!
I've built example locally, and everything works fine at my side:
<img width="577" alt="image" src="https://github.com/Kotlin/dokka/assets/50462752/b8cecd3d-138f-475a-9c7a-503f0a59c878">

Works on MacOS in Safari and in Chrome - could it be browser related? Could you also check that `navigation.html` is produced near `index.html` and that it's downloaded when you are opening the page?

**Comment by hamorillo** [comment]
I'm so sorry. It was my fault, I was trying to open `index.html` as a file in the browser:

`file:///.../dokka/examples/gradle/dokka-multimodule-example/parentProject/build/dokka/htmlMultiModule/index.html`

So I was getting a `CORS error` under the hood:

<img width="1122" alt="image" src="https://github.com/Kotlin/dokka/assets/6974554/b5a293dd-def6-4a69-8dac-599775bd5491">

Using a web-server works fine 🤦🏼‍♂️

<img width="573" alt="image" src="https://github.com/Kotlin/dokka/assets/6974554/1f7ab0fa-86e5-4864-8a05-d96a4cb5f8fc">
