### ISSUE TITLE
How to put a README.md file on index.html page?

### ISSUE THREAD

**Issue by tangible-idea** [Kotlin/dokka#3546]
**Question**
How to put a README.md file on index.html page? 
I am using a single module project. and it works when I build it without `includes` syntax.

when I `./gradlew dokkaHtml` it shows  Unexpected classifier: "##", expected either "Module" or "Package". 

**Screenshots**
![스크린샷 2024-03-21 오전 10 09 31](https://github.com/Kotlin/dokka/assets/4496005/6e79a44c-866c-4151-8d3e-bbfcd997a24f)

**Installation**
- Operating system: macOS
- Build tool: Gradle v8.0
- Dokka version: 1.9.20

**Additional context**
my gradle setup here.
```
dokkaHtml.configure
              {
                  dokkaSourceSets {
                      named("main") {
                          includes.from("../README.md")
                          noAndroidSdkLink.set(false) 
                      }

                  }
              }
```

**Comment by vmishenev** [comment]
The markdown files from `includes` should have the defined format that is used for [package and module documentation](https://kotlinlang.org/docs/dokka-module-and-package-docs.html).
See https://kotlinlang.org/docs/dokka-gradle.html#e8d576e7
Here's an example file:
```md
# Module kotlin-demo

This content appears under your module name.

# Package org.jetbrains.kotlin.demo

This content appears under your package name in the packages list.
It also appears under the first-level heading on your package's page.

## Level 2 heading for package org.jetbrains.kotlin.demo

Content after this heading is also part of documentation for `org.jetbrains.kotlin.demo`

# Package org.jetbrains.kotlin.demo2

This content appears under your package name in the packages list.
It also appears under the first-level heading on your package's page.

## Level 2 heading for package org.jetbrains.kotlin.demo2

Content after this heading is also part of documentation for `org.jetbrains.kotlin.demo2`
```

**Comment by tangible-idea** [comment]
@vmishenev it is working great! thank you :)
