### ISSUE TITLE
[K2] Spike: research the behaviour of Kotlin/Java interop around getters/setters and inheritance

### ISSUE THREAD

**Issue by IgnatBeresnev** [Kotlin/dokka#3576]
## Context

During the discussion of #3338, it became apparent that there are many corner cases with no obvious "correct" solution, as it depends.

## Spike

The user scenario from #3338 should be researched to help us figure out how to address it:
* Try different cases, see how they work in K1/K2
* Compare it to the behaviour of IntelliJ IDEA.
* Reason about how it should work, what our users would like or expect to see.

Expected outcome of this spike: 
* some summary of the research that would help us make a decision about #3338 (and possibly other similar issues, but not necessarily)
* some proposals as to how #3338 should be fixed, and why

**Comment by vmishenev** [comment]
https://docs.google.com/presentation/d/1CdCwZeIxzKUenvQImBdDhVXJbXg8XM_FETB6ebVZK78/edit?usp=sharing
