### ISSUE TITLE
Add documentation/Change readme for the Gradle Kotlin DSL

### ISSUE THREAD

**Issue by StefMa** [Kotlin/dokka#359]
This project should update the readme to show how to use this plugin with the Gradle Kotlin DSL.

See also https://github.com/gradle/gradle/issues/6790

Maybe related: https://github.com/Kotlin/dokka/issues/196 & https://github.com/Kotlin/dokka/pull/358

**Comment by StefMa** [comment]
Why is that ticket closed? 🤔

**Comment by kamilok1965** [comment]
Because the documentation for Kotlin DSL has been added on https://github.com/Kotlin/dokka/tree/multiplatform-support and will be released with 0.10.0. Also there is a PR for kotlin-examples repository with a .kts buildscript for dokka

**Comment by StefMa** [comment]
Ah cool thank you ☺ 👍

**Comment by kamilok1965** [comment]
No problem, happy to help

**Comment by albertocavalcante** [comment]
The example mentioned for reference: https://github.com/Kotlin/kotlin-examples/commit/8502703e9c01c8ee5f92ec3fde7973faee1c0e56#diff-2d4b1934ca9e06a737bad2fc16982a878a943df6a22cb44320633e675071310b
