### ISSUE TITLE
Add "--help" argument

### ISSUE THREAD

**Issue by mathjeff** [Kotlin/dokka#364]
Could Dokka support, for example, "--help" argument that explains its usage?

(I was looking into the usage of a Dokka binary that seemed to have come from somewhere other than the master branch of this git repo (after some investigation, it seems to have come from the devsite-with-java-layout-html branch of this git repo), making it not as easy to just browse the README to discover its usage (specifically, to discover the dac-as-java format))

Thanks!

**Comment by mathjeff** [comment]
(specifically, something like `java -jar dokka-fatjar.jar --help`)

**Comment by semoro** [comment]
Dokka does support `-help` argument, but it doesn't include a list of output formats at that point

**Comment by kamildoleglo** [comment]
Done in the CLI runner in `1.4.10.2`
