### ISSUE TITLE
[K2] Regression: Display expanded function types instead of abbreviated ones

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3649]
Due to the implemented [issue KT-68341](https://youtrack.jetbrains.com/issue/KT-68341/Analysis-API-Expanded-function-types-from-libraries-dont-have-an-abbreviated-type), Dokka generates, for example, the signature

```kt
fun <T> exception(callback: String.(T) -> String)
```
instead of

```kt
fun <T> exception(callback: HttpExceptionCallback<T>)
```
for 
```kt
typealias HttpExceptionCallback<T> = String.(T) -> String
fun <T> exception(callback: HttpExceptionCallback<T>){}"""
```

It is blocked by https://youtrack.jetbrains.com/issue/KT-68341/Analysis-API-Expanded-function-types-from-libraries-dont-have-an-abbreviated-type

**Comment by whyoleg** [comment]
@vmishenev AA issue is resolved, this means that we are not blocked anymore here?
