### ISSUE TITLE
Gradle plugin: `findProperty` causes "Project <x> cannot dynamically look up a property in the parent project" when Isolated Projects enabled

### ISSUE THREAD

**Issue by 3flex** [Kotlin/dokka#3656]
**Describe the bug**
Using Gradle's Isolated Projects mode flags an issue caused by this plugin.

dokka uses [`findProperty`](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api/-project/find-property.html) to check whether the `org.jetbrains.dokka.experimental.tryK2` property has been enabled or not. This is problematic as one of its behaviours is to "Search up through this project's ancestor projects" which causes the IP violation.

**Expected behaviour**
It should be possible to use dokka with Isolated Projects enabled.

**Screenshots**

**To Reproduce**
1. Checkout https://github.com/detekt/detekt
2. Run `./gradlew build -Dorg.gradle.unsafe.isolated-projects=true`

**Dokka configuration**
Run dokka with Gradle runner with `org.jetbrains.dokka.experimental.tryK2` property unset.

**Installation**
- Operating system: Windows
- Build tool: Gradle v8.8
- Dokka version: 1.9.20

**Additional context**
Possibly dokka support should be added & tracked in YouTrack under https://youtrack.jetbrains.com/issue/KT-64575.

A fix is likely as simple as using [`gradleProperty`](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#gradleProperty(java.lang.String)) instead on Gradle 6.2 and up.

**Comment by whyoleg** [comment]
Fixed in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html)
