### ISSUE TITLE
`//Unresolved` samples in javadoc

### ISSUE THREAD

**Issue by holgerbrandl** [Kotlin/dokka#366]
The `README.md` is counter-intuitive when it comes to building javadoc. It seems that when doing as suggested:
```
task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}
```
we **don't** inherit any properties of the `dokka{}` configuration, which results int samples not being resolved in the javadoc:

![image](https://user-images.githubusercontent.com/200952/46155647-1640a700-c278-11e8-801e-4a0477af5c29.png)

So to make it work what seems necessary is reconfigure it again (like point to samples dir again):
```
task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
    outputFormat = 'javadoc'
    outputDirectory = javadoc.destinationDir

    samples = ['src/test/kotlin/krangl/samples']

    inputs.dir 'src/main/kotlin'
}
```

With this configuration the javadoc (unzipped from the jar in the local maven repo) is fine:
![image](https://user-images.githubusercontent.com/200952/46155737-48ea9f80-c278-11e8-9fb2-bbefa02caefd.png)

**Comment by semoro** [comment]
It is OK that every new Dokka task should have its own documentation
Documentation should be updated

**Comment by Kordyjan** [comment]
This task is about the old way of defining dokka task which is no longer supported.
