### ISSUE TITLE
[K2] In case of multiple inheritance overriden methods from superclass missed

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3686]
In the scenario below `ChildWithTwoParent` misses `toString` method on it's page in K2

```Kotlin
open class FirstParent {
    fun basicMethod() = "OK"
    override fun toString(): String {
        return super.toString()
    }
}

interface ISecondParent {}

class ChildWithOneParent : FirstParent()
class ChildWithTwoParent : FirstParent(), ISecondParent
```

K2
<img width="600" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/35700884-2c8e-41d9-95a1-831f38094cce">

---

K1
<img width="600" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/b939ad94-1a9a-4ecf-a292-bb09329beacd">

---
**Installation**
- Dokka version: 2.0.0

**Comment by vmishenev** [comment]
It is worth to test with non-`toString`.

**Comment by vmishenev** [comment]
There is a workaround for https://youtrack.jetbrains.com/issue/KT-70326/Analysis-API-Inconsistent-allOverriddenSymbols-and-directlyOverriddenSymbols-for-an-intersection-symbol

**Comment by atyrin** [comment]
A minor thing: The `toString` method appeared in K2, but I see that we missed `override` keyword.
