### ISSUE TITLE
[K2] Synthetic property misses annotations from getter/setter

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3688]
Create a Java class and annotate the setter method.
```java
// JavaParent.java
import java.beans.BeanProperty;

public class JavaParent {
    private int context = 0;

    public int getContext() {
        return context;
    }

    @BeanProperty(required = true)
    public void setContext(int context) {
        this.context = context;
    }
}
```
Use it as a superclass in Kotlin.
```Kotlin
class A : JavaParent()
```
The synthetic property `context` will miss the annotation in Dokka.

K1:
<img width="600" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/b4f76e1a-6dea-48a3-b86d-a2afc8d35d24">

---

K2
<img width="600" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/180ae87e-5cd8-46c7-9a90-376cf3ff0d21">

**Comment by vmishenev** [comment]
In K2, we should get rid of this check.
