### ISSUE TITLE
Does not generate/copy stylesheet

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/dokka#37]
There is no style.css file generated in the build/dokka directory after using the Gradle plugin.

**Comment by mikehearn** [comment]
Actually this happens with the command line jar too.

**Comment by superbobry** [comment]
Even with `dokka` 0.9.2.

**Comment by cy6erGn0m** [comment]
I suppose it should be an option to copy stylesheet. The other issue is the path to css in the generated html is absolute so it will never work locally

**Comment by yole** [comment]
Fixed with https://github.com/Kotlin/dokka/pull/38
