### ISSUE TITLE
Generate javadocs ONLY for list of files

### ISSUE THREAD

**Issue by thejoswamy** [Kotlin/dokka#370]
I am working on an android library project. I want to provide javadocs ONLY for some classes to the library consumer. I want to generate javadocs only for a given list of classes using dokka.

**Comment by hannesa2** [comment]
I failed by specify it with

```
dokka {
    outputFormat = 'javadoc'
    includes = ['README.md']
    includeNonPublic = false
    skipDeprecated = true
    reportUndocumented = false
    skipEmptyPackages = true 
    cacheRoot = 'default'
    noStdlibLink = true

    packageOptions {
        prefix = "my.package.abc.internal"
        suppress = true
    }

    packageOptions {
        prefix = "internal"
        suppress = true
    }
}
```
I can do what I want, `suppress = true` doesn't work and include all classes in `internal` und sub packages

**Comment by semoro** [comment]
Package options should work for you
Strange that it doesn't work for `internal` prefix
Are you sure that prefix is correct, and your classes are actually in a package named `internal` or `internal.*`  ?

**Comment by hannesa2** [comment]
I can confirm the `internal` prefix and the classes are in package `my.package.abc.internal.*` and filter is not working

**Comment by thejoswamy** [comment]
My list of classes(for which kdocs are to be generated) are across packages, so I cant use packageOptions.

I don't want to include all the classes within a package path. Is there any other way I can reset the source file tree for dokka?

**Comment by dinuchiriac** [comment]
I'm trying to achieve the same results, `packageOptions suppress = true` is not working, any other ideas?

**Comment by dinuchiriac** [comment]
I managed to do this by overriding the `kotlinTasks` then use `sourceDirs` and `packageOptions` to add/filter packages, see example below:
```
kotlinTasks {
}
processConfigurations = []
sourceDirs = files("src/main/kotlin")

packageOptions {
    prefix = "com.domain.package"
    suppress = true
}
packageOptions {
    prefix = "com.domain.package"
    suppress = true
}

```

**Comment by davibe** [comment]
I want to exclude everything and only generate doc for some sub-package I have tried suppressing the top leven and un-suppressing the leaf but it does not work :(

**Comment by davibe** [comment]
Actually, it works if i invert the order

            perPackageOption {
                prefix = "com.very.specific.module"
                moduleName = 'output'
                suppress = false
            }

            perPackageOption {
                prefix = "com" 
                moduleName = 'outputnull'
                suppress = true
            }

**Comment by Kordyjan** [comment]
This issue is about the old way of configuring dokka tasks, which is as of 1.4.0 no longer supported.
