### ISSUE TITLE
[K2] KMP: Missed top level extension for type from another module in Android + JVM

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3700]
1. Create a project with 2 KMP module (android + jvm + any other target)
2. In Module1 declare a type
e.g.
```Kotlin
object Firebase
```

3. In Module2 declare an `expect` extension in common and create actual counterparts in all platform source sets.

With K1 the extension page will have all platforms
<img width="513" alt="image" src="https://github.com/user-attachments/assets/a8f2aad4-1db6-4db7-b59b-aa6487b88351">

K2:
<img width="526" alt="image" src="https://github.com/user-attachments/assets/159dce11-49b9-4d99-b845-0fcbce023b17">

[dokka-repros.zip](https://github.com/user-attachments/files/16311509/dokka-repros.zip)

**Comment by vmishenev** [comment]
Possible related:  [#3386](https://github.com/Kotlin/dokka/issues/3386)

**Comment by atyrin** [comment]
The issue was fixed in master somewhere. Probably by https://github.com/Kotlin/dokka/pull/3662
