### ISSUE TITLE
AndroidX kotlin package list is not recognized

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/dokka#372]
You can notice the difference between the [Kotlin version](https://developer.android.com/reference/kotlin/androidx/package-list) and the [non Kotlin version](https://developer.android.com/reference/androidx/package-list) where the Kotlin version has two extra lines at the beginning:
```
$dokka.format:java-layout-html
$dokka.mode:kotlin
```
These are not recognized by Dokka when having such a task:
```groovy
tasks.withType(dokka.getClass()) {
    externalDocumentationLink {
        url = new URL("https://developer.android.com/reference/kotlin/androidx/")
    }
}
```
and makes it impossible to refer to the Kotlin AndroidX doc.

I'd like to refer to it for this PR: https://github.com/Kotlin/kotlinx.coroutines/pull/655

**Comment by semoro** [comment]
This is not yet published linking format, as AndroidX Kotlin reference is preview

**Comment by LouisCAD** [comment]
Is there any workaround in the meantime?

**Comment by semoro** [comment]
Manual package list, so you can download one from AndroidX and modify it, and then use 
`packageListUrl = File(....).toUri().toURL()`

**Comment by Kordyjan** [comment]
As far as I understand this issue is no longer valid. Closing it for now, feel free to reopen.
