### ISSUE TITLE
Support backtick identifiers

### ISSUE THREAD

**Issue by EPadronU** [Kotlin/dokka#373]
## Explanation
The following does not work right now:

```
@sample com.domain.project.package.`identifier`
[com.domain.project.package.`identifier`]
```

## Why this would be nice to have?

In my particular case, I reuse tests as sample code in kdoc. Such tests are defined as follows:

```
@Test
fun `my human readable test name`() { ... }
```

## Current workaround

Given the fact _backtick identifier_ are not supported, I've had to rename my tests in order to use them as samples:

```
@Test(description = "my human readable test name")
fun my_not_so_human_readable_test_name() { ... }
```

Which is a shame.

**Comment by Kordyjan** [comment]
As far as I know, it is no longer an issue after the rewrite (1.4.0-rc and later). Closing for now, feel free to reopen.
