### ISSUE TITLE
Support text between samples

### ISSUE THREAD

**Issue by EPadronU** [Kotlin/dokka#384]
## Explanation
The following does not work right now:

```
### First scenario
@sample com.domain.project.package.identifier1
### Second scenario
@sample com.domain.project.package.identifier2
```

`Second scenario` is not shown in the output.

## Why this would be nice to have?

It would be nice to insert a header, a note, or any other use case for a specific sample.

**Comment by Kordyjan** [comment]
This should work in version 1.4.0-rc and later. If this problem persists feel free to reopen.

**Comment by LVMVRQUXL** [comment]
@Kordyjan This problem persists in Dokka 1.8.20... 😕

<img width="775" alt="Capture d’écran 2024-09-18 à 12 58 47" src="https://github.com/user-attachments/assets/25043d4e-f496-4eb2-9ca9-8c1fe8678a7a">
