### ISSUE TITLE
Silence / Reduce verbosity

### ISSUE THREAD

**Issue by xerus2000** [Kotlin/dokka#385]
Is there a setting or parameter for Dokka to not emit non-critical warnings or code-style issues? I am getting flooded, especially with `No documentation for ...`, even though not every single thing needs to be documented...

**Comment by Xerus2000** [comment]
Okay, now it is getting really weird. I tried to silence my dokka task using Gradle's built-in tools (https://docs.gradle.org/current/userguide/logging.html#sec:external_tools), but even that didn't work:
```
logging.captureStandardOutput(LogLevel.DEBUG)
logging.captureStandardError(LogLevel.DEBUG)
```
this should log stdout and stderr only when I am one the debug loglevel. It worked on a test task, but for the DokkaTask still everything came through...

**Comment by d4vidi** [comment]
Have you tried using `reportUndocumented = false`? (see https://github.com/Kotlin/dokka#using-the-gradle-plugin)

**Comment by Xerus2000** [comment]
That seems new. But I'd also like a setting that turns off all noncritical warnings at once, or a way to redirect the output.

**Comment by Xerus2000** [comment]
I have added that flag that now, but still: https://travis-ci.com/CAU-Kiel-Tech-Inf/socha/builds/143039544
The log consists of over a thousand lines, almost 500 of which are some obscure dokka errors.
Using dokka version 0.9.17, in the process of migrating to the newer one.

**Comment by Kordyjan** [comment]
This shouldn't be a problem in dokka after the rewrite, as it shares virtually no common code with the old dokka. If the problems occur again, feel free to report them.
