### ISSUE TITLE
Dokka plugin fails on Gradle 5.0

### ISSUE THREAD

**Issue by liutikas** [Kotlin/dokka#388]
I initially thought it was a bug in Gradle ([filled issue here](https://github.com/gradle/gradle/issues/7598)), however Gradle folks came back to me pointing out that Dokka plugin POM files have an issue.

Namely artifacts pushed to jcenter() seem to have broken POM files. Full details noted in the [Gradle issue comment](https://github.com/gradle/gradle/issues/7598#issuecomment-435814748). Important thing to note is that Gradle plugin portal has the correct POM files.

**Comment by tiembo** [comment]
@semoro this can be closed
