### ISSUE TITLE
[Dokka 2] Unable to override `source_set_selector.ftl`

### ISSUE THREAD

**Issue by MGaetan89** [Kotlin/dokka#3884]
I'd like to customize the `source_set_selector.ftl` template to change how the platform buttons are displayed (or rather hide them if there is only one available).

**Describe the bug**

In my Dokka configuration, I've added:
```kotlin
dokka {
    pluginsConfiguration.html {
        templatesDir.set(file("docs/templates"))
    }
}
```

And my `docs/templates/includes/source_set_selector.ftl` contains the following:
```ftl
<#macro display>
    Hello!
</#macro>
```

But the default template seems to be used, as I still see the platform buttons, instead of my `Hello!` message.

**Expected behaviour**

The platform buttons are not shown, and `Hello!` is displayed instead. I also have a `page_metadata.ftl` file, which is applied as expected.

**Alternatives**

Is my project, we only have one platform (Android), so we have no use for the platform filters in the navigation bar, on the platform indicators in the lists of symbols. So if there is an option to hide these when there is only one platform, that would work for us too.

**Installation**

- Operating system: macOS 15.0.1
- Build tool: Gradle 8.10.2
- Dokka version: 2.0.0-Beta

**Comment by adam-enko** [comment]
Hi, please could you try relocating `docs/templates/source_set_selector.ftl` to `docs/templates/includes/source_set_selector.ftl`? The new file needs to have the same relative path to the one you want to overwrite.

I don't think this behaviour is intuitive so I'd like to see it improved.

**Comment by MGaetan89** [comment]
Oops, sorry, that was a typo in the issue description. The file is actually in `docs/templates/includes/source_set_selector.ftl`.
It's in the same folder as our custom `page_metadata.ftl`, which works fine.

**Comment by MGaetan89** [comment]
The problem was actually on my side.
The file had a trailing space in its name: `source_set_selector.ftl ` instead of `source_set_selector.ftl`.

Sorry about the confusion.

**Comment by adam-enko** [comment]
Thanks for the update, I'm glad you got it working.
