### ISSUE TITLE
[Dokka 2] Adding external documentation link to Ktor points to the wrong page

### ISSUE THREAD

**Issue by MGaetan89** [Kotlin/dokka#3889]
**Describe the bug**

In my project, I've added the following source set configuration in order to have links to the Ktor API documentation:

```kotlin
dokka {
    dokkaSourceSets.getByName("main") {
        externalDocumentationLinks.register("ktor") {
            url.set(URI("https://api.ktor.io"))
            packageListUrl.set(URI("https://api.ktor.io/package-list"))
        }
    }
}
```

However, my generated Dokka documentation points to the wrong link.
For example, given the following KDoc:

```kotlin
import io.ktor.client.plugins.ClientRequestException

/**
 * Some documentation using [ClientRequestException].
 */
```

The link on `ClientRequestException` will point to:
https://api.ktor.io/ktor-client-core/io.ktor.client.plugins/-client-request-exception/index.html
instead of:
https://api.ktor.io/ktor-client/ktor-client-core/io.ktor.client.plugins/-client-request-exception/index.html
(note the missing `ktor-client` folder after the hostname).

**Expected behaviour**

The link on `ClientRequestException` should point to the right page.

**Installation**

- Operating system: macOS 15.1
- Build tool: Gradle v8.10.2
- Dokka version: 2.0.0-Beta

**Comment by whyoleg** [comment]
same as https://github.com/Kotlin/dokka/issues/2444

**Comment by MGaetan89** [comment]
Oops, sorry about that. I'll close this issue to keep the discussion in one place.
