### ISSUE TITLE
[Dokka 2] References from a module description to module's classes are no longer rendered as links

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/dokka#3890]
**Describe the bug**

After updating DGP to `2.0.0-Beta`, references from a markdown document describing a module to classes/functions from that module are no longer rendered as HTML links in resulting documentation.

**Expected behaviour**
References to classes are rendered as links to corresponding classes documentation.

**Screenshots**
<img width="1151" alt="Screenshot 2024-10-30 at 1 55 24 PM" src="https://github.com/user-attachments/assets/413598fd-862b-4786-84aa-df9898bdc77a">

**To Reproduce**
Checkout [dgp-2.0](https://github.com/Kotlin/kotlinx.coroutines/tree/dgp-2.0) branch from `kotlinx.coroutines` and run `./gradlew dokkaGenerate`.

Check https://github.com/Kotlin/kotlinx.coroutines/pull/4257 for detailed configuration.
The same issue is also reproducible with `kotlinx-io` after updating the Dokka.

**Comment by whyoleg** [comment]
kotlinx-io PR: https://github.com/Kotlin/kotlinx-io/pull/410

Let's recheck after https://github.com/Kotlin/dokka/pull/3814 is merged - I have a good feeling it could be related

**Comment by whyoleg** [comment]
fixed in https://github.com/Kotlin/dokka/pull/3942
