### ISSUE TITLE
Doc from Java files not included

### ISSUE THREAD

**Issue by jankotek** [Kotlin/dokka#39]
I have project with mixed Kotlin and Java files. Both depends on each other and compile together just fine. But Dokka does not include Java files  in documentation.

**Comment by yole** [comment]
How exactly are you invoking Dokka?

**Comment by jankotek** [comment]
Maven project, but I also tried command line fat jar with the same result. 

Both java and kotlin files are in `src/main/java`. It will be on github next week. Relevant pom:

```
  <dokka.version>0.9.3</dokka.version>
...
   <!-- required for Dokka (Kotlin javadoc) -->
    <pluginRepositories>
        <pluginRepository>
            <id>jcenter</id>
            <name>JCenter</name>
            <url>https://jcenter.bintray.com/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </pluginRepository>
    </pluginRepositories>
....
            <plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>${dokka.version}</version>
                <executions>
                    <execution>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>dokka</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by jankotek** [comment]
Source code & pom file is here (branch `mapdb3`, submodule `mapdb`)
https://github.com/jankotek/mapdb/tree/mapdb3/mapdb

It uses dokka 0.9.4. Result does not include java classes (for example `org.mapdb.Serializer`). 

I invoke maven with `mvn clean site`. I also tried fatjar:

`java -jar ~/downloads/dokka-fatjar.jar src/main/java/`

**Comment by jankotek** [comment]
Thanks
