### ISSUE TITLE
Suggestion: Add ability to supply custom stylesheets

### ISSUE THREAD

**Issue by thomorl** [Kotlin/dokka#394]
With `javadoc`, you can supply your own stylesheet through the `-stylesheet` command line option or via configuration in the build system (Gradle, Maven).  
It would be nice to have a similar configuration option for dokka (at least for the _html_ and _javadoc_ output formats), instead of hacking it into the documentation by replacing files after the `dokka` task is finished.

**Comment by pvillela** [comment]
I agree.  The existing default stylesheet results in text that is too small on both my 13" Ubuntu machine and my 15" Mac.

**Comment by mikezx6r** [comment]
This would allow for styling of the code blocks too, unless someone is aware of an alternate approach.

**Comment by kamildoleglo** [comment]
Done in `1.4.10.2`
