### ISSUE TITLE
How Can I get class annotations from kotlin?

### ISSUE THREAD

**Issue by fvoidCN** [Kotlin/dokka#400]
I can't get class annotations from kotlin. But it can work in Java. 

![image](https://user-images.githubusercontent.com/27288499/50761228-d2146800-12a4-11e9-80e6-1ad761bba391.png)

![image](https://user-images.githubusercontent.com/27288499/50761350-20296b80-12a5-11e9-8c8e-9d8dce461857.png)

**Comment by Kordyjan** [comment]
This question is about the old dokka model, which is no longer maintained. For the new dokka equivalent: https://github.com/Kotlin/dokka/blob/master/plugins/developer_guide.md#dokka-data-model
