### ISSUE TITLE
https urls are broken

### ISSUE THREAD

**Issue by rekire** [Kotlin/dokka#405]
Url get broken by dokka. Here is my example:

```
/**
 * Possible types of Emphasis. [https://www.w3.org/TR/speech-synthesis11/#S3.2.2]
 */
```

The result of the generated markdown file is this here:

    Possible types of Emphasis. [https//www.w3.org/TR/speech-synthesis11/#S3.2.2](https//www.w3.org/TR/speech-synthesis11/#S3.2.2)

That should be fixed.

**Comment by kamilok1965** [comment]
Fixed in https://github.com/Kotlin/dokka/commit/61a3587abeb35908b09e169bb55e2a9f1890c195
