### ISSUE TITLE
When is the next dokka release?

### ISSUE THREAD

**Issue by DarrylBayliss** [Kotlin/dokka#406]
Hi,

When is the next release of dokka expected? There is an issue (
https://github.com/Kotlin/dokka/issues/343) marked to be fixed in 0.9.18  https://github.com/Kotlin/dokka/milestone/6 that we would like to take advantage of.

**Comment by KrystianUjma** [comment]
Hello, 

release is coming soon, it's almost done.

**Comment by KrystianUjma** [comment]
released new version [0.9.18](https://github.com/Kotlin/dokka/releases/tag/0.9.18).
