### ISSUE TITLE
Support more compact docs on same line as code

### ISSUE THREAD

**Issue by sschuberth** [Kotlin/dokka#410]
Esp. for documenting `enum` members, it would be nice if a more compact documentation format would be supported, similar to [Doxygen](http://www.doxygen.nl/manual/docblocks.html#memberdoc). So for example instead of

    enum class Foo {
        /**
         * Docs for BAR.
         */
        BAR
    }

one could write

    enum class Foo {
        BAR ///< Docs for BAR.
    }

**Comment by Fleshgrinder** [comment]
While I agree that this would be awesome it would also require an issue to be filed against IntelliJ and probably even KDoc since it’s non-standard and would only be supported by Dokka and nothing else. In the meantime: write it in a single line:

```kotlin
enum class Foo {
    /** Docs for BAR. */
    BAR
}
```

**Comment by Kordyjan** [comment]
This is an interesting idea, but KDoc is part of language standard so it is not up to us to decide on that.
