### ISSUE TITLE
Dokka generates link with text "class Foo" for class reference `[Foo]`

### ISSUE THREAD

**Issue by timmc** [Kotlin/dokka#415]
I'm using `org.jetbrains.dokka/dokka-maven-plugin` version 0.9.17. Here's a sample comment:

```
    /**
     * Parse a full URL into an intermediate representation that a [Url]
     * implementation can read.
     */
```

Expected behavior: The reference becomes a link like so (bold standing in for link):

> Parse a full URL into an intermediate representation that a **Url** implementation can read.

Actual behavior: The `[Url]` reference is correctly resolved, but an extra word is added:

> Parse a full URL into an intermediate representation that a **class Url** implementation can read.

**Comment by Kordyjan** [comment]
As far as I know, this is no longer an issue in 1.4.0-rc and later versions.
