### ISSUE TITLE
DokkaAndroidTask generates BuildConfig and R files for multi module setting

### ISSUE THREAD

**Issue by CoderSpinoza** [Kotlin/dokka#419]
I am using below task to generate dokka documentation for my multi-module project. The problem is that the generated documentation contains files for BuildConfig and R classes that should be usually excluded when I override org.jetbrains.dokka.gradle.DokkaAndroidTask, as specified in #224. I believe that these files are added to the sourceDirs settings due to my kotlinTasks settings. Since dokka currently does not support excluding specific classes, only packages, I can't find an easy way to achieve this simply.

What would be the best way to fix this problem?

```gradle
task dokka(overwrite: true, type: org.jetbrains.dokka.gradle.DokkaAndroidTask) {
    outputFormat = 'html'

    kotlinTasks {
        defaultKotlinTasks() + rootProject.subprojects.compileDebugKotlin
    }

    outputDirectory = "${rootProject.buildDir}/dokka"

    includes = [ 'dokka.md' ]
    includeNonPublic = false
    skipEmptyPackages = true

    for (String docUrl: ["https://d.android.com/reference/"
                         "http://reactivex.io/RxJava/javadoc/",
                         "https://square.github.io/retrofit/2.x/retrofit/"
    ]) {
        externalDocumentationLink {
            // Root URL of the generated documentation to link with. The trailing slash is required!
            url = new URL(docUrl)
            // If package-list file located in non-standard location
            packageListUrl = new URL("${docUrl}package-list")
        }
    }

    for (String pkg : ["androidx", "dagger", "io.reactivex", "com.google"]) {
        packageOptions {
            prefix = pkg
            suppress = true
        }
    }
}
```

**Comment by CoderSpinoza** [comment]
I guess this issue has been resolved by 0.10.0 subProjects setting. Is that right?

**Comment by kamilok1965** [comment]
Probably yes. I think you can also add files you want to suppress to the `suppressedFiles` list (this is an undocumented param as it is not tested yet)

**Comment by CoderSpinoza** [comment]
@kamilok1965  Tested with 0.10.0 and checked the issue was resolved.

> Probably yes. I think you can also add files you want to suppress to the `suppressedFiles` list (this is an undocumented param as it is not tested yet)

Cool! Does it also accept regex?

**Comment by kamilok1965** [comment]
Nope, unfortunately it's only a list of files, however you can select the files you want to suppress with regex in the Gradle DSL itself 

I'm happy that your issue has been resolved, I'll close this issue then
