### ISSUE TITLE
Cannot configure external documentation links in Dokka Gradle plugin

### ISSUE THREAD

**Issue by CommanderTvis** [Kotlin/dokka#421]
I'm using Dokka to generate docs of my Kotlin project. 

My project has well-documented dependencies and I want to configure external documentation links. But it doesn't work and links that should lead to external JD lead to #. 

```kotlin
tasks.withType<DokkaTask> {
    externalDocumentationLinks = mutableListOf(
        ExternalDocumentationLinkImpl(
            URL("https://hub.spigotmc.org/javadocs/spigot/"),
            URL("https://hub.spigotmc.org/javadocs/spigot/package-list")
        ),
        ExternalDocumentationLinkImpl(
            URL("https://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/"),
            URL("https://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/package-list")
        )
    )
    impliedPlatforms = mutableListOf("JVM")
    includes = listOf(file("PACKAGES.md"))
    moduleName = "main"
    noStdlibLink = false
    outputDirectory = "public/"
    outputFormat = "html"
    perPackageOptions = mutableListOf(
        PackageOptions().apply {
            includeNonPublic = false
            prefix = "kotlin"
            reportUndocumented = true
            skipDeprecated = false
            suppress = false
        }
    )
    sourceRoots = mutableListOf(
        SourceRoot().apply { path = "common/src/main/kotlin/" },
        SourceRoot().apply { path = "chat/src/main/kotlin/" },
        SourceRoot().apply { path = "config-yml/src/main/kotlin/" }
    )
}
```

This is my configuration, what's wrong with `externalDocumentationLinks` field?

**Comment by CommanderTvis** [comment]
I've published generated documentation, if it can help. http://tvis.gitlab.io/plugin-api/main/

**Comment by semoro** [comment]
Looks like classpath configuration is missing, so Dokka can't find out what dependencies is 
Check the build log with `--debug` option for `CLASSPATH: ` from Dokka output and verify that every jar which is used in compilation also provided there. If not, consider providing `classpath` option to Dokka configuration

**Comment by CommanderTvis** [comment]
I've fixed this problem by adding my dependencies to `allprojects` from `subprojects` block. Thanks!
