### ISSUE TITLE
How can I get the qualified name of annotations.

### ISSUE THREAD

**Issue by fvoidCN** [Kotlin/dokka#422]
I want to get the annotations qualified name of class and method. But I can only get the simple name. How can I get the qualified name of them?

**Comment by Kordyjan** [comment]
I know it is an older issue about the old dokka model, but it is worth answering if it comes up in search results for someone in the future.
Right now it is really simple. Having a `DFunction` instance called `method` you can access it like that `method.extra[Annotations]` this gives you a map expressing what annotations are assigned to a given symbol in different sourcesets. Annotation objects stored in that map have `dri` property which is equivalent to fully qualified name.

For more info: https://github.com/Kotlin/dokka/blob/master/plugins/developer_guide.md#dokka-data-model
