### ISSUE TITLE
Why don't use qualified name in annotations?

### ISSUE THREAD

**Issue by fvoidCN** [Kotlin/dokka#423]
In JavaPsiDocumentationBuilder.kt
![image](https://user-images.githubusercontent.com/27288499/52768543-c6b51900-3068-11e9-984e-a4db47343d4d.png)
Why don't use qualified name? I can't distinguish the annotation Which use same name.

**Comment by Kordyjan** [comment]
It is no longer a case in newer versions of dokka. Annotations are identified by their fqnames.
