### ISSUE TITLE
Allow including docs for internal/protected members but not private members

### ISSUE THREAD

**Issue by TAGC** [Kotlin/dokka#434]
Currently Dokka only exposes the boolean configuration option `includeNonPublic`, which forces you to choose between including only public members; or private, internal, protected and public members with no in-between.

It would be nice to be able to be able to include documentation for internal/protected members without having a plethora of warnings about not documenting private members.

**Comment by mkrussel77** [comment]
What I would really want is to show public and protected and not internal and private.
The default option now is to show public/internal and skip protected/private. 

Internal should be grouped with private, and protected with public if you do want to have a single flag.

**Comment by IgnatBeresnev** [comment]
Will be in one of the nearest releases (1.6.20?). You'll be able to document whatever visibilities you choose

```
    documentedVisibilities.set(
        setOf(
            Visibility.PUBLIC,
            Visibility.PRIVATE,
            Visibility.PROTECTED,
            Visibility.INTERNAL
        )
    )
```
