### ISSUE TITLE
Exception name is missing in Javadoc

### ISSUE THREAD

**Issue by ltennstedt** [Kotlin/dokka#437]
The exception name is missing in generated Javadoc but is shown in generated HTML.

**Javadoc**
![javadoc](https://user-images.githubusercontent.com/27898583/53697924-91355d00-3dd6-11e9-9dde-a198ea0c38ac.png)

**Dokka**
![dokka](https://user-images.githubusercontent.com/27898583/53697925-92ff2080-3dd6-11e9-9764-2747e88a1491.png)

**Steps to reproduce**

- Clone [example project](https://github.com/ltennstedt/dokka-javadoc-exception)
- Run `gradle dokka dokkaJavadoc`
- Take a look at the generated Javadoc and HTML

Kotlin 1.3.21
Dokka 0.9.17
Gradle 5.2.1
OpenJDK 1.8.0_202-b26
OS: Arch Linux (Linux 4.20.13-arch1-1-ARCH amd64)

**Comment by Kordyjan** [comment]
Should be fixed in 1.4.0-rc.
