### ISSUE TITLE
generate Android kotlin library aar

### ISSUE THREAD

**Issue by yan612468** [Kotlin/dokka#439]
i hava a kotlin module library , i want generate aar file, how to use dokka to generate kotlin aar file?

**Comment by semoro** [comment]
It's not clear what the point of generating aar file with documentation
Basically, you should make it like creating documentation jar

Ex:
```
task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}

task javadocJar(type: Jar, dependsOn: dokkaJavadoc) {
    classifier = 'javadoc'
    from "$buildDir/javadoc"
}
```

**Comment by kamilok1965** [comment]
Hi @yan612468, is this still relevant?
