### ISSUE TITLE
Provide a way to identify which Dokka version has been used for the generation

### ISSUE THREAD

**Issue by wild-lynx** [Kotlin/dokka#444]
Sometimes it's good to know which version of the plugin was actually used for the documentation. Not which version is specified in build configurtion, but which was actually used. 
`gradlew -dependencies` or `gradlew -debug` didn't work well

**Comment by Kordyjan** [comment]
In 1.4.0 and later versions, dokka is printing its version to output. You can also use `./gradlew dependencies` task to check out what exact versions of dokka plugins are resolved for different tasks.
