### ISSUE TITLE
Show members visibility at the summary page

### ISSUE THREAD

**Issue by wild-lynx** [Kotlin/dokka#445]
Currently, members visibility isn't shown at the summary page. For example, for the following code: 
```
open class WithProtected {
    /**
     * This is a protected fun 
     * */
    protected fun pfun() { }
}
```
— preview of `pfun` at `WithProtected` documentation page wouldn't have the visibility modifier. 

It might be useful to display these at the preview as well.

**Comment by IgnatBeresnev** [comment]
Not relevant for 1.6.21. Note: to see non-public members you need to add `documentedVisibilities` setting

![2022-04-27_19-33-58](https://user-images.githubusercontent.com/22685910/165568553-be0d7efc-120c-423e-b620-2c97c8e857bf.png)
