### ISSUE TITLE
Add another Dokka distribution that is not a fatjar 

### ISSUE THREAD

**Issue by apatrida** [Kotlin/dokka#45]
For use in other systems where we want to control the dependencies a bit more, we can test if we change anything that conflicts.

**Comment by yole** [comment]
What exactly do you want to control? We ship dokka as a fatjar because its key dependencies (such as kotlin-for-upsource.jar) are not available as separate artifacts with proper versioning, and we don't currently plan to make them available as such.

**Comment by apatrida** [comment]
Make a semi-fatjar alternative that doesn't include the kitchen sink.  What if we have a slightly bug-fixed version of JSoup, or some other common library, and you prevent us from using it.  At least shade/rename things that are common (see other issue)

**Comment by semoro** [comment]
@apatrida Are cli and ant launchers should be included?

**Comment by semoro** [comment]
Closing ticket as got no replay
