### ISSUE TITLE
When using tests as source, Dokka complains the tests don't have documentation

### ISSUE THREAD

**Issue by mikezx6r** [Kotlin/dokka#452]
But of course the tests are being used as samples, and we don't normally document tests with KDoc, so.

Here's a sample project. When I run `./gradlew dokka` in the `mw/dokka-tests-not-covered-issue` branch, it complains that the tests don't have documentation.

https://gitlab.com/mikezx6r/dokka-demo/tree/mw/dokka-tests-not-covered-issue

**Comment by gabrielshanahan** [comment]
I'd like to +1 this, and someone else has asked a similar question on StackOverflow(https://stackoverflow.com/questions/55463556/exclude-samples-from-dokka-documentation).

My use case is, I want to point @sample at code in my tests, but I don't want doc's generated for my tests. If I use the "samples" configuration directive, I get doc's generated for all my test classes. How do I achieve this?

I don't think it should be necessary to annotate every class in every test file just to be able to reference some code. Furthermore, I don't believe that the samples directive should include the files for doc's generation, there is a completely separate mechanism for that. If that is what the user wants, he will add them using the appropriate directives, such as sourceRoot.

**Comment by kamilok1965** [comment]
Have you tried to exclude the tests with `perPackageOption`s?

**Comment by gabrielshanahan** [comment]
@kamilok1965 The tests are in the same package as the source files, which I believe is commonly the case

**Comment by cmoine** [comment]
I think I have found a way to achieve this. It is not 100% clean, but it seems to work:
I add tests to samples in the `build.gradle`:
```
dokka {
    configuration {
        samples = ['src/test/kotlin']
    }
}
```
Then in order to do not have the tests in the generated documentation, I add
`@suppress` in my Kotlin tests (it seems to be an issue with Java files...)

**Comment by 05nelsonm** [comment]
Is there any way to include samples from a different module? For example, an Android Library and a Demo App. Generate docs for the Library and link to samples within the Demo Application?
