### ISSUE TITLE
Dokka not generating documentation for Test Cases

### ISSUE THREAD

**Issue by HemanParbhakar** [Kotlin/dokka#454]
I am using Dokka in Kotlin Android Project the document is getting generated but the document is not covering the Unit Test and AndroidJUnit test Cases.

**Comment by KrystianUjma** [comment]
Hello,

according to dokka readme you can generate docs for tests by adding `sourceDirs` or `sourceRoot` to your `build.gradle`. Here is short example:
```kotlin
task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
    sourceDirs = files('src/test/kotlin')

    //or

    sourceRoot {
        // Path to source root
        path = "src/test/kotlin"
        // See platforms section of documentation
        platforms = ["JVM"]
    }
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/dokkaJavadoc"
}

```

**Comment by kamilok1965** [comment]
Hi @HemanParbhakar, is this still relevant?
