### ISSUE TITLE
Get docs at runtime 

### ISSUE THREAD

**Issue by Kinmarui** [Kotlin/dokka#456]
Is there any way to use dokka to retrieve dokka / javadoc from files at runtime similar to `com.sun.tools.javadoc.Main.execute()` ?

I would need that to dynamicly add information taken from source classes to [C4 model](https://c4model.com/) in structurizr you can check implementation for javadoc [here](https://github.com/structurizr/java/blob/master/structurizr-analysis/src/com/structurizr/analysis/SourceCodeComponentFinderStrategy.java)

FYI I also opened https://github.com/structurizr/java/issues/120 in which I will also try to find solution how to dynamically add docs to structurizr.

**Comment by Kordyjan** [comment]
It seems like a perfect use for our plugin system introduced in 1.4.0. You can check it out here: https://github.com/Kotlin/dokka/blob/master/plugins/developer_guide.md
