### ISSUE TITLE
Option to fail on warning

### ISSUE THREAD

**Issue by 3flex** [Kotlin/dokka#459]
It would be useful to have an option to fail the build when warnings are found so this can be enforced by CI builds.

**Comment by langsmith** [comment]
Yes, would love this feature as well 🙏

**Comment by tobrun** [comment]
you can use a simple bash script to work around this limitation:
```
./gradlew module:dokka -i | grep -i 'No documentation for' && { echo 'kdoc validation failed' ; exit 1; }
```
not ideal, but suffices until this feature is implemented
