### ISSUE TITLE
Gradle build fails for multiple DokkaTasks: cannot change dokkaRuntime configuration after it has been resolved

### ISSUE THREAD

**Issue by knolleCC** [Kotlin/dokka#462]
Besides the default dokka task I have a special JavaDoc task.
Since 0.9.18 I cannot run both in the same build, since dokka tries to change the dokkaRuntime configuration for each task which is permitted by Gradle:

> Cannot change dependencies of configuration 'dokkaRuntime' after it has been resolved.

**Comment by semoro** [comment]
This is a regression introduced by #432, need to fix in `0.9.19`

**Comment by michaelbayles** [comment]
Any workaround for this? (Besides downgrading to `0.9.17` of course)

**Comment by semoro** [comment]
Please, try manually configure `dokkaRuntime` 
Like: 
```
dependencies {
    dokkaRuntime 'org.jetbrains.dokka:dokka-fatjar:0.9.18'
}
```

**Comment by KrystianUjma** [comment]
pushed on [multiplatform branch](https://github.com/Kotlin/dokka/tree/multiplatform-support). We will release it in 0.9.19.

**Comment by Den-Rimus** [comment]
> Please, try manually configure `dokkaRuntime`
> Like:
> 
> ```
> dependencies {
>     dokkaRuntime 'org.jetbrains.dokka:dokka-fatjar:0.9.18'
> }
> ```

@semoro 
Adding this results in error: `Gradle DSL method not found: 'dokkaRuntime()'`

I'm trying to use Dokka 0.9.18 with Gradle 6.0.1 (for some reasons we need 0.9.18, not 0.10)
