### ISSUE TITLE
Allow for property injection, templating, or other static information

### ISSUE THREAD

**Issue by michaelbayles** [Kotlin/dokka#468]
I want to put some common information on every page of the HTML output. Company name, company logo, copyright information, version information, etc. Basic stuff, but I'm struggling to find a way to inject these properties

**Comment by semoro** [comment]
You should look into custom formats I'd think. Take a look on #293

**Comment by Kordyjan** [comment]
Right now it waaaay easier to achieve using plugins. Just take a look: https://github.com/Kotlin/dokka/blob/1.4.0-rc/plugins/developer_guide.md
