### ISSUE TITLE
Enum Values are listed in lexicographical order instead of their natural order

### ISSUE THREAD

**Issue by mfulton26** [Kotlin/dokka#47]
e.g.

Given the following Kotlin `enum class`:

    enum class Gender { MALE, FEMALE }

Dokka generates HTML like this:

> # Gender
> `enum class Gender`
> <table><tbody><tr><td><a href="#-f-e-m-a-l-e">FEMALE</a></td><td></td></tr><tr><td><a href="#-m-a-l-e">MALE</a></td><td></td></tr></tbody></table>

But I expect HTML like this:

> # Gender
> `enum class Gender`
> <table><tbody><tr><td><a href="#-m-a-l-e">MALE</a></td><td></td></tr><tr><td><a href="#-f-e-m-a-l-e">FEMALE</a></td><td></td></tr></tbody></table>

(With `MALE` before `FEMALE`.)

**Comment by yole** [comment]
Fixed

**Comment by LanderlYoung** [comment]
@yole Also, I don't want my methods/properties be sorted, is there any flag to do so?

**Comment by yole** [comment]
No, and such a flag cannot be added. Dokka groups overloads of a method on the same page, so it's impossible to preserve the order of members in the source code in a general case.
