### ISSUE TITLE
Dokka build fail with DataBinding enabled

### ISSUE THREAD

**Issue by btrincao-i9** [Kotlin/dokka#473]
When dataBinding is added to gradle, dokka cannot build Docs.

```
dataBinding {
        enabled = true
}
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
```

Also, databinding tags on xml files trow an exception:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /app/src/main/res/layout/activity_splash.xml:31: AAPT: error: '@{viewModel.showLoading ? View.VISIBLE : View.GONE}' is incompatible with attribute visibility (attr) enum [gone=2, invisible=1, visible=0].
```

After I comment/remove dataBinding from xml and gradle:

```
BUILD SUCCESSFUL in 4s
17 actionable tasks: 6 executed, 11 up-to-date
```

I saw that on version 0.9.16 was implemented package suppress, but only works for folders inside src/main/java. There is a way to suppress 'res' folder?

**Comment by IgnatBeresnev** [comment]
@atyrin I bet you have an android project at hand :) Can I ask you to try to reproduce it please? I don't have a working android project at the moment, unfortunately

**Comment by atyrin** [comment]
I've tried to build [official sample projects](https://github.com/android/databinding-samples) with Dokka `1.7.20`, and everything went well. So, I assume that the issue is not actual anymore. Please, reopen the issue if it isn't true.
