### ISSUE TITLE
externalDocumentationLink is not working

### ISSUE THREAD

**Issue by joserobjr** [Kotlin/dokka#474]
I'm generating javadocs using dokka in two different libraries. [NBT-Manipulator](https://github.com/GameModsBR/NBT-Manipulator) and [Region-Manipulator](https://github.com/GameModsBR/Region-Manipulator). The Region library uses and exposes the NBT library.

The issue is that the Region-Manipulator's javadoc isn't linking to the NBT-Manipulator's javadoc even though I've added that to the file:
```gradle
dokka {
        externalDocumentationLink {
            url = new URL('https://gamemodsbr.github.io/NBT-Manipulator/javadoc/')
            packageListUrl = new URL("https://gamemodsbr.github.io/NBT-Manipulator/javadoc/package-list")
        }
    }
```

The dokka configuration block is inside a if condition, I tried without that but still didn't work. I also tried to generate a html format but without success, it just doesn't link.

https://github.com/GameModsBR/Region-Manipulator/blob/e668971ad3f1b52d81baaa7d9883c2c7b23216e7/build.gradle#L143-L158

This is what I get using the javadoc format:
```java
Can't find node by signature `not implemented for deserialized class NbtCompound with psi: null`, referenced at br.com.gamemods.regionmanipulator.Chunk$compound (Chunk.kt:17)
```

And this is what I get using the html format:
```java
Can't find node by signature `br.com.gamemods.nbtmanipulator.NbtCompound`, referenced at br.com.gamemods.regionmanipulator.Chunk$compound (Chunk.kt:17)
```
And this what I have at Chunk.kt:17:
https://github.com/GameModsBR/Region-Manipulator/blob/e668971ad3f1b52d81baaa7d9883c2c7b23216e7/src/main/kotlin/br/com/gamemods/regionmanipulator/Chunk.kt#L17-L21

This is the generated javadoc:
https://gamemodsbr.github.io/Region-Manipulator/javadoc/br/com/gamemods/regionmanipulator/Chunk.html

And this is there the javadoc should be linking:
https://gamemodsbr.github.io/NBT-Manipulator/javadoc/br/com/gamemods/nbtmanipulator/package-summary.html

I also tried to add `classpath = configurations.compile` as stated in FAQ but nothing...

**Comment by kamilok1965** [comment]
Hi @joserobjr, is this still relevant?
