### ISSUE TITLE
Missing line breaks on <init> with multiple constructors

### ISSUE THREAD

**Issue by joserobjr** [Kotlin/dokka#475]
```kotlin
/**
 * A tag which wraps a byte value.
 * @property value The wrapped value
 */
data class NbtByte(var value: Byte) : NbtTag() {
    /**
     * Wraps a byte `1` if the value is `true` and `0` otherwise.
     * @param value The value to be checked
     */
    constructor(value: Boolean): this(if (value) BYTE_TRUE else 0)

    /**
     * Converts the int value to an unsigned byte and wraps it.
     * @param unsigned Unsigned value from `0` to `255`.
     */
    constructor(unsigned: Int): this((unsigned and 0xFF).toByte())
}
```

Is becoming:

> [br.com.gamemods.nbtmanipulator](../index.md) / [NbtByte](index.md) / [&lt;init&gt;](./-init-.md)
> 
> # &lt;init&gt;
> 
> `NbtByte(value: `[`Boolean`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/index.html)`)`
> 
> Wraps a byte `1` if the value is `true` and `0` otherwise.
> 
> ### Parameters
> 
> `value` - The value to be checked`NbtByte(unsigned: `[`Int`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-int/index.html)`)`
> 
> Converts the int value to an unsigned byte and wraps it.
> 
> ### Parameters
> 
> `unsigned` - Unsigned value from `0` to `255`.`NbtByte(value: `[`Byte`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte/index.html)`)`
> 
> A tag which wraps a byte value.
> 

Expected result:

> [br.com.gamemods.nbtmanipulator](../index.md) / [NbtByte](index.md) / [&lt;init&gt;](./-init-.md)
> 
> # &lt;init&gt;
> 
> `NbtByte(value: `[`Boolean`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/index.html)`)`
> 
> Wraps a byte `1` if the value is `true` and `0` otherwise.
> 
> ### Parameters
> 
> `value` - The value to be checked
> 
> `NbtByte(unsigned: `[`Int`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-int/index.html)`)`
> 
> Converts the int value to an unsigned byte and wraps it.
> 
> ### Parameters
> 
> `unsigned` - Unsigned value from `0` to `255`.
> 
> `NbtByte(value: `[`Byte`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte/index.html)`)`
> 
> A tag which wraps a byte value.

Affects `gfm`, `jekyll` and `markdown` output formats.

It affects both <init> details and summary as seen here:
https://gamemodsbr.github.io/NBT-Manipulator/kdoc/br.com.gamemods.nbtmanipulator/-nbt-byte/

**Comment by joserobjr** [comment]
I also noticed it happening on methods with the same name, like this one:
https://gamemodsbr.github.io/Region-Manipulator/kdoc/br.com.gamemods.regionmanipulator/-region/remove.html

**Comment by Kordyjan** [comment]
I think it is no longer relevant when we have the new html format.
