### ISSUE TITLE
Could not get unknown property 'org' for project ':library' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by yizems** [Kotlin/dokka#479]
I want create single file,but have any problem

```gradle
apply plugin: 'org.jetbrains.dokka-android'
apply plugin: 'maven'

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "${MAVEN_UPLOAD_URL}") {
                authentication(userName: "${MAVEN_USER}", password: "${MAVEN_PWD}")
            }

            pom.groupId = "com.gwmfc.android"
            pom.artifactId = "klog"
            pom.version = "1.0.0"
            pom.packaging = "aar"
        }
    }
}


task generateSourcesJar(type: Jar) {
    group = 'jar'
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
    outputFormat = "javadoc"
    outputDirectory = javadoc.destinationDir
}

task generateJavadoc(type: Jar, dependsOn: dokkaJavadoc) {
    group = 'jar'
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives generateJavadoc
    archives generateSourcesJar
}

```
and
`apply from: 'upload.gradle'`

have error
Could not get unknown property 'org' for project ':library' of type org.gradle.api.Project.

What should I do?

When dokka is removed, it's ok

**Comment by Crazy-Ann** [comment]
I had the same problem.

**Comment by Crazy-Ann** [comment]
> I want create single file,but have any problem
> 
> ```groovy-gradle
> apply plugin: 'org.jetbrains.dokka-android'
> apply plugin: 'maven'
> 
> uploadArchives {
>     repositories {
>         mavenDeployer {
>             repository(url: "${MAVEN_UPLOAD_URL}") {
>                 authentication(userName: "${MAVEN_USER}", password: "${MAVEN_PWD}")
>             }
> 
>             pom.groupId = "com.gwmfc.android"
>             pom.artifactId = "klog"
>             pom.version = "1.0.0"
>             pom.packaging = "aar"
>         }
>     }
> }
> 
> 
> task generateSourcesJar(type: Jar) {
>     group = 'jar'
>     from android.sourceSets.main.java.srcDirs
>     classifier = 'sources'
> }
> 
> task javadoc(type: Javadoc) {
>     source = android.sourceSets.main.java.srcDirs
>     classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
> }
> 
> task dokkaJavadoc(type: org.jetbrains.dokka.gradle.DokkaTask) {
>     outputFormat = "javadoc"
>     outputDirectory = javadoc.destinationDir
> }
> 
> task generateJavadoc(type: Jar, dependsOn: dokkaJavadoc) {
>     group = 'jar'
>     classifier = 'javadoc'
>     from javadoc.destinationDir
> }
> 
> artifacts {
>     archives generateJavadoc
>     archives generateSourcesJar
> }
> ```
> 
> and
> `apply from: 'upload.gradle'`
> 
> have error
> Could not get unknown property 'org' for project ':library' of type org.gradle.api.Project.
> 
> What should I do?
> 
> When dokka is removed, it's ok

请问你是否解决了这个问题？

**Comment by kamilok1965** [comment]
Could you give us an example project please? I've tried your `build.gradle`, but couldn't reproduce the problem

**Comment by yizems** [comment]
@kamilok1965  I think there is something wrong with my writing. Thank you very much for your support.

I didn't reproduce that mistake, and there was another problem.

or give me an example.

sample: https://github.com/yizems/DokkaSample

**Comment by kamilok1965** [comment]
@yizems your build had some different problems, fixed it for you 
https://github.com/yizems/DokkaSample/pull/1

**Comment by yizems** [comment]
@kamilok1965 I'm misconfigured. Look at the problem now.

**Comment by yizems** [comment]
I updated the sample

**Comment by yizems** [comment]
Duplicate of #483

**Comment by o0starshine0o** [comment]
dokkaJavadoc() has a offical implement, so just remove this function, the issues will be resloved at the same time.
