### ISSUE TITLE
Missing line breaks on extension method overloads in gfm

### ISSUE THREAD

**Issue by swankjesse** [Kotlin/dokka#480]
Related to [#475](https://github.com/Kotlin/dokka/issues/475).

This code:

```
    /**
     * Returns a new response body that transmits this string. If [contentType] is non-null and
     * lacks a charset, this will use UTF-8.
     */
    fun String.toResponseBody(contentType: MediaType? = null): ResponseBody {
      TODO()
    }

    /** Returns a new response body that transmits this byte array. */
    fun ByteArray.toResponseBody(contentType: MediaType? = null): ResponseBody {
      TODO()
    }

    /** Returns a new response body that transmits this byte string. */
    fun ByteString.toResponseBody(contentType: MediaType? = null): ResponseBody {
      TODO()
    }
```

Yields this table:

```
| Name | Summary |
|---|---|
| [asResponseBody](as-response-body.md) | `fun `[`BufferedSource`](https://square.github.io/okio/2.x/okio/jvm/okio/-buffered-source/index.html)`.asResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null, contentLength: `[`Long`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html)` = -1L): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this source. |
| [toResponseBody](to-response-body.md) | `fun `[`String`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html)`.toResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this string. If [contentType](to-response-body.md#okhttp3.ResponseBody.Companion$toResponseBody(kotlin.String, okhttp3.MediaType)/contentType) is non-null and lacks a charset, this will use UTF-8.`fun `[`ByteArray`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte-array/index.html)`.toResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this byte array.`fun `[`ByteString`](https://square.github.io/okio/2.x/okio/jvm/okio/-byte-string/index.html)`.toResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this byte string. |
```

| Name | Summary |
|---|---|
| [asResponseBody](as-response-body.md) | `fun `[`BufferedSource`](https://square.github.io/okio/2.x/okio/jvm/okio/-buffered-source/index.html)`.asResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null, contentLength: `[`Long`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html)` = -1L): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this source. |
| [toResponseBody](to-response-body.md) | `fun `[`String`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html)`.toResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this string. If [contentType](to-response-body.md#okhttp3.ResponseBody.Companion$toResponseBody(kotlin.String, okhttp3.MediaType)/contentType) is non-null and lacks a charset, this will use UTF-8.`fun `[`ByteArray`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte-array/index.html)`.toResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this byte array.`fun `[`ByteString`](https://square.github.io/okio/2.x/okio/jvm/okio/-byte-string/index.html)`.toResponseBody(contentType: `[`MediaType`](../-media-type/index.md)`? = null): `[`ResponseBody`](./index.md)<br>Returns a new response body that transmits this byte string. |

Note that it needs a `<br>` between function declarations.

**Comment by Kordyjan** [comment]
I think it is no longer relevant after a complete rewrite of gmf renderer.
