### ISSUE TITLE
Generating from command line, enable private functions

### ISSUE THREAD

**Issue by RazorneckCodes** [Kotlin/dokka#481]
Hi,
I want to generate my doc with dokka from cmd line. I would like to include private functions from my code in the doc. I use the following command:
`java -jar dokka-fatjar.jar ../src/ -format html -packageOptions +privateApi`

But it says:
`ERROR: error: source file or directory not found: -packageOptions
ERROR: error: source file or directory not found: +privateApi`

Does anyone know how to enable private functions? Thanks for the help

**Comment by RodrigoAmaroEng** [comment]
Same problem here

**Comment by kamilok1965** [comment]
I think it is `-includeNonPublic`, could you please check if it works?

**Comment by RazorneckCodes** [comment]
> I think it is `-includeNonPublic`, could you please check if it works?

No still the same error. I think the option `-includeNonPublic` is recognized as a source file. It should be listed as a Module. I tried different options but it still doesn't work.

`java -jar dokka-fatjar.jar ../src/ -format html -includeNonPublic
Module:
Output: out\doc
Sources: ../src/, -includeNonPublic
Classpath: C:\Program Files\Java\jre1.8.0_211\lib\charsets.jar, C:\Program Files\Java\jre1.8.0_211\lib\deploy.jar, C:\Program Files\Java\jre1.8.0_211\lib\javaws.jar, C:\Program Files\Java\jre1.8.0_211\lib\jce.jar, C:\Program Files\Java\jre1.8.0_211\lib\jfr.jar, C:\Program Files\Java\jre1.8.0_211\lib\jfxswt.jar, C:\Program Files\Java\jre1.8.0_211\lib\jsse.jar, C:\Program Files\Java\jre1.8.0_211\lib\management-agent.jar, C:\Program Files\Java\jre1.8.0_211\lib\plugin.jar, C:\Program Files\Java\jre1.8.0_211\lib\resources.jar, C:\Program Files\Java\jre1.8.0_211\lib\rt.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\access-bridge-64.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\cldrdata.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\dnsns.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\jaccess.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\jfxrt.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\localedata.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\nashorn.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\sunec.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\sunjce_provider.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\sunmscapi.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\sunpkcs11.jar, C:\Program Files\Java\jre1.8.0_211\lib\ext\zipfs.jar,
Analysing sources and libraries...
ERROR: error: source file or directory not found: -includeNonPublic
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.`

**Comment by kamilok1965** [comment]
Yup, because it's a per package option. So you should add it like: `-packageOptions +includeNonPublic`

**Comment by RazorneckCodes** [comment]
I tried `java -jar dokka-fatjar.jar ../src/ -packageOptions +includeNonPublic` but it still won't work.

**Comment by kamilok1965** [comment]
I've checked that and it probably is a bug in 0.9.18. This is fixed in 0.9.19 on branch `multiplatform-support`. You can build it yourself or wait for official release, which should happen soon
