### ISSUE TITLE
Implementation or Extends class are not shown

### ISSUE THREAD

**Issue by rona-tombo** [Kotlin/dokka#482]
![image](https://user-images.githubusercontent.com/41550858/60099584-ec7ac900-9792-11e9-9f83-318247726619.png)
the picture's class is extends JavaPlugin and implemantation RonaChat
![image](https://user-images.githubusercontent.com/41550858/60099661-1338ff80-9793-11e9-8b10-5938eddfdf79.png)
but it not shown.

**Comment by kamilok1965** [comment]
Hi @rona-tombo, is this still relevant? I can't reproduce it
