### ISSUE TITLE
Custom block types

### ISSUE THREAD

**Issue by JanMalch** [Kotlin/dokka#487]
Is it possible to have custom output for custom block tags? How would you do this with dokka?

For example via plugins and hooking into existing generators.

**Comment by kamilok1965** [comment]
Hi @JanMalch, could you elaborate on that (preferably show an example)?

**Comment by JanMalch** [comment]
I would like to define my own block tags like the `@say` in the following code:

```kotlin
/**
 * Does something.
 * @say Hello World
 */
fun foo() {}
```

So I can later write a plugin / generator which reads this custom tag and has custom output.

```
Starting MyCustomDokkaGenerator ...
Function 'foo' says 'Hello World'
```

Hope that helps.

**Comment by kamilok1965** [comment]
Yup, I get it now. It is planned for the next release (0.10.1)

**Comment by Kordyjan** [comment]
Plugin api is ready to be used, so I consider this issue to be closed. 
More info about plugins: https://github.com/Kotlin/dokka/blob/master/plugins/developer_guide.md
