### ISSUE TITLE
Reporting values of cont vals.

### ISSUE THREAD

**Issue by eGorets** [Kotlin/dokka#488]
I suppose I have to use `@value ` annotation to add 
`const val KEY = "key" ` to see it in the doc

**Comment by Kordyjan** [comment]
I think this issue is about deciding how const vals should be reported by dokka.

**Comment by aburmeis** [comment]
The problem is not completely solved. Default values are now visible in the generated documentation but real constants not:

```kotlin
/**
 * You can see this, but not the value here: [FOO].
 */
class Test {
  companion object {
    const val FOO = "bar"
  }
}
```
