### ISSUE TITLE
Javadoc format generates inconsistent Anchor tags

### ISSUE THREAD

**Issue by jhansche** [Kotlin/dokka#489]
When `outputFormat = 'javadoc'`, and given a class such as:

```java
package com.example.library;

public class BaseObject {
    /** The docs... */
    public void doStuff(AnotherClass arg) {}
}
```

Dokka generates the `BaseObject.html` with an anchor tag of:

```html
    <a name="doStuff-arg-"><!--   --></a>
```

However, when attaching the `*-javadoc.jar` file to a no-source library artifact in an IDE (in this case, Android Studio / IntelliJ IDEA), and trying to view documentation for the `BaseObject.doStuff()` method, the documentation popup _does not_ show any of the generated documentation for that method, and instead shows this (which doesn't explicitly look like an error, but it seems to me like it's a fallback when it can't find what it's looking for):

```
The following documentation urls were checked:
http://localhost:63342/SomeKindOfGeneratedHash/AppProject/closed-source-library-SNAPSHOT-javadoc.jar/com/example/library/BaseObject.html#doStuff-com.example.library.AnotherClass- 
http://localhost:63342/SomeKindOfGeneratedHash/AppProject/closed-source-library-SNAPSHOT-javadoc.jar/com/example/library/BaseObject.html#doStuff(com.example.library.AnotherClass)
Edit API docs paths
```

This link that the IDE is looking for does not match the generated HTML fromDokka.  Dokka is generating an anchor fragment consisting of `$methodName-$argNAME-`, while the IDE is looking for `$methodName-$argTYPE-`.

To be consistent with Javadoc, I believe the `<a name/>` anchor should be generated with the argument _type_ rather than the argument name.

**Comment by Kordyjan** [comment]
This issue was about an old javadoc renderer. The new renderer which is the default one since 1.4.0-rc shouldn't have such issues.

**Comment by nenko-tabakov** [comment]
I have the exact same issue.I used https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-library-publishing-example as a template and added another method with a single argument: 
```
class Greeter(val name: String) {

   ...

    /**
     * Prints the greeting to a Person to the standard output.
     */
    fun greet(p: Person) {
        println("Hello ${p.name}")
    }
}

class Person (val name: String) {
}
```

however, the created javadoc jar still didn't use the FQN in the anchors thus resulting in IntelliJ not able to pick up the documentation and showing the errors above.

Is there a configuration or a workaround to make the generated javadoc in a format that IntelliJ understand?

Thanks

**Comment by jhansche** [comment]
@Kordyjan given comment from @nenko-tabakov above, should this be reopened? It sounds like the new renderer didn't resolve it. I don't have access to reopen.

**Comment by nenko-tabakov** [comment]
Hey @jhansche, do you still experience the same issue? I tried with few different configuration options and generating the doc from the CLI but I couldn't make the output use the FQN for the arguments.

@Kordyjan Any tips how to make that works? Is it a configuration that needs to be enabled?

**Comment by jhansche** [comment]
@nenko-tabakov we gave up on Dokka entirely back in 2019, because it was too buggy for our needs (this was just one of a dozen issues).

We haven't tried going back to it after the rewrites that @Kordyjan mentioned, so I don't know if this issue was resolved or not.
