### ISSUE TITLE
Dokka for outputFormat Markdown generates an exception

### ISSUE THREAD

**Issue by apatrida** [Kotlin/dokka#49]
```
Execution failed for task ':klutter-aws-core-jdk6:dokka'.
> Unable to create injector, see the following errors:

  1) org.jetbrains.dokka.MarkdownFormatService has more than one constructor annotated with @Inject. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
    at org.jetbrains.dokka.MarkdownFormatService.class(MarkdownFormatService.kt:7)
    at org.jetbrains.dokka.Utilities.DokkaModule.configure(DokkaModule.kt:43)

  1 error
```

**Comment by porokoro** [comment]
Same issue for outputFormat Jekyll (dokka-gradle-plugin 0.9.6):

```
> Unable to create injector, see the following errors:

  1) org.jetbrains.dokka.JekyllFormatService has more than one constructor annotated with @Inject. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
    at org.jetbrains.dokka.JekyllFormatService.class(JekyllFormatService.kt:6)
    at org.jetbrains.dokka.Utilities.DokkaModule.configure(DokkaModule.kt:43)

  1 error
```

**Comment by kosiara** [comment]
Markdown doesn't generate for me as well....

`dokka {
    outputFormat = 'markdown' 
    outputDirectory = "$buildDir/kotlindocs"
}`


gradle plugin, dokka version 0.9.7

Error:Execution failed for task ':app:dokka'.
> Unable to create injector, see the following errors:
  1) org.jetbrains.dokka.MarkdownFormatService has more than one constructor annotated with @Inject. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
    at org.jetbrains.dokka.MarkdownFormatService.class(MarkdownFormatService.kt:7)
    at org.jetbrains.dokka.Utilities.DokkaModule.configure(DokkaModule.kt:43)
  1 error
