### ISSUE TITLE
Multiplatform branch cannot extract KotlinCompilation from kotlin-android projects

### ISSUE THREAD

**Issue by jhansche** [Kotlin/dokka#491]
`org.jetbrains.dokka.gradle.ConfigurationExtractor.getMainCompilation(KotlinTarget)` only works if there is a `target.compilations.getByName("main")`.  On Android projects, there is no `"main"` compilation (typically just `"debug", "release"`, and a few others for tests).

The first problem is that `getByName(String)` throws an exception if the named element cannot be found. Since Android does not create a `"main"` compilation, this was causing the build to fail. To work around that exception, I first changed this to `findByName("main")`, and that resolved the exception.  However, even after this, the generated documentation was empty, because it was not able to locate any sources or classpath.

I tried adding `kotlinTasks { ["compileReleaseKotlin"] }`, based on what I found in the testData examples, but that did not change anything and it would still produce empty documentation. I wasn't able to find out how to run the integration tests to check whether it was expected to work or not.

What finally ended up working for me, was one of these changes:
```kotlin
target?.compilations?.findByName("main") ?: target?.compilations?.first()
```
```kotlin
listOf("main", "release", "debug").mapNotNull {
    target?.compilations?.findByName(it)
}.first()
```

Now it's able to locate the `"release"` compilation, finds the sources and classpath, and the documentation is generated successfully.

It might make sense to run this only for release variants, in which case it would be nice if the dokka-android plugin would create the tasks only for release variants, or at least generate separate DokkaAndroidTask for separate variants that will utilize the matching KotlinCompilation. But as I'm not familiar with the roadmap for where you intend to take this, I don't really know the best way to address this in order to create a PR.

**Comment by kamilok1965** [comment]
Fixed in https://github.com/Kotlin/dokka/commit/da9d43e0b3293b36a3a6fd2986b0e6bc2e9b915d
Thank you for reporting
