### ISSUE TITLE
@suppress not honored in java files (Android)

### ISSUE THREAD

**Issue by carloswabreu1** [Kotlin/dokka#492]
I'm working on a mixed-language Java/Kotlin Android project and I was weighing migrating our documentation to dokka from doclava. In doclava, we have several classes/methods using the `@hide` notation to avoid showing them in the documentation and I was happy to see an equivalent `@suppress` notation in dokka. 

However, although `@suppress` works as expected in kotlin files, it doesn't in java files. Both classes and methods continue to be present in the output, regardless of its type (I've tried html and gfm), although being annotated with `@suppress`. If necessary, I can submit a project showing so.

I'm using dokka-android-gradle-plugin, version 0.9.18.

Thanks!

**Comment by kamilok1965** [comment]
Please do submit an example project if you can, it will save us some time

**Comment by carloswabreu1** [comment]
[Here](https://github.com/carloswabreu1/DokkaTest) it is. I created a new project using an Android Sample and just configured it to use Dokka. There are two classes in it:

- MainActivity.kt: this is the kotlin class. If you run Dokka you'll see that `@suppress` is working correctly here, hiding the method `onCreate` from the documentation
- JavaTest.java: this is the java class. If you run Dokka you'll see that both methods `method1` and `method2` appear in the documentation although `method2` is annotated with `@suppress`

**Comment by carloswabreu1** [comment]
Is there any workaround we can use?

**Comment by kamilok1965** [comment]
I've checked that and it's not supported, because javadoc does not support a suppress tag. See here: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#CHDJGIJB
and here: https://www.oracle.com/technetwork/java/javase/documentation/proposed-tags-142378.html - proposed tag `@exclude` for it, but not supported yet

**Comment by kamilok1965** [comment]
I think I need to discuss this issue, right now I'll mark it as an enhancement

**Comment by carloswabreu1** [comment]
Understood. Hope you include this capability in the near future. Not having a `@suppress` tag is a deal-breaker for libraries which have to be documented for third-party access

**Comment by carloswabreu1** [comment]
Is there any workaround to this situation?

**Comment by fAntel** [comment]
@carloswabreu1 For dokka 1.4.30 you can try to add android documentation plugin
```
dependencies {
    dokkaHtmlPlugin("org.jetbrains.dokka:android-documentation-plugin:$versions.dokka")
}
```
It'll add support for `@hide` in javadoc comments for java files.

Another solution is new `matchingRegex`. For example, you have this structure of files:
```
a
|_ A.java
|_ AImpl.kt
|_ b
   |_ B.java
   |_ c
      |_ C.java
      |_ CImpl.kt
      |_ CConstants.kt
```
And you want to exclude all in a.b but not all the files in a.b.c. I've configured it with a negative look ahead. In gradle file for dokka 1.4.30 it looks like this:
```
perPackageOption {
    matchingRegex.set("a\\.b(?!\\.c).*")
    suppress.set(true)
}
```
But my attempts to exclude only several files (for example, to exclude all in a.b and in a.b.c except C.java and CConstants.kt) was unsuccessful.

**Comment by carloswabreu1** [comment]
@fAntel just tried the plugin and it seems to be working as intended. Thanks for this!

**Comment by macharya** [comment]
I tried @hide @hidden still cant hide a java class or public method
