### ISSUE TITLE
Custom styles.css for HTML format

### ISSUE THREAD

**Issue by dlazarus** [Kotlin/dokka#493]
I need a custom styles.css in HTML docs. For now, the only way I see is to rewrite styles.css before deployment. Is there a better way?

IMHO, the best solution would be to have an option like css="path_to_custom_template_file".

**Comment by kamilok1965** [comment]
Currently there is no better way to my knowledge. This is planned for 0.9.20 release

**Comment by kamildoleglo** [comment]
Implemented in `1.4.10.2`
