### ISSUE TITLE
[Question] How to use the Dokka API programmatically?

### ISSUE THREAD

**Issue by drochetti** [Kotlin/dokka#494]
Is there a way to use Dokka API programmatically? My goal is to inspect the `DocumentationNode` before they are actually turned into HTML/Markdown documentation. Ideally I don't even want to generate the HTML files, I just need access to the nodes with their type info and documentation content.

I could not find a way of using the Dokka service classes programmatically from my project. Are they available?

**Comment by kamilok1965** [comment]
I don't know what you want to accompilsh but I think inspection of the `DocumentationNodes` is easiest to do somewhere in the `DocumentationBuilder` class. As for now there is no easy way (none that I'm aware of at least) to do that

**Comment by Kordyjan** [comment]
I know it is an older question but if it shows up in someone's search results in the future, it is worth mentioning it here.
Dokka was completely reimplemented from scratch before version 1.4.0-rc. Right now we have stable and ritch api. You can read more about it here: https://github.com/Kotlin/dokka/blob/master/plugins/developer_guide.md#dokka-data-model
