### ISSUE TITLE
Running dokka offline

### ISSUE THREAD

**Issue by binaykumarrana** [Kotlin/dokka#500]
Hi,
Is there any way I can run this in offline to generate the document? Someone, plz assist on this it's important.

Thanks
Binay

**Comment by kamilok1965** [comment]
That kind of depends on how you want to use it but basically you need to download the dokka-fatjar and run it locally with `noStdlibLink` and `noJdkLink`

**Comment by kamilok1965** [comment]
Hi @binaykumarrana, did you resolve your problem?

**Comment by binaykumarrana** [comment]
Hi, not yet done. I will do it soon.
