### ISSUE TITLE
Feature request: Display deprecation messages in the documentation

### ISSUE THREAD

**Issue by curioustechizen** [Kotlin/dokka#501]
In [this example](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/combine-latest.html), the docs display that a function has been deprecated and that deprecation level is `ERROR`. It would be helpful if the docs also displayed the deprecation message i.e., the value of the `message` parameter of the `@Deprecated` annotation.

This would save us from having to click on `(source)` to see the suggested alternative.

**Comment by vmishenev** [comment]
#2622 is in [v1.7.20](https://github.com/Kotlin/dokka/releases/tag/v1.7.20)
