### ISSUE TITLE
Does dokka have an impact on production Android app size?

### ISSUE THREAD

**Issue by AdamSHurwitz** [Kotlin/dokka#505]
Because dokka is added to a Kotlin IntelliJ project as an additional library, does this have an impact on the compiled production app size? If so, by how much?

Please correct me if mistaken, however it seems that an IntelliJ plugin such as [BugKotlinDocument](https://plugins.jetbrains.com/plugin/9781-bugkotlindocument) provides the same funtionality without adding to the app size.

Thanks!

**Comment by kamilok1965** [comment]
That depends on how you compile the production app. You can package your app with dokka but I don't see a good use case for that. 

If I recall correctly, the BugKotlinDocument plugin only generates KDoc comments, while dokka generates a standalone documentation out of those (eg. in `html` or `markdown` format)

**Comment by AdamSHurwitz** [comment]
Thank you for the clarification @kamilok1965! 

**Is there a sample available that compiles dokka's libraries in the 'debug' only variant?** The [dokka-gradle-example](https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka-gradle-example) doesn't show the dokka library compiled in the `debug` variant.

**Comment by kamilok1965** [comment]
I don't really get what you want to do. Do you want to generate the documentation (eg. in javadoc format) and then package it with the release files of the `debug` variant or do you want to generate documentation from the `debug` variant source code?

**Comment by AdamSHurwitz** [comment]
The goal is to ensure the dokka libraries are not included in the production `buildType`. As it appears from the current implementation in the documentation and sample code the dokka library is built with all variants of the app.

**Comment by kamilok1965** [comment]
Don't be afraid, dokka is not included in any of the buildTypes. Dokka is a Gradle plugin, not a dependency to your project ;)

**Comment by AdamSHurwitz** [comment]
I see. Thanks for your patience in explaining!

**Comment by kamilok1965** [comment]
No problem, here to help
