### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by mathjeff** [Kotlin/dokka#508]
It would be nice if there were a super easy way to cause Dokka to run in an offline mode where it doesn't download from the internet (to improve build reproducibility).

I previously mistakenly assumed that if a package-list is passed to Dokka then Dokka would skip loading the corresponding package-list from the internet.

I've now noticed that there are individual flags in Dokka for disabling downloading from certain specific websites: noJdkLink, noStdlibLink, noAndroidSdkLink  . Could we have one flag (for example, "offline") that sets all of these flags so that if new websites are added in a future version of Dokka, the build will fail when updating to the new version of Dokka rather than causing Dokka to download from the new website?

(Also observe https://github.com/Kotlin/dokka/issues/500 and https://github.com/Kotlin/dokka/issues/470 where other developers were surprised that Dokka failed with no network. Perhaps a parameter named "offline" would also be easier for us to recognize?)

Thanks!

**Comment by kamilok1965** [comment]
Yup, we could do that, thanks for the feedback!

**Comment by sellmair** [comment]
@kamildoleglo What is the current status on that one?

**Comment by kamildoleglo** [comment]
Done, needs some more testing
