### ISSUE TITLE
Dokka 0.10.0 creates links to packages with no public declarations

### ISSUE THREAD

**Issue by serebit** [Kotlin/dokka#510]
**Describe the bug**
When using Dokka 0.10.0, the plugin's generated root index.html will contain links to packages that have no public declarations, and those packages will also have pages in the root folder of the built docs, albeit empty ones.

**Expected behaviour**
In Dokka 0.9.18, these "internal" packages would be ignored completely.

**Screenshots**
[0.10.0](https://user-images.githubusercontent.com/12981608/66341833-02616380-e916-11e9-82aa-b98ae414b146.png)
[0.9.18](https://user-images.githubusercontent.com/12981608/66341750-eb227600-e915-11e9-8d10-aedac6aa2e55.png)

**To Reproduce**
Run `./gradlew dokka` on this project and check the results.
[dokka-bug-example.zip](https://github.com/Kotlin/dokka/files/3699092/dokka-bug-example.zip)

**Dokka configuration**
No special configuration required, this happens even with the default configuration.

**Installation**
- Operating system: Linux, kernel 5.3.1
- Build tool: Gradle 5.6.2 on OpenJDK 11
- Dokka version: 0.10.0

**Comment by kamilok1965** [comment]
Thanks for the feedback! As a workaround, you can suppress this package in dokka configuration

**Comment by kamilok1965** [comment]
Fixed in e560fe3
