### ISSUE TITLE
Include metadata

### ISSUE THREAD

**Issue by aljacinto** [Kotlin/dokka#517]
**Question**
Is there a way I can include metadata for the generated markdown?  I would like to include data or link for example that I can provide in gradle script.

Example below is from mkdocs-material

```
title: Lorem ipsum dolor sit amet
description: Nullam urna elit, malesuada eget finibus ut, ac tortor.
path: path/to/file
source: file.js

# Headline

...
```

**Comment by kamilok1965** [comment]
None that I'm aware of right now, you can add it manually or write a script for that. You can also edit  the `StructuredFormatService` or maybe even the `FileGenerator` itself, however this change will be much easier after the next release, which will introduce pluggability.
