### ISSUE TITLE
Source links are not created for functions in commonMain

### ISSUE THREAD

**Issue by ingonoka** [Kotlin/dokka#519]
**Describe the bug**
I have a multi-platform project with sources in src/androidMain/kotlin, src/commonMain/kotlin and src/jvmMain/kotlin. The documentation is generated correctly, but there are no source links for classes or functions in `commonMain`.  For functions or classes that are JVM or Android specific and only appear in androidMain or jvmMain, source links are created and point to the right place on Github.

**Expected behaviour**
I am expecting source links to be created for all functions, but only classes that are unique to android or JVM have a link.  There are no source links for any function in commonMain.

**Dokka configuration**
```Kotlin
tasks {
    val dokka by getting(DokkaTask::class) {
        outputFormat = "html"
        multiplatform {
            val global by creating {
                reportUndocumented = true
                includes =
                    listOf("src/commonMain/kotlin/com/ingonoka/qcat/module.md")
            }

            val common by creating {
                targets = listOf("Common")
                platform = "common"

                sourceLink {
                    path = "src/commonMain/kotlin"
                    url = "https://github.com/ingonoka/QCAT-LIB-MP/blob/master/qcatlib/src/commonMain/kotlin"
                    lineSuffix = "#L"
                }

            }

            val jvm by creating {
                targets = listOf("Jvm")
                platform = "jvm"

                sourceLink {
                    path = "src/jvmMain/kotlin"
                    url = "https://github.com/ingonoka/QCAT-LIB-MP/blob/master/qcatlib/src/jvmMain/kotlin"
                    lineSuffix = "#L"
                }

            }

            val android by creating {
                targets = listOf("Android")
                platform = "android"

                sourceLink {
                    path = "src/androidMain/kotlin"
                    url = "https://github.com/ingonoka/QCAT-LIB-MP/blob/master/qcatlib/src/androidMain/kotlin"
                    lineSuffix = "#L"
                }
            }

        }

    }
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.6.2
- Dokka version: 0.10.0
- Kotlin: 1.3.50

**Additional context**
The same project uses "kotlinx-serialization", "com.jfrog.artifactory" and sqdelight.

**Comment by rnett** [comment]
I'm seeing this in the new dokka as well.  See https://github.com/rnett/krosstalk

**Comment by rnett** [comment]
Or not, I just didn't have source links configured correctly.

**Comment by IgnatBeresnev** [comment]
This should work with modern versions of Dokka such as 1.7.0+

For instance, see https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html

Closing the issue as resolved/fixed, but do let us know if you encounter any problems related to this.
