### ISSUE TITLE
Generated doc structure inconsistent when class has the same name like the package - Can't be referenced as external

### ISSUE THREAD

**Issue by liedQM** [Kotlin/dokka#522]
**Describtion**
We have a sealed class, that has the same name like the sub package and the Kt file. This leads to an inconsistent doc structure, which leads to not invalid references when this doc is referenced as external documentation from another framework.
The sealed class generates a `-class.html` where as its subclasses become a `-class/index.html` structure.
The reference of the other frameworks also expects a `-class/index.html`, which does not exist.

**Expected behaviour**
The structure should be consistent, so that when the docs are referenced as external documentation the links will work.

**Screenshots**
Inconsistent data structure:
 ![Screenshot 2019-11-06 at 09 56 24](https://user-images.githubusercontent.com/33150549/68283445-d869a100-007b-11ea-8c87-ea6e0afe3398.png)

Invalid reference from another framework:
![Screenshot 2019-11-06 at 09 59 09](https://user-images.githubusercontent.com/33150549/68283624-27173b00-007c-11ea-8ae3-5e55de1a428d.png)

**To Reproduce**
file name: `Result.kt`
```kotlin
package result

sealed class Result<ResultType, ErrorType>

data class Success<ResultType, ErrorType>(val result: ResultType) : Result<ResultType, ErrorType>()

data class Failure<ResultType, ErrorType>(val error: ErrorType) : Result<ResultType, ErrorType>()
```

**Dokka configuration**
```groovy
dokka {
    outputFormat = 'html' 
    outputDirectory = "$buildDir/javadoc"

    skipEmptyPackages = true // Do not create index pages
    skipDeprecated = false
    reportUndocumented = true // Emit warnings about not documented members 
    includeNonPublic = false
 
    impliedPlatforms = ["JVM"] // See platforms section of documentation

    jdkVersion = 8 // Used for linking to JDK

     // No default documentation link to kotlin-stdlib
    noStdlibLink = false

    // Disable linking to online JDK documentation
    noJdkLink = false
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.6.3
- Dokka version: 0.9.18

**Comment by Kordyjan** [comment]
This issue is about old dokka. Since it has been reimplemented from the scratch there is a chance that it was fixed. Nevertheless I think we shuld check that exact case.

**Comment by IgnatBeresnev** [comment]
Indeed, this has since then been fixed, just checked. In case I missed something and it's still relevant, do let me know.
![2022-04-27_19-12-58](https://user-images.githubusercontent.com/22685910/165563702-819fc54c-b1bd-4f4c-a134-3bc1d7f4dff5.png)
