### ISSUE TITLE
java.lang.ClassCastException: org.gradle.api.internal.file.CompositeFileTree$3 cannot be cast to org.jetbrains.dokka.DokkaConfiguration$SourceRoot on Android project

### ISSUE THREAD

**Issue by ryansgot** [Kotlin/dokka#523]
**Describe the bug**
Class cast exception when running dokka task on android library project

**Expected behaviour**
I expect variant-aware documentation to be generated for my android library

**Screenshots**
N/A

**To Reproduce**
1. Create an android library project (using gradle 5.4.1, kotlin dsl)
2. `./gradlew :libraryproject:dokka`
3. see exception

**Dokka configuration**
```kotlin
tasks {
    val dokka by getting(DokkaTask::class) {
        outputFormat = "javadoc"
    }
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.4.1
- Dokka version: 0.10.0

**Additional context**
Was able to generate documentation for non-android submodule (a sibling of the android module) just fine.

Note that the caused by line in the stacktrace is below:
```
Caused by: java.lang.ClassCastException: org.gradle.api.internal.file.CompositeFileTree$3 cannot be cast to org.jetbrains.dokka.DokkaConfiguration$SourceRoot
        at org.jetbrains.dokka.gradle.DokkaTask.getInputFiles(DokkaTask.kt:489)
```
However, I do not see a line 489 when I access [DokkaTask.kt](https://github.com/Kotlin/dokka/blob/tmp--release--0.10.0/runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTask.kt). So I can't get insight into what may have gone wrong.

**Comment by kamilok1965** [comment]
That's very strange. I can't reproduce it, could you please send me your project or a MRE?

**Comment by illuzor** [comment]
@kamilok1965 
![dokka bug](https://user-images.githubusercontent.com/1530314/69529523-7d8fdf00-0f81-11ea-9157-36b3801c7743.png)
[DokkaBugTest.zip](https://github.com/Kotlin/dokka/files/3885919/DokkaBugTest.zip)

**Comment by kamilok1965** [comment]
Thanks @illuzor! 
Yeah, I see it. That's because the configuration has changed and `sourceRoots` is not a list of Files anymore, it is now a list of `SourceRoot`s. 
So right now to set it, you should either pass a list of `SourceRoot`s (`GradleSourceRootImpl` should be visible) or use 
```kotlin
sourceRoot { 
  path = "foo/bar.java"
}  
sourceRoot { 
  path = "baz.java"
}  
``` 
these closures

**Comment by illuzor** [comment]
@kamilok1965 thank you for the answer. I`ll try

**Comment by masteramyx** [comment]
@kamilok1965 So is there no way to short form a list of `SourceRoot`? In my project I have a a good amount of submodules so im doing 

```
sourceRoot{path = "a/src/main/java"}
sourceRoot{path = "b/src/main/java"}
sourceRoot{path = "c/src/main/java"}
sourceRoot{path = "d/src/main/java"}
.
.
.
```

However as we add more modules this will become more tedious.

Previously I tried `souceRoots = [files("src/main/java"]` or something along those lines but obviously as you said above we are looking for list of `SourceRoot` and not `File`. 

Could we maybe add one in next release if not possible?

Thanks

**Comment by baruchn** [comment]
You really should update the documentation accordingly. 
It took me a lot of time to get to this thread.

**Comment by kamilok1965** [comment]
Oh, I omitted the documentation for that, that's true. 
Yes, I think we should change that and allow a `List`

**Comment by kamilok1965** [comment]
Readme updated for now

**Comment by kamildoleglo** [comment]
SourceRoots are now a `fileCollection`
