### ISSUE TITLE
Plans for pluggability support

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#524]
Dokka is in need of internal refactoring to support plugins in some reasonable way. Better modularity is required in order to properly implement some enhancements, like: 

- Custom stylesheets for formats
- Custom stylesheet location ? https://github.com/Kotlin/dokka/issues/163
- Package-info.java support
- Grouping methods/classes
- Javadoc linking to Kotlin
- Different structure for every format
- Copy docs from other objects https://github.com/Kotlin/dokka/issues/202 ?
- Document all packages / objects
- Filtering generated docs using annotations
- Using markdown for Javadoc
- Possibility to document XML Attributes
- Documenting internal/private/... members
- Show members visibility at the summary page
- Syntax highlighting in markdown
- Suppress useless (companion, componentN()) objects from javadoc (https://github.com/Kotlin/dokka/issues/200, https://github.com/Kotlin/dokka/issues/201)
- Custom output formats
- Custom nodes/classes
- User-definable API in runners, passed down to output formats
- Custom tags (like @say) in KDoc https://github.com/Kotlin/dokka/issues/487

Dokka should support plugins and plugin composition (if it's possible), which requires internal refactoring

**Comment by IgnatBeresnev** [comment]
I see that a lot of points from this list have been addressed and implemented. 

Closing this issue as mostly outdated now. If you believe some things from the list are missing and worth implementing, please create a feature request.
