### ISSUE TITLE
No line break between documentation and class/method/property signature

### ISSUE THREAD

**Issue by xit0c** [Kotlin/dokka#526]
**Describe the bug**
No line break between documentation and class/method/property signature.

**Expected behaviour**
Dokka should output a line break (a `<br>` could be enough?) between the description of a class/method/property and its signature.

**Screenshots**
* Class case: as you can see in the generated table, classes signatures are in the same line of their respective descriptions.
![image](https://user-images.githubusercontent.com/15820253/68936084-12345900-079a-11ea-8c18-19aed720d865.png)

* Method/Property case: the issue persist in constructors, properties and functions generated tables.
![image](https://user-images.githubusercontent.com/15820253/68936142-37c16280-079a-11ea-8d55-087be6740c63.png)

**To Reproduce**
Screenshots' project: https://github.com/xit0c/mapbox-plugin-offline

**Dokka configuration**
```groovy
dokka {
        outputFormat = 'gfm'
        outputDirectory = javadocDir
        configuration {
            sourceLink {
                path = "./"
                url = "https://github.com/xit0c/mapbox-plugin-offline/tree/master/mapboxpluginoffline/"
                lineSuffix = "#L" // suffix used to append the line number to the URL (#L for GitHub)
            }
            externalDocumentationLink {
                url = new URL("https://developer.android.com/reference/")
                packageListUrl = new URL("https://developer.android.com/reference/androidx/package-list")
            }
        }
    }
```

**Installation**
- Operating system: Linux Mint 19.2
- Build tool: Gradle v5.4.1
- Dokka version: 0.10.0

**Comment by xit0c** [comment]
Project's generated docs here: https://xit0c.github.io/mapbox-plugin-offline/

**Comment by i-walker** [comment]
I've created https://github.com/Kotlin/dokka/pull/613 to resolve it. Maybe there could be another `0.10.1` release like today.

**Comment by maggud** [comment]
I have the same problem. 

I'd also like to add that I'd expect the signature to be before the description, not after. It appears that this was the case in earlier versions (I just recently started using Dokka).

**Comment by Kordyjan** [comment]
Dokka renderers were reimplemented from scratch in 1.4.0-rc. This issue should no longer be relevant.
