### ISSUE TITLE
Private annotation visible in javadoc output format

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/dokka#528]
**Describe the bug**
A `private annotation class` appears in the "javadoc" output format despite being `private`.

**Expected behaviour**
`private` annotations are omitted

**Screenshots**
![Screen Shot 2019-11-18 at 11 08 47 PM](https://user-images.githubusercontent.com/66577/69115922-69675180-0a58-11ea-93a8-68765f68d514.png)

**To Reproduce**
```kotlin
@DslMarker
private annotation class PicnicDsl
```

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
def javadocJarTaskProvider = tasks.register('javadocJar', org.jetbrains.dokka.gradle.DokkaTask) { task ->
  task.outputFormat = 'javadoc'
  task.outputDirectory = "$buildDir/javadoc"
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.0
- Dokka version: 0.10.0

**Comment by kamildoleglo** [comment]
Fix confirmed on `1.4.30`
