### ISSUE TITLE
-Werror for dokka gradle task

### ISSUE THREAD

**Issue by mikesamuel** [Kotlin/dokka#529]
I'd like to be able to write pre-commit checks that fail if I try to `git commit` with broken markdown in kdoc.

For example, if I write some kdoc like

```kotlin
  /**
   * (before, after) pairs that capture relationships like
   * x.length must be checked before x[0] can be read.
   */
```

The markdown converter doesn't known that `[0]` is not a link; I should've formatted `x[0]` as code.  The logs from the gradle dokka plugin contain a hint at the very end:

> \> gradle dokka
>
> \> Configure project :
> Kotlin Multiplatform Projects are an experimental feature.
>
> \> Task :dokka
> warning: duplicate source root: /fake/path/to/myproject/src/commonMain/kotlin
> warning: duplicate source root: /fake/path/to/myproject/src/commonMain/kotlin
> logging: loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt]
> **Unresolved link to 0 in doc comment of myproject.MyFile (MyFile.kt:1)**

The bolded line is the relevant one.  It contains no "warning" or "error" prefix that my pre-commit hooks can easily parse for though,and I'd rather not parse if an exit code can convey the same info.

## Possible solution: -Werror configuration option

It'd suffice if I could configure dokka in gradle so that if there are warnings like this, I can make `gradle dokka` fail.

Then I would add a dependency from my *check* task on the *dokka* task, and have `.git/hooks/pre-commit` run `gradle clean check` so that I know to fix subtle documentation formatting bugs when I have the code change in mind.

## Alternative

Alternatively, the dokka plugin could define a task like *dokkaCheckKdoc* that errors out on markdown formatting problems and broken links.

Ideally, I wouldn't have to do anything in my build.gradle{.kts,} to get the configuration for `gradle dokka` to carry over to `gradle dokkaCheckKdoc`.

**Comment by kamildoleglo** [comment]
Implemented as `failOnWarning`
