### ISSUE TITLE
Why make API private starting from 0.10.0?

### ISSUE THREAD

**Issue by Den-Rimus** [Kotlin/dokka#534]
**Is your feature request related to a problem? Please describe**
Plugin users left out with no ability to customise documentation by subclassing `DokkaPlugin` and/or `DokkaTask` classes - all their essential methods were made private starting from 0.10.0 version. Why?

We had perfectly working 'document whitelisted classes only' approach before set up in our project, with modified logic of `collectSuppressedFiles` method in `DokkaTask`. Now it is private and we can't override a thing.

**Describe the solution you'd like**
Make key methods of plugin and task `protected open`

**Describe alternatives you've considered**
Stuck with using dokka 0.9.18 for kotlin classes only (there are some bugs in that version when applying dokka to mixed java&kotlin sourceSet - not an option) and separate javadoc task for java classes. Making the output contain two documentations, instead of all docs in one place.

**Comment by kamilok1965** [comment]
This is my mistake, I rewrote most of the Gradle runner to support multiplatform projects and forgot about that. Thanks for reporting!

**Comment by kamilok1965** [comment]
Fixed in 29a4cc77cb981265c3a420a47fd35e4f8da18a25
