### ISSUE TITLE
Using the classic javadoc layout

### ISSUE THREAD

**Issue by lcarnevale** [Kotlin/dokka#535]
Hello all,

I would like to turn the documentation layout into the classic javadoc one, as shown in the picture below. Is there any option for allowing this change?

**Screenshots**
![image](https://user-images.githubusercontent.com/8748737/70243114-459f4d80-1772-11ea-8f5c-33b2a252dfde.png)

Best regards,
Lorenzo.

**Comment by lcarnevale** [comment]
Hello all,

I have also tried out the configuration below, which raises an exception.
```
dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}
```
```
> Task :dokka FAILED
Cause: com/sun/tools/doclets/formats/html/HtmlDoclet
```

Best regards,
Lorenzo.

**Comment by kamildoleglo** [comment]
Hi, this is not possible and not planned for now.  You can write a dokka plugin which will provide this output format. 
The exception has been fixed in the new dokka
