### ISSUE TITLE
Line wrapping inside code blocks

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/dokka#54]
Code blocks are not treated like preformatted text, line breaks in source gets merged.
An example from `kotlin.jvm.Throws` annotation docs:

```
 * ```
 * throws(IOException::class)
 * fun readFile(name: String): String {...}
 * ```
```

gets rendered as 

Example:
`throws(IOException::class)fun readFile(name: String): String {...}`

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-throws/

**Comment by kosiara** [comment]
Should one use 
```
code block
```

or rather use the annotation @sample and somehow put the code from the samples directory....
and if so, how should we use @sample annotation? Is this documented?
