### ISSUE TITLE
Generate Docs off of debug build

### ISSUE THREAD

**Issue by masteramyx** [Kotlin/dokka#543]
I have a project that contains component libraries used in our other projects. We only build debug as we don't need a release build and it was just double compilation time. I ran into an issue where I kept getting an error regarding an empty list and the top stacktrace call referred to this method in the `ConfigurationExtractor` class. 

```
    private fun getMainCompilationName(target: KotlinTarget) = if (target.isAndroidTarget())
        getVariants(project).filter { it.buildType.name == BuilderConstants.RELEASE }.map { it.name }.first()
    else
        KotlinCompilation.MAIN_COMPILATION_NAME
```

So it looks like we're forced to generate docs off of the Release build? Is there anyway to disable this or to generate docs off Debug build?

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.4.1/Maven
- Dokka version: 0.10.0

**Comment by kamilok1965** [comment]
There is a way to do it, but it's only for Gradle (because it's only for Android), not tested and won't work with multiplatform in `0.10.0`. It will be fully functional in `0.10.1` (I hope):
There is a configuration option called `androidVariant` which takes a String with the variant name:

```groovy
dokka {
  configuration {
    androidVariant = "debug"
  }
}
```
