### ISSUE TITLE
<ERROR CLASS> in report for all android api classes

### ISSUE THREAD

**Issue by KhlopotovAI** [Kotlin/dokka#549]
**Screenshots**
![image](https://user-images.githubusercontent.com/38380226/71255889-49210000-2340-11ea-8fcf-93c9ba291bee.png)

**To Reproduce**
1) unzip [test.zip](https://github.com/Kotlin/dokka/files/3988353/test.zip)
2) ./gradlew dokka
3) open MainActivity class in report
Note: you need to specify android sdk.dir

**Dokka configuration**
default

**Installation**
- Operating system: macOS
- Build tool: Gradle 5.6.4
- Dokka version: 0.10.1-dev-28

Is not reproduced in dokka 0.10.0

**Comment by kamilok1965** [comment]
Fixed in 9e7154fef3394698dc52c52d61dd1aefde29251e, thanks!
