### ISSUE TITLE
Links to stdlib on kotlinlang don't work for dokka-maven-plugin

### ISSUE THREAD

**Issue by mshishkina** [Kotlin/dokka#551]
Worked for dokka-maven-plugin v.0.9.18
Does not work for dokka-maven-plugin v.0.10.1
**Description**
In generated documention the links that refer to stdlib (e.g. String, Unit) should lead to corresponding pages on kotlinlang.org, in 0.10.1 such links don't work.

**Steps:**
1. Unzip
[Dokka.zip](https://github.com/Kotlin/dokka/files/4000379/Dokka.zip)

2. Run compile, dokka:dokka
3. Open generated index.html.
Actual behavior:
String, Unit are not links.
Expected behavior:
Click on String, Unit should lead to koltinlang.org

**Comment by BryanSer** [comment]
Same issue.
noJdkLink and noStdlibLink is useless.

**Comment by mshishkina** [comment]
Fixed in 0.10.1-dev-31
