### ISSUE TITLE
dokka task for Gradle runs very long

### ISSUE THREAD

**Issue by ltennstedt** [Kotlin/dokka#552]
**Describe the bug**
The dokka task for Gradle runs very long and sometimes does not terminate in a reasonable time.

**Expected behaviour**
The dokka task for Gradle should terminate in a couple of minutes.

**To Reproduce**
- Clone https://github.com/ltennstedt/finnmath.git
- Run `gradle dokka`

**Dokka configuration**
```kotlin
dokka {
    configuration {
        jdkVersion = 11
        noJdkLink = true
        noStdlibLink = true
    }
}
```

**Installation**
- Operating system: Arch Linux
- Build tool: Gradle v6.0.1
- Dokka version: 0.10.0
- OpenJDK 64-Bit Server VM (11.0.5+10, mixed mode)

**Comment by ltennstedt** [comment]
The last run terminated after 42 minutes on my not so fast machine but it's too long for my taste.

**Comment by kamilok1965** [comment]
That's very strange, it should not take this much time

**Comment by ltennstedt** [comment]
Build tool: Gradle 6.1.1
Dokka version: 0.10.1
OS: Arch Linux

I verified this behaviour with OpenJDK 8 and 11 from the Arch repositories.

**Comment by ltennstedt** [comment]
I think that it has something to do with inheritance or abstract classes. After I refactored some generic code into abstract classes, the duration increased from about three minutes to forty-two on my machine.

Processor: 2 x AMD A4-3000 APU
Memory: 16 GB
No SSD

**Comment by ltennstedt** [comment]
It seems that the bug has been fixed in recent version.

**Installation**
- Operating system: Ubuntu 20.04.1 LTS
- Kotlin version: 1.4.10
- Build tool: Gradle 6.6.1
- Dokka version: 1.4.10
- Azul Zulu OpenJDK 11 LTS 64-Bit Server VM (11.0.8+10, mixed mode)

I will close the bug report.
