### ISSUE TITLE
dokka fatjar not able to load jar from given "-classpath" option

### ISSUE THREAD

**Issue by shubhamJay** [Kotlin/dokka#553]
I am trying to use Dokka fatjar to generate documentation from the command line. It is showing `<ERROR CLASS>` as a placeholder wherever it is not able to resolve the references. I am trying the  use `-pass -classpath` option to provide dependencies, but I don't see any of the modules getting loaded from the provided jar in logs (which says `logging: loading modules: [<some jdk modules>]`) nor I see my problem fixed. 

For eg. I was trying to load coroutines modules. For the same, I have a jar of coroutines downloaded on my local and I am executing following command in my project

`java -jar ~/Downloads/dokka-fatjar-0.10.0.jar -pass -src . -pass -classpath ~/Downloads/kotlinx-coroutines-core-1.3.2.jar -format html -output ./tmp/`

**Comment by shubhamJay** [comment]
Tried the same command with fat jar of dokka version 0.9.17 (removed `-pass` from command) and it worked fine.
Command - 
 `java -jar ~/Downloads/dokka-fatjar-0.9.17.jar -src src -format html -output ./targetDoc -classpath ~/Downloads/kotlinx-coroutines-core-1.3.2.jar`

**Comment by kamilok1965** [comment]
Could you please check if changing the `.jar` path from relative to absolute fixes the problem?

**Comment by shubhamJay** [comment]
I tried giving path both ways, absolute and relative, but looks like it did not fix my problem.

**Comment by kamilok1965** [comment]
Could you please provide some project to reproduce that?

**Comment by kamildoleglo** [comment]
Fatjar has been removed and this issue has been fixed
