### ISSUE TITLE
Change name of generated files

### ISSUE THREAD

**Issue by masteramyx** [Kotlin/dokka#560]
**Question**
My current setup:
  I currently am using dokka to generate docs for a component library which when changes are pushed up to gitlab, creates an artifact of all the generated documents. 
This triggers the pipeline for a Gitlab Pages project specifically for documentation; this documentation project pulls the artifact created in project 1(component project), unzips and adds+commits the contents to itself(docs project). 
This worked the 1st time around however now on each commit, even though the contents of the docs.html files have changed the titles have not, thus my CI fails because there are no changes to commit. 

Question:
If I can append my project's version number I think this would solve the problem.
 Everytime we commit changes and bump the version to Project 1, dokka will generate `documentation/build/dokka/index-versionNum.html`, giving project2 something to commit.  Is there an option for customizing documentation file names?

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v5.6.0/Maven/Cli/3rd party plugin 
- Dokka version: 0.10.0

**Comment by kamilok1965** [comment]
No, there isn't. You can customize the output directory though, which may help with your issue
