### ISSUE TITLE
Visibility of protected members for final classes.

### ISSUE THREAD

**Issue by yevhenii8** [Kotlin/dokka#587]
**Describe the bug**
We have an abstract class with one protected member. And another class that inherits from abstract one.
```kotlin
abstract class ClassA {
    protected abstract val color: String
}

class ClassB : ClassA() {
    override val color: String
        get() = TODO("not implemented")
}
```

**Expected behaviour**
We expect `color` property to be effectively private for final classes.  And so it is. It's inaccessible.
Dokka generates properties [without](https://github.com/Kotlin/dokka/issues/445) visibility modifiers. Okay. I expect property `color` to be shown in ClassA doc, but I don't expect it to be shown in ClassB as it's private for this class. But it does.
```kotlin
val b = ClassB()
println(b.color) // error!
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13679188/72668265-c8801d00-3a2d-11ea-9363-bc4e12f616d5.png)
![image](https://user-images.githubusercontent.com/13679188/72668270-d170ee80-3a2d-11ea-9414-e2a507f5c5b8.png)

**Dokka configuration**
```kotlin
tasks.dokka {
    outputFormat = "html"
    outputDirectory = "$buildDir/dokka"

    configuration {
        includeNonPublic = false
        skipDeprecated = false
        reportUndocumented = true
        skipEmptyPackages = true
        includes = listOf("packages.md")
    }
}
```

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v6.1
- Dokka version: 0.10.0

**Comment by kamildoleglo** [comment]
FIx confirmed in `1.4.10.2`
