### ISSUE TITLE
Any chance Kotlin Dokka will support emoji?

### ISSUE THREAD

**Issue by mfulton26** [Kotlin/dokka#60]
e.g. Can support be added for the emoji/emoticons listed on http://www.emoji-cheat-sheet.com/?

**Comment by Kordyjan** [comment]
I was cleaning old issues and though it may be worth it to clarify it for the future:
Dokka is supporting Unicode, so you can put any chars, including emojis, in your documentation and dokka will render it. We don't have any plans for supporting custom emojis shortcuts.
