### ISSUE TITLE
Java package-info.html files not included in documentation

### ISSUE THREAD

**Issue by mikeholler** [Kotlin/dokka#62]
I'd like my Java classes to have package-level documentation. I've setup the package-info.html files in each package and it works for my Gradle Javadoc task, but when I run `./gradlew dokka` the text in the package-info.html files is nowhere to be seen.

**Comment by eskatos** [comment]
Javadoc content from `package-info.java` files is ignored as well.

**Comment by rodolfodpk** [comment]
https://youtrack.jetbrains.com/issue/KT-22384

**Comment by GlenKPeterson** [comment]
Maybe a small point, but the java conventions are `package.html` and `package-info.java` - there was never a `package-info.html`.  You might want to change the title of this issue to reflect that.  I would be happy for dokka to work automatically with either of those, and/or something dokka-specific like `package.md` or `module.md`.

In the meantime, I tried configuring `build.gradle.kts`, but it didn't seem to have any effect:

```kotlin
tasks.dokkaHtml.configure {
    dokkaSourceSets {
        configureEach { // Or source set name, for single-platform the default source sets are `main` and `test`
            // List of files with module and package documentation
            // https://kotlinlang.org/docs/reference/kotlin-doc.html#module-and-package-documentation
            includes = listOf("package.md", "module.md")
        }
    }
}
```

I tried with my .md files in the `src/main/kotlin/some-package` directory or just in the project root, but neither worked.
