### ISSUE TITLE
Multiple  `Constructors`, `Properties` and `Functions` blocks on multiplatform classes' pages

### ISSUE THREAD

**Issue by kamilok1965** [Kotlin/dokka#646]
<img width="622" alt="Screenshot 2020-02-14 at 11 30 52" src="https://user-images.githubusercontent.com/9080183/74523590-a17a1580-4f1d-11ea-9317-4a642d0c47d9.png">

**Comment by sellophane** [comment]
https://github.com/Kotlin/dokka/pull/654
