### ISSUE TITLE
Terrible L&F in the generated document should be improved

### ISSUE THREAD

**Issue by kmizu** [Kotlin/dokka#65]
The following image is screenshot of the generated document using `output=html` from my project [kotbinator](https://github.com/kmizu/kotbinator).  The L&F is too terrible. Better style sheet should be applied.  Note that the L&F of generated document using `output=javadoc` is good.

![It](https://pbs.twimg.com/media/CevuM_QWQAQjYJX.jpg:large)

**Comment by yole** [comment]
Specific problem reports, suggestions for improvement and pull requests are welcome. Saying that something is terrible is not constructive feedback, sorry.

**Comment by kmizu** [comment]
I'm sorry.  However, it seems that something is broken in generated documents (`output=html`) for me (please **see** the linked image.  I believe that you understand what you want to say).   IMO, L&F of generated documents(`output=html`) should be similar with L&F of generated documents(`output=javadoc`)

**Comment by yole** [comment]
Yes, this is the style for the Dokka HTML output; nothing is broken. I don't see why the HTML output needs to be similar to the JavaDoc output style; I don't find it to be the most readable documentation style.

**Comment by kmizu** [comment]
OK.  I understood your opinion.

**Comment by yole** [comment]
Once again: I'm happy to accept pull requests improving the default styles.

**Comment by yole** [comment]
Resubmitted as https://youtrack.jetbrains.com/issue/KT-11757
