### ISSUE TITLE
Example: Dokka + MPP + MavenPublish

### ISSUE THREAD

**Issue by chrisjenx** [Kotlin/dokka#653]
**Question**

Thank you for adding MPP support. I was wondering if there is an example of how we can now make uploading documentation via the maven-publish plugin?
(Or if it's possible to make it detect the maven-publish plugin to auto attach artifacts)

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.1.1 / Kotlin 1.3.70-eap / MPP
- Dokka version: 0.10.1

**Additional context**

Example for how to attach javadoc artifacts - or support adding them automatically when the maven-publish plugin is added.

**Comment by utybo** [comment]
Seconded, it would be nice to have a docs on that 😄

**Comment by kamilok1965** [comment]
There is no example that I'm aware of, you have to attach the docs manually. We should create some docs for that

**Comment by IgnatBeresnev** [comment]
An example project has been added: https://github.com/Kotlin/dokka/tree/master/examples/gradle/dokka-library-publishing-example

And some points are addressed in #2728 as well
