### ISSUE TITLE
Rename `DocumentationToPageTranslator` et al. to `DocumentableToPageTranslator` and other corresponding names and move them to separate package `translators`

### ISSUE THREAD

**Issue by kamilok1965** [Kotlin/dokka#655]

**Comment by Kordyjan** [comment]
You've created this issue 2 hours after my commit: https://github.com/Kotlin/dokka/commit/f01dd465a08a1b940ff3778966a23197d301c367 😁

**Comment by BarkingBad** [comment]
@kamilok1965 Can we mark it then as Done?
