### ISSUE TITLE
Can't use 'org.jetbrains.dokka-android'

### ISSUE THREAD

**Issue by liungkejin** [Kotlin/dokka#66]
when i use this in Android Studio, I can't build success
```
apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.dokka-android'
....
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:${dokka_version}"
```
and i find there did no 'dokka-android-gradle-plugin' on jcenter or maven!

**Comment by yole** [comment]
Yes, because the version of Dokka containing this plugin has not been released yet.
