### ISSUE TITLE
"javadoc" output format generates incorrect output for Java's @return

### ISSUE THREAD

**Issue by chrismiller** [Kotlin/dokka#681]
**Describe the bug**
When generating documentation using outputFormat = "javadoc", Java methods that have a @return tag generate output that is prefixed with org.jetbrains.dokka.NodeRenderContent@108d48ce

**Expected behaviour**
Javadocs generated with a "Returns:" section identical to the JDK's javadoc output.

**Screenshots**
For example, the following Java code results in the screenshot below:
```java
  /**
   * @return the report date that this {@code FileKey} is for.
   */
  public LocalDate getReportDate() {
    return reportDate;
  }
```
![image](https://user-images.githubusercontent.com/328751/75343998-8bf7da80-5891-11ea-8e0d-7107d2172ab2.png)

**To Reproduce**
Use Dokka to generate javadoc output with the source including a Java method that has a @return javadoc entry.

**Dokka configuration**
Dokka 0.10.1

```groovy
dokka { 
    outputFormat = 'javadoc'
    ...
}
```

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v6.0.1
- Dokka version: 0.10.1

**Comment by kamildoleglo** [comment]
AFAIK fixed in `1.4.10.2`
