### ISSUE TITLE
flowchart doesn't work

### ISSUE THREAD

**Issue by AllenVork** [Kotlin/dokka#70]
I'm using kotlin to develop android app.We know kotlin support markdow.So i try to draw a flowchart:    

```flow    

st=>start: Start|past:>http://www.google.com[blank]
e=>end: End:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Stuff|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes 
or No?|approved:>http://www.baidu.com
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|request

st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e

```

and place it to a class. But it doesn't show the diagram, just show the code above.

**Comment by AllenVork** [comment]
But i use some simple syntax is ok such as `**Bold**`

**Comment by yole** [comment]
Flowcharts are not a standard feature of Markdown, but rather a third-party extension. We have no plans to support flowchart rendering in Dokka at this time.
