### ISSUE TITLE
dokka markdown generation doesn't generate table header correctly.

### ISSUE THREAD

**Issue by apatrida** [Kotlin/dokka#72]
For the list of packages in a module, dokka markdown generates:

```
| [uy.klutter.vertx](uy.klutter.vertx/index.md) |  |
| [uy.klutter.vertx.json](uy.klutter.vertx.json/index.md) |  |
```

and that needs a header for the table or most markdown processors will not generate a correct table, it should be:

```
|package name|whatever|
|---|---|
| [uy.klutter.vertx](uy.klutter.vertx/index.md) |  |
| [uy.klutter.vertx.json](uy.klutter.vertx.json/index.md) |  |
```

see https://help.github.com/articles/organizing-information-with-tables/

**Comment by apatrida** [comment]
this makes package list, and all types useless in markdown for those (which is most) viewers that do not process tables without the header.

**Comment by apatrida** [comment]
and the index of a package.  it turns out almost every page is affected by this.

**Comment by yole** [comment]
Resolved by c0064d2b43ec30237d0d39bf5a9aaa4ce5e14744

**Comment by karvar** [comment]
I am still running into this issue. I am using `mkdoc` and it does not render tables without a header. dokka is omitting the table headers.

**Comment by fgsalomon** [comment]
I'm also having this issue with 0.9.18.

**Comment by kamilok1965** [comment]
Do you use the `GMF` markdown format in dokka?

**Comment by fgsalomon** [comment]
I tried with just `markdown` and `jekyll` as output format. With `GMF` works ok. Sorry for the inconvenience.

**Comment by kamilok1965** [comment]
No problem, happy to help
