### ISSUE TITLE
Unresolved link to xxx warning for external links

### ISSUE THREAD

**Issue by fschoellhammer** [Kotlin/dokka#74]
/**
      * @see [Documentation](http://www.example.com)
      **/
     class MyClass {
     }

This code generates a warning:

     Unresolved link to Documentation in doc comment of xxx.MyClass (MyClass.kt:yy)

**Comment by yole** [comment]
As documented in https://kotlinlang.org/docs/reference/kotlin-doc.html the @see tag is followed by an identifier, not by free-form Markdown text.

**Comment by CLOVIS-AI** [comment]
That document doesn't reference any way to link to external URLs. Is there any way to do it now?

**Comment by Xerus2000** [comment]
Same question, I'd like to put a link into an @see tag or have a viable alternative.

**Comment by weickmanna** [comment]
```
@see <a href="http://www.example.com">Documentation</a>
```
