### ISSUE TITLE
No support for @hide annotation

### ISSUE THREAD

**Issue by simoarpe** [Kotlin/dokka#751]
Currently, Dokka offers no support for [`@hide` annotations](https://stackoverflow.com/questions/17035271/what-does-hide-mean-in-the-android-source-code)
They are quite common when dealing with large Android codebase.
The behavior is very simple: when an API is marked as hidden it will not land in the generated API documentation.

I'm not sure if I can achieve this behavior by using a [custom Dokka runtime](https://github.com/Kotlin/dokka#dokka-runtime).
I've invested some time looking at some examples like [Dokka Hugo Extension](https://github.com/cotechde/dokka-hugo-extension) and [spring-auto-restdocs](https://github.com/ScaCap/spring-auto-restdocs/tree/master/spring-auto-restdocs-dokka-json) but they seem to focus on something different.

Any suggestions how to tackle this?

**Comment by kamilok1965** [comment]
It will be possible to create a plugin that does this when `0.11.0` is released

**Comment by MariusVolkhart** [comment]
FYI, using `@suppress` is broken in 1.4.x version of Dokka. See #1612
