### ISSUE TITLE
GFM: no space before inline codeblock

### ISSUE THREAD

**Issue by davibe** [Kotlin/dokka#763]
**Describe the bug**
inline code blocks are not separated with a space from preceding text

**Expected behaviour**
To have a space there. In the example below I expect a space right before "`enum"

**Screenshots**
This is from a table with the Type index
<img width="901" alt="Screenshot 2020-03-23 at 09 39 20" src="https://user-images.githubusercontent.com/123929/77297851-2eb54480-6cea-11ea-88cc-593aabac17ec.png">

This is how it gets rendered with my rendering engine

<img width="970" alt="Screenshot 2020-03-23 at 09 37 38" src="https://user-images.githubusercontent.com/123929/77297685-f31a7a80-6ce9-11ea-8d9f-ed3847e2070c.png">

**Dokka configuration**

```groovy
dokka { 
    outputFormat = 'gfm'
    ...
}
```

**Installation**
- Operating system: macOS
- Build tool: Android studio up to date
- Dokka version: 0.10.1

**Comment by kamildoleglo** [comment]
AFAIK fixed in `1.4.10.2`
