### ISSUE TITLE
Treat warning/reports as errors

### ISSUE THREAD

**Issue by cmoine** [Kotlin/dokka#769]
**Is your feature request related to a problem? Please describe**
The dokka generation reports problem such as:
`Unresolved function ...`
It would be nice to not only log those errors but set the build as failed in CI environnement

**Describe the solution you'd like**
Add an attribute in the dokka.configuration, such as `buildFailure = true` (false by default for backward compatibility)

**Comment by kamildoleglo** [comment]
Closing as a duplicate of https://github.com/Kotlin/dokka/issues/459, please follow that issue for updates
