### ISSUE TITLE
How can I hide data-class generated methods?

### ISSUE THREAD

**Issue by fschoellhammer** [Kotlin/dokka#77]
I am looking for a way to remove `componentX()` and `copy(...)` methods of a `data class` from my Dokka generated Javadoc. Is there a way to do that?

**Comment by yole** [comment]
There is no way to do that. The Dokka-generated Javadoc shows the actual Java API of your Kotlin class, which does include the copy() and componentX() methods.

**Comment by superbobry** [comment]
Well, you could probably add a tag for hiding methods, e.g. `@exclude copy, component*`.

**Comment by RenegadesLabs** [comment]
> @exclude copy, component*

Where should one put it? 
I tried to put it in class documentation, but it did not work.
`/**`
` * An icon placed at a particular point on the map's surface.`
` * @param position GeoPoint at which marker will be set.`
` * @exclude copy, component*`
` */`
`data class Marker(val position: GeoPoint)`

**Comment by semoro** [comment]
It was proposed but never implemented

**Comment by RenegadesLabs** [comment]
@semoro Ok, thanks for answer! Really need this feature...

**Comment by cleanerx** [comment]
Can you please elaborate as to why there is no way to do that ? Is there no way to do it in dokka or is somewhere else that things are missing ?

**Comment by saschpe** [comment]
[@suppress﻿](https://kotlinlang.org/docs/kotlin-doc.html#suppress)
