### ISSUE TITLE
@JvmName is ignored by Dokka Javadoc 

### ISSUE THREAD

**Issue by fschoellhammer** [Kotlin/dokka#78]
Using Dokka-Android Javadoc 0.9.8

Source:

    class Apple {
        @get:JvmName("_tree")
        internal val source: Tree
    }

The actual JVM method that will be generated is `public Tree _tree()`, however Dokka calls the method `public Tree getTree$module()`

**Comment by yole** [comment]
Most likely this happens because Dokka doesn't see the standard library dependency in Android projects (known issue, will fix)

**Comment by sevar83** [comment]
Seems it is still ignored.

```kotlin
@get:JvmName("hasCredentials")
val hasCredentials: Boolean get()
```

This appears in Javadoc as:

getHasCredentials
@JvmName(name = "hasCredentials") final Boolean getHasCredentials()
