### ISSUE TITLE
Leave out "interface" in links

### ISSUE THREAD

**Issue by GladeDiviney** [Kotlin/dokka#780]
I want:

```kotlin
interface Foo

/** A [Foo] which can also [bar]. */
class Bar : Foo {
    fun bar() { }
}
```

to result in this javadoc for `Bar`:

> A [Foo]() which can also [bar].

But instead dokka generates Javadoc with an extra word in it:

> A [interface Foo]() which can also [bar].

**Installation**
- Dokka version: 0.10.1

**Comment by IgnatBeresnev** [comment]
Seems like this has been fixed

![2022-04-27_18-54-06](https://user-images.githubusercontent.com/22685910/165559931-0497191e-62d2-4e73-9f28-66ef20a9e4f2.png)
