### ISSUE TITLE
How to configure the html file names

### ISSUE THREAD

**Issue by charleszq** [Kotlin/dokka#789]
Hi

We're using dokka to generate our kotlin docs, but our publishing system has a problem with the fairly long file names generated, for example, the following is a function inside a companion object:

-application-configuration/create-app-config-from-json-string.html

So I'm wondering is there a way to customize the package/function file names?
Thanks
Qiang

**Comment by kamilok1965** [comment]
No, there isn't right now. This will be possible in `0.11.0` as a plugin but discouraged, as it will possibly be problematic to link to this documentation from other dokka versions (with standard urls)
