### ISSUE TITLE
Publish dokka-maven-plugin to Maven Central

### ISSUE THREAD

**Issue by bdemers** [Kotlin/dokka#791]
The Dokka Maven Plugin, should be available on Maven Central (just like the other Kotlin libs and plugins)

**Comment by benjamin-bader** [comment]
Yes, please - I try to avoid jcenter wherever possible and would very much appreciate dokka being available on Central.

**Comment by kamildoleglo** [comment]
Closing as a duplicate of https://github.com/Kotlin/dokka/issues/41
