### ISSUE TITLE
Use dokka in IntelliJ IDEA / Android Studio without Gradle

### ISSUE THREAD

**Issue by sollyucko** [Kotlin/dokka#802]
**Is your feature request related to a problem? Please describe**
I have a Kotlin file with documentation comments (pure text), and want to generate some sort of viewable documentation file, without setting up a Gradle/Maven/Ant project. (Having to install them is fine, though.)

**Describe the solution you'd like**
Some way to run `dokka` (or some other documentation generator) on my Kotlin file without setting up a Gradle/Maven/Ant project. (Having to install them is fine, though.) An in-IDE button or menu item would be nice, but a command line program or something else is also completely fine.

**Describe alternatives you've considered**
1. Convert my project to Gradle/Maven/Ant
2. Convert the interfaces to Java and run `javadoc`

**Additional context**
- Tools > Generate JavaDoc... says "Error running 'Javadoc': Selected scope contain no Java classes"
- Tools > Kotlin contains nothing of use
- All the ways of setting up or running `dokka` appear to require setting up a Gradle/Maven/Ant project

**Comment by kamildoleglo** [comment]
Dokka is not a part of IntelliJ nor Android Studio, it is a separate project. If you don't want to setup a build tool for your project, you can download the fatjar and use dokka from the command line, please see the Readme

**Comment by IgnatBeresnev** [comment]
This can indeed be achieved by using the CLI runner. You can find documentation for it here: https://kotlinlang.org/docs/dokka-cli.html
