### ISSUE TITLE
Multiplatform multiprojects

### ISSUE THREAD

**Issue by InsanusMokrassar** [Kotlin/dokka#845]
Some time ago I have faced with the problem, that it is impossible (or not clear described in readme and FAQ) to create multiplatform project with subprojects. I am maintainer of [TelegramBotAPI](https://github.com/InsanusMokrassar/TelegramBotAPI) library. In this library there are three subprojects and all of them are multiplatform with the same structure, but I was not able to build docs without a little [crutch](https://github.com/InsanusMokrassar/TelegramBotAPI/blob/0.27.2/docs/build.gradle#L21-L85).

In my opinion, you could add opportunity to include subprojects inside of multiplatform submodules. It could look like:

```groovy
dokka {
    ...

    multiplatform {
        jvm {
            subProjects = ["multiplatformSubprojectWithTheSamePlatformName", "jvmOnlySubproject", "multiplatformSubprojectWithTheSamePlatformAndCustomPlatformName/PlatformName"]
        }
        ...
    }
}
```

Unfortunatelly, I can't imagine opportunities of current system to offer something else

**Comment by kamildoleglo** [comment]
Yeah, the `subProjects` is currently more of a hack than an actual solution, however it should work. Could you please explain why adding the `subProjects = ["multiplatformSubprojectWithTheSamePlatformName", "jvm ...]` line to the toplevel dokka configuration does not work as intended?

**Comment by kamildoleglo** [comment]
Dokka features now a proper multiplatform multiproject support, starting from `1.4.30`
