### ISSUE TITLE
Java `{@link}` tags are not displayed correctly in Markdown

### ISSUE THREAD

**Issue by ShaishavGandhi** [Kotlin/dokka#848]
**Describe the bug**
If you generate Markdown docs for `javaLinkTag.java` in `testdata`, the markdown output is wrong. 
```java
/**
 * Call {@link #bar()} to do the job.
 */
class Foo {
  public void bar()
}
```

Markdown generated:
[test](../../index.md) / [Foo](./index.md)

# Foo

`protected open class Foo`

Call ``[`#bar()`](bar.md) to do the job.

### Constructors

| [&lt;init&gt;](-init-.md) | Call ``[`#bar()`](bar.md) to do the job.`Foo()` |

### Functions

| [bar](bar.md) | `open fun bar(): Unit` |

**Expected behaviour**
As you can see, the backticks aren't placed correctly. 

**Screenshots**
If applicable, add screenshots to help explain your problem

**To Reproduce**
Add the following code in `MarkdownFormatTest`
```kotlin
@Test 
fun javaLinkTag() {
    verifyJavaMarkdownNode("javaLinkTag", defaultModelConfig)
}
```
and check the output.

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dokka { 
    outputFormat = 'gfm'
    ...
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v5.6.0
- Dokka version: 0.10.0

** Additional Context **

Another example:
```java
/**
 * Call {@link #bar()} to do the job.
 */
class Foo {
  public static final int CONSTANT = 1;
  /**
   * Check out {@link #CONSTANT}
   */
  public void bar()
}

```

Markdown generated:

[test](../../index.md) / [Foo](./index.md)

# Foo

`protected open class Foo`

Call ``[`#bar()`](bar.md) to do the job.

### Constructors

| [&lt;init&gt;](-init-.md) | Call ``[`#bar()`](bar.md) to do the job.`Foo()` |

### Properties

| [CONSTANT](-c-o-n-s-t-a-n-t.md) | `static val CONSTANT: Int` |

### Functions

| [bar](bar.md) | Check out ``[`#CONSTANT`](-c-o-n-s-t-a-n-t.md)`open fun bar(): Unit` |

**Comment by kamildoleglo** [comment]
Probably fixed in Dokka `1.4.10.2`
