### ISSUE TITLE
Missing class: DocErrorReporter

### ISSUE THREAD

**Issue by norswap** [Kotlin/dokka#85]
On the command line, running `java -jar dokka-fatjar.jar src -java` requires the class `com.sun.javadoc.DocErrorReporter` (and maybe others).

The fix, include `tools.jar` on the classpath, which makes the correct command (note `-jar` is incompatible with `-cp`):

```
java -cp $JAVA_HOME/lib/tools.jar:dokka-fatjar.jar org.jetbrains.dokka.MainKt src -java
```

This should probably be documented in the README.

This relates to #58, which you might wish to revisit that one as well, because on my machine (OS X El Capitan with jdk 1.8.0_92 (also confirmed on 1.8.0_51 -- I'm suspecting jdk 8 in general)), `classes.jar` doesn't exist, and `tools.jar` is not `$JAVA_HOME/../lib/tools.jar` but `$JAVA_HOME/lib/tools.jar` (with `JAVA_HOME = /usr/libexec/java_home`).

**Comment by AlmasB** [comment]
Can confirm the issue is present with dokka-maven-plugin 0.9.10 with goal set to `javadocJar` (windows 10x64, jdk 1.8.0_112).
