### ISSUE TITLE
Support for `reportUndocumented` in `perPackageOptions` and toplevel

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#853]
What do we want to accomplish?
 We want to have every declaration in code that has empty documentation logged in the console with the fully qualified name of the declaration. 

* implement a DocumentableTransformer for reporting undocumented declarations 
* undocumented packages and modules should not be reported (only classes, functions and so on) 
* parameters should not be reported 

optional: 
* have different levels of reporting undocumented declarations (like full for all parameters and packages, regular only for classes and functions, ...)

**Comment by sellmair** [comment]
We might also not want to report functions overriding methods from kotlin.Any (hashCode, equals, etc), right?

**Comment by kamildoleglo** [comment]
Yes, that's true
