### ISSUE TITLE
Dokka and JDK6

### ISSUE THREAD

**Issue by DenEwout** [Kotlin/dokka#86]
Hi,

Is Dokka supposed to work with JDK6? I got the error that the Java Path class (https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html) was missing when running Dokka.

Is interoperability with JDK6 planned?

Kind regards,

Ewout.

**Comment by yole** [comment]
No, it is not planned. The javadoc generation APIs have changed significantly between different versions of Java, and Dokka is only compatible with the Java 8 version of the API. Note that the Java version required to run Dokka has no impact on the Java version required to compile and run your actual application.
