### ISSUE TITLE
HTML Escapes generated inside code blocks

### ISSUE THREAD

**Issue by norswap** [Kotlin/dokka#87]
When using `-markdown` and `-jekyll`, Dokka will insert html escapes (e.g. `&nbsp;`) inside `<code>` blocks, which causes them to render verbatim (so you actually see `&nbsp;`).

**Comment by yole** [comment]
Fixed in c0064d2b43ec30237d0d39bf5a9aaa4ce5e14744; fix will be included in Dokka 0.9.9
