### ISSUE TITLE
Doesn't resolve gradle plugin with Kotlin 1.4-M2

### ISSUE THREAD

**Issue by terrakok** [Kotlin/dokka#873]
After update kotlin version from "1.3.72" to "1.4-M2-eap-77" Dokka gradle plugin is not resolving.

Applying plugin in 'build.gradle.kts`:
```
plugins {
    kotlin("multiplatform") version "1.4-M2-eap-77"
    id("org.jetbrains.dokka") version "0.9.18"
   //...
}
``` 
*Work around:*
Add resolution strategy block to  `settings.gradle.kts`:
```
pluginManagement {
    repositories {
        maven("https://kotlin.bintray.com/kotlin-dev")
        jcenter()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("org.jetbrains.dokka")) {
                useModule("org.jetbrains.dokka:dokka-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

**Comment by terrakok** [comment]
My experiments are here:
https://github.com/terrakok/uuid/commit/f753c713081559082ad4471e52757caa09f239f1

**Comment by kamilok1965** [comment]
This is not a bug, Kotlin 1.4 hasn't been published yet, that's why you need to add the `kotlin-dev` repository in the `pluginManagement` block

**Comment by terrakok** [comment]
Yes, I added `kotlin-dev` repository for new kotlin version. It's not a problem.
My question is why I have to add `resolutionStrategy` block for Dokka in this case?

**Comment by kamilok1965** [comment]
You don't have to, but while specifying the `repositories` for `pluginManagement` you have overridden the default ones with
```
        maven("https://kotlin.bintray.com/kotlin-dev")
        jcenter()
```
and dokka plugin is not published to either of these. You can add `gradlePluginPortal` or `jcenter` to this block and it'll work without the `resolutionStrategy`

**Comment by terrakok** [comment]
Oh! Thank you, you are right. I've added `gradlePluginPortal()` and removed `resolutionStrategy` block and now it works
```
pluginManagement {
    repositories {
        maven("https://kotlin.bintray.com/kotlin-dev")
        gradlePluginPortal()
    }
}
```

**Comment by kamilok1965** [comment]
Great to hear that!
