### ISSUE TITLE
Pair and Triple show up as <ERROR CLASS>

### ISSUE THREAD

**Issue by drmoose** [Kotlin/dokka#91]
The [`Pair<A, B>`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-pair/index.html) and [`Triple<A, B, C>`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-triple/index.html) data classes from Kotlin's stdlib show up in the output as `<ERROR CLASS>`, even with kotlin-stdlib explicitly added to the classpath.

[Here](https://github.com/kyonifer/golem/blob/master/golem-core/src/golem/matrix/Matrix.kt#L73) is a sample line of code from @kyonifer's "golem" project which renders incorrectly in dokka, invoked with:

```bash
java -cp $kotlinStdlibJar:$toolsJar:$dokkaJar org.jetbrains.dokka.MainKt golem/*/src/golem
```

**Comment by kyonifer** [comment]
Seems to work if you pass it into the jar using the [-classpath option](https://github.com/Kotlin/dokka#using-the-command-line):

```
java -jar dokka-fatjar.jar -classpath ~/kotlin-stdlib-1.0.3.jar golem-core
```

**Comment by drmoose** [comment]
Ah so it does. I had conflated the dokka classpath with the java classpath, not realizing they were distinct things.
