### ISSUE TITLE
'Modules should have similar names' error

### ISSUE THREAD

**Issue by JonatanPlesko** [Kotlin/dokka#912]
**Describe the bug**
I tried to pass the module name while building docs via the command line.

```
java -jar "dokka/dokka-fatjar.jar" -output "testdocs" -format html-as-java -pass -classpath "$ANDROID_HOME/platforms/android-26/android.jar" -pass -src "app/src/main/java" -pass -module "app"
```

What I get:
```
Exception in thread "main" java.lang.IllegalArgumentException: Modules should have similar names: , , app
	at org.jetbrains.dokka.Generation.DocumentationMerger.<init>(DocumentationMerger.kt:15)
	at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:45)
	at org.jetbrains.dokka.MainKt.entry(main.kt:189)
	at org.jetbrains.dokka.MainKt.main(main.kt:273)
```

If i build without the `-pass -module "app"` argument, the generated docs are structured like this:
```
docs/--root--
docs/style.css
```

**Expected behaviour**
I expect the module name to be accepted and generated docs to be structured as:
```
docs/app
docs/style.css
```

**To Reproduce**
Not sure what is causing it and how to reproduce with a different project. I'm building a library, but it still shows as a separate module in Android Studio so I don't think that's the issue.

The key line seems to be:
`Modules should have similar names: , , app`
I looked into this and for some reason, empty module names are recognized. 

**Dokka configuration**
I'm using the 0.10.1 fatjar.

**Installation**
- Operating system: macOS
- Dokka version: 0.10.1

**Comment by kamildoleglo** [comment]
Please add the `-module "app"` flag to all pass configurations and see if it helps

**Comment by JonatanPlesko** [comment]
Seems rather counterintuitive, but it worked! 👍 
For future reference, here's the correct command:
```
java -jar "dokka/dokka-fatjar.jar" -output "testdocs" -format html-as-java -pass -classpath "$ANDROID_HOME/platforms/android-26/android.jar" -module "app" -pass -src "app/src/main/java" -module "app"
```
