### ISSUE TITLE
Incorrect behavior of sourceset filters

### ISSUE THREAD

**Issue by Kordyjan** [Kotlin/dokka#918]
Right now, clicking on sourceset filter toggles it. As designed, it should cycle between three states:
* all sourcesets
* this sourceset and its dependencies
* only this sourceset

**Comment by pikinier20** [comment]
"Acts as a filter, including/disabling the visibility of packages of selected platforms. By default, all selectors are activated.  If all selects are inactive and the user has activated any selector, if it is a specific platophram (JVM, JS, Native) —  the «Common» selector is activated automatically (after that its activation can be turned off manually)"    and I think it is working this way
