### ISSUE TITLE
Dokka appears to delete apostrophes from the output

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/dokka#95]
I have a KDoc comment with the word "couldn't" in it, and it's rendered as "couldnt".

**Comment by simonorono** [comment]
Same happens to me. This comment:

~~~Kotlin
    /**
     * Retrieves this pool's corresponding quark for [str].
     *
     * @param str The string
     * @return An integer corresponding to a quark in the pool
     */
~~~

Turns into:
`Retrieves this pools corresponding quark for str.`

**Comment by nexbit** [comment]
Same here..
The only workaround I've found is to use `&apos;` html entity in my comments.. Horrible to see, but it works, I'll refactor them when this issue will be resolved!
