### ISSUE TITLE
Functional interfaces introduced in Kotlin 1.4 are reported in a wrong way

### ISSUE THREAD

**Issue by alexey-anufriev** [Kotlin/dokka#971]
**Describe the bug**
Dokka generates documentation for functional interfaces with the wrong format.

For functional interface like this:
```
fun interface Test {
    fun test()
}
```

Dokka will generate the following line:
```
fun <no name provided>(): Unit
```

**Expected behaviour**
Ideally, Dokka should know that this is not a function but rather interface and generate documentation properly.

**To Reproduce**
1. Define functional interface
2. Generate documentation

**Dokka configuration**
Default

**Installation**
- Operating system: Ubuntu 20.04
- Build tool: Gradle v5.5.1
- Dokka version: 0.10.1

**Comment by Kordyjan** [comment]
Released versions of Dokka officially do not support kotlin 1.4. We added 1.4 support in 0.11. I'll leave this issue for checking if there are no problems caused by `fun interface`s in 0.11.
