### ISSUE TITLE
Support search-bar in new-javadoc

### ISSUE THREAD

**Issue by sellmair** [Kotlin/dokka#985]

**Comment by leon-li1** [comment]
I am using the dokka-maven-plugin version 1.4.32 and the search functionality is glitchy/slow and sometimes times out.
![image](https://user-images.githubusercontent.com/30182031/121388021-1e05e400-c919-11eb-91c0-5f00ae0be150.png)
Is there something I can do to speed it up or maybe disable the searchbar?
